// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Pineify
// 

//======================================================================//
//                    ____  _            _  __                          //
//                   |  _ \(_)_ __   ___(_)/ _|_   _                    //
//                   | |_) | | '_ \ / _ \ | |_| | | |                   //
//                   |  __/| | | | |  __/ |  _| |_| |                   //
//                   |_|   |_|_| |_|\___|_|_|  \__, |                   //
//                                             |___/                    //
//======================================================================//

//@version=5

// @description Pineify/common
library("common")

// @function Split one string into two.
// @param str_value any string
// @param separator separator
// @returns [str_a, str_b]
export str_split_into_two(string str_value, string separator) =>
	string[] values = str.split(str_value, separator)
	string str_a = na
	string str_b = na
	if array.size(values) == 2
        str_a := array.get(values, 0)
        str_b := array.get(values, 1)
	[str_a, str_b]


// @function Convert the time to hour and minute
// @param time_str time string
// @returns [hour, minute]
export time_to_hour_minute(string time_str) =>
	[time_hour, time_minute] = str_split_into_two(time_str, ":")
	[math.floor(str.tonumber(time_hour)), math.floor(str.tonumber(time_minute))]


// @function Convert the time range to Unix time
// @param time_range timeRange
// @param date_time The Unix timestamp for the date.
// @param timezone Timezone
// @returns [start_unix_time, end_unix_time]
export time_range_to_unix_time(string time_range, int date_time = time, string timezone = syminfo.timezone) =>
	int start_unix_time = na
	int end_unix_time = na
	int start_time_hour = na
	int start_time_minute = na
	int end_time_hour = na
	int end_time_minute = na
	if str.length(time_range) == 11
		// Format: hh:mm-hh:mm
		start_time_hour := math.floor(str.tonumber(str.substring(time_range, 0, 2)))
		start_time_minute := math.floor(str.tonumber(str.substring(time_range, 3, 5)))
		end_time_hour := math.floor(str.tonumber(str.substring(time_range, 6, 8)))
		end_time_minute := math.floor(str.tonumber(str.substring(time_range, 9, 11)))
	else if str.length(time_range) == 9
		// Format: hhmm-hhmm
		start_time_hour := math.floor(str.tonumber(str.substring(time_range, 0, 2)))
		start_time_minute := math.floor(str.tonumber(str.substring(time_range, 2, 4)))
		end_time_hour := math.floor(str.tonumber(str.substring(time_range, 5, 7)))
		end_time_minute := math.floor(str.tonumber(str.substring(time_range, 7, 9)))
	start_unix_time := timestamp(timezone, year(date_time, timezone), month(date_time, timezone), dayofmonth(date_time, timezone), start_time_hour, start_time_minute, 0)
	end_unix_time := timestamp(timezone, year(date_time, timezone), month(date_time, timezone), dayofmonth(date_time, timezone), end_time_hour, end_time_minute, 0)
	[start_unix_time, end_unix_time]


// @function Convert the time range to start unix time
// @param time_range timeRange
// @param date_time The Unix timestamp for the date.
// @param timezone Timezone
// @returns start_unix_time
export time_range_to_start_unix_time(string time_range, int date_time = time, string timezone = syminfo.timezone) =>
	int start_time_hour = na
	int start_time_minute = na
	if str.length(time_range) == 11
		// Format: hh:mm-hh:mm
		start_time_hour := math.floor(str.tonumber(str.substring(time_range, 0, 2)))
		start_time_minute := math.floor(str.tonumber(str.substring(time_range, 3, 5)))
	else if str.length(time_range) == 9
		// Format: hhmm-hhmm
		start_time_hour := math.floor(str.tonumber(str.substring(time_range, 0, 2)))
		start_time_minute := math.floor(str.tonumber(str.substring(time_range, 2, 4)))
	timestamp(timezone, year(date_time, timezone), month(date_time, timezone), dayofmonth(date_time, timezone), start_time_hour, start_time_minute, 0)



// @function Convert the time range to end unix time
// @param time_range timeRange
// @param date_time The Unix timestamp for the date.
// @param timezone Timezone
// @returns end_unix_time
export time_range_to_end_unix_time(string time_range, int date_time = time, string timezone = syminfo.timezone) =>
	int end_time_hour = na
	int end_time_minute = na
	if str.length(time_range) == 11
		end_time_hour := math.floor(str.tonumber(str.substring(time_range, 6, 8)))
		end_time_minute := math.floor(str.tonumber(str.substring(time_range, 9, 11)))
	else if str.length(time_range) == 9
		end_time_hour := math.floor(str.tonumber(str.substring(time_range, 5, 7)))
		end_time_minute := math.floor(str.tonumber(str.substring(time_range, 7, 9)))
	timestamp(timezone, year(date_time, timezone), month(date_time, timezone), dayofmonth(date_time, timezone), end_time_hour, end_time_minute, 0)

// @function Convert the timeframe to seconds
// @param tf timeframe
// @returns seconds
export timeframe_to_seconds(simple string tf) =>
	float seconds = 0
    tf_lower = str.lower(tf)
	value = str.tonumber(str.substring(tf_lower, 0, str.length(tf_lower) - 1))
	if str.endswith(tf_lower, 's')
		seconds := value
	else if str.endswith(tf_lower, 'd')
		seconds := value * 86400
	else if str.endswith(tf_lower, 'w')
		seconds := value * 604800
	else if str.endswith(tf_lower, 'm')
		seconds := value * 2592000
	else
		seconds := str.tonumber(tf_lower) * 60
	seconds

