// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © robbatt

//@version=6
// @description this library is a very simplistic demo countdown clock. If the time runs out, the indicator stops working with a runtime error. I use it to end a forward test with fixed end.
library("lib_demo")
const int ONE_MINUTE = 60 * 1000 // milliseconds
const int ONE_HOUR   = 60 * ONE_MINUTE
const int ONE_DAY    = 24 * ONE_HOUR

// @function shows a countdown box at the top top right "Demo time remaining\n<countdown d/h/m>"
// @param end_time timestamp in ms since unix epoch until end of demo
export demo_countdown(int end_time) =>

	int remainingTime = end_time - timenow

	// Convert milliseconds to readable units
	int days    = math.max(0, int( remainingTime / ONE_DAY 				 )) // cuts hour remainder
	int hours   = math.max(0, int((remainingTime % ONE_DAY ) / ONE_HOUR	 )) // uses hour remainder, cuts minute remainder
	int minutes = math.max(0, int((remainingTime % ONE_HOUR) / ONE_MINUTE)) // uses minute remainder, drops seconds remainder

	// Format the string for the table
	string countdownText = str.format("Demo time remaining\n{0}d {1}h {2}m", days, hours, minutes)
	var table countdownTable = table.new(position.top_right, 1, 1)
	if barstate.islast
		if remainingTime < 0
			runtime.error("Demo ended on " + str.format_time(end_time))
		table.cell(countdownTable, 0, 0, countdownText, bgcolor = #f9944181, text_color = color.white, text_size = size.small)


// GMT Sun Apr 26 2026 00:00:00 GMT+0000
int demo_end_time = input.time(1777161600 * 1000, "Demo End")
demo_countdown(demo_end_time)

if barstate.isfirst
	line.new(demo_end_time, 0, demo_end_time, 1, xloc.bar_time, extend.both, color.red, force_overlay = true)
	line.new(demo_end_time, 0, demo_end_time, 1, xloc.bar_time, extend.both, color.red)