// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © mutantdog

// @version=6


// @description 
// 
// A collection of functions by:
// mutantdog
// 
// The majority of these are used within published projects, some useful variants have been included here aswell.
// This is volume one consisting mainly of smaller functions, predominantly the filters and standard deviations from Weight Gain 4000.
// Also included at the bottom are various snippets of related code for demonstration. These can be copied and adjusted according to your needs.
//
// A full up-to-date table of contents is located at the top of the main script.
// 
//
// WEIGHT GAIN FILTERS
//
// A collection of moving average type filters with adjustable volume weighting.
// Based upon the two most common methods of volume weighting.
// 'Simple' uses the standard method in which a basic VWMA is analogous to SMA.
// 'Elastic' uses exponential method found in EVWMA which is analogous to RMA.
//
// Volume weighting is applied according to an exponent multiplier of input volume.
// 0 >> volume^0 (unweighted), 1 >> volume^1 (fully weighted), use float values for intermediate weighting.
// Additional volume filter switch for smoothing of outlier events.
//
// 
// DIVA MODULAR DEVIATIONS
//
// A small collection of standard and absolute deviations.
// Includes the weightgain functionality as above.
//
// Basic modular functionality for more creative uses.
// Optional input (ct) for external central tendency (aka: estimator).
// Can be assigned to alternative filter or any float value. Will default to internal filter when no ct input is received.
//
//
// Some other useful or related functions included at the bottom along with basic demonstration use.
// 


library ('RawCuts_01')

// contents:
// 
// 		weightgain_sma 			(src, len, xVol, fVol) 		SMA (Standard) 						Simple
// 		weightgain_hsma 		(src, len, xVol, fVol) 		hSMA (Harmonic) 					Simple
// 		weightgain_gsma 		(src, len, xVol, fVol) 		gSMA (Geometric) 					Simple
// 		weightgain_ema 			(src, len, xVol, fVol) 		EMA 								Elastic
// 		weightgain_dema 		(src, len, xVol, fVol) 		Double EMA 							Elastic
// 		weightgain_tema 		(src, len, xVol, fVol) 		Triple EMA 							Elastic
// 		weightgain_rma 			(src, len, xVol, fVol) 		RMA 								Elastic
// 		weightgain_drma 		(src, len, xVol, fVol) 		Double RMA 							Elastic
// 		weightgain_trma 		(src, len, xVol, fVol) 		Triple RMA 							Elastic
// 		weightgain_wma 			(src, len, xVol, fVol) 		WMA 								Simple
// 		weightgain_hma 			(src, len, xVol, fVol) 		HMA 								Simple
// 		weightgain_sema 		(src, len, xVol, fVol) 		sEMA 								Simple
// 		weightgain_vidya_rma 	(src, len, xVol, fVol) 		VIDYA v1 RMA 						Elastic
// 		weightgain_vidya_ema 	(src, len, xVol, fVol) 		VIDYA v1 EMA 						Elastic
//
// 		diva_sd_sma 			(src, len, xVol, fVol, ct) 	Standard Deviation: SMA 			Simple
// 		diva_sd_wma 			(src, len, xVol, fVol, ct) 	Standard Deviation: WMA 			Simple
// 		diva_aad_sma 			(src, len, xVol, fVol, ct) 	Average Absolute Deviation: SMA 	Simple
// 		diva_aad_wma 			(src, len, xVol, fVol, ct) 	Average Absolute Deviation: WMA 	Simple
// 		diva_sd_ema 			(src, len, xVol, fVol, ct) 	Standard Deviation: EMA 			Elastic
// 		diva_sd_rma 			(src, len, xVol, fVol, ct) 	Standard Deviation: RMA 			Elastic
// 		diva_sd_sema 			(src, len, xVol, fVol) 		Standard Deviation: EMA 			Simple (internal ct only)
// 		diva_mad_mm 			(src, len, ct) 				Median Absolute Deviation: MM 		(no weightgain)
// 		diva_sd_vidya_rma 		(src, len, xVol, fVol, ct) 	Standard Deviation: VIDYA v1 RMA 	Elastic
// 		diva_sd_vidya_ema 		(src, len, xVol, fVol, ct) 	Standard Deviation: VIDYA v1 EMA 	Elastic
//
//      source_switch 			(slct, aux1, aux2, aux3, aux4) 				Custom Source Switch
//      colour_gradient_ma_div 	(ma1, ma2, div, bull, bear, mid, mult) 		Bull/Bear Colour Gradient for 2 MA Divergence
//
//




// Volume weighting functions with optional wma(4) or rma(2) smoothing.
// Used within main functions.
volume_wma (xVol, fVol) =>
    v0      =   volume > 1      ?   math.pow (volume, xVol) :   1                                       
    v1      =   ta.wma (v0, 4)
    v2      =   fVol            ?   v1                      :   v0
//	
volume_rma (xVol, fVol) =>
    v0      =   volume > 1      ?   math.pow (volume, xVol) :   1                                       
    v1      =   ta.rma (v0, 2)
    v2      =   fVol            ?   v1                      :   v0
//



// --------------------------------------------- //
// --- WEIGHT GAIN FILTERS --- SIMPLE VOLUME --- //
// --------------------------------------------- //


// @function        Simple Moving Average (SMA):                Weight Gain (Simple Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Standard Simple Moving Average with Simple Weight Gain applied.
export weightgain_sma   (float src, int len, float xVol, bool fVol) =>
    vwt         =   volume_wma (xVol, fVol)
    sma         =   ta.sma (src * vwt, len)     /   ta.sma (vwt, len)
//

// @function        Harmonic Simple Moving Average (hSMA):      Weight Gain (Simple Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Harmonic Simple Moving Average with Simple Weight Gain applied.
export weightgain_hsma  (float src, int len,    float xVol, bool fVol) =>
    vwt         =   volume_wma (xVol, fVol)
    hsma        =   ta.sma (vwt, len)   /   ta.sma (vwt/src, len)
//

// @function        Geometric Simple Moving Average (gSMA):      Weight Gain (Simple Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Geometric Simple Moving Average with Simple Weight Gain applied.
export weightgain_gsma  (float src, int len,    float xVol, bool fVol) =>
    vwt         =   volume_wma (xVol, fVol)
    sma         =   ta.sma (src * vwt, len)     /   ta.sma (vwt, len)
    hsma        =   ta.sma (vwt, len)           /   ta.sma (vwt/src, len)
    gsma        =   math.sqrt (sma * hsma)
//

// @function        Linear Weighted Moving Average (WMA):       Weight Gain (Simple Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Basic Linear Weighted Moving Average with Simple Weight Gain applied.
export weightgain_wma   (float src, int len,    float xVol, bool fVol) =>
    vwt         =   volume_wma (xVol, fVol)
    wma         =   ta.wma (src * vwt, len)     /   ta.wma (vwt, len)
//

// @function        Hull Moving Average (HMA):                  Weight Gain (Simple Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Basic Hull Moving Average with Simple Weight Gain applied.
export weightgain_hma   (float src, int len,    float xVol, bool fVol) =>
    vwt         =   volume_wma (xVol, fVol)

    halfLen     =   math.max (int (len / 2), 2)
    rootLen     =   int (math.sqrt (len))

    w0          =   ta.wma (src * vwt, len)         /   ta.wma (vwt, len)
    w1          =   ta.wma (src * vwt, halfLen)     /   ta.wma (vwt, halfLen)
    w2          =   2 * w1 - w0
    hma         =   ta.wma (w2 * vwt, rootLen)      /   ta.wma (vwt, rootLen)
//



// ------------------------------------------------- //
// --- DIVA MODULAR DEVIATIONS --- SIMPLE VOLUME --- //
// ------------------------------------------------- //


// --- STANDARD DEVIATION

// @function        Standard Deviation (SD SMA):        		Diva / Weight Gain (Simple Volume)
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @param   ct      Central tendency (optional, na = bypass).   Internal: weightgain_sma().
// @returns         [Calculated Deviation value,		Central Tendency (as used)]
export diva_sd_sma  (float src, int len,    float xVol, bool fVol,  float ct) =>
    vwt         =   volume_wma (xVol, fVol)
    sma         =   weightgain_sma (src, len, xVol, fVol)
    ctx         =   nz (ct, sma)

    variSum     =   0.0
    weightSum   =   0.0

    for i = 0 to len - 1
        variSum     :=  variSum     +   vwt[i] * math.pow (ctx - src[i], 2)
        weightSum   :=  weightSum   +   vwt[i]
    
    dev         =   math.sqrt (variSum / weightSum)
    [dev, ctx]
//

// @function        Standard Deviation (SD WMA):        		Diva / Weight Gain (Simple Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @param   ct      Central tendency (optional, na = bypass).   Internal: weightgain_wma().
// @returns         [Calculated Deviation value, 	Central Tendency (as used)]
export diva_sd_wma  (float src, int len,    float xVol, bool fVol,  float ct) =>
    vwt         =   volume_wma (xVol, fVol)
    wma         =   weightgain_wma (src, len, xVol, fVol)
    ctx         =   nz (ct, wma)

    variSum     =   0.0
    weightSum   =   0.0

    for i = 0 to len - 1
        volWeight   =   nz (vwt[i] + (len - i), 1)

        variSum     :=  variSum     +   volWeight * math.pow (ctx - src[i], 2)
        weightSum   :=  weightSum   +   volWeight
    
    dev         =   math.sqrt (variSum / weightSum)
    [dev, ctx]
//

// --- AVERAGE ABSOLUTE DEVIATION

// @function        Average Absolute Deviation (AAD SMA): 		Diva / Weight Gain (Simple Volume).   
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @param   ct      Central tendency (optional, na = bypass).   Internal: weightgain_sma().
// @returns         [Calculated Deviation value,	Central Tendency (as used)]
export diva_aad_sma (float src, int len,    float xVol, bool fVol,  float ct) =>
    vwt         =   volume_wma (xVol, fVol)
    sma         =   weightgain_sma (src, len, xVol, fVol)
    ctx         =   nz (ct, sma)

    variSum     =   0.0
    weightSum   =   0.0

    for i = 0 to len -1
        variSum     :=  variSum     +   vwt[i] * math.abs (ctx - src[i])
        weightSum   :=  weightSum   +   vwt[i]

    dev         =   variSum / weightSum
    [dev, ctx]
//

// @function        Average Absolute Deviation (AAD WMA):  		Diva / Weight Gain (Simple Volume) . 
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @param   ct      Central tendency (optional, na = bypass).   Internal: weightgain_wma().
// @returns         [Calculated Deviation value,	Central Tendency (as used)]
export diva_aad_wma (float src, int len,    float xVol, bool fVol,  float ct) =>
    vwt         =   volume_wma (xVol, fVol)
    wma         =   weightgain_wma (src, len, xVol, fVol)
    ctx         =   nz (ct, wma)

    variSum     =   0.0
    weightSum   =   0.0

    for i = 0 to len -1
        volWeight   =   nz (vwt[i] + (len - i), 1)

        variSum     :=  variSum     +   volWeight * math.abs (ctx - src[i])
        weightSum   :=  weightSum   +   volWeight

    dev         =   variSum / weightSum
    [dev, ctx]
//



// ---------------------------------------------- //
// --- WEIGHT GAIN FILTERS --- ELASTIC VOLUME --- //
// ---------------------------------------------- //


// --- EMA VARIANTS

// @function        Exponential Moving Average (EMA):           Weight Gain (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Exponential Moving Average with Elastic Weight Gain applied.
export weightgain_ema   (float src, int len,    float xVol, bool fVol) =>
    var float       ema = na

    vwt         =   volume_rma (xVol, fVol)
    alpha       =   2 * vwt / (math.sum (vwt, len) + vwt)
    ema         :=  alpha * src     +   (1 - alpha) * nz(ema[1], src[1])
//

// @function        Double Exponential Moving Average (DEMA):   Weight Gain (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Double Exponential Moving Average with Elastic Weight Gain applied.
export weightgain_dema  (float src, int len,    float xVol, bool fVol) =>
    var float       e0 = na
    var float       e1 = na

    vwt         =   volume_rma (xVol, fVol)
    alpha       =   2 * vwt / (math.sum (vwt, len) + vwt)
    e0          :=  alpha * src     +   (1 - alpha) * nz(e0[1], src[1])
    e1          :=  alpha * e0      +   (1 - alpha) * nz(e1[1], e0[1])

    dema        =   (2 * e0) - e1
//

// @function        Triple Exponential Moving Average (TEMA):   Weight Gain (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Triple Exponential Moving Average with Elastic Weight Gain applied.
export weightgain_tema  (float src, int len,    float xVol, bool fVol) =>
    var float       e0 = na
    var float       e1 = na
    var float       e2 = na       

    vwt         =   volume_rma (xVol, fVol)
    alpha       =   2 * vwt / (math.sum (vwt, len) + vwt)
    e0          :=  alpha * src     +   (1 - alpha) * nz(e0[1], src[1])
    e1          :=  alpha * e0      +   (1 - alpha) * nz(e1[1], e0[1])
    e2          :=  alpha * e1      +   (1 - alpha) * nz(e2[1], e1[1])

    tema        =   3 * (e0 - e1)   + e2
//

// --- RMA VARIANTS

// @function        Rolling Moving Average (RMA):               Weight Gain (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Rolling Moving Average with Elastic Weight Gain applied.
export weightgain_rma   (float src, int len,    float xVol, bool fVol) =>
    var float       rma = na

    vwt         =   volume_rma (xVol, fVol)
    alpha       =   vwt / math.sum (vwt, len)
    rma         :=  alpha * src     +   (1 - alpha) * nz(rma[1], src[1])
//

// @function        Double Rolling Moving Average (DRMA):       Weight Gain (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Double Rolling Moving Average with Elastic Weight Gain applied.
export weightgain_drma  (float src, int len,    float xVol, bool fVol) =>
    var float       e0 = na
    var float       e1 = na

    vwt         =   volume_rma (xVol, fVol)
    alpha       =   vwt / math.sum (vwt, len)
    e0          :=  alpha * src     +   (1 - alpha) * nz(e0[1], src[1])
    e1          :=  alpha * e0      +   (1 - alpha) * nz(e1[1], e0[1])

    drma        =   (2 * e0)    - e1
//

// @function        Triple Rolling Moving Average (TRMA):       Weight Gain (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Triple Rolling Moving Average with Elastic Weight Gain applied.
export weightgain_trma  (float src, int len,    float xVol, bool fVol) =>
    var float       e0 = na
    var float       e1 = na
    var float       e2 = na       

    vwt         =   volume_rma (xVol, fVol)
    alpha       =   vwt / math.sum (vwt, len)
    e0          :=  alpha * src     +   (1 - alpha) * nz(e0[1], src[1])
    e1          :=  alpha * e0      +   (1 - alpha) * nz(e1[1], e0[1])
    e2          :=  alpha * e1      +   (1 - alpha) * nz(e2[1], e1[1])

    trma        =   3 * (e0 - e1)   + e2
//





// -------------------------------------------------- //
// --- DIVA MODULAR DEVIATIONS --- ELASTIC VOLUME --- //
// -------------------------------------------------- //


// @function        Standard Deviation (SD EMA):           		Diva / Weight Gain: (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @param   ct      Central tendency (optional, na = bypass).   Internal: weightgain_ema().
// @returns         [Calculated Deviation value,	Central Tendency (as used)]
export diva_sd_ema  (float src, int len,    float xVol, bool fVol,  float ct) =>
    var float       vari = na

    vwt         =   volume_rma (xVol, fVol)
    ema         =   weightgain_ema (src, len, xVol, fVol)
    ctx         =   nz (ct, ema)
    alpha       =   2 * vwt 		/ 	(math.sum (vwt, len) + vwt)
    vari        :=  (1 - alpha) 	* 	((alpha * math.pow (src - ctx[1], 2)) + nz(vari[1]))

    dev         =   math.sqrt (vari)
    [dev, ctx]
//

// @function        Standard Deviation (SD RMA):           		Diva / Weight Gain: (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @param   ct      Central tendency (optional, na = bypass).   Internal: weightgain_rma().
// @returns         [Calculated Deviation value,	Central Tendency (as used)]
export diva_sd_rma  (float src, int len,    float xVol, bool fVol,  float ct) =>
    var float       vari = na

    vwt         =   volume_rma (xVol, fVol)
    rma         =   weightgain_rma (src, len, xVol, fVol)
    ctx         =   nz (ct, rma)
    alpha       =   vwt 			/ 	math.sum (vwt, len)
    vari        :=  (1 - alpha) 	* 	((alpha * math.pow (src - ctx[1], 2)) + nz(vari[1]))

    dev         =   math.sqrt (vari)
    [dev, ctx]
//



// ---------------------------------------------- //
// --- VIDYA NASTI --- WEIGHT GAIN DIVA BASIC --- //
// ---------------------------------------------- //


// Volatility Index used within VIDYA functions.
// Based upon original VIDYA v1 configeration, with added weightgain.
vidyavix_wg 	(float src, int len, float xVol, bool fVol) =>
    [dev, ct]   =   diva_sd_sma (src, len, xVol, fVol, na)
    sma         =   weightgain_sma   (dev, len, xVol, fVol)

    vix   		=	nz (dev / sma, 1)
//



// @function        VIDYA v1 RMA base (VIDYA-RMA):           	Weight Gain (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		VIDYA v1, RMA base with Elastic Weight Gain applied.
export weightgain_vidya_rma (float src, int len, 	float xVol, bool fVol) =>
    var float       rma = na

    vwt         =   volume_rma (xVol, fVol)
	vix			=	vidyavix_wg (src, len, xVol, fVol) 
    alpha       =   vix * vwt 		/ 	math.sum (vwt, len)
    rma         :=  alpha * src     +   (1 - alpha) * nz(rma[1], src[1])
//

// @function        VIDYA v1 EMA base (VIDYA-EMA):           	Weight Gain (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		VIDYA v1, EMA base with Elastic Weight Gain applied.
export weightgain_vidya_ema	(float src, int len, 	float xVol, bool fVol) =>
    var float       ema = na

    vwt         =   volume_rma (xVol, fVol)
	vix			=	vidyavix_wg (src, len, xVol, fVol) 
    alpha       =   2 * vix * vwt 	/ 	(math.sum (vwt, len) + vwt)
    ema         :=  alpha * src     +   (1 - alpha) * nz(ema[1], src[1])
//



// @function        Standard Deviation (SD VIDYA-RMA):          Diva / Weight Gain: (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @param   ct      Central tendency (optional, na = bypass).   Internal: weightgain_vidya_rma().
// @returns         [Calculated Deviation value,	Central Tendency (as used)]
export diva_sd_vidya_rma    (float src, int len, 	float xVol, bool fVol, 	float ct) =>
    var float       vari = na

    vwt         =   volume_rma (xVol, fVol)
	vix			=	vidyavix_wg (src, len, xVol, fVol) 
    rma         =   weightgain_vidya_rma (src, len, xVol, fVol)
    ctx         =   nz (ct, rma)

    alpha       =   vix * vwt 		/ 	math.sum (vwt, len)
    vari        :=  (1 - alpha) 	* 	((alpha * math.pow (src - ctx[1], 2)) + nz(vari[1]))

    dev         =   math.sqrt (vari)
    [dev, ctx]
//

// @function        Standard Deviation (SD VIDYA-EMA):          Diva / Weight Gain: (Elastic Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @param   ct      Central tendency (optional, na = bypass).   Internal: weightgain_vidya_ema().
// @returns         [Calculated Deviation value,	Central Tendency (as used)]
export diva_sd_vidya_ema 	(float src, int len, 	float xVol, bool fVol, 	float ct) =>
    var float       vari = na

    vwt         =   volume_rma (xVol, fVol)
	vix			=	vidyavix_wg (src, len, xVol, fVol) 
    ema         =   weightgain_vidya_ema (src, len, xVol, fVol)
	ctx			=	nz (ct, ema)

    alpha       =   2 * vix * vwt 	/ 	(math.sum (vwt, len) + vwt)
    vari        :=  (1 - alpha) 	* 	((alpha * math.pow (src - ctx[1], 2)) + nz(vari[1]))

    dev         =   math.sqrt (vari)
    [dev, ctx]
//



// ------------------------------------------- //
// --- ADDITIONAL --- FILTERS & DEVIATIONS --- //
// ------------------------------------------- //


// @function        Exponential Moving Average (sEMA):          Weight Gain (Simple Volume).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns 		Exponential Moving Average with simple Weight Gain.
export weightgain_sema  (float src, int len,    float xVol, bool fVol) =>
    vwt         =   volume_rma (xVol, fVol)
    sema        =   ta.ema (src * vwt, len)     /   ta.ema (vwt, len)
//

// @function        Standard Deviation (SD sEMA):             	Diva / Weight Gain (Simple Volume)    (uses internal ct only).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   xVol    Volume exponent multiplier 					(0 = unweighted, 1 = fully weighted).
// @param   fVol    Volume smoothing filter.
// @returns         [Calculated Deviation value,	Central Tendency (as used)]
export diva_sd_sema (float src, int len,    float xVol, bool fVol) =>
    vwt         =   volume_rma (xVol, fVol)
    ctx         =   weightgain_sema (src, len, xVol, fVol)

    d0          =   ta.ema (src * src * vwt, len)   /   ta.ema (vwt, len)
    d1          =   math.pow (ctx, 2)
    d2          =   math.sqrt (d0 - d1)
    [d2, ctx]
//

// @function        Median Absolute Deviation (MAD MM):         Diva (no volume weighting).
// @param	src		Source input.
// @param   len		Length (number of bars).
// @param   ct      Central tendency (optional, na = bypass).   Internal: ta.median()
// @returns         [Calculated Deviation value,	Central Tendency (as used)]
export diva_mad_mm  (float src, int len,    float ct) =>
    float   smm     =   ta.median (src, len)
    float   ctx     =   nz (ct, smm)
    float[] pool    =   array.new_float()
    
    for i = 0 to len -1
        array.push (pool, math.abs (ctx - src[i]))

    dev             =   array.median (pool) 
    [dev, ctx]
//





// --------------------------- //
// --- OTHER USEFUL THINGS --- //
// --------------------------- //


// @function        Custom Source Selector/Switch function. Features standard & custom 'weighted' sources with additional aux inputs.
// @param   slct    Choose from custom set of string values.
// @param   aux1    Additional input for user-defined source, eg: standard input.source(). Optional, use na to bypass.
// @param   aux2    Additional input for user-defined source, eg: standard input.source(). Optional, use na to bypass.
// @param   aux3    Additional input for user-defined source, eg: standard input.source(). Optional, use na to bypass.
// @param   aux4    Additional input for user-defined source, eg: standard input.source(). Optional, use na to bypass.
// @returns         Float value, to be used as src input for other functions.
export source_switch    (string slct, 	float aux1, float aux2, float aux3, float aux4) =>
    source = switch slct
        'open'      =>  open
        'high'      =>  high
        'low'       =>  low
        'close'     =>  close
        'hl2'       =>  hl2
        'hlc3'      =>  hlc3
        'ohlc4'     =>  ohlc4
        'hlcc4'     =>  hlcc4

        'oc2'       =>  (open + close) / 2
        'occ3'      =>  (open + close + close) / 3
        'hlc2-o2'   =>  (high + low + close - open) / 2
        'hl-oc2'    =>  (high + low) - (open + close) / 2
        'cc-ohlc4'  =>  2 * close - ohlc4
        'oc-hl2'    =>  open + close - hl2

        'pre.smth'  =>  (close + hl2 + ohlc4[1]) / 3

        '> AUX'     =>  aux1

        '> AUX.1'   =>  aux1
        '> AUX.2'   =>  aux2
        '> AUX.3'   =>  aux3
        '> AUX.4'   =>  aux4

//


// @function        Colour Gradient for plot fill between two moving averages etc, with seperate bull/bear and divergence strength.
// @param   ma1     Input for fast moving average 	(eg: bullish when above ma2).
// @param   ma2     Input for slow moving average 	(eg: bullish when below ma1).
// @param   div     Input deviation/divergence value used to calculate strength of colour.
// @param   bull    Colour when ma1 above ma2.
// @param   bear    Colour when ma1 below ma2.
// @param   mid     Neutral colour when ma1 = ma2.
// @param   mult    Opacity multiplier. 			100 = maximum, 0 = transparent.
// @returns			Colour with transparency (according to specified inputs)
export  colour_gradient_ma_div  (float ma1, float ma2,	float div, 	color bull, color bear, color mid, 	int mult) =>
    bullstrong  =   color.new (bull,    100 - mult)
    bullweak    =   color.new (bull,    100 - mult / 10)
    bearstrong  =   color.new (bear,    100 - mult)
    bearweak    =   color.new (bear,    100 - mult / 10)

    base        =   color.new (mid,     100 - mult / 10)

    bullgrad    =   div !=  0   ?   color.from_gradient (ma1,   ma2,        ma2 + div,  bullweak,   bullstrong)     :   bullstrong
    beargrad    =   div !=  0   ?   color.from_gradient (ma1,   ma2 - div,  ma2,        bearstrong, bearweak)       :   bearstrong

    color grad  =   ma1 > ma2   ?   bullgrad 		:	ma1 < ma2 	? 	beargrad        :      base
//





// --------------------- //
// --- DEMONSTRATION --- //
// --------------------- //


// Example string shorteners, 		copy as needed into project for use with source_switch()

S01 = 'open',
S02 = 'high'
S03 = 'low'
S04 = 'close'
S05 = 'hl2'
S06 = 'hlc3'
S07 = 'ohlc4'
S08 = 'hlcc4'

S11 = 'oc2'
S12 = 'occ3'
S13 = 'hlc2-o2'
S14 = 'hl-oc2'
S15 = 'cc-ohlc4'
S16 = 'oc-hl2'
S21 = 'pre.smth'

SA0 = '> AUX'
SA1 = '> AUX.1'
SA2 = '> AUX.2'
SA3 = '> AUX.3'
SA4 = '> AUX.4'


// INPUTS //

auxInput    =   input.source    (close,         'Aux Input',                                                                                                                                group='Source Switch')
srcInput    =   input.string    ('pre.smth',    'Source (Main)',    [S01, S02, S03, S04, S05, S06, S07, S08, S11, S12, S13, S14, S15, S16, S21, SA0],                                       group='Source Switch')

wgType      =   input.string    ('EMA',         'Type',             ['SMA', 'EMA', 'WMA', 'RMA', 'DEMA', 'TEMA', 'DRMA', 'TRMA', 'HMA', 'VIDYA:RMA', 'VIDYA:EMA', 'hSMA', 'gSMA', 'sEMA'],  group='Weight Gain Filters')
wgLength    =   input.int       (21,            'Length',                   minval=1,                                                                                                       group='Weight Gain Filters')
wgxVol      =   input.float     (0.5,           'Volume Weight',            minval=0,   maxval=1,   step=0.05,                                                                              group='Weight Gain Filters')
wgfVol      =   input.bool      (true,          'Filter Volume',                                                                                                                            group='Weight Gain Filters')

divaType    =   input.string    ('SD EMA',      'Dev Type',         ['SD SMA', 'SD WMA', 'SD EMA', 'SD RMA', 'AAD SMA', 'AAD WMA', 'SD sEMA', 'MAD MM'],                                    group='Diva Modular Deviations')
divaLength  =   input.int       (21,            'Dev Length',           minval=1,                                                                                                           group='Diva Modular Deviations')
divaxVol    =   input.float     (0.5,           'Volume Weight',        minval=0,   maxval=1,   step=0.05,                                                                                  group='Diva Modular Deviations')
divafVol    =   input.bool      (true,          'Filter Volume',                                                                                                                            group='Diva Modular Deviations')
divaCT      =   input.string    ('internal',    'CT (Examples)',    ['internal', 'Weight Gain', 'Aux', 'MM', 'close @ len'],                                                                group='Diva Modular Deviations')



// PROCESS //

srcSwitch   =   source_switch   (srcInput, auxInput, na, na, na)

wgSwitch    =   switch  wgType
    'SMA'       =>  weightgain_sma  		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'EMA'       =>  weightgain_ema  		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'WMA'       =>  weightgain_wma  		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'RMA'       =>  weightgain_rma  		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'DEMA'      =>  weightgain_dema 		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'TEMA'      =>  weightgain_tema 		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'DRMA'      =>  weightgain_drma 		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'TRMA'      =>  weightgain_trma 		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'HMA'       =>  weightgain_hma  		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'hSMA'      =>  weightgain_hsma 		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'gSMA'      =>  weightgain_gsma 		(srcSwitch, wgLength,   wgxVol, wgfVol)
    'sEMA'      =>  weightgain_sema 		(srcSwitch, wgLength,   wgxVol, wgfVol)
	'VIDYA:RMA' => 	weightgain_vidya_rma	(srcSwitch, wgLength, 	wgxVol, wgfVol)
	'VIDYA:EMA' => 	weightgain_vidya_ema	(srcSwitch, wgLength, 	wgxVol, wgfVol)
//

ctSwitch    =   switch  divaCT
    'internal'      =>  na
    'Weight Gain'   =>  wgSwitch
    'Aux'           =>  auxInput
    'SMM'           =>  ta.median (srcSwitch, divaLength)
    'close @ len'   =>  close [divaLength] 
//

[divaSwitch, ctxSwitch]     =   switch  divaType
    'SD SMA'    =>  diva_sd_sma    (srcSwitch, divaLength,     divaxVol, divafVol,     ctSwitch)
    'SD WMA'    =>  diva_sd_wma    (srcSwitch, divaLength,     divaxVol, divafVol,     ctSwitch)
    'SD EMA'    =>  diva_sd_ema    (srcSwitch, divaLength,     divaxVol, divafVol,     ctSwitch)
    'SD RMA'    =>  diva_sd_rma    (srcSwitch, divaLength,     divaxVol, divafVol,     ctSwitch)
    'AAD SMA'   =>  diva_aad_sma   (srcSwitch, divaLength,     divaxVol, divafVol,     ctSwitch)
    'AAD WMA'   =>  diva_aad_wma   (srcSwitch, divaLength,     divaxVol, divafVol,     ctSwitch)
    'SD sEMA'   =>  diva_sd_sema   (srcSwitch, divaLength,     divaxVol, divafVol)
    'MAD MM'    =>  diva_mad_mm    (srcSwitch, divaLength,                             ctSwitch)
//



// PLOTS //

plotSource      =   plot    (srcSwitch,     'Demo Source',          color.blue,     2,                          force_overlay=true)
plotWeightGain  =   plot    (wgSwitch,      'Weight Gain Filters',  color.yellow,   2,                          force_overlay=true)
plotDivaDevs    =   plot    (divaSwitch,    'Diva Deviations',      color.gray,     2,  plot.style_histogram)







