// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AlgoTrader_Pro

//@version=5

// @description: Contains multiple useful utilities.
library("formattingUtilities", true)

// CONSTANTS 
//-------------
color COLOR_TRANSP              = color.new(color.gray, 100)       // Transparent

// Trend
color COLOR_BEARGR              = color.rgb(133, 17, 17)           // Bearish Growing
color COLOR_BULLGR              = color.green                      // Bullish Growing
color COLOR_BEARSH	            = color.red                        // Bearish Shrinking
color COLOR_BULLSH	            = color.rgb(27, 96, 29)            // Bullish Shrinking
color COLOR_UPTREND             = color.new(color.green,50)
color COLOR_DNTREND             = color.new(color.red,50)

// Trade 
color COLOR_UP                  = color.green                      // Color for upward movement
color COLOR_DOWN                = color.red                        // Color for downward movement
color COLOR_NEUTRAL             = color.gray                       // Neutral color
color ENTRY_PRICE_COLOR 		= color.new(color.orange,0)
color LIQUIDATION_COLOR 		= color.new(color.purple,0)
color TRAILING_STOPLOSS_COLOR	= color.new(color.fuchsia,0)
color PROFIT_COLOR 				= color.new(color.green,85)
color LOSS_COLOR 				= color.new(color.red, 85)
color STOPLOSS_COLOR 			= color.new(color.red,0)
color LONG_TRADE_COLOR			= color.new(color.green,0)
color SHORT_TRADE_COLOR 		= color.new(color.red,0)

// Background
color BG_COLOR_UP               = color.new(color.green,90)
color BG_COLOR_DOWN             = color.new(color.red,90)

// Volume Profile
color POC_COLOR                 = color.new(color.orange,65)
color VUP_COLOR                 = color.new(color.blue, 65)     
color VDOWN_COLOR               = color.new(color.orange, 65)  
color VP_UP_COLOR               = color.new(color.blue, 85)     
color VP_DOWN_COLOR             = color.new(color.orange, 85)  

// Structure
color RESISTANCE_COLOR          = color.red
color SUPPORT_COLOR             = color.green
color MID_COLOR                 = color.new(color.orange,0)

// Table Color 
color HEADER_COLOR              = color.black 
color HEADER_TEXTCOLOR          = color.white
color TITLE_COLOR               = #69952F // AlgoTrader_Pro 
color TITLE_TEXTCOLOR           = color.white
color SUBTITLE_COLOR            = #515559 // AlgoTrader_Pro
color SUBTITLE_TEXTCOLOR        = color.white
color ITEM_COLOR                = #76797B // AlgoTrader_Pro
color ITEM_TEXTCOLOR            = color.white
color DATA_COLOR                = color.white
color DATA_TEXTCOLOR            = color.black
color TOTAL_COLOR               = #E0DD00 // AlgoTrader_Pro
color TOTAL_TEXTCOLOR           = color.black
color COMMENT_COLOR             = color.white 
color COMMENT_TEXTCOLOR         = color.black 

string HEADER_TEXTSIZE      	= size.normal
string HEADER_TEXTALIGN    	    = text.align_center
string TITLE_TEXTSIZE      	    = size.normal
string TITLE_TEXTALIGN    	    = text.align_center
string SUBTITLE_TEXTSIZE        = size.auto
string SUBTITLE_TEXTALIGN       = text.align_left
string ITEM_TEXTSIZE            = size.auto
string ITEM_TEXTALIGN           = text.align_right
string DATA_TEXTSIZE            = size.auto
string DATA_TEXTALIGN           = text.align_center
string COMMENT_TEXTSIZE         = size.auto
string COMMENT_TXTALIGN         = text.align_left



// EXPORTS 
//-------------
// @function: 						Converts a decimal number into a string formatted as percentage.
// @param x (simple float): 		Float number to be converted
// @param decimals (simple int):	Number of decimals to apply
// @returns: 						Returns a string with x as percentage.
export toPercentageString(float x, int decimals) =>
    str.tostring(math.round(x * 100, decimals)) + '%'

// @function: 						Converts a decimal number into a string formatted as Factor.
// @param x (simple float): 		Float number to be converted
// @param decimals (simple int):	Number of decimals to apply
// @returns: 						Returns a string with x as a Factor.
export toFactorString(float x, int decimals) =>
    str.tostring(math.round(x,decimals)) + 'x'

// @function: 						Converts a decimal number into a string formatted as currency.
// @param x (simple float): 		Float number to be converted
// @param decimals (simple int):	Number of decimals to apply
// @returns: 						Returns a string with x as currency.
export toCurrencyString(float x, int decimals) =>
    '$' + str.tostring(math.round(x,decimals),"#,###.##")

// @function: 						Converts a decimal number into a string formatted as decimal.
// @param x (simple float): 		Float number to be converted
// @param decimals (simple int):	Number of decimals to apply
// @returns: 						Returns a string with x as a decimal.
export toNumberString(float x, int decimals) =>
    str.tostring(math.round(x,decimals),"#,###.#####")

// @function: 						Returns a different color if the reference is above, below or equal to x.
// @param x (simple float): 		The number that will be tested, above, below or equal.
// @param reference (simple float):	The reference for for determining if x is above, below or equal.
// @returns: 						The color returned if above, below or equal.
export colorByAboveBelow(float x, float reference, color above, color below, color equal) =>
	x > reference ? above :
	 x > reference ? below :
	 equal

// @function: 						Returns a map with different colors
// @returns: 						Returns a map with multiple colors
export colorMap()=>

    // Create Map
    colorMap = map.new<string, color>()

    // General
    colorMap.put("COLOR_TRANSP", COLOR_TRANSP)

    // Trend
    colorMap.put("COLOR_BEARGR", COLOR_BEARGR)
    colorMap.put("COLOR_BULLGR", COLOR_BULLGR)
    colorMap.put("COLOR_BEARSH", COLOR_BEARSH)
    colorMap.put("COLOR_BULLSH", COLOR_BULLSH)
    colorMap.put("COLOR_UPTREND", COLOR_UPTREND)
    colorMap.put("COLOR_DNTREND", COLOR_DNTREND)

    // Trade
    colorMap.put("COLOR_UP", COLOR_UP)
    colorMap.put("COLOR_DOWN", COLOR_DOWN)
    colorMap.put("COLOR_NEUTRAL", COLOR_NEUTRAL)
    colorMap.put("ENTRY_PRICE_COLOR", ENTRY_PRICE_COLOR)
    colorMap.put("LIQUIDATION_COLOR", LIQUIDATION_COLOR)
    colorMap.put("TRAILING_STOPLOSS_COLOR", TRAILING_STOPLOSS_COLOR)
    colorMap.put("PROFIT_COLOR", PROFIT_COLOR)
    colorMap.put("LOSS_COLOR", LOSS_COLOR)
    colorMap.put("STOPLOSS_COLOR", STOPLOSS_COLOR)
    colorMap.put("LONG_TRADE_COLOR", LONG_TRADE_COLOR)   
    colorMap.put("SHORT_TRADE_COLOR", SHORT_TRADE_COLOR)

    // Background
    colorMap.put("BG_COLOR_UP", BG_COLOR_UP)
    colorMap.put("BG_COLOR_DOWN", BG_COLOR_DOWN)

    // Volume Profile 
    colorMap.put("POC_COLOR", POC_COLOR)
    colorMap.put("VUP_COLOR", VUP_COLOR)
    colorMap.put("VDOWN_COLOR", VDOWN_COLOR)
    colorMap.put("VP_UP_COLOR", VP_UP_COLOR)
    colorMap.put("VP_DOWN_COLOR", VP_DOWN_COLOR)

    // Structure 
    colorMap.put("RESISTANCE_COLOR", RESISTANCE_COLOR)
    colorMap.put("SUPPORT_COLOR", SUPPORT_COLOR)
    colorMap.put("MID_COLOR", MID_COLOR)

    // Table 
    colorMap.put("HEADER_COLOR", HEADER_COLOR)
    colorMap.put("HEADER_TEXTCOLOR", HEADER_TEXTCOLOR)
    colorMap.put("TITLE_COLOR", TITLE_COLOR)
    colorMap.put("TITLE_TEXTCOLOR", TITLE_TEXTCOLOR)
    colorMap.put("SUBTITLE_COLOR", SUBTITLE_COLOR)
    colorMap.put("SUBTITLE_TEXTCOLOR", SUBTITLE_TEXTCOLOR)
    colorMap.put("ITEM_COLOR", ITEM_COLOR)
    colorMap.put("ITEM_TEXTCOLOR", ITEM_TEXTCOLOR)
    colorMap.put("DATA_COLOR", DATA_COLOR)
    colorMap.put("DATA_TEXTCOLOR", DATA_TEXTCOLOR)
    colorMap.put("TOTAL_COLOR", TOTAL_COLOR)
    colorMap.put("TOTAL_TEXTCOLOR", TOTAL_TEXTCOLOR)
    colorMap.put("COMMENT_COLOR", COMMENT_COLOR)
    colorMap.put("COMMENT_TEXTCOLOR", COMMENT_TEXTCOLOR)

    colorMap

// @function:   Creates a map with multiple formats for different uses.
// @returns:    Returns a formatsMap which is a map with multiple formats. 
export formatsMap()=>

    // Create Map 
    formatsMap = map.new<string, string>()

    // Table 
    formatsMap.put('HEADER_TEXTSIZE', HEADER_TEXTSIZE)
    formatsMap.put('HEADER_TEXTALIGN', HEADER_TEXTALIGN)
    formatsMap.put('TITLE_TEXTSIZE', TITLE_TEXTSIZE)
    formatsMap.put('TITLE_TEXTALIGN', TITLE_TEXTALIGN)
    formatsMap.put('SUBTITLE_TEXTSIZE', SUBTITLE_TEXTSIZE)
    formatsMap.put('SUBTITLE_TEXTALIGN', SUBTITLE_TEXTALIGN)
    formatsMap.put('ITEM_TEXTSIZE', ITEM_TEXTSIZE)
    formatsMap.put('ITEM_TEXTALIGN', ITEM_TEXTALIGN)
    formatsMap.put('DATA_TEXTSIZE', DATA_TEXTSIZE)
    formatsMap.put('DATA_TEXTALIGN', DATA_TEXTALIGN)
    formatsMap.put('COMMENT_TEXTSIZE', COMMENT_TEXTSIZE)
    formatsMap.put('COMMENT_TEXTALIGN', COMMENT_TXTALIGN)

    formatsMap

// @function: 						Generates a color by a direction string
// @param direction_str (string):   Direction string: long, short or neutral
// @returns: 						Returns a color
export getColorByDirection(string direction_str)=>

    color direction_color = switch str.lower(direction_str)
        'long'      => color.green 
        'short'     => color.red 
        'neutral'   => color.yellow

    direction_color 
