//@version=6
indicator(title="Ease of Movement Z-Score Trend | Dextra", shorttitle="EOM-Z Trend | Dextra", format=format.volume, timeframe="", timeframe_gaps=true)

// Input parameters
var cumVol = 0.
cumVol += nz(volume)
if barstate.islast and cumVol == 0
    runtime.error("No volume is provided by the data vendor.")
length = input.int(20, minval=1, title="EOM Length")
z_length = input.int(93, minval=1, title="Z-Score Lookback Period")

// Calculate Ease of Movement
hl2 = (high + low) / 2
eom = ta.sma(10000 * ta.change(hl2) * (high - low) / volume, length)

// Calculate Z-Score
mean_eom = ta.sma(eom, z_length) // Rata-rata sederhana EOM
std_dev_eom = ta.stdev(eom, z_length) // Deviasi standar EOM
z_score = (eom - mean_eom) / std_dev_eom // Z-Score

// Define Trend Thresholds 
upperthreshold = input.float(1.03, step=0.01, title="Uptrend Threshold")
lowerthreshold = input.float(-1.93, step=0.01, title="Downtrend Threshold")

// Determine Trend State
var eom_is_up = false
var eom_is_down = false
if (z_score > upperthreshold)
    eom_is_up := true
    eom_is_down := false
else if (z_score < lowerthreshold)
    eom_is_up := false
    eom_is_down := true

// Determine Colors
trend_color = eom_is_up ? color.rgb(14, 255, 122) : eom_is_down ? #f10a3c : color.gray
candle_color = eom_is_up ? color.green : eom_is_down ? color.red : color.gray

// Plotting
plot(z_score, title="Z-Score", color=trend_color, linewidth=2)
hline(upperthreshold, "Uptrend Threshold", color=color.gray, linestyle=hline.style_dashed)
hline(lowerthreshold, "Downtrend Threshold", color=color.gray, linestyle=hline.style_dashed)

// Plot Candles with Color
plotcandle(open, high, low, close, "Candle Color", color=candle_color, wickcolor=candle_color, bordercolor=candle_color, force_overlay=true)