// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © LuTrader_LB

//@version=6
indicator(title="Money Printer 1.0", overlay=true)

// Bollinger Bands

length = input.int(20, minval=1,group = 'Bollinger Bands')
maType = input.string("SMA", "Basis MA Type", options = ["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
src = input(close, title="Source")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")

ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

basis = ma(src, length, maType)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, "Offset", minval = -500, maxval = 500, display = display.data_window)
plot(basis, "Basis", color=#2962FF, offset = offset)
p1 = plot(upper, "Upper", color=#F23645, offset = offset)
p2 = plot(lower, "Lower", color=#089981, offset = offset)
fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95),display = display.none)

// EMA 

src1= input(close,title='Source',group = "ema")
len1= input(200,title='Length',group = "ema")
ema1= ta.ema(src1,len1)
plot(ema1,title='EMA',color= color.purple ,linewidth=2)

// alerts

upperBand= close < ema1 and close > upper
lowerBand= close > ema1 and close < lower

buy1= ta.barssince(lowerBand)
sell1 = ta.barssince(low > lower)
buyCond= buy1[1] > sell1[1] ? lowerBand : false
plotshape(buyCond,title="Cross Lower Band",color=color.green, style=shape.triangleup,location=location.belowbar,size=size.tiny,display=  display.all - display.status_line) 

buy2= ta.barssince(upperBand)
sell2 = ta.barssince(high < upper)
sellCond= buy2[1] > sell2[1] ? upperBand : false
plotshape(sellCond, title="Cross Upper Band",color=color.red, style=shape.triangledown,location=location.abovebar,size=size.tiny,display=  display.all - display.status_line) 

alertcondition(buyCond,'Cross Lower Band','Lower Band Crossed, TimeFrame={{interval}}')
alertcondition(sellCond,'Cross Upper Band Alert','Upper Band Crossed, TimeFrame={{interval}}')

if (buyCond)          
    alert('Lower Band Crossed' + '\n Timeframe =' + str.tostring(timeframe.period), freq = alert.freq_once_per_bar_close)
if (sellCond)          
    alert('Upper Band Crossed' + '\n Timeframe =' + str.tostring(timeframe.period), freq = alert.freq_once_per_bar_close)    

