//---------------------------------------------------------------------------------------------------------------------|    
//                                                                                                                     |                                                                                        
//             #        ####### #####      #     ####  ##### #####   #   ####      ##### ####   ##### #####            |                                        
//            # #          #    #    #    # #    #   # #     #    #  #  #          #     #   # #      #               L|L                       
//           #####         #    #####    #####   #   # ####  #####       ###       ####  #   # #  ### ####            I|I                       
//          #     #        #    #   #   #     #  #   # #     #   #          #      #     #   # #    # #               B|B                 
//         #       #       #    #    # #       # ####  ##### #    #     ####       ##### ####   ####  #####           R|R                                      
//                                                                                                                    A|A                                                                                            
//               FIND your edge.                                                                                      R|R
//                     BUILD your edge.                                                                               Y|Y
//                           TRADE your edge.                                                                          |
//                                                                                                                     |
//---------------------------------------------------------------------------------------------------------------------|

// @version=5
// @description - A Trader's Edge (ATE)_Library was created to assist in constructing COM Scanners

library(title="COM_Scanner_Library")

//== TICKERID FORMATION ==\\
// @function  
//     TickerIDs: You must form this single tickerID input string exactly as described in the scripts info panel (little gray 'i' that 
//     is circled at the end of the settings in the settings/input panel that you can hover your cursor over this 'i' to read the 
//     details of that particular input). IF the string is formed correctly then it will break up this single string parameter into 
//     a total of 40 separate strings which will be all of the tickerIDs that the script is using in your COM Scanner.
//   
// @param  _string  (string)
//     A maximum of 40 Tickers (ALL joined as 1 string for the input parameter) that is formulated EXACTLY as described 
//     within the tooltips of the TickerID inputs in my COM Scanner scripts: 
//     assets = input.text_area(tIDs, title="TickerIDs (MUST READ TOOLTIP)", group=g2, tooltip="Accepts 40 TICKERID's 
//     for each copy of the script on the chart. \n\n*** MUST FORMAT THIS WAY ***\n\n Each FULL tickerID 
//     (ie 'Exchange:ticker') must be separated by A SINGLE BLANK SPACE for correct formatting. The blank space tells 
//     the script where to break off the ticker to assign it to a variable to be used later in the script. So this input
//     will be a single string constructed from up to 40 tickerID's with a space between each tickerID 
//     (ie. 'BINANCE:BTCUSDT BINANCE:SXPUSDT BINANCE:XRPUSDT').", display=display.none)
// 
// @returns
//     Returns 40 output variables in the tuple (ie. between the '[]') with the separated TickerIDs,

export TickerIDs(simple string _string) =>	
    _regex = "^(.*?\\s)" 
	t01=str.match(_string,_regex), a01=str.replace(_string,t01,""),        
	t02=str.match(a01,_regex),     a02=str.replace(a01,t02,"")             
	t03=str.match(a02,_regex),     a03=str.replace(a02,t03,"")             
	t04=str.match(a03,_regex),     a04=str.replace(a03,t04,"")             
	t05=str.match(a04,_regex),     a05=str.replace(a04,t05,"")             
	t06=str.match(a05,_regex),     a06=str.replace(a05,t06,"")             
	t07=str.match(a06,_regex),     a07=str.replace(a06,t07,"")             
	t08=str.match(a07,_regex),     a08=str.replace(a07,t08,"")             
	t09=str.match(a08,_regex),     a09=str.replace(a08,t09,"")             
	t10=str.match(a09,_regex),     a10=str.replace(a09,t10,"")         
	t11=str.match(a10,_regex),     a11=str.replace(a10,t11,"")        
	t12=str.match(a11,_regex),     a12=str.replace(a11,t12,"")        
	t13=str.match(a12,_regex),     a13=str.replace(a12,t13,"")        
	t14=str.match(a13,_regex),     a14=str.replace(a13,t14,"")        
	t15=str.match(a14,_regex),     a15=str.replace(a14,t15,"")        
	t16=str.match(a15,_regex),     a16=str.replace(a15,t16,"")        
	t17=str.match(a16,_regex),     a17=str.replace(a16,t17,"")        
	t18=str.match(a17,_regex),     a18=str.replace(a17,t18,"")        
	t19=str.match(a18,_regex),     a19=str.replace(a18,t19,"")        
	t20=str.match(a19,_regex),     a20=str.replace(a19,t20,"")           
    t21=str.match(a20,_regex),     a21=str.replace(a20,t21,"") 
    t22=str.match(a21,_regex),     a22=str.replace(a21,t22,"") 
    t23=str.match(a22,_regex),     a23=str.replace(a22,t23,"") 
    t24=str.match(a23,_regex),     a24=str.replace(a23,t24,"") 
    t25=str.match(a24,_regex),     a25=str.replace(a24,t25,"") 
    t26=str.match(a25,_regex),     a26=str.replace(a25,t26,"") 
    t27=str.match(a26,_regex),     a27=str.replace(a26,t27,"") 
    t28=str.match(a27,_regex),     a28=str.replace(a27,t28,"") 
    t29=str.match(a28,_regex),     a29=str.replace(a28,t29,"") 
    t30=str.match(a29,_regex),     a30=str.replace(a29,t30,"") 
    t31=str.match(a30,_regex),     a31=str.replace(a30,t31,"") 
    t32=str.match(a31,_regex),     a32=str.replace(a31,t32,"") 
    t33=str.match(a32,_regex),     a33=str.replace(a32,t33,"") 
    t34=str.match(a33,_regex),     a34=str.replace(a33,t34,"") 
    t35=str.match(a34,_regex),     a35=str.replace(a34,t35,"") 
    t36=str.match(a35,_regex),     a36=str.replace(a35,t36,"") 
    t37=str.match(a36,_regex),     a37=str.replace(a36,t37,"") 
    t38=str.match(a37,_regex),     a38=str.replace(a37,t38,"") 
    t39=str.match(a38,_regex),     a39=str.replace(a38,t39,"") 
    t40=str.match(a39,_regex),     a40=str.replace(a39,t40,"") 

    [t01,t02,t03,t04,t05,t06,t07,t08,t09,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28,t29,t30,t31,t32,t33,t34,t35,t36,t37,t38,t39,t40]


//== ASSIGNMENT OF COLORS TO ASSETS AND LOCATIONS FOR ALERT LABELS ==\\
// @function  
//     Locations: This function is used when there's a desire to print an assets ALERT LABELS. A set Location on the scale is assigned to each asset.
//     This is created so that if a lot of alerts are triggered, they will stay relatively visible and not overlap each other.
//     If you set your '_firstLocation' parameter as 1, since there are a max of 40 assets that can be scanned, the 1st asset's location 
//     is assigned the value in the '_firstLocation' parameter, the 2nd asset's location is the (1st asset's location+1)...and so on.                            
// 
// @param  _firstLocation (simple int) 
//     Optional (starts at 1 if no parameter added). 
//     Location that you want the first asset to print its label if is triggered to do so. 
//     ie. loc2=loc1+1, loc3=loc2+1, etc.
// 
// @returns
//     Returns 40 variables for the locations for alert labels                                                                                                                       

export Locations(simple int _firstLocation=1) =>
    
    //== ALERT LABEL LOCATIONS ==\\
    var loc01=0, var loc02=0, var loc03=0, var loc04=0, var loc05=0, var loc06=0, var loc07=0, var loc08=0, var loc09=0, var loc10=0
    var loc11=0, var loc12=0, var loc13=0, var loc14=0, var loc15=0, var loc16=0, var loc17=0, var loc18=0, var loc19=0, var loc20=0
    var loc21=0, var loc22=0, var loc23=0, var loc24=0, var loc25=0, var loc26=0, var loc27=0, var loc28=0, var loc29=0, var loc30=0
    var loc31=0, var loc32=0, var loc33=0, var loc34=0, var loc35=0, var loc36=0, var loc37=0, var loc38=0, var loc39=0, var loc40=0 
    if barstate.isfirst
        loc01:=_firstLocation, loc02:=loc01+1, loc03:=loc02+1, loc04:=loc03+1, loc05:=loc04+1, loc06:=loc05+1, loc07:=loc06+1, loc08:=loc07+1, loc09:=loc08+1, loc10:=loc09+1
        loc11:=loc10+1,        loc12:=loc11+1, loc13:=loc12+1, loc14:=loc13+1, loc15:=loc14+1, loc16:=loc15+1, loc17:=loc16+1, loc18:=loc17+1, loc19:=loc18+1, loc20:=loc19+1
        loc21:=loc20+1,        loc22:=loc21+1, loc23:=loc22+1, loc24:=loc23+1, loc25:=loc24+1, loc26:=loc25+1, loc27:=loc26+1, loc28:=loc27+1, loc29:=loc28+1, loc30:=loc29+1
        loc31:=loc30+1,        loc32:=loc31+1, loc33:=loc32+1, loc34:=loc33+1, loc35:=loc34+1, loc36:=loc35+1, loc37:=loc36+1, loc38:=loc37+1, loc39:=loc38+1, loc40:=loc39+1

    [loc01,loc02,loc03,loc04,loc05,loc06,loc07,loc08,loc09,loc10,loc11,loc12,loc13,loc14,loc15,loc16,loc17,loc18,loc19,loc20,loc21,loc22,loc23,loc24,loc25,loc26,loc27,loc28,loc29,loc30,loc31,loc32,loc33,loc34,loc35,loc36,loc37,loc38,loc39,loc40]

//== INVALID TICKERID'S FROM SECURITY CALL ==\\
// @function                                
//     INVALID TICKERIDs: This is to add a table in the middle right of your chart that prints all the TickerID's that were either not formulated 
//     correctly in the '_source' input or that is not a valid symbol and should be changed. 
//
//     LABEL SIZES: This function sizes your Alert Trigger Labels according to the amount of Printed Bars the chart has printed within 
//     a set time period, while also keeping in mind the smallest relative reference size you input in the 'lblSzRfrnceInput' 
//     parameter of this function. A HIGHER % of Printed Bars(aka...more trades occurring for that asset on the exchange), 
//     the LARGER the Name Label will print, potentially showing you the better opportunities on the exchange to avoid 
//     exchange manipulation liquidations. 
//     *** SHOULD NOT be used as size of labels that are your asset Name Labels next to each asset's Line Plot...
//       if your COM Scanner includes these as you want these to be the same size for every asset so the larger ones dont cover the 
//       smaller ones if the plots are all close to each other ***
//
// @param  _barCnt  (float)           
//     Get the 1st variable('barCnt') from the Security function's tuple and input it as this functions 1st input 
//     parameter which will directly affect the size of the 2nd output variable ('alertTrigLabel') that is also outputted by this function. 
//
// @param _close  (float)            
//     Put your 'close' variable named '_close' from the security function here.
//                                           
// @param _securityTickerid  (string) 
//     Throughout the entire charts updates, if a '_close' value is never registered then the logic counts the asset as INVALID.
//     This will be the 1st TickerID variable (named _securityTickerid) outputted from the tuple of the TickeridForLabels() 
//     function above this one.
// 
// @param _invalidArray  (array string)  
//     Input the array from the original script that houses all of the invalidArray strings.
// 
// @param _tablePosition  (string)   
//     Optional (if parameter not included, it defaults to position.middle_right). Location on the chart you want the table printed. 
//     Possible strings include: position.top_center, position.top_left, position.top_right, position.middle_center, 
//       position.middle_left, position.middle_right, position.bottom_center, position.bottom_left, position.bottom_right.                                          
// 
// @param _stackVertical  (bool)     
//     Optional (if parameter not included, it defaults to true). All of the assets that are counted as INVALID will be 
//     created in a list. If you want this list to be prited as a column then input 'true' here, otherwise they will all be in a row.   
//                                           
// @param  _lblSzRfrnce  (string)          
//     Optional (if parameter not included, it defaults to size.small). This will be the size of the variable outputted 
//     by this function named 'assetNameLabel' BUT also affects the size of the output variable 'alertTrigLabel' as it uses this parameter's size
//     as the smallest size for 'alertTrigLabel' then uses the '_barCnt' parameter to determine the next sizes up depending on the "_barCnt" value.
// 
// @returns  ([string,string]) 
//     Returns 2 variables: 
//     1st output variable ('AssetNameLabel') is assigned to the size of the 'lblSzRfrnceInput' parameter. 
//     2nd output variable('alertTrigLabel') can be of variying sizes depending on the 'barCnt' parameter...BUT the smallest 
//     size possible for the 2nd output variable ('alertTrigLabel') will be the size set in the 'lblSzRfrnceInput' parameter.                                      

export LabelSize(float _barCnt, string _lblSzRfrnce=size.small) =>

    //== ASSET NAME LABELS SIZES & ALERT TRIGGER LABEL SIZES ==\\
	sz1 = _lblSzRfrnce=='1' ? size.tiny   : _lblSzRfrnce=='2' ? size.small  : size.normal                                                                                                                                                                                                                                                                  
	sz2 = _lblSzRfrnce=='1' ? size.small  : _lblSzRfrnce=='2' ? size.normal : size.large
	sz3 = _lblSzRfrnce=='1' ? size.normal : _lblSzRfrnce=='2' ? size.large  : size.huge
	assetNameLabel = sz1
	alertTrigLabel = _barCnt<35 ? sz1 : _barCnt>=35 and _barCnt<70 ? sz2 : sz3

    [assetNameLabel, alertTrigLabel]

export InvalidTickerIDs(series float _close, series string _securityTickerid, array<string>_invalidArray, simple string _tablePosition=position.middle_right, simple bool _stackVertical=true) =>             
    var bool valid=false    
    if not valid 
        if _close>0.0
            valid := true 
        if barstate.islast 
            array.push(_invalidArray,_securityTickerid) 
    var table resultTable = table.new(_tablePosition, 1, 1, bgcolor=#FFFF0000)
    if barstate.islast
        invalidList = array.join(_invalidArray, _stackVertical?'\n':', ')
        table.cell(resultTable, 0, 0, invalidList, text_color=chart.fg_color, text_size=size.small)

//== PRINTED BARCOUNT FILTER FUNCTION ==\\
// @function 
//     The Printed BarCount Filter looks back a User Defined amount of minutes and calculates the % of bars that have printed 
//     out of the TOTAL amount of bars that COULD HAVE been printed within the same amount of time.
//
// @param  _time  (int) 
//     The time associated with the chart of the particular asset that is being screened at that point. 
//
// @param  _barCntLength  (int) 
//     The amount of time (IN MINUTES) that you want the logic to look back at to calculate the % of bars that have actually 
//     printed in the span of time you input into this parameter.
//
// @param  _barCntPercentMin  (int) 
//     The minimum % of Printed Bars of the asset being screened has to be GREATER than the value set in this parameter 
//     for the output variable 'bc_gtg' to be true.
//
// @returns  ([float, bool])
//     Returns 2 outputs: 
//     1st is the % of Printed Bars that have printed within the within the span of time you input in the '_barCntLength' parameter.
//     2nd is true/false according to if the Printed BarCount % is above the threshold that you input into the '_barCntPercentMin' parameter.

export PrintedBarCount(int _time, int _barCntLength, int _barCntPercentMin) =>
    var times=array.new_int(0)
    if _barCntLength>0 and _barCntPercentMin>0
        array.push(times,_time) 
        if array.size(times)>0 
            while _time-array.get(times,0) >= _barCntLength*60000
                array.shift(times)
        barCnt = ((array.size(times)*(timeframe.in_seconds(timeframe.period)/60))/_barCntLength)*100
	    bc_gtg = barCnt>=_barCntPercentMin

	    [barCnt, bc_gtg] 
    else
        [na, na]


