//@version=5
library("map_custom_value_full")
//@type contains maps fields for creating array with map.Must be expanded if you want to create map other types 
export type maps_arrays
    map<int,int> maps_arrays_int = na
    map<string,int> maps_arrays_string = na

//@type contains array fields of all available array types for create value for maps
//@field int field for create int array
//@field float field for create float array
//@field string field for create string array
//@field bool field for create bool array
//@field color field for create color array
//@field table field for create table array
//@field polyline field for create polyline array
//@field linefill field for create linefill array
//@field line field for create line array
//@field label field for create label array
//@field arrays basic field for create must be specified as a value map
//@field maps_arrays field for create array from maps 
export type arrays 
    int[] int = na
    float[] float = na
    string[] string = na
    bool[] bool = na
    color[] color = na
    table[] table = na
    polyline[] polyline = na
    linefill[] linefill = na
    line[] line = na
    label[] label = na
    arrays[] arrays = na
    maps_arrays[] maps_arrays = na

//@type contains map fields of all available map types for create value for map 
//@field int_key_int_value field for create maps with key = int and value = int
//@field int_key_float_value field for create maps with key = int and value = float
//@field int_key_string_value field for create maps with key = int and value = string
//@field int_key_bool_value field for create maps with key = int and value = bool
//@field int_key_color_value field for create maps with key = int and value = color
//@field int_key_table_value field for create maps with key = int and value = table
//@field int_key_polyline_value field for create maps with key = int and value = polyline
//@field int_key_linefill_value field for create maps with key = int and value = linefill
//@field int_key_line_value field for create maps with key = int and value = line
//@field int_key_label_value field for create maps with key = int and value = label
//@field int_key_arrays_value field for create maps with key = int and value = arrays which can contain any fields of this type 
//@field float_key_int_value field for create maps with key = float and value = int
//@field float_key_float_value field for create maps with key = float and value = float
//@field float_key_string_value field for create maps with key = float and value = string
//@field float_key_bool_value field for create maps with key = float and value = bool
//@field float_key_color_value field for create maps with key = float and value = color
//@field float_key_table_value field for create maps with key = float and value = table
//@field float_key_polyline_value field for create maps with key = float and value = polyline
//@field float_key_linefill_value field for create maps with key = float and value = linefill
//@field float_key_line_value field for create maps with key = float and value = line
//@field float_key_label_value field for create maps with key = float and value = label
//@field float_key_arrays_value field for create maps with key = float and value = arrays which can contain any fields of this type 
//@field string_key_int_value field for create maps with key = string and value = int
//@field string_key_float_value field for create maps with key = string and value = float
//@field string_key_string_value field for create maps with key = string and value = string
//@field string_key_bool_value field for create maps with key = string and value = bool
//@field string_key_color_value field for create maps with key = string and value = color
//@field string_key_table_value field for create maps with key = string and value = table
//@field string_key_polyline_value field for create maps with key = string and value = polyline
//@field string_key_linefill_value field for create maps with key = string and value = linefill
//@field string_key_line_value field for create maps with key = string and value = line
//@field string_key_label_value field for create maps with key = string and value = label
//@field string_key_arrays_value field for create maps with key = string and value = arrays which can contain any fields of this type 
//@field bool_key_int_value field for create maps with key = bool and value = int
//@field bool_key_float_value field for create maps with key = bool and value = float
//@field bool_key_string_value field for create maps with key = bool and value = string
//@field bool_key_bool_value field for create maps with key = bool and value = bool
//@field bool_key_color_value field for create maps with key = bool and value = color
//@field bool_key_table_value field for create maps with key = bool and value = table
//@field bool_key_polyline_value field for create maps with key = bool and value = polyline
//@field bool_key_linefill_value field for create maps with key = bool and value = linefill
//@field bool_key_line_value field for create maps with key = bool and value = line
//@field bool_key_label_value field for create maps with key = bool and value = label
//@field bool_key_arrays_value field for create maps with key = bool and value = arrays which can contain any fields of this type 
//@field color_key_int_value field for create maps with key = color and value = int
//@field color_key_float_value field for create maps with key = color and value = float
//@field color_key_string_value field for create maps with key = color and value = string
//@field color_key_bool_value field for create maps with key = color and value = bool
//@field color_key_color_value field for create maps with key = color and value = color
//@field color_key_table_value field for create maps with key = color and value = table
//@field color_key_polyline_value field for create maps with key = color and value = polyline
//@field color_key_linefill_value field for create maps with key = color and value = linefill
//@field color_key_line_value field for create maps with key = color and value = line
//@field color_key_label_value field for create maps with key = color and value = label
//@field color_key_arrays_value field for create maps with key = color and value = arrays which can contain any fields of this type
export type maps
    //int_key
    map<int, int> int_key_int_value = na
    map<int, float> int_key_float_value = na
    map<int, string> int_key_string_value = na
    map<int, bool> int_key_bool_value = na
    map<int, color> int_key_color_value = na
    map<int, table> int_key_table_value = na
    map<int, polyline> int_key_polyline_value = na
    map<int, linefill> int_key_linefill_value = na
    map<int, line> int_key_line_value = na
    map<int, label> int_key_label_value = na
    map<int, arrays> int_key_arrays_value = na
    //float_key
    map<float, int> float_key_int_value = na
    map<float, float> float_key_float_value = na
    map<float, string> float_key_string_value = na
    map<float, bool> float_key_bool_value = na
    map<float, color> float_key_color_value = na
    map<float, table> float_key_table_value = na
    map<float, polyline> float_key_polyline_value = na
    map<float, linefill> float_key_linefill_value = na
    map<float, line> float_key_line_value = na
    map<float, label> float_key_label_value = na
    map<float, arrays> float_key_arrays_value = na
    //string_key
    map<string, int> string_key_int_value = na
    map<string, float> string_key_float_value = na
    map<string, string> string_key_string_value = na
    map<string, bool> string_key_bool_value = na
    map<string, color> string_key_color_value = na
    map<string, table> string_key_table_value = na
    map<string, polyline> string_key_polyline_value = na
    map<string, linefill> string_key_linefill_value = na
    map<string, line> string_key_line_value = na
    map<string, label> string_key_label_value = na
    map<string, arrays> string_key_arrays_value = na
    //bool_key
    map<bool, int> bool_key_int_value = na
    map<bool, float> bool_key_float_value = na
    map<bool, string> bool_key_string_value = na
    map<bool, bool> bool_key_bool_value = na
    map<bool, color> bool_key_color_value = na
    map<bool, table> bool_key_table_value = na
    map<bool, polyline> bool_key_polyline_value = na
    map<bool, linefill> bool_key_linefill_value = na
    map<bool, line> bool_key_line_value = na
    map<bool, label> bool_key_label_value = na
    map<bool, arrays> bool_key_arrays_value = na
    //color_key
    map<color, int> color_key_int_value = na
    map<color, float> color_key_float_value = na
    map<color, string> color_key_string_value = na
    map<color, bool> color_key_bool_value = na
    map<color, color> color_key_color_value = na
    map<color, table> color_key_table_value = na
    map<color, polyline> color_key_polyline_value = na
    map<color, linefill> color_key_linefill_value = na
    map<color, line> color_key_line_value = na
    map<color, label> color_key_label_value = na
    map<color, arrays> color_key_arrays_value = na

//put for array type 

//int key

export method put(map<int,arrays> id , int key, int[] value)=>
    id.put(key,arrays.new(int = value))

export method put(map<int,arrays> id , int key, float[] value)=>
    id.put(key,arrays.new(float = value))

export method put(map<int,arrays> id , int key, string[] value)=>
    id.put(key,arrays.new(string = value))

export method put(map<int,arrays> id , int key, bool[] value)=>
    id.put(key,arrays.new(bool = value))

export method put(map<int,arrays> id , int key, color[] value)=>
    id.put(key,arrays.new(color = value))

export method put(map<int,arrays> id , int key, table[] value)=>
    id.put(key,arrays.new(table = value))

export method put(map<int,arrays> id , int key, polyline[] value)=>
    id.put(key,arrays.new(polyline = value))

export method put(map<int,arrays> id , int key, linefill[] value)=>
    id.put(key,arrays.new(linefill = value))

export method put(map<int,arrays> id , int key, line[] value)=>
    id.put(key,arrays.new(line = value))

export method put(map<int,arrays> id , int key, label[] value)=>
    id.put(key,arrays.new(label = value))

export method put(map<int,arrays> id , int key, arrays[] value)=>
    id.put(key,arrays.new(arrays = value))

//float 
export method put(map<float,arrays> id , float key, int[] value)=>
    id.put(key,arrays.new(int = value))

export method put(map<float,arrays> id , float key, float[] value)=>
    id.put(key,arrays.new(float = value))

export method put(map<float,arrays> id , float key, string[] value)=>
    id.put(key,arrays.new(string = value))

export method put(map<float,arrays> id , float key, bool[] value)=>
    id.put(key,arrays.new(bool = value))

export method put(map<float,arrays> id , float key, color[] value)=>
    id.put(key,arrays.new(color = value))

export method put(map<float,arrays> id , float key, table[] value)=>
    id.put(key,arrays.new(table = value))

export method put(map<float,arrays> id , float key, polyline[] value)=>
    id.put(key,arrays.new(polyline = value))

export method put(map<float,arrays> id , float key, linefill[] value)=>
    id.put(key,arrays.new(linefill = value))

export method put(map<float,arrays> id , float key, line[] value)=>
    id.put(key,arrays.new(line = value))

export method put(map<float,arrays> id , float key, label[] value)=>
    id.put(key,arrays.new(label = value))

export method put(map<float,arrays> id , float key, arrays[] value)=>
    id.put(key,arrays.new(arrays = value))

//string
export method put(map<string,arrays> id , string key, int[] value)=>
    id.put(key,arrays.new(int = value))

export method put(map<string,arrays> id , string key, float[] value)=>
    id.put(key,arrays.new(float = value))

export method put(map<string,arrays> id , string key, string[] value)=>
    id.put(key,arrays.new(string = value))

export method put(map<string,arrays> id , string key, bool[] value)=>
    id.put(key,arrays.new(bool = value))

export method put(map<string,arrays> id , string key, color[] value)=>
    id.put(key,arrays.new(color = value))

export method put(map<string,arrays> id , string key, table[] value)=>
    id.put(key,arrays.new(table = value))

export method put(map<string,arrays> id , string key, polyline[] value)=>
    id.put(key,arrays.new(polyline = value))

export method put(map<string,arrays> id , string key, linefill[] value)=>
    id.put(key,arrays.new(linefill = value))

export method put(map<string,arrays> id , string key, line[] value)=>
    id.put(key,arrays.new(line = value))

export method put(map<string,arrays> id , string key, label[] value)=>
    id.put(key,arrays.new(label = value))

export method put(map<string,arrays> id , string key, arrays[] value)=>
    id.put(key,arrays.new(arrays = value))

//bool
export method put(map<bool,arrays> id , bool key, int[] value)=>
    id.put(key,arrays.new(bool = value))

export method put(map<bool,arrays> id , bool key, float[] value)=>
    id.put(key,arrays.new(float = value))

export method put(map<bool,arrays> id , bool key, string[] value)=>
    id.put(key,arrays.new(string = value))

export method put(map<bool,arrays> id , bool key, bool[] value)=>
    id.put(key,arrays.new(bool = value))

export method put(map<bool,arrays> id , bool key, color[] value)=>
    id.put(key,arrays.new(color = value))

export method put(map<bool,arrays> id , bool key, table[] value)=>
    id.put(key,arrays.new(table = value))

export method put(map<bool,arrays> id , bool key, polyline[] value)=>
    id.put(key,arrays.new(polyline = value))

export method put(map<bool,arrays> id , bool key, linefill[] value)=>
    id.put(key,arrays.new(linefill = value))

export method put(map<bool,arrays> id , bool key, line[] value)=>
    id.put(key,arrays.new(line = value))

export method put(map<bool,arrays> id , bool key, label[] value)=>
    id.put(key,arrays.new(label = value))

export method put(map<bool,arrays> id , bool key, arrays[] value)=>
    id.put(key,arrays.new(arrays = value))

//color
export method put(map<color,arrays> id , color key, int[] value)=>
    id.put(key,arrays.new(int = value))

export method put(map<color,arrays> id , color key, float[] value)=>
    id.put(key,arrays.new(float = value))

export method put(map<color,arrays> id , color key, string[] value)=>
    id.put(key,arrays.new(string = value))

export method put(map<color,arrays> id , color key, bool[] value)=>
    id.put(key,arrays.new(bool = value))

export method put(map<color,arrays> id , color key, color[] value)=>
    id.put(key,arrays.new(color = value))

export method put(map<color,arrays> id , color key, table[] value)=>
    id.put(key,arrays.new(table = value))

export method put(map<color,arrays> id , color key, polyline[] value)=>
    id.put(key,arrays.new(polyline = value))

export method put(map<color,arrays> id , color key, linefill[] value)=>
    id.put(key,arrays.new(linefill = value))

export method put(map<color,arrays> id , color key, line[] value)=>
    id.put(key,arrays.new(line = value))

export method put(map<color,arrays> id , color key, label[] value)=>
    id.put(key,arrays.new(label = value))

export method put(map<color,arrays> id , color key, arrays[] value)=>
    id.put(key,arrays.new(arrays = value))

//1. Create map with array value
map_int_arrays = map.new<string,arrays>()
map_int_arrays.put("int_array",array.from(1,2,3,4,5))
map_int_arrays.put("color_array",array.from(color.red,color.green))

//label.new(bar_index,close,str.tostring(map_int_arrays.get("int_array").int),color = map_int_arrays.get("color_array").color.get(0))

//2. Create map with map value
map_map_values = map.new<string,maps>()
map_map_values.put("mapas",maps.new(string_key_arrays_value = map_int_arrays))

//label.new(bar_index,open,str.tostring(map_map_values.get("mapas").string_key_arrays_value.get("int_array").int),color = map_int_arrays.get("color_array").color.get(1))


//3.maps with value in array with maps
map_int_int = map.new<int,int>()
map_int_int.put(1,1)
map_string_int = map.new<string,int>()
map_string_int.put("a",1)
map_arrays_map = map.new<color,arrays>()
map_arrays_map.put(color.red,arrays.new(maps_arrays = array.from(maps_arrays.new(maps_arrays_int = map_int_int),maps_arrays.new(maps_arrays_string = map_string_int))))
// label.new(bar_index,close-close/2,str.tostring(map_arrays_map.get(color.red).maps_arrays.get(0).maps_arrays_int.get(1)))

var example_usage = table.new(position = position.bottom_right, columns = 3, rows = 2, border_width = 1,border_color =color.black, frame_color = color.black, frame_width = 1)
if barstate.islast
    table.merge_cells(example_usage, 0, 0, 2, 0)
    table.cell(table_id = example_usage, column = 0, row = 0, text = "Example usage:")
    table.cell(table_id = example_usage, column = 0, row = 1, text = '1.Create map with array value:\n\n\n
     map_int_arrays = map.new<string,arrays>()\n\n
     map_int_arrays.put("int_array",array.from(1,2,3,4,5))\n\n
     map_int_arrays.put("color_array",array.from(color.red,color.green))\n\n\n
     we got map map_int_arrays\n\n
     which contains key int_array with value = field arrays type,\n\n
     need request field int and we get array int\n\n
     and key color_array with value = field arrays type,\n\n
     need request field color\n\n
     and we get array color\n\n
     method put which we usage\n\nput value in certain array field based on its type
     ',text_halign = text.align_left,text_valign = text.align_top)
    table.cell(table_id = example_usage, column = 1, row = 1, text = '2.Create map with map value:\n\n\n
     map_map_values = map.new<string,maps>()\n\n
     map_map_values.put("mapas",maps.new\n\n(string_key_arrays_value =
     map_int_arrays))\n\n\n
     we get map map_map_values\n\n
     which contains key mapas with value = field maps type,\n\n
     need request field string_key_arrays_value\n\n
     and we get map <string,int>\n\n
     which equal map map_int_arrays from example 1\n\n
     ',text_halign = text.align_left,text_valign = text.align_top)
    table.cell(table_id = example_usage, column = 2, row = 1, text = '3.Create maps with value in array with maps:\n\n\n
     map_int_int = map.new<int,int>()\n\n
     map_int_int.put(1,1)\n\n
     map_string_int = map.new<string,int>()\n\n
     map_string_int.put("a",1)\n\n
     map_arrays_map = map.new<color,arrays>()\n\n
     map_arrays_map.put(color.red,arrays.new(maps_arrays = \n\n
     array.from(maps_arrays.new(maps_arrays_int = map_int_int),\n\n
     maps_arrays.new(maps_arrays_string = map_string_int))))\n\n\n
     we got map map_arrays_map\n\n
     which contains key color.red with value = field arrays type,\n\n
     need request field maps_arrays\n\n
     and we get array from maps_arrays type\n\n
     need request 0 element and maps_arrays_int field\n\n
     and we get map map_int_int with key = 1 and value = 1\n\n
     need reques 1 element and maps_arrays_string field\n\n
     and we get map map_string_int which key = a and value = 1
      ',text_halign = text.align_left,text_valign = text.align_top)
