// @author algotraderdev
// @version=5
library('zigzag', overlay = true)

const int UP = 1
const int DOWN = -1

// @type Wrapper object for each bar's data on the chart.
// @field time The unix timestamp of the bar.
// @field x The index of the bar.
// @field high The high price of the bar.
// @field low The low price of the bar.
export type Bar
    int time = time
    int x = bar_index
    float high = high
    float low = low

// @function Gets the high point of the bar.
// @returns The high point of the bar.
method highPoint(Bar this) =>
    chart.point.new(this.time, this.x, this.high)

// @function Gets the low point of the bar.
// @returns The low point of the bar.
method lowPoint(Bar this) =>
    chart.point.new(this.time, this.x, this.low)

// @type Settings for the ZigZag algorithm.
// @field swingLen The default length of each swing.
// @field lineColor The color of the ZigZag lines.
// @field lineStyle The style of the ZigZag lines. Any of `line.style_solid`, `line.style_dashed`, and
//     `line.style_dotted`.
// @field lineWidth The width of the ZigZag lines.
export type Settings
    int swingLen = 5
    color lineColor = color.blue
    string lineStyle = line.style_solid
    int lineWidth = 1

// @type A swing in the chart.
// @field settings The settings object.
// @field prev The previous swing.
// @field start The starting point of the swing.
// @field end The ending point of the swing.
export type Swing
    Settings settings
    Swing prev
    chart.point start
    chart.point end

// @function Initializes the swing.
// @param settings The settings object.
// @param prev The previous swing.
// @param start The starting point of the swing.
// @param end The ending point of the swing.
// @returns The intialized instance.
method init(Swing this, Settings settings, Swing prev, chart.point start, chart.point end) =>
    this.settings := settings
    this.prev := prev
    this.start := start
    this.end := end
    this

// @function Gets the direction of the swing.
// @returns The direction of the swing.
method direction(Swing this) =>
    this.end.price >= this.start.price ? UP : DOWN

// @function Gets the length of the swing.
// @returns The length of the swing.
method len(Swing this) =>
    this.end.index - this.start.index + 1

// @function Gets the amplitude of the swing.
// @returns The amplitude of the swing.
method amplitude(Swing this) =>
    math.abs(this.end.price - this.start.price)

// @function Checks if the swing is valid. A swing is valid if it has enough bars or its amplitude is greater than the
//     its previous swing.
// @returns Whether the swing is valid.
method isValid(Swing this) =>
    if this.len() >= this.settings.swingLen
        true
    else if not na(this.prev)
        this.amplitude() > this.prev.amplitude()
    else
        false

// @function Checks if the swing is extended by the given bar.
// @param bar The bar to check against.
// @returns Whether the swing is extended by the given bar.
method isExtendedBy(Swing this, Bar bar) =>
    this.direction() == UP ? bar.high > this.end.price : bar.low < this.end.price

// @function Extends the swing to the given bar.
// @param The bar to extend to.
method extend(Swing this, Bar bar) =>
    chart.point end = this.direction() == UP ? bar.highPoint() : bar.lowPoint()
    this.end := end

// @type The ZigZag algorithm.
// @field _settings The settings object.
// @field _firstPoint The first pivot point of the ZigZag lines.
// @field _swings The identified swings.
// @field _swingPoly The polyline representation of the swings.
export type ZigZag
    Settings _settings
    chart.point _firstPoint
    Swing[] _swings

    polyline _swingsPoly

// @function Initializes the ZigZag object.
// @param settings The settings object.
// @returns The initialized instance.
export method init(ZigZag this, Settings settings) =>
    this._settings := settings
    this._swings := array.new<Swing>()
    this

// @function Updates the ZigZag by analyzing the new bar.
// @param bar The new bar. If `na` is provided, then automatically constructs a bar and uses it.
export method tick(ZigZag this, Bar bar = na) =>
    Bar b = na(bar) ? Bar.new() : bar
    int size = this._swings.size()
    if size == 0
        if na(this._firstPoint)
            // If there's no existing swing and no first point defined, then assume the low point of the
            // first bar is the first point.
            this._firstPoint := b.lowPoint()
        else
            // If the first point is defined and the current bar is lower than that, then use the low of the current bar
            // as the first point.
            if b.low < this._firstPoint.price
                this._firstPoint := b.lowPoint()
            else
                // If the first point is defined and the current bar is NOT lower than that, then create a new swing
                // from the first point to the high of the current bar.
                Swing swing = Swing.new().init(
                  this._settings,
                  prev = na,
                  start = this._firstPoint,
                  end = b.highPoint())
                this._swings.push(swing)
    else // size > 0
        // Current swing, which might not be valid yet.
        Swing s = this._swings.last()
        // The previous swing, which is guranteed to be valid already.
        Swing prevS = size > 1 ? this._swings.get(size - 2) : na
        bool extendedPrev = if not na(prevS)
            if prevS.isExtendedBy(b) and not s.isValid()
                // If the current swing is not valid, then delete it and extend the previous one.
                this._swings.pop()
                prevS.extend(b)
                true
        if not extendedPrev
            if s.isExtendedBy(b)
                s.extend(b)
            else if s.isValid()
                Swing newSwing = Swing.new().init(
                  this._settings,
                  prev = s,
                  start = s.end,
                  end = s.direction() == UP ? b.lowPoint() : b.highPoint())
                this._swings.push(newSwing)
    0

// @function Draws the ZigZag lines on the chart.
export method draw(ZigZag this) =>
    chart.point[] points = array.new<chart.point>()
    for [i, s] in this._swings
        if i == 0
            points.push(s.start)
        points.push(s.end)
    if not na(this._swingsPoly)
        this._swingsPoly.delete()
    this._swingsPoly := polyline.new(
      points,
      xloc = xloc.bar_time,
      line_color = this._settings.lineColor,
      line_style = this._settings.lineStyle,
      line_width = this._settings.lineWidth)

// @function Gets the identified swings.
// @param validOnly Whether to only return the valid swings (the ones that are long enough in terms of number of bars or
//     amplitude).
// @returns The identified swings.
export method swings(ZigZag this, bool validOnly = true) =>
    Swing[] swings = this._swings.copy()
    if validOnly and swings.size() > 0
        if not swings.last().isValid()
            swings.pop()
    swings


//#region Demo code below. These will NOT be executed in indicators or strategies that import this library.

import algotraderdev/material/1 as material

var ZigZag zz5 = ZigZag.new().init(
  Settings.new(
      swingLen = 5,
      lineColor = material.lightBlue(),
      lineStyle = line.style_solid,
      lineWidth = 2))
zz5.tick()

var ZigZag zz25 = ZigZag.new().init(
  Settings.new(
      swingLen = 25,
      lineColor = material.indigo(),
      lineStyle = line.style_dotted,
      lineWidth = 2))
zz25.tick()

var ZigZag zz125 = ZigZag.new().init(
  Settings.new(
      swingLen = 125,
      lineColor = material.purple(),
      lineStyle = line.style_dotted,
      lineWidth = 2))
zz125.tick()

if barstate.islast
    zz5.draw()
    zz25.draw()
    zz125.draw()

//#endregion