// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © KevZ3R1

//@version=6
indicator("Sessions with timeframe filter", "Disable sessions above", true, max_boxes_count = 100)

// ====== Predefinitions ======
h = high, l = low, t = time

// ====== Timeframe Filtering ======
timeframe_input = input.string("60min", "Timeframe Filter",
 ["1min", "2min", "3min", "4min", "5min", "10min", "15min", "20min", "25min", "30min", "35min", "40min", "45min", "50min", "55min", "60min", "90min", "120min", "180min", "240min", "360min", "480min", "720min"],
 "If chart timeframe greater than the input, it will disasble all sessions", display = display.status_line)

get_timeframe_number = str.replace(timeframe_input, "min", "")

intraday        = str.tonumber(timeframe.period) <= str.tonumber(get_timeframe_number)

// ====== Session Indicator ======
// === Inputs ===
show_major     = input.bool(true, "", group = "Session Box - Settings", inline = "SessionA")
show_minor     = input.bool(true, "", group = "Session Box - Settings", inline = "SessionB")
show_extra     = input.bool(true, "", group = "Session Box - Settings", inline = "SessionX")
session_major  = input.session("0700-1800", "Session A", group = "Session Time - Settings", inline = "SessionA", display = display.none)
session_minor  = input.session("1400-1800", "Session B", group = "Session Time - Settings", inline = "SessionB", display = display.none)
session_extra  = input.session("0700-0800", "Session X", group = "Session Time - Settings", inline = "SessionX", display = display.none)
majorbox_color = input.color(color.new(#2962FF, 88), "#1 Box Color", group = "Session Box - Settings", inline = "SessionA")
minorbox_color = input.color(color.new(#FF9800, 88), "#2 Box Color", group = "Session Box - Settings", inline = "SessionB")
extrabox_color = input.color(#00ff7b58, "#3 Box Color",              group = "Session Box - Settings", inline = "SessionX")
tz_int         = input.int(1, "Timezone in GMT", group = "Session Time - Settings", display = display.none)
timezone       = "GMT+" + str.tostring(tz_int)

// ====== Session Functions and Calculations ======
//#region
type boxing
    int   start_time = 0
    float b_top      = 0.0
    float b_btm      = 0.0
    box box = na
var boxing box_major  = boxing.new()
var boxing box_minor  = boxing.new()
var boxing extra_box  = boxing.new()

method main_box(boxing this, session_range, box_color) =>

    if session_range
        if not session_range[1]                          // If previous bar isn't in session, current high is box' high 
            this.b_top      := h                         // Result is that every candle has a box with its own high and low -> overlapping
            this.b_btm      := l     
            this.start_time := t                         // If previous bar isn't in session, start_time is current time.
        else
            this.start_time := (this[1]).start_time      // If previous bar is in session, starting time is previous bar's time. Irrelevant
            this.box.delete()                            // Delete overlapping if previous bar is in session
        this.b_top := h > this.b_top ? h : this.b_top    // If current bar's high is greater than the session start's high, it will be the new high, else it won't be updated
        this.b_btm := l < this.b_btm ? l : this.b_btm    // If current bar's low  is greater than the session start's low,  it will be the new low,  else it won't be updated

    // 2. Session Box Configurations
        this.box      := box.new(
         left         = this.start_time,
         right        = t,
         top          = this.b_top,
         bottom       = this.b_btm,
         xloc         = xloc.bar_time,
         border_width = 0,
         bgcolor      = box_color
         )
//#endregion

// ========== Plottings ==========
trading_time(session_range) => intraday and not na(time(timeframe.period, session_range, timezone))
major_session = show_major ? box_major.main_box(trading_time(session_major), majorbox_color) : na
minor_session = show_minor ? box_minor.main_box(trading_time(session_minor), minorbox_color) : na
extra_session = show_extra ? extra_box.main_box(trading_time(session_extra), extrabox_color) : na