//\__\         /\  \                     /\__\    
//    /:/ _/_       /::\  \       ___         /:/ _/_   
//   /:/ /\  \     /:/\:\__\     /\__\       /:/ /\  \  
//  /:/ /::\  \   /:/ /:/  /    /:/  /      /:/ /::\  \ 
//:/_/:/\:\__\ /:/_/:/  /    /:/__/      /:/_/:/\:\__\
// \:\/:/ /:/  / \:\/:/  /    /::\  \      \:\/:/ /:/  /
//  \::/ /:/  /   \::/__/    /:/\:\  \      \::/ /:/  / 
//   \/_/:/  /     \:\  \    \/__\:\  \      \/_/:/  /  
//     /:/  /       \:\__\        \:\__\       /:/  /   
//     \/__/         \/__/         \/__/       \/__/    
//
// Statistical Package for the Trading Sciences by Steversteves///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This is the library addendum to the SPTS indicator that features crutical statistical functions that can be quickly imported into your own indicators. 
//
/// Table of Contents/directory:        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// 1. Linear Regression (single independent and single dependent)  
// 2. Multiple Regression (2 independent variables, 1 dependent) 
// 3. Triple regression (linear regression on 3 independent variables) 
// 4. Nearest Known Neighbour (KNN) based regression 
// 5. Standard Error of Residual Assessment 
// 6. Z-Score 
// 7. Effect Size 
// 8. Confidence Interval 
// 9. Paired Sample Test 
// 10. Two Tailed T-Test 
// 11. Qualitative assessment of T-Test 
// 12. T-test table and p value assigner 
// 13. Correlation of two arrays 
// 14. Quadratic correlation (curvlinear) 
// 15. R Squared value of 2 arrays 
// 16. R Squared value of 2 floats 
// 17. Test of normality 
// 18. Simplified test of normality (for float variables) 
// 19. Forecast function 
// 20. ANOVA of 3 Independent Variables 

//@version=5
library("SPTS_StatsPakLib")

//  _      _                         _____                              _             
// | |    (_)                       |  __ \                            (_)            
// | |     _ _ __   ___  __ _ _ __  | |__) |___  __ _ _ __ ___  ___ ___ _  ___  _ __  
// | |    | | '_ \ / _ \/ _` | '__| |  _  // _ \/ _` | '__/ _ \/ __/ __| |/ _ \| '_ \ 
// | |____| | | | |  __/ (_| | |    | | \ \  __/ (_| | | |  __/\__ \__ \ | (_) | | | |
// |______|_|_| |_|\___|\__,_|_|    |_|  \_\___|\__, |_|  \___||___/___/_|\___/|_| |_|
//                                               __/ |                                
//                                              |___/                            
// @function creates a simple linear regression model between two variables. 
// @param x independent = independent variable of interest, dependent = the variable influenced by the independent, len = length of assessment, variable = should be a repeat of the independent variable and will 
// serve as the variable the model reviews to forecast forward. 
// @returns returns 6 float variables 
// result: The result of the regression model 
// pear_cor: The pearson correlation of the regresion model 
// rsqrd: the R2 of the regression model 
//std_err: the error of residuals 
//slope: the slope of the model (coefficient) 
//intercept: the intercept of the model (y = mx + b is y = slope x + intercept)

export f_linear_regression(float dependent, float independent, int len) =>
    float result = 0.0 
    float pear_cor = 0.0
    float rsqrd = 0.0  
    float std_err = 0.0 
    dep_array = array.new<float>() 
    indep_array = array.new<float>() 
    for i = 0 to len 
        array.push(dep_array, dependent[i])
        array.push(indep_array, independent[i])
    // Average 
    dep_avg = array.avg(dep_array) 
    indep_avg = array.avg(indep_array) 
    // Covariance
    integration_covariance = array.covariance(dep_array, indep_array) 
    variance = array.variance(indep_array) 
    slope = (integration_covariance / variance) 
    intercept = dep_avg - (indep_avg * slope) 
    result := (independent * slope) + intercept 
     // Correlation 
    stdev1 = array.stdev(dep_array)
    stdev2 = array.stdev(indep_array)
    xy_cov = array.covariance(dep_array, indep_array)
    pear_cor := xy_cov / (stdev1 * stdev2) 
    // R2 
    rsqrd := math.pow(pear_cor,2)
    // Standard Error
    se_residuals = array.new_float() 
    for i = 0 to len 
        array.push(se_residuals, (result[i] - dependent[i]) * (result[i] - dependent[i]))
    se_add = array.sum(se_residuals) 
    r1 = se_add / (len - 2) 
	std_err := math.sqrt(r1) 
    [result, pear_cor, rsqrd, std_err, slope, intercept]

// This function performs linear regression between two arrays. It will not return the values, it will simply export the model parameters (the slope, intercept and regression statistics)
// @function TODO: Performs linear regression on two, equal sized arrays 
// @param x TODO: 1) array with the independent variables (independent) and 2) array with the dependent variables (dependent) 
// @returns TODO: Returns 5 floats, R2, Correlation, standard error, slope and intercept 

export f_linear_regression_array(float[] independent, float[] dependent) =>
    result = 0.0 
    rsqrd = 0.0 
    pear_cor = 0.0 
    std_err = 0.0 
    slope = 0.0 
    intercept = 0.0 
    len = array.size(independent) - 1 

	y_array = array.new_float() 
	y_sq_array = array.new_float() 
	x_array = array.new_float() 
	x_sq_array = array.new_float() 
	xy_array = array.new_float() 

	// Loop functions
	for i = 0 to len
		array.push(y_array, array.get(dependent, i))
		array.push(y_sq_array, array.get(dependent, i) * array.get(dependent, i)) 
		array.push(x_array, array.get(independent, i))
		array.push(x_sq_array, array.get(independent, i) * array.get(independent,i)) 
		array.push(xy_array, array.get(independent,i) * array.get(dependent,i))
	
	// Regression Calculations 
	y = array.sum(y_array)
	y2 = array.sum(y_sq_array) 
	x = array.sum(x_array) 
	x2 = array.sum(x_sq_array)
	xy = array.sum(xy_array) 

	b1 = xy - (x * y) / len 
	bbb2 = x2 - (math.pow(x, 2) / len) 
	slope := (b1 / bbb2) 

	abc = y - (slope * x) 
	intercept := abc / len 
	result_array = array.new_float() 
	for i = 0 to len 
		array.push(result_array, array.get(independent, i) * slope + intercept)
     // Correlation 
    stdev1 = array.stdev(x_array)
    stdev2 = array.stdev(y_array)
    xy_cov = array.covariance(y_array, x_array)
    pear_cor := xy_cov / (stdev1 * stdev2) 
    // R2 
    rsqrd := math.pow(pear_cor,2)
    // Standard Error
    se_residuals = array.new_float() 
    for i = 0 to len 
        array.push(se_residuals, (array.get(result_array, i) - array.get(dependent, i)) * (array.get(result_array, i) - array.get(dependent,i)))
    se_add = array.sum(se_residuals) 
    r1 = se_add / (len - 2) 
	std_err := math.sqrt(r1) 
    [rsqrd, pear_cor, std_err, slope, intercept]
//  __  __       _ _   _       _        _____                              _             
// |  \/  |     | | | (_)     | |      |  __ \                            (_)            
// | \  / |_   _| | |_ _ _ __ | | ___  | |__) |___  __ _ _ __ ___  ___ ___ _  ___  _ __  
// | |\/| | | | | | __| | '_ \| |/ _ \ |  _  // _ \/ _` | '__/ _ \/ __/ __| |/ _ \| '_ \ 
// | |  | | |_| | | |_| | |_) | |  __/ | | \ \  __/ (_| | | |  __/\__ \__ \ | (_) | | | |
// |_|  |_|\__,_|_|\__|_| .__/|_|\___| |_|  \_\___|\__, |_|  \___||___/___/_|\___/|_| |_|
//                      | |                         __/ |                                
//                      |_|                        |___/                                
//
// @function TODO: creates a multiple regression model between two independent variables and 1 dependent variable. 
// @param x TODO: y = independent variable of interest, x1 = the first independent variable, x2 = the second independent variable
// len = length of assessment, 
//input1 & input2 = should be a repeat of the independent variables and will serve as the variable the model reviews to forecast forward. 
// @returns TODO: returns 7 float variables 
// result: The result of the regression model 
// pear_cor: The pearson correlation of the regresion model 
// rsqrd: the R2 of the regression model 
//std_err: the error of residuals 
//b1 & b2: the slopes of the model (coefficients) 
//intercept: the intercept of the model (y = mx + b is y = b1 x + b2 x + intercept)

export f_multiple_regression(float y, float x1, float x2, float input1, float input2, int len) =>
    result = 0.0 
    rsqrd = 0.0 
    pear_cor = 0.0 
    std_err = 0.0 
    b1 = 0.0 
    b2 = 0.0 
    b0 = 0.0 

    x1_sq = array.new_float() 
    x2_sq = array.new_float() 
    x1_array = array.new_float() 
    x2_array = array.new_float() 
    x1_y = array.new_float() 
    x2_y = array.new_float() 
    x1_x2 = array.new_float() 
    y_array = array.new_float() 


    for i = 0 to len 
        array.push(x1_sq, (x1[i] * x1[i]))
        array.push(x2_sq, (x2[i] * x2[i]))
        array.push(x1_array, x1[i]) 
        array.push(x2_array, x2[i])
        array.push(x1_y, (x1[i] * y[i]))
        array.push(x2_y, (x2[i] * y[i]))
        array.push(x1_x2, (x1[i] * x2[i])) 
        array.push(y_array, y[i]) 
    
    x1_sq_sum = array.sum(x1_sq) 
    x2_sq_sum = array.sum(x2_sq)
    x1_sum = array.sum(x1_array)
    x2_sum = array.sum(x2_array)
    x1_y_sum = array.sum(x1_y)
    x2_y_sum = array.sum(x2_y) 
    x1_x2_sum = array.sum(x1_x2) 
    y_sum = array.sum(y_array) 

    i1_x = x1_sq_sum - (math.pow(x1_sum, 2) / len) 
    i2_x = x2_sq_sum - (math.pow(x2_sum, 2) / len)
    i1_y = x1_y_sum - ((x1_sum * y_sum) / len)
    i2_y = x2_y_sum - ((x2_sum * y_sum) / len)

    ix1x2 = x1_x2_sum - ((x1_sum * x2_sum) / len)

    b1 := ((i2_x * i1_y) - (ix1x2 * i2_y)) / ((i1_x * i2_x) - math.pow(ix1x2, 2))
    b2 := ((i1_x * i2_y) - (ix1x2 * i1_y)) / ((i1_x * i2_x) - math.pow(ix1x2, 2))
    b0 := (y_sum / len) - (b1 * (x1_sum / len)) - (b2 * (x2_sum / len)) 

    result := (input1 * b1) + (input2 * b2) + b0 
    // Correlation 
    stdev1 = array.stdev(x1_x2)
    stdev2 = array.stdev(y_array)
    xy_cov = array.covariance(y_array, x1_x2)
    pear_cor := xy_cov / (stdev1 * stdev2) 
    // R2 
    rsqrd := math.pow(pear_cor,2)
    // Standard Error
    se_residuals = array.new_float() 
    for i = 0 to len 
        array.push(se_residuals, (result[i] - y[i]) * (result[i] - y[i]))
    se_add = array.sum(se_residuals) 
    r1 = se_add / (len - 2) 
	std_err := math.sqrt(r1) 
    [result, pear_cor, rsqrd, std_err, b1, b2, b0]

//Triple Independent Regression 
// @function  performs a multiple regression with up to 3 independent variables and 1 dependent variable 
// @param x dependent (y), the 3 independents (x1, x2, x3) and length of assessment 
// @returns result, error, p value, r2, coefficients for b1, b2, b3 and intercept (b0) 
export f_triple_regression(float y, float x1, float x2, float x3, int len) =>
    x1_array = array.new<float>() 
    x2_array = array.new<float>() 
    x3_array = array.new<float>() 
    y_array = array.new<float>() 
    float b1 = 0.0 
    float b2 = 0.0 
    float b3 = 0.0 
    float b0 = 0.0 
    float result = 0.0 
	float r = 0.0 
	float r2= 0.0 
	float se = 0.0 
    // Store variables
    for i = 0 to len 
        array.push(x1_array, x1[i])
        array.push(x2_array, x2[i])
        array.push(x3_array, x3[i])
        array.push(y_array, y[i])
    // Sums 
    x1_avg = array.avg(x1_array) 
    x2_avg = array.avg(x2_array)  
    x3_avg = array.avg(x3_array)   
    y_avg = array.avg(y_array)
    // Compute covariance 
    x1_cov = array.covariance(x1_array, y_array) 
    x2_cov = array.covariance(x2_array, y_array) 
    x3_cov = array.covariance(x3_array, y_array) 

    // Compute variance
    x1_variance = array.variance(x1_array)  
    x2_variance = array.variance(x2_array) 
    x3_variance = array.variance(x3_array)  

    // Calculate coefficients 
    b1 := (x1_cov / x1_variance) 
    b2 := (x2_cov / x2_variance) 
    b3 := (x3_cov / x3_variance) 
    b0 := y_avg - ((b1 * x1_avg) + (b2 * x2_avg) + (b3 * x3_avg))
    // Result 
    result := (x1 * b1) + (x2 * b2) + (x3 * b3) + b0 
	// Residuals 
	se_residuals = array.new_float() 
	for i = 0 to len 
		array.push(se_residuals, (result[i] - y[i]) * (result[i] - y[i]))
	
	se_add = array.sum(se_residuals) 

	r1 = se_add / (len - 2) 
	se := math.sqrt(r1) 
	// Correlation 
	cor_array = array.new_float() 
	for i = 0 to len 
		array.push(cor_array, result[i])
	correlation_cov = array.covariance(cor_array, y_array) 
	sd1 = array.stdev(cor_array) 
	sd2 = array.stdev(y_array) 
	r := correlation_cov / (sd1 * sd2) 
	r2 := math.pow(r, 2) 
	[result, se, r, r2, b1, b2, b3, b0]

//KNN Machine Learning based Regression 
// @function  performs up to 3 types of KNN based regression assessments 
// @param x the independent variable (x), dependent (y), the assessment type in string ("Last Instance" vs "Cluster" vs "Avg"), 
    // # of clusters and tolerance level for looking at clusters within a specified range. 
// @returns result, error of estimates, correlation and basic R2 
export knn_regression(float y, float x, int len, string last_instance_or_cluster_or_avg, int clusters, float tolerance) => 
    int index_of = 0
    float result = 0.0
    float error = 0.0 
    int inst = 0 
    float y_result = 0.0 
    float cor = 0.0 
    float r2 = 0.0 
    y_in = y[1] 
    ed_y = math.abs(math.sqrt(math.pow(y[1] - x[1],2)))
    ed_x = math.abs(math.sqrt(math.pow(y - x, 2)))
    ed_array = array.new<float>() 
    y_array = array.new<float>() 
    cluster_array = array.new<float>() 
    cluster_avg = array.new<float>() 
    for i = 0 to len 
        array.push(ed_array, ed_y[i]) 
        array.push(y_array, y_in[i])
    // Find KNN 
    if last_instance_or_cluster_or_avg == "Last Instance"
        if array.includes(ed_array, ed_x) 
            index_of := array.indexof(ed_array, ed_x) 
            result := array.get(y_array, index_of) 
        else if result[1] > 0 
            result := result[1] 
        else if result[2] > 0 
            result := result[2] 
        else if result[3] > 0 
            result := result[3] 
        else 
            na 
    else if last_instance_or_cluster_or_avg == "Avg" 
        for i = 0 to array.size(ed_array) - 1 
            if array.get(ed_array, i) == ed_x
                y_result += array.get(y_array, i)
                inst += 1 
                
        result := y_result / inst 
    else if last_instance_or_cluster_or_avg == "Cluster" 
        for i = 0 to array.size(ed_array) - 1 
            if array.get(ed_array, i) >= ed_x - tolerance and array.get(ed_array, i) <= ed_x + tolerance 
                array.push(cluster_array, array.get(y_array, i))
        if array.size(cluster_array) - 1 > clusters 
            for i = 0 to clusters 
                array.push(cluster_avg, array.get(cluster_array, i))
            result := array.avg(cluster_avg) 


    // Error 
    bool above_result = y > result 
    bool below_result = y < result 
    above_arr = array.new<float>() 
    below_arr = array.new<float>() 
    above_dif = y - result 
    below_dif = result - y 
    for i = 0 to len 
        if above_result[i]
            array.push(above_arr, above_dif[i])
        else if below_result[i] 
            array.push(below_arr, below_dif[i])
        else 
            na 
    avg1 = array.avg(above_arr) 
    avg2 = array.avg(below_arr) 
    error := math.avg(avg1, avg2) 
    // Correlation 
    result_array = array.new<float>() 
    for i = 0 to array.size(y_array) - 1 
        array.push(result_array, result[i])
    cov = array.covariance(result_array, y_array) 
    y_sd = array.stdev(y_array) 
    r_sd = array.stdev(result_array) 
    cor := cov / (y_sd * r_sd) 
    // R2 
    r2 := math.pow(cor, 2) 
    [result, error, cor, r2]
//  ______                              __   _____           _     _             _     
// |  ____|                            / _| |  __ \         (_)   | |           | |    
// | |__   _ __ _ __ ___  _ __    ___ | |_  | |__) |___  ___ _  __| |_   _  __ _| |___ 
// |  __| | '__| '__/ _ \| '__|  / _ \|  _| |  _  // _ \/ __| |/ _` | | | |/ _` | / __|
// | |____| |  | | | (_) | |    | (_) | |   | | \ \  __/\__ \ | (_| | |_| | (_| | \__ \
// |______|_|  |_|  \___/|_|     \___/|_|   |_|  \_\___||___/_|\__,_|\__,_|\__,_|_|___/
                                                                                     
// @function x TODO: performs an assessment on the error of residuals, can be used with any variable in which there are residual values (such as moving averages or more comlpex models) 
// param x TODO: result is the output, for example, if you are calculating the residuals of a 200 EMA, the result would be the 200 EMA
// dependent: is the dependent variable. In the above example with the 200 EMA, your dependent would be the source for your 200 EMA 
// @returns x TODO: the standard error of the residual, which can then be multiplied by standard deviations or used as is. 

export f_stanard_error(float result, float dependent, int length) =>
	se_residuals = array.new_float() 
	for i = 0 to length 
		array.push(se_residuals, (result[i] * dependent[i]) * (result[i] * dependent[i]))
	
	se_add = array.sum(se_residuals) 

	r1 = se_add / (length - 2) 
	se= math.sqrt(r1) 

//  ______     _____                    
// |___  /    / ____|                   
//    / /____| (___   ___ ___  _ __ ___ 
//   / /______\___ \ / __/ _ \| '__/ _ \
//  / /__     ____) | (_| (_) | | |  __/
// /_____|   |_____/ \___\___/|_|  \___|
//                                                                          
// @function TODO: Calculates the z-score 
// @param x TODO: input the variable of interest and the length of assessment 
// @returns TODO: returns float z-score 

export f_zscore(float variable, int length) =>
	z = (variable - ta.sma(variable, length)) / ta.stdev(variable, length) 
	
//  ______  __  __          _      _____ _         
// |  ____|/ _|/ _|        | |    / ____(_)        
// | |__  | |_| |_ ___  ___| |_  | (___  _ _______ 
// |  __| |  _|  _/ _ \/ __| __|  \___ \| |_  / _ \
// | |____| | | ||  __/ (__| |_   ____) | |/ /  __/
// |______|_| |_| \___|\___|\__| |_____/|_/___\___|
                                                                                           
// @function TODO: Calculates the effect size between two arrays of equal scale. 
// @param x TODO: parameters are the 2 arrays you wish to calculate the effect size for. It will use the entire size of each array, so its important to ensure they are of equal size. 
// @returns TODO: returns the effect size (float) 
export f_effect_size(float[] array1, float[] array2) => 
    float a1_sd = 0.0 
    float a2_sd = 0.0 
    int a1_size = 0 
    int a2_size = 0 
    float ps = 0.0 
    float avg1 = 0.0 
    float avg2 = 0.0 
    a1_sd := array.stdev(array1) 
    a2_sd := array.stdev(array2) 
    // Pooled standard deviation 
    a1_size := array.size(array1) 
    a2_size := array.size(array2) 
    sp1 = ((a1_size - 1) * (math.pow(a1_sd,2))) + ((a2_size - 1) * (math.pow(a2_sd,2)))
    sp2 = (a1_size + a2_size) - 2 
    sp3 = (sp1 / sp2) 
    ps := math.sqrt(sp3) 

    avg1 := array.avg(array1)
    avg2 := array.avg(array2) 

    es = (avg1 - avg2) / ps 

//   _____             __ _     _                       _____       _                       _ 
//  / ____|           / _(_)   | |                     |_   _|     | |                     | |
// | |     ___  _ __ | |_ _  __| | ___ _ __   ___ ___    | |  _ __ | |_ ___ _ ____   ____ _| |
// | |    / _ \| '_ \|  _| |/ _` |/ _ \ '_ \ / __/ _ \   | | | '_ \| __/ _ \ '__\ \ / / _` | |
// | |___| (_) | | | | | | | (_| |  __/ | | | (_|  __/  _| |_| | | | ||  __/ |   \ V / (_| | |
//  \_____\___/|_| |_|_| |_|\__,_|\___|_| |_|\___\___| |_____|_| |_|\__\___|_|    \_/ \__,_|_|
                                                                                            
// @function TODO: Calculates the confidence interval between two arrays 
// @param x TODO: parameters are the 2 arrays you wish to calculate, as well as the desired confidence level (generally 1.96)  
// @returns TODO: returns the upper_bound and lower_bound cofidence interval as float values 
export f_confidence_interval(float[] array1, float[] array2, float ci_input) =>
    upper_bound = 0.0 
    lower_bound = 0.0 
    // Standard Error 
    avg1 = array.avg(array1)
    avg2 = array.avg(array2) 
    asd1 = array.stdev(array1) 
    asd2 = array.stdev(array2) 
    se1 = (math.pow(asd1,2) / array.size(array1))
    se2 = (math.pow(asd2,2) / array.size(array2))
    se3 = (se1 + se2) 
    s_er = math.sqrt(se3) 
    // Confidence interval 
    avg_dif = (avg1 - avg2)
    ci = s_er * ci_input 
    upper_bound := avg_dif + ci 
    lower_bound := avg_dif - ci 
    [upper_bound, lower_bound]


//  _____      _              _    _____                       _        _______ 
// |  __ \    (_)            | |  / ____|                     | |      |__   __|
// | |__) |_ _ _ _ __ ___  __| | | (___   __ _ _ __ ___  _ __ | | ___     | |   
// |  ___/ _` | | '__/ _ \/ _` |  \___ \ / _` | '_ ` _ \| '_ \| |/ _ \    | |   
// | |  | (_| | | | |  __/ (_| |  ____) | (_| | | | | | | |_) | |  __/    | |   
// |_|   \__,_|_|_|  \___|\__,_| |_____/ \__,_|_| |_| |_| .__/|_|\___|    |_|   
//                                                     | |                     
//                                                     |_|                    
// Paired Sample t-test 
// This will output the t_statistic (T-Statistic) and the dfs (Degress of Freedom), similar to the one tailed test. 
// @function TODO: Performs a paired sample t-test 
// @param x TODO: parameter input include the two sources for comparison of the t-test and the length of the t-test
// @returns TODO: Returns the t-statistic and degrees of freedom of a paired sample t-test
export paired_sample_t(float src1, float src2, int len) => 
    t_static = 0.0 
    dfs = 0.0 
    dif = array.new_float() 
    for i = 0 to len
        array.push(dif, src1[i] - src2[i]) 
    avg_dif = array.avg(dif) 
    stdev_dif = array.stdev(dif) 
    t1 = stdev_dif / math.sqrt(array.size(dif))
    t_static := avg_dif / t1 
    dfs := array.size(dif) - 1 
    [t_static, dfs]
    // End of function 

//  _______              _______    _ _          _   _______  _______        _   
// |__   __|            |__   __|  (_) |        | | |__   __||__   __|      | |  
//    | |_      _____      | | __ _ _| | ___  __| |    | |______| | ___  ___| |_ 
//    | \ \ /\ / / _ \     | |/ _` | | |/ _ \/ _` |    | |______| |/ _ \/ __| __|
//    | |\ V  V / (_) |    | | (_| | | |  __/ (_| |    | |      | |  __/\__ \ |_ 
//    |_| \_/\_/ \___/     |_|\__,_|_|_|\___|\__,_|    |_|      |_|\___||___/\__|
//                                                                              
// Two Tailed T-Test
// Similar to the one-tailed. You need to push the two variables you wish to analyze into an array. The rest remains the same! It will export the degress of freedom and the t-statistic.
// @function TODO: Perofrms a two tailed t-test 
// @param x TODO: parameter input include the two sources for comparison which need to be pushed to two arrays 
// @returns TODO: Returns the t-statistic and degrees of freedom of a two_tail_t_test sample t-test

export two_tail_t_test(float[] array1, float[]array2) =>
    tstat = 0.0 
    df6 = 0.0 
    avg1 = array.avg(array1) 
    avg2 = array.avg(array2) 
    sd1 = array.stdev(array1) 
    sd2 = array.stdev(array2) 
    d1 = (avg1 - avg2) 
    d2 = (math.pow(sd1,2) / array.size(array1)) + (math.pow(sd2,2) / array.size(array2))
    d3 = math.sqrt(d2) 
    tstat := (d1 / d3) 
    //
    df1 = (math.pow(sd1,2) / array.size(array1))
    df2 = (math.pow(sd2,2) / array.size(array2))
    df3 = (df1 + df2) 
    df4 = math.pow(d3, 2)
    df5 = ((1/ array.size(array1)) * math.pow(df1, 2)) + ((1 / array.size(array2)) * math.pow(df2,2))
    df6 := df4 / df5 
    [tstat, df6]
    // End of function 

//  _______  _______    _     _      
// |__   __||__   __|  | |   | |     
//    | |______| | __ _| |__ | | ___ 
//    | |______| |/ _` | '_ \| |/ _ \
//    | |      | | (_| | |_) | |  __/
//    |_|      |_|\__,_|_.__/|_|\___|
                                   
                                  

// The T-table // 
// @function TODO: This is to make a qualitative assessment of your paired and single sample t-test 
// @param x TODO: add you input the t_stat and degrees of freedom for your t-est 
// @returns TODO: the function will return 2 string variables and 1 colour variable. The 2 string variables indicate whether the results are significant or not and the colour will 
// output red for insigificant and green for significant 

export t_table_analysis(float t_stat, float df) => 
    string p_value = na 
    string p_imp = na 
    color col = na 
    if df <= 1 and t_stat < 3.3 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 1 and t_stat >= 3.3 
        p_value := "p = 0.05"
        p_imp := "The results are significant."
    else if df > 1 and df <= 2 and t_stat < 2.9 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <=2 and df > 1 and t_stat >= 2.9 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 3 and df > 2 and t_stat < 2.3 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 3 and df > 2 and t_stat >= 2.3 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 4 and df > 3 and t_stat < 2.1 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <=4 and df > 3 and t_stat >= 2.1 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 5 and df > 4 and t_stat < 2
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 5 and df > 4 and t_stat >= 2 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 6 and df > 5 and t_stat < 1.9 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 6 and df > 5 and t_stat >= 1.9 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 7 and df > 6 and t_stat < 1.8 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 7 and df > 6 and t_stat >= 1.8 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 8 and df > 7 and t_stat < 1.8 // ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 8 and df > 7 and t_stat >= 1.8 // signific
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 9 and df > 8 and t_stat <1.82 // ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 9 and df > 8 and t_stat >= 1.82// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 10 and df > 9 and t_stat < 1.81// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 10 and df > 9 and t_stat >= 1.81// sig
        p_value := "p <= 0.05"
        p_imp := "The results are significant." 
    else if df <= 11 and df > 10 and t_stat < 1.79// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 11 and df > 10 and t_stat >= 1.79// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 12 and df > 11 and t_stat < 1.78 // ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 12 and df > 11 and t_stat >= 1.78// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 13 and df > 12 and t_stat < 1.77// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 13 and df > 12 and t_stat >= 1.77// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 14 and df > 13 and t_stat < 1.76// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 14 and df > 13 and t_stat >= 1.76// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 15 and df > 14 and t_stat < 1.75// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 15 and df > 13 and t_stat >= 1.75// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 16 and df > 15 and t_stat < 1.746// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 16 and df > 15 and t_stat >= 1.746// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 17 and df > 16 and t_stat < 1.74// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 17 and df > 16 and t_stat > 1.74 // sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 18 and df > 17 and t_stat < 1.73// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 18 and df > 17 and t_stat >= 1.73// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 19 and df > 18 and t_stat < 1.729 // ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 19 and df > 18 and t_stat >= 1.729 // sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 20 and df > 19  and t_stat < 1.725// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 20 and df > 19 and t_stat >= 1.725// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 21 and df > 20 and t_stat < 1.721 // ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 21 and df > 20 and t_stat >= 1.721// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 22 and df > 21 and t_stat < 1.717// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 22 and df > 21 and t_stat >= 1.717 // sig
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 23 and df > 22 and t_stat < 1.714 // ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 23 and df > 22 and t_stat >= 1.714// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 24 and df > 23 and t_stat < 1.711// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 24 and df > 23 and t_stat >= 1.711// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 25 and df > 24 and t_stat < 1.708// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 25 and df > 24  and t_stat >= 1.708// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 26 and df > 25 and t_stat < 1.706// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 26 and df > 25 and t_stat >= 1.706 // sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 27 and df > 26 and t_stat < 1.703// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 27 and df > 26 and t_stat >= 1.703// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 28 and df > 27 and t_stat < 1.701// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 28 and df > 27 and t_stat >= 1.701// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 29 and df > 28 and t_stat < 1.699// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 29 and df > 28 and t_stat >= 1.699// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 30 and df > 29 and t_stat < 1.697// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 30 and df > 29 and t_stat >= 1.697// sig
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 40 and df > 30 and t_stat < 1.684// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 40 and df > 30 and t_stat >= 1.684// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 60 and df > 40 and t_stat < 1.671 // ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 60 and df > 40 and t_stat >= 1.671 // sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 80 and df > 60 and t_stat < 1.664// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 80 and df > 60 and t_stat >= 1.664// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df <= 100 and df > 80 and t_stat < 1.660// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df <= 100 and df > 80 and t_stat >= 1.660// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    else if df > 100 and t_stat < 1.646// ns 
        p_value := "p > 0.05"
        p_imp := "The results are not significant."
        col := color.red 
    else if df > 100 and t_stat >= 1.646// sig 
        p_value := "p <= 0.05"
        p_imp := "The results are significant."
    [p_value, p_imp, col]
    // End of function 

// @function TODO: This performs a quantaitive assessment on your t-tests to determine the statistical significance p value 
// @param x TODO: add the dif (degrees of freedom) and t_stat (t-statistic) of your t_test to get the results. 
// @returns TODO: The function will return 1 float variable, the p value of the t-test. 


export t_table_p_value(float df, float t_stat)=>  
    sig = 0.0
    a1 = array.from(0.000, 1.000, 1.376, 1.963, 3.078, 6.314, 12.71, 31.82, 63.66, 318.31, 636.62)
    a2 = array.from(0.000, 0.816, 1.061, 1.386, 1.886, 2.920, 4.303, 6.965, 9.925, 22.327, 31.599)
    a3 = array.from( 0.000, 0.765, 0.978, 1.250, 1.638, 2.353, 3.182, 4.541, 5.841, 10.215, 12.924)
    search_arr = array.from( 0.000, 0.741, 0.941, 1.190, 1.533, 2.132, 2.776, 3.747, 4.604, 7.173, 8.610)
    search_arr1 = array.from(0.000, 0.727, 0.920, 1.156, 1.476, 2.015, 2.571, 3.365, 4.032, 5.893, 6.869)
    search_arr2 = array.from( 0.000, 0.718, 0.906, 1.134, 1.440, 1.943, 2.447, 3.143, 3.707, 5.208, 5.959)
    search_arr3 = array.from( 0.000, 0.711, 0.896, 1.119, 1.415, 1.895, 2.365, 2.998, 3.499, 4.785, 5.408)
    search_arr4 = array.from(0.000, 0.706, 0.889, 1.108, 1.397, 1.860, 2.306, 2.896, 3.355, 4.501, 5.041)
    search_arr5 = array.from(0.000, 0.703, 0.883, 1.100, 1.383, 1.833, 2.262, 2.821, 3.250, 4.297, 4.781)
    search_arr6 = array.from(0.000, 0.700, 0.879, 1.093, 1.372, 1.812, 2.228, 2.764, 3.169, 4.144, 4.587)
    search_arr7 = array.from( 0.000, 0.687, 0.860, 1.064, 1.325, 1.725, 2.086, 2.528, 2.845, 3.552, 3.850)
    search_arr8 = array.from(0.000, 0.683, 0.854, 1.055, 1.310, 1.697, 2.042, 2.457, 2.750, 3.385, 3.646)
    search_arr9 = array.from(0.000, 0.681, 0.851, 1.050, 1.303, 1.684, 2.021, 2.423, 2.704, 3.307, 3.551)
    search_arr10 = array.from(0.000, 0.679, 0.848, 1.045, 1.296, 1.671, 2.000, 2.390, 2.660, 3.232, 3.460)
    search_arr11 = array.from(0.000, 0.678, 0.846, 1.043, 1.292, 1.664, 1.990, 2.374, 2.639, 3.195, 3.416)
    search_arr12 = array.from(0.000, 0.677, 0.845, 1.042, 1.290, 1.660, 1.984, 2.364, 2.626, 3.174, 3.390)
    search_arr13 = array.from( 0.000, 0.675, 0.842, 1.037, 1.282, 1.646, 1.962, 2.330, 2.581, 3.098, 3.300)
    if df <= 1 
        sig := t_stat <= array.get(a1, 0) ? 0.5 : t_stat <= array.get(a1, 1) ? 0.25 : t_stat <= array.get(a1, 2) ? 0.20 : t_stat <= array.get(a1, 3) ? 0.15 : t_stat <= array.get(a1, 4) ? 0.10 : t_stat <= array.get(a1, 5) ? 0.05 : t_stat <= array.get(a1, 6) ? 0.025 : t_stat <= array.get(a1, 7) ? 0.01 : t_stat <= array.get(a1, 8) ? 0.005 : t_stat <= array.get(a1, 9) ? 0.001 : t_stat >= array.get(a1, 10) ? 0.0005 : na
    else if df <= 2 and df > 1
        sig := t_stat <= array.get(a2, 0) ? 0.5 : t_stat <= array.get(a2, 1) ? 0.25 : t_stat <= array.get(a2, 2) ? 0.20 : t_stat <= array.get(a2, 3) ? 0.15 : t_stat <= array.get(a2, 4) ? 0.10 : t_stat <= array.get(a2, 5) ? 0.05 : t_stat <= array.get(a2, 6) ? 0.025 : t_stat <= array.get(a2, 7) ? 0.01 : t_stat <= array.get(a2, 8) ? 0.005 : t_stat <= array.get(a2, 9) ? 0.001 : t_stat >= array.get(a2, 10) ? 0.0005 : na
    else if df <= 3 and df > 2 
        sig := t_stat <= array.get(a3, 0) ? 0.5 : t_stat <= array.get(a3, 1) ? 0.25 : t_stat <= array.get(a3, 2) ? 0.20 : t_stat <= array.get(a3, 3) ? 0.15 : t_stat <= array.get(a3, 4) ? 0.10 : t_stat <= array.get(a3, 5) ? 0.05 : t_stat <= array.get(a3, 6) ? 0.025 : t_stat <= array.get(a3, 7) ? 0.01 : t_stat <= array.get(a3, 8) ? 0.005 : t_stat <= array.get(a3, 9) ? 0.001 : t_stat >= array.get(a3, 10) ? 0.0005 : na
    else if df <= 4 and df > 3 
        sig := t_stat <= array.get(search_arr, 0) ? 0.5 : t_stat <= array.get(search_arr, 1) ? 0.20 : t_stat <= array.get(search_arr, 2) ? 0.25 : t_stat <= array.get(search_arr, 3) ? 0.15 : t_stat <= array.get(search_arr, 4) ? 0.10 : t_stat <= array.get(search_arr, 5) ? 0.05 : t_stat <= array.get(search_arr, 6) ? 0.025 : t_stat <= array.get(search_arr, 7) ? 0.01 : t_stat <= array.get(search_arr, 8) ? 0.005 : t_stat <= array.get(search_arr, 9) ? 0.001 : t_stat >= array.get(search_arr, 10) ? 0.0005 : 1
    else if df <= 5 and df > 4 
        sig := t_stat <= array.get(search_arr1, 0) ? 0.5 : t_stat <= array.get(search_arr1, 1) ? 0.20 : t_stat <= array.get(search_arr1, 2) ? 0.25 : t_stat <= array.get(search_arr1, 3) ? 0.15 : t_stat <= array.get(search_arr1, 4) ? 0.10 : t_stat <= array.get(search_arr1, 5) ? 0.05 : t_stat <= array.get(search_arr1, 6) ? 0.025 : t_stat <= array.get(search_arr1, 7) ? 0.01 : t_stat <= array.get(search_arr1, 8) ? 0.005 : t_stat <= array.get(search_arr1, 9) ? 0.001 : t_stat >= array.get(search_arr1, 10) ? 0.0005 : 1
    else if df <= 6 and df > 5 
        sig := t_stat <= array.get(search_arr2, 0) ? 0.5 : t_stat <= array.get(search_arr2, 1) ? 0.20 : t_stat <= array.get(search_arr2, 2) ? 0.25 : t_stat <= array.get(search_arr2, 3) ? 0.15 : t_stat <= array.get(search_arr2, 4) ? 0.10 : t_stat <= array.get(search_arr2, 5) ? 0.05 : t_stat <= array.get(search_arr2, 6) ? 0.025 : t_stat <= array.get(search_arr2, 7) ? 0.01 : t_stat <= array.get(search_arr2, 8) ? 0.005 : t_stat <= array.get(search_arr2, 9) ? 0.001 : t_stat >= array.get(search_arr2, 10) ? 0.0005 : 1
    else if df <= 7 and df > 6 
        sig := t_stat <= array.get(search_arr3, 0) ? 0.5 : t_stat <= array.get(search_arr3, 1) ? 0.20 : t_stat <= array.get(search_arr3, 2) ? 0.25 : t_stat <= array.get(search_arr3, 3) ? 0.15 : t_stat <= array.get(search_arr3, 4) ? 0.10 : t_stat <= array.get(search_arr3, 5) ? 0.05 : t_stat <= array.get(search_arr3, 6) ? 0.025 : t_stat <= array.get(search_arr3, 7) ? 0.01 : t_stat <= array.get(search_arr3, 8) ? 0.005 : t_stat <= array.get(search_arr3, 9) ? 0.001 : t_stat >= array.get(search_arr3, 10) ? 0.0005 : 1
    else if df <= 8 and df > 7
        sig := t_stat <= array.get(search_arr4, 0) ? 0.5 : t_stat <= array.get(search_arr4, 1) ? 0.20 : t_stat <= array.get(search_arr4, 2) ? 0.25 : t_stat <= array.get(search_arr4, 3) ? 0.15 : t_stat <= array.get(search_arr4, 4) ? 0.10 : t_stat <= array.get(search_arr4, 5) ? 0.05 : t_stat <= array.get(search_arr4, 6) ? 0.025 : t_stat <= array.get(search_arr4, 7) ? 0.01 : t_stat <= array.get(search_arr4, 8) ? 0.005 : t_stat <= array.get(search_arr4, 9) ? 0.001 : t_stat >= array.get(search_arr4, 10) ? 0.0005 : 1
    else if df <= 9 and df > 8
        sig := t_stat <= array.get(search_arr5, 0) ? 0.5 : t_stat <= array.get(search_arr5, 1) ? 0.20 : t_stat <= array.get(search_arr5, 2) ? 0.25 : t_stat <= array.get(search_arr5, 3) ? 0.15 : t_stat <= array.get(search_arr5, 4) ? 0.10 : t_stat <= array.get(search_arr5, 5) ? 0.05 : t_stat <= array.get(search_arr5, 6) ? 0.025 : t_stat <= array.get(search_arr5, 7) ? 0.01 : t_stat <= array.get(search_arr5, 8) ? 0.005 : t_stat <= array.get(search_arr5, 9) ? 0.001 : t_stat >= array.get(search_arr5, 10) ? 0.0005 : 1
    else if df <= 10 and df > 9 
        sig := t_stat <= array.get(search_arr6, 0) ? 0.5 : t_stat <= array.get(search_arr6, 1) ? 0.20 : t_stat <= array.get(search_arr6, 2) ? 0.25 : t_stat <= array.get(search_arr6, 3) ? 0.15 : t_stat <= array.get(search_arr6, 4) ? 0.10 : t_stat <= array.get(search_arr6, 5) ? 0.05 : t_stat <= array.get(search_arr6, 6) ? 0.025 : t_stat <= array.get(search_arr6, 7) ? 0.01 : t_stat <= array.get(search_arr6, 8) ? 0.005 : t_stat <= array.get(search_arr6, 9) ? 0.001 : t_stat >= array.get(search_arr6, 10) ? 0.0005 : 1
    else if df <= 20 and df > 10 
        sig := t_stat <= array.get(search_arr7, 0) ? 0.5 : t_stat <= array.get(search_arr7, 1) ? 0.20 : t_stat <= array.get(search_arr7, 2) ? 0.25 : t_stat <= array.get(search_arr7, 3) ? 0.15 : t_stat <= array.get(search_arr7, 4) ? 0.10 : t_stat <= array.get(search_arr7, 5) ? 0.05 : t_stat <= array.get(search_arr7, 6) ? 0.025 : t_stat <= array.get(search_arr7, 7) ? 0.01 : t_stat <= array.get(search_arr7, 8) ? 0.005 : t_stat <= array.get(search_arr7, 9) ? 0.001 : t_stat >= array.get(search_arr7, 10) ? 0.0005 : 1
    else if df <= 30 and df > 20 
        sig := t_stat <= array.get(search_arr8, 0) ? 0.5 : t_stat <= array.get(search_arr8, 1) ? 0.20 : t_stat <= array.get(search_arr8, 2) ? 0.25 : t_stat <= array.get(search_arr8, 3) ? 0.15 : t_stat <= array.get(search_arr8, 4) ? 0.10 : t_stat <= array.get(search_arr8, 5) ? 0.05 : t_stat <= array.get(search_arr8, 6) ? 0.025 : t_stat <= array.get(search_arr8, 7) ? 0.01 : t_stat <= array.get(search_arr8, 8) ? 0.005 : t_stat <= array.get(search_arr8, 9) ? 0.001 : t_stat >= array.get(search_arr8, 10) ? 0.0005 : 1
    else if df <= 40 and df > 30 
        sig := t_stat <= array.get(search_arr9, 0) ? 0.5 : t_stat <= array.get(search_arr9, 1) ? 0.20 : t_stat <= array.get(search_arr9, 2) ? 0.25 : t_stat <= array.get(search_arr9, 3) ? 0.15 : t_stat <= array.get(search_arr9, 4) ? 0.10 : t_stat <= array.get(search_arr9, 5) ? 0.05 : t_stat <= array.get(search_arr9, 6) ? 0.025 : t_stat <= array.get(search_arr9, 7) ? 0.01 : t_stat <= array.get(search_arr9, 8) ? 0.005 : t_stat <= array.get(search_arr9, 9) ? 0.001 : t_stat >= array.get(search_arr9, 10) ? 0.0005 : 1
    else if df <= 60 and df > 40 
        sig := t_stat <= array.get(search_arr10, 0) ? 0.5 : t_stat <= array.get(search_arr10, 1) ? 0.20 : t_stat <= array.get(search_arr10, 2) ? 0.25 : t_stat <= array.get(search_arr10, 3) ? 0.15 : t_stat <= array.get(search_arr10, 4) ? 0.10 : t_stat <= array.get(search_arr10, 5) ? 0.05 : t_stat <= array.get(search_arr10, 6) ? 0.025 : t_stat <= array.get(search_arr10, 7) ? 0.01 : t_stat <= array.get(search_arr10, 8) ? 0.005 : t_stat <= array.get(search_arr10, 9) ? 0.001 : t_stat >= array.get(search_arr10, 10) ? 0.0005 : 1
    else if df <= 80 and df > 60 
        sig := t_stat <= array.get(search_arr11, 0) ? 0.5 : t_stat <= array.get(search_arr11, 1) ? 0.20 : t_stat <= array.get(search_arr11, 2) ? 0.25 : t_stat <= array.get(search_arr11, 3) ? 0.15 : t_stat <= array.get(search_arr11, 4) ? 0.10 : t_stat <= array.get(search_arr11, 5) ? 0.05 : t_stat <= array.get(search_arr11, 6) ? 0.025 : t_stat <= array.get(search_arr11, 7) ? 0.01 : t_stat <= array.get(search_arr11, 8) ? 0.005 : t_stat <= array.get(search_arr11, 9) ? 0.001 : t_stat >= array.get(search_arr11, 10) ? 0.0005 : 1
    else if df <= 100 and df > 80 
        sig := t_stat <= array.get(search_arr12, 0) ? 0.5 : t_stat <= array.get(search_arr12, 1) ? 0.20 : t_stat <= array.get(search_arr12, 2) ? 0.25 : t_stat <= array.get(search_arr12, 3) ? 0.15 : t_stat <= array.get(search_arr12, 4) ? 0.10 : t_stat <= array.get(search_arr12, 5) ? 0.05 : t_stat <= array.get(search_arr12, 6) ? 0.025 : t_stat <= array.get(search_arr12, 7) ? 0.01 : t_stat <= array.get(search_arr12, 8) ? 0.005 : t_stat <= array.get(search_arr12, 9) ? 0.001 : t_stat >= array.get(search_arr12, 10) ? 0.0005 : 1
    else if df > 100 
        sig := t_stat <= array.get(search_arr13, 0) ? 0.5 : t_stat <= array.get(search_arr13, 1) ? 0.25 : t_stat <= array.get(search_arr13, 2) ? 0.25 : t_stat <= array.get(search_arr13, 3) ? 0.15 : t_stat <= array.get(search_arr13, 4) ? 0.10 : t_stat <= array.get(search_arr13, 5) ? 0.05 : t_stat <= array.get(search_arr13, 6) ? 0.025 : t_stat <= array.get(search_arr13, 7) ? 0.01 : t_stat <= array.get(search_arr13, 8) ? 0.005 : t_stat <= array.get(search_arr13, 9) ? 0.001 : t_stat >= array.get(search_arr13, 10) ? 0.0005 : 1
    else 
        sig := 1
    // End of function 

//                                   _____                    _       _   _             
//     /\                           / ____|                  | |     | | (_)            
//    /  \   _ __ _ __ __ _ _   _  | |     ___  _ __ _ __ ___| | __ _| |_ _  ___  _ __  
//   / /\ \ | '__| '__/ _` | | | | | |    / _ \| '__| '__/ _ \ |/ _` | __| |/ _ \| '_ \ 
//  / ____ \| |  | | | (_| | |_| | | |___| (_) | |  | | |  __/ | (_| | |_| | (_) | | | |
// /_/    \_\_|  |_|  \__,_|\__, |  \_____\___/|_|  |_|  \___|_|\__,_|\__|_|\___/|_| |_|
//                           __/ |                                                      
//                          |___/                                                      
// @function TODO: This performs a pearson correlation assessment of two arrays. They need to be of equal size!  
// @param x TODO: Input your two arrays ensuring they are of equal size.  
// @returns TODO: The function will return the pearson correlation. 
export cor_of_array(float[] array1, float[] array2) => 
    array1_stdev = array.stdev(array1) 
    array2_stdev = array.stdev(array2) 
    cov = array.covariance(array1, array2) 
    p_cor = cov / (array1_stdev * array2_stdev) 
    // end of function 

//   ____                  _           _   _         _____                    _       _   _             
//  / __ \                | |         | | (_)       / ____|                  | |     | | (_)            
// | |  | |_   _  __ _  __| |_ __ __ _| |_ _  ___  | |     ___  _ __ _ __ ___| | __ _| |_ _  ___  _ __  
// | |  | | | | |/ _` |/ _` | '__/ _` | __| |/ __| | |    / _ \| '__| '__/ _ \ |/ _` | __| |/ _ \| '_ \ 
// | |__| | |_| | (_| | (_| | | | (_| | |_| | (__  | |___| (_) | |  | | |  __/ | (_| | |_| | (_) | | | |
//  \___\_\\__,_|\__,_|\__,_|_|  \__,_|\__|_|\___|  \_____\___/|_|  |_|  \___|_|\__,_|\__|_|\___/|_| |_|
                                                                                                      
                                                                                                     
// @function TODO: This performs a quadratic (curvlinear) pearson correlation between two values.   
// @param x TODO: Input your two sources and the length of assessment. 
// @returns TODO: The function will return the pearson correlation (quadratic based). 
export quadratic_correlation(float src1, float src2, int len) => 
    x = array.new_float() 
    y = array.new_float() 
    a3 = array.new_float() 
    a4 = array.new_float() 
    for i = 0 to len 
        array.push(x, src2[i] * math.pow(src2[i], 2)) 
        array.push(y, src1[i])
    x_sd = array.stdev(x) 
    y_sd = array.stdev(y) 
    xy_cov = array.covariance(x, y)
    q_cor = xy_cov / (x_sd * y_sd) 
    // End of function 

//  _____  ___   
// |  __ \|__ \  
// | |__) |  ) | 
// |  _  /  / /  
// | | \ \ / /_  
// |_|  \_\____| 
               
// @function TODO: Calculates the r2 of two arrays 
// @param x TODO: parameters are the 2 arrays you wish to calculate the rsqrd for, make sure they are equal size! 
// @returns TODO: returns the R2 value
export f_r2_array(float[] array1, float[] array2) => 
    array1_stdev = array.stdev(array1) 
    array2_stdev = array.stdev(array2) 
    cov = array.covariance(array1, array2) 
    pp_cor = cov / (array1_stdev * array2_stdev) 
    res = math.pow(pp_cor, 2)

// @function TODO: Calculates the r2 of two float variables 
// @param x TODO: parameters are the 2 float variables you wish to calculate the R2rd for and the length of assessment 
// @returns TODO: returns the R2 value
export f_rsqrd(float src1, float src2, int len) =>  
    a = ta.correlation(src1, src2, len) 
    res = math.pow(a, 2)

//  _______        _            __   _   _                            _ _ _         
// |__   __|      | |          / _| | \ | |                          | (_) |        
//    | | ___  ___| |_    ___ | |_  |  \| | ___  _ __ _ __ ___   __ _| |_| |_ _   _ 
//    | |/ _ \/ __| __|  / _ \|  _| | . ` |/ _ \| '__| '_ ` _ \ / _` | | | __| | | |
//    | |  __/\__ \ |_  | (_) | |   | |\  | (_) | |  | | | | | | (_| | | | |_| |_| |
//    |_|\___||___/\__|  \___/|_|   |_| \_|\___/|_|  |_| |_| |_|\__,_|_|_|\__|\__, |
//                                                                             __/ |
//                                                                            |___/
// @function TODO: tests the normal distribution hypothesis 
// @param x TODO: requires values to be pushed into an array (i.e. an array of close values) then inptu the src of the array (i.e. close)  
// @returns TODO: returns 4 variables, 2 float and 2 string 
// Skew: the skewness of the dataset 
// Kurt: the kurtosis of the dataset 
// dist = the distribution type (recognizes 7 different distribution types) 
// implication = a string assessment of the implication of the distribution (qualitative) 
export test_of_normality(float[] array, float src) =>
    // Skewedness 
    float skew = 0.0 
    float kurt = 0.0 
    avga = array.avg(array)
    stdv = array.stdev(array)
    sum = math.pow(src - avga, 3)
    for i = 0 to array.size(array)
        sum := sum + math.pow(src[i] - avga, 3)
    skew := ((sum / array.size(array)) / math.pow(stdv, 3))
    // Kurtosis 
    avgb = array.avg(array)
    stdvb = array.stdev(array)
    sq_df = array.new_float() 
    for i = 0 to array.size(array) 
        array.push(sq_df, math.pow(src[i] - avgb, 4))
    sumb = array.sum(sq_df) 
    c = array.size(array) * math.pow(stdvb, 4)
    kurt := (sumb / c ) - 3

    // Assessment of the normal distribution 
    bool normal_dist = kurt >= -2 and kurt <= 2 and skew >= -1 and skew <= 1 
    bool leptokurtic = kurt > 2 and skew >= -1 and skew <= 1 
    bool platykurtic = kurt < -2 and skew >= -1 and skew <= 1 
    bool right_tailed = kurt >= -2 and kurt <= 2 and skew > 1 
    bool left_tailed = kurt >= -2 and kurt <= 2 and skew < -1 
    bool leptokurtic_heavy_right = kurt > 2 and skew > 1 
    bool platykurtic_heavy_left = kurt <-2 and skew < -1 

    string dist = na 
    string implication = na 

    if normal_dist 
        dist := "Normally Distributed"
        implication := "The Data is normally distributed, with a kurtosis of \n " + str.tostring(math.round(kurt,2)) + " and a skewness of " + str.tostring(math.round(skew,2)) + ". \n The data will respond well to most statistical measures and is highly predictable." 
    else if leptokurtic 
        dist := "Leptokurtic"
        implication := "The Data shows signs of being leptokurtic, with a kurtosis of \n" + str.tostring(math.round(kurt,2)) + " and a skewness of " + str.tostring(math.round(skew,2)) + " \n The data has heavier tails than a normal distribution but is symmetric. \n Extreme deviations in variations are to be expected."
    else if platykurtic 
        dist := "Platykurtic"
        implication := "The Data shows signs of being platykurtic, with a kurtosis of \n" + str.tostring(math.round(kurt,2)) + " and a skewness of " + str.tostring(math.round(skew,2)) + ". \n The data has lighter tails than a normal distribution but is symmetric. \n The data is less prone to extreme variations over time." 
    else if right_tailed 
        dist := "Positive, Right-tailed Distribution"
        implication := "The Data shows signs of a positive, right-tailed distribution, with a kurtosis of \n" + str.tostring(math.round(kurt,2)) + " and a skewness of " + str.tostring(math.round(skew,2)) + ". \n The data is skewed to the right which suggests extreme outliars. \n There is an over-arching, positive bias in the data \n indicating a greater likelihood of extreme variations to the upside." 
    else if left_tailed 
        dist := "Negative, Left-tailed Distribution"
        implication :=  "The Data shows signs of a negative, left-tailed distribution, with a kurtosis of \n" + str.tostring(math.round(kurt,2)) + " and a skewness of " + str.tostring(math.round(skew,2)) + ". \n The data is skewed to the left which suggests extreme outliers, \n there is an over-arching negative bias in the data \n indicating a greater likelihood of extreme variations to the downside."
    else if leptokurtic_heavy_right 
        dist := "Leptokurtic, heavy right tailed"
        implication := "The Data shows signs of a laeptokurtic distribution with heavier tails to the right, with a kurtosis of \n " + str.tostring(math.round(kurt,2)) + " and a skewness of " + str.tostring(math.round(skew,2)) + ". \n The data is heavily skewed to the right which suggests extreme outliers, \n the data is prone to sudden dramatic spikes to the upside and downside."
    else if platykurtic_heavy_left 
        dist := "Platykurtic, heavy left tailed"
        implication := "The Data shows signs of a platykurtic distribution with heavier tails to the left, with a kurtosis of \n" + str.tostring(math.round(kurt,2)) + " and a skewness of " + str.tostring(math.round(skew,2)) + ". \n The data is heavily skewed to the left which suggests extreme outliers, \n the data is prone to drops to the downside, but not overly extreme."
    else  
        dist := "Unable to determine." 
        implication := "The distribution is not normally distributed. \n Unable to determine the distribution type."

    // Output 
    [skew, kurt, dist, implication]

// Simplified Normal Distribution for Float Values 
// @function TODO: tests the normal distribution hypothesis as above but only does not require the use of arrays. 
// @param x TODO: requires two variables, float source (i.e. close or high) and int length of assessment of the normal distribution  
// @returns TODO: returns only 1 variable, the distribution type (normal, platykurtic, etc.) 

export simplified_test_of_normality(int len, float src) =>
    // Skewedness 
    float skew = 0.0 
    float kurt = 0.0 
    avga = ta.sma(src, len) 
    stdv = ta.stdev(src, len)
    sum = math.pow(src - avga, 3)
    for i = 0 to len
        sum := sum + math.pow(src[i] - avga, 3)
    skew := ((sum / len) / math.pow(stdv, 3))
    // Kurtosis 

    sq_df = array.new_float() 
    for i = 0 to len 
        array.push(sq_df, math.pow(src[i] - avga, 4))
    sumb = array.sum(sq_df) 
    c = len * math.pow(stdv, 4)
    kurt := (sumb / c ) - 3

    // Assessment of the normal distribution 
    bool normal_dist = kurt >= -2 and kurt <= 2 and skew >= -1 and skew <= 1 
    bool leptokurtic = kurt > 2 and skew >= -1 and skew <= 1 
    bool platykurtic = kurt < -2 and skew >= -1 and skew <= 1 
    bool right_tailed = kurt >= -2 and kurt <= 2 and skew > 1 
    bool left_tailed = kurt >= -2 and kurt <= 2 and skew < -1 
    bool leptokurtic_heavy_right = kurt > 2 and skew > 1 
    bool platykurtic_heavy_left = kurt <-2 and skew < -1 

    string dist = na 


    if normal_dist 
        dist := "Normally Distributed"
    else if leptokurtic 
        dist := "Leptokurtic"
    else if platykurtic 
        dist := "Platykurtic"
    else if right_tailed 
        dist := "Positive, Right-tailed Distribution"
    else if left_tailed 
        dist := "Negative, Left-tailed Distribution"
    else if leptokurtic_heavy_right 
        dist := "Leptokurtic, heavy right tailed"
    else if platykurtic_heavy_left 
        dist := "Platykurtic, heavy left tailed"
    else  
        dist := "Unable to determine." 

    // Output 
    dist 
//  ______                           _   
// |  ____|                         | |  
// | |__ ___  _ __ ___  ___ __ _ ___| |_ 
// |  __/ _ \| '__/ _ \/ __/ _` / __| __|
// | | | (_) | | |  __/ (_| (_| \__ \ |_ 
// |_|  \___/|_|  \___|\___\__,_|___/\__|
                                       
                                    

// @function TODO: This performs a simple forecast function on a single dependent variable. It will autoregress this based on the train time, to the desired length of output,
// then it will push the forecasted values to 3 float arrays, one that contains the forecasted result, 1 that contains the Upper Confidence Result and one with the lower confidence
// result.  
// @param x TODO: The output variable (desired forecasted variable), the input variable (the variable to forecast from), len is the length of learning for the model, forecast_length
// is the desired length into the future you want to forecast, then the array inputs for the forecast result, ucl and lcl.  
// @returns TODO: Will return 3 arrays, one with the forecasted results, one with the upper confidence results, and a final with the lower confidence results. Example is given below. 
export f_forecast(float output, float input, int train_len, int forecast_length, float[] output_array, float[] upper_array, float[] lower_array) =>
    result = 0.0 
    std_err = 0.0 
    slope = 0.0 
    intercept = 0.0 

	y_array = array.new_float() 
	y_sq_array = array.new_float() 
	x_array = array.new_float() 
	x_sq_array = array.new_float() 
	xy_array = array.new_float() 

	// Loop functions
	for i = 0 to train_len
		array.push(y_array, output[i])
		array.push(y_sq_array, output[i] * output[i]) 
		array.push(x_array, input[i])
		array.push(x_sq_array, input[i] * input[i]) 
		array.push(xy_array, input[i] * output[i])
	
	// Regression Calculations 
	y = array.sum(y_array)
	y2 = array.sum(y_sq_array) 
	x = array.sum(x_array) 
	x2 = array.sum(x_sq_array)
	xy = array.sum(xy_array) 

	b1 = xy - (x * y) / train_len 
	bbb2 = x2 - (math.pow(x, 2) / train_len) 
	slope := (b1 / bbb2) 

	abc = y - (slope * x) 
	intercept := abc / train_len 

	result := (input * slope) + intercept
    // Standard Error
    se_residuals = array.new_float() 
    for i = 0 to train_len 
        array.push(se_residuals, (result[i] - output[i]) * (result[i] - output[i]))
    se_add = array.sum(se_residuals) 
    r1 = se_add / (train_len - 2) 
	std_err := math.sqrt(r1) 
    float prediction = result 
    float ucl = result + std_err 
    float lcl = result - std_err 
    for i = 0 to forecast_length 
        array.push(output_array, result[i])
        array.push(upper_array, ucl[i])
        array.push(lower_array, lcl[i])
        prediction := prediction * slope + intercept 
        ucl := prediction + std_err 
        lcl := prediction - std_err 
    [output_array, upper_array, lower_array]



// Dickey Fuller Test  
//@function: Performs a basic Dickey Fuller Test 
// @param  TODO: change_x: Change value (delta x) calculated from the second variable subtracted from the first variable, lagged_x is the immediate previous variable 
// @returns: returns t-statistic as float and significance and bool (true or false) 

export f_dickey_fuller_test(float change_x, float lagged_x, int len) =>
    result = 0.0 
    rsqrd = 0.0 
    pear_cor = 0.0 
    std_err = 0.0 
    slope = 0.0 
    intercept = 0.0 
    float t_statistic = 0.0 
    bool pass = na 

	y_array = array.new_float() 
	y_sq_array = array.new_float() 
	x_array = array.new_float() 
	x_sq_array = array.new_float() 
	xy_array = array.new_float() 

	// Loop functions
	for i = 0 to len
		array.push(y_array, change_x[i])
		array.push(y_sq_array, change_x[i] * change_x[i]) 
		array.push(x_array, lagged_x[i])
		array.push(x_sq_array, lagged_x[i] * lagged_x[i]) 
		array.push(xy_array, change_x[i] * lagged_x[i])
	
	// Regression Calculations 
	y = array.sum(y_array)
	y2 = array.sum(y_sq_array) 
	x = array.sum(x_array) 
	x2 = array.sum(x_sq_array)
	xy = array.sum(xy_array) 

	b1 = xy - (x * y) / len 
	bbb2 = x2 - (math.pow(x, 2) / len) 
	slope := (b1 / bbb2) 

	abc = y - (slope * x) 
	intercept := abc / len 

	result := (lagged_x * slope)
     // Correlation 
    stdev1 = array.stdev(x_array)
    stdev2 = array.stdev(y_array)
    xy_cov = array.covariance(y_array, x_array)
    pear_cor := xy_cov / (stdev1 * stdev2) 
    // R2 
    rsqrd := math.pow(pear_cor,2)
    // Standard Error
    se_residuals = array.new_float() 
    for i = 0 to len 
        array.push(se_residuals, (result[i] - lagged_x[i]) * (result[i] - lagged_x[i]))
    se_add = array.sum(se_residuals) 
    r1 = se_add / (len - 2) 
	std_err := math.sqrt(r1) 
    t_statistic := (slope / rsqrd)
    // Significance 
    if t_statistic <= -1.62 
        pass := true 
    else if t_statistic > -1.62 
        pass := false 
    [t_statistic, pass]

//anova 
// @function  performs a 3 way ANOVA analysis of 3 independent variables. Returns the F Statistic and the significance (P value) 
// @param x 3 independent groups and the length of ANOVA assessment  
// @returns F Statistic and P value 
export ANOVA(float group1, float group2, float group3, int len) => 
    float sig = 0.0 
    g1_ar = array.new<float>() 
    g2_ar = array.new<float>() 
    g3_ar = array.new<float>() 
    for i = 0 to len 
        array.push(g1_ar, group1[i])
        array.push(g2_ar, group2[i]) 
        array.push(g3_ar, group3[i]) 
    //
    g1_avg = array.avg(g1_ar) 
    g2_avg = array.avg(g2_ar) 
    g3_avg = array.avg(g3_ar) 
    total_avg = math.avg(g1_avg, g2_avg, g3_avg) 
    // Sum of Squares 
    sos_g1 = array.new<float>() 
    sos_g2 = array.new<float>() 
    sos_g3 = array.new<float>() 
    for i = 0 to len 
        array.push(sos_g1, (group1[i] - g1_avg) * (group1[i] - g1_avg)) 
        array.push(sos_g2, (group2[i] - g2_avg) * (group2[i] - g2_avg))
        array.push(sos_g3, (group3[i] - g3_avg) * (group3[i] - g3_avg))
    g1_sum = array.sum(sos_g1) 
    g2_sum = array.sum(sos_g2) 
    g3_sum = array.sum(sos_g3) 
    total_sum = (array.size(g1_ar) - 1 + array.size(g2_ar) - 1 + array.size(g3_ar) - 1)
    sum_of_squares = (g1_sum + g2_sum + g3_sum) 
    mss = (sum_of_squares) / (total_sum - 3) 
    //
    m1 = (array.size(g1_ar) - 1) * math.pow((g1_avg - total_avg),2)
    m2 = (array.size(g2_ar) - 1) * math.pow((g2_avg - total_avg),2)
    m3 = (array.size(g3_ar) - 1) * math.pow((g3_avg - total_avg),2)
    // sum
    m_sum = (m1 + m2 + m3) / 2 
    f_stat = (m_sum / mss)  
    df_b = 2 
    df_w = total_sum - 3 
    if f_stat >= 4.61 
        sig := 0.01 
    else if f_stat >= 3.00 
        sig := 0.05 
    else if f_stat >= 2.30 
        sig := 0.10 
    else
        sig := 1 


    [sig, f_stat]  
    

//  ______                           _           
// |  ____|                         | |          
// | |__  __  ____ _ _ __ ___  _ __ | | ___  ___ 
// |  __| \ \/ / _` | '_ ` _ \| '_ \| |/ _ \/ __|
// | |____ >  < (_| | | | | | | |_) | |  __/\__ \
// |______/_/\_\__,_|_| |_| |_| .__/|_|\___||___/
//                            | |                
//                            |_|               

// Test of Normality //////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

close_array = array.new_float() 
for i = 0 to 50
    array.push(close_array, close[i])

[skew, kurt, dist, implication] = test_of_normality(close_array, close)

var label normality_lbl = na 
var label kurt_lbl = na 
if barstate.islast 
    label.delete(normality_lbl) 
    label.delete(kurt_lbl)
    normality_lbl := label.new(bar_index + 10, y = high, text = str.tostring(dist), color = color.white, textcolor = color.black)
    kurt_lbl := label.new(bar_index, y = low, text = "Kurtosis = " + str.tostring(math.round(kurt,2)) + "\n Skewness = " + str.tostring(math.round(skew,2)), color = color.white, textcolor = color.black, style = label.style_label_up)
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


// Regression //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
[result, pear_cor, rsqrd, std_err, slope, intercept] = f_linear_regression(close, close[1], 150)

plot(result) 

var table reg = table.new(position.top_center, 2, 2, bgcolor = color.white) 
table.cell(reg, 1, 1, text = "y = " + str.tostring(math.round(result,4)) + "x + " + str.tostring(math.round(intercept,2)), bgcolor = color.white, text_color = color.black)

// Forecast //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

btc_prediction = array.new_float() 
btc_ucl = array.new_float()
btc_lcl = array.new_float() 

[thing, thing1, thing2] = f_forecast(close, close[1], 150, 10, btc_prediction, btc_ucl, btc_lcl)

var table btc_table = table.new(position.middle_right, 4, 20, bgcolor = color.black) 
table.cell(btc_table, 1, 1, text = "Forecast", bgcolor = color.black, text_color = color.white) 
table.cell(btc_table, 2, 1, text = "UCL", bgcolor = color.black, text_color = color.white)
table.cell(btc_table, 3, 1, text = "LCL", bgcolor = color.black, text_color = color.white)
for i = 0 to array.size(btc_prediction) - 1
    table.cell(btc_table, 1, 2 + i, text = str.tostring(array.get(btc_prediction, i)), bgcolor = color.black, text_color = color.white) 
    table.cell(btc_table, 2, 2 + i, text = str.tostring(array.get(btc_ucl, i)), bgcolor = color.black, text_color = color.white) 
    table.cell(btc_table, 3, 2 + i, text = str.tostring(array.get(btc_lcl, i)), bgcolor = color.black, text_color = color.white) 

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

