// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © UkutaLabs

 //   ██╗   ██╗██╗  ██╗██╗   ██╗████████╗ █████╗ ██╗      █████╗ ██████╗ ███████╗
 //   ██║   ██║██║ ██╔╝██║   ██║╚══██╔══╝██╔══██╗██║     ██╔══██╗██╔══██╗██╔════╝
 //   ██║   ██║█████╔╝ ██║   ██║   ██║   ███████║██║     ███████║██████╔╝███████╗
 //   ██║   ██║██╔═██╗ ██║   ██║   ██║   ██╔══██║██║     ██╔══██║██╔══██╗╚════██║
 //   ╚██████╔╝██║  ██╗╚██████╔╝   ██║   ██║  ██║███████╗██║  ██║██████╔╝███████║
 //    ╚═════╝ ╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚══════╝

//@version=6

// @description This library was designed to simplify everyday code.
library("UkutaLabs_General_library")


//@function
export isGreenBar() =>
    close > open

//@function
export isRedBar() =>
    close < open

//@function
/// 1 = Green
/// -1 = Red
/// 0 = Doji
export barColor() =>
    close > open ? 1 : close < open ? -1 : 0

//@function
export GetTimeFramePeriod() =>
    timeframe.isintraday and not timeframe.isseconds ? (str.tonumber(timeframe.period)) 
 : timeframe.isseconds ? (timeframe.period == "S" ? 1/60 : str.tonumber(str.substring(timeframe.period, 0, str.length(timeframe.period)-1))/60)
 : 0

//@function
export IsTwoUpBar() =>
    high > high[1] and low > low[1]

//@function
export IsTwoDownBar() =>
    low < low[1] and high < high[1]

//@function
export IsInsideBar() =>
    low > low[1] and high < high[1]

//@function
export IsOutsideBar() =>
    low < low[1] and high > high[1]

//@function
export IsHigherClose() =>
    close > high[1]

//@function
export IsLowerClose() =>
    close < low[1]

//@function
///string textAlign = input.string(defval="Right", title="Text Alignment", options=["Left", "Center", "Right"], group="<Your Group Name>")
export GetHAlign(string TextHAlignment) =>
    TextHAlignment == "Left" ? text.align_left : TextHAlignment == "Center" ? text.align_center : text.align_right

//@function
///string TextVAlign = input.string(defval="Top", title="Text VAlignment", options=["Top", "Bottom"], group="<Your Group Name>")
///These values are reversed on purpose
export GetVAlign(string TextVAlignment) =>
    TextVAlignment == "Top" ? text.align_bottom : text.align_top


//@function
///string fontSize = input.string(defval="Tiny", title="Font Size", options=["Tiny", "Small", "Medium", "Large"], group="<Your Group Name>")
export GetFontSize(string fontSize) =>
    fontSize == "Tiny" ? size.tiny : fontSize == "Small" ? size.small : fontSize == "Medium" ? size.normal : size.large

//@function
///string lineStyle = input.string(defval="Solid",title="Line Style",options=["Dashed","Solid","Dotted"], group="<Your Group Name>")
export GetLineStyle(string lineStyle) =>
    lineStyle == "Dashed" ? line.style_dashed : lineStyle == "Solid" ? line.style_solid : line.style_dotted

///string InputSource = input.string(defval="Close", title="Input Source", options=["Open","Close","High","Low","(H+L)/2","(H+L+C)/3","(O+H+L+C)/4","(H+L+C+C)/4"], group="<Your Group Name>")
export GetInputSource(string InputSource) =>
    InputSource == "Open" ? open : InputSource == "Close" ? close : InputSource == "High" ? high : InputSource == "Low" ? low : InputSource == "(H+L)/2" ? (high+low)/2 : InputSource == "(H+L+C)/3" ? (high+low+close)/3 : InputSource == "(O+H+L+C)/4" ? (open+high+low+close)/4 : InputSource == "(H+L+C+C)/4" ? (high+low+close+close)/4 : close
