// @version=5
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// Thanks to jdehorty

// @description "An optimised library for non-repainting Rational Quadratic Kernel Library.
// Change log:
// 1. Removed Starting window
// 2. The size is determined based on a user-defined value, providing greater flexibility in managing the data for the bars, with the possibility of exceeding the value 2000 if necessary.

// Import the "RationalQuadraticKernelFunction" library with the option to overwrite existing variables.
library("RationalQuadraticKernelFunction", true)

// Define an exported function called "rationalQuadraticKernel" with the following parameters:
// - series float src: Input series to apply the Rational Quadratic Kernel to.
// - simple int lookback: Size of the input series to consider.
// - simple float relativeWeight: Weight used in the calculation.
export rationalQuadraticKernel(series float src, simple int lookback, simple float relativeWeight) =>
    // Initialize variables to store the weighted sum and cumulative weight.
    float currentEstimate = 0.
    float cumulativeWeight = 0.
    
    // Determine the size of the input series (limited by lookback or available bars).
    size = math.min(lookback, bar_index + 1)
    
    // Loop through the input series.
    for i = 0 to size - 1
        // Get the value at the current index from the input series.
        y = src[i]
        
        // Calculate the weight using the Rational Quadratic Kernel formula,
        // avoiding division by zero.
        weight = math.pow(1 + (math.pow(i, 2) / ((math.pow(lookback, 2) * 2 * relativeWeight))), -relativeWeight)
        
        // Accumulate the weighted sum of input values.
        currentEstimate += y * weight
        
        // Accumulate the weights.
        cumulativeWeight += weight
    
    // Prevent division by zero if cumulativeWeight is zero.
    if cumulativeWeight == 0
        // If cumulativeWeight is zero, set it to a small non-zero value.
        cumulativeWeight := 0.001
    
    // Calculate the final Rational Quadratic Kernel estimate by dividing the weighted sum by cumulativeWeight.
    rationalQuadraticEstimate = currentEstimate / cumulativeWeight

// Example
// @version=5
// @author vinayakavajiraya
// @description "An implementation of optimised RationalQuadraticKernelFunction as a indicator for analysis"
// indicator(title="Relational Quadratic Kernel Estimate [Vin]", shorttitle="RQKE-V", overlay=true, timeframe = "", timeframe_gaps = false)

// Import (latest) external library
// import vinayakavajiraya/RationalQuadraticKernelFunction/2 as kernel

// Input parameters for the kernel estimate
// length = input.int(title="Lookback Window", defval=10, minval=1, step=1, group="Kernel Estimate", tooltip="The number of previous bars to consider when calculating the rationalQuadraticEstimate. Higher values capture longer-term trends.")
// relativeWeight = input.float(title="Relative Weight", defval=8, minval=1, step=1, group="Kernel Estimate", tooltip="A factor that controls the importance of each data point in the calculation. A higher value emphasizes recent data.")
// source = input.source(title="Source", defval=close, group="Kernel Estimate"), // Data source (e.g., close price) for the calculation

// Calculate the rational quadratic estimate using the imported library
// rationalQuadraticEstimate = kernel.rationalQuadraticKernel(
//   source,           // Data source for calculation
//   length,           // Lookback window
//   relativeWeight    // Relative weight of data points
//   )

// Plot the rational quadratic estimate on the chart
// plot(rationalQuadraticEstimate, color=color.orange, title="Relational Quadratic Estimate")
