// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © kenneth7e7a

//@version=5

// @description Library for chart utilities, including managing tables
library("ChartUtils")

// @function Initializes a table with specific dimensions and color
// @param position (table.position) The position of the table on the chart
// @param rows (int) Number of rows in the table
// @param cols (int) Number of columns in the table
// @param bgcolor (color) Background color of the table
// @returns (table) The initialized table
export initTable(int rows, int cols, color bgcolor) =>
    table.new(position.bottom_left, rows, cols, bgcolor)

// @function Updates the trading table
// @param tbl (table) The table to update
// @param is_price_below_avg (bool) If the current price is below the average price
// @param current_investment_USD (float) The current investment in USD
// @param strategy_position_size (float) The size of the current position
// @param strategy_position_avg_price (float) The average price of the current position
// @param strategy_openprofit (float) The current open profit
// @param strategy_opentrades (int) The number of open trades
// @param isBullishRate (bool) If the current rate is bullish
// @param isBearishRate (bool) If the current rate is bearish
// @param mlRSIOverSold (bool) If the ML RSI is oversold
// @param mlRSIOverBought (bool) If the ML RSI is overbought
export updateTable(table tbl, bool is_price_below_avg, float current_investment_USD, float strategy_position_size, float strategy_position_avg_price, float strategy_openprofit, int strategy_opentrades, bool isBullishRate, bool isBearishRate, bool mlRSIOverSold, bool mlRSIOverBought) =>
    table.set_bgcolor(tbl, is_price_below_avg ? color.rgb(4, 255, 0) : color.rgb(243, 129, 35))
    table.cell(tbl, 0, 0, "Invertido")
    table.cell(tbl, 1, 0, str.format("{0,number,#.##}", current_investment_USD) + "💲")
    table.cell(tbl, 0, 1, "Nº Monedas")
    table.cell(tbl, 1, 1, str.format("{0,number,#.##}", strategy_position_size) + "🪙")
    table.cell(tbl, 0, 2, "Compra @")
    table.cell(tbl, 1, 2, str.format("{0,number,#.####}", strategy_position_avg_price) + "🏷️")
    table.cell(tbl, 0, 3, "Current P/L")
    table.cell(tbl, 1, 3, str.format("{0,number,#.##}", strategy_openprofit) + "💲")
    table.cell(tbl, 0, 4, "Nº Posiciones")
    table.cell(tbl, 1, 4, str.format("{0,number,#}", strategy_opentrades) + "🔢")
    table.cell(tbl, 0, 5, "Tendencia Kernel")
    table.cell(tbl, 1, 5, isBullishRate ? "🔼" : isBearishRate ? "🔻" : "neutral")
    table.cell(tbl, 0, 6, "RSI ML")
    table.cell(tbl, 1, 6, mlRSIOverSold ? "oversold" : mlRSIOverBought ? "overbought" : "neutral")

// @function Updates the table when there is no position
// @param tbl (table) The table to update
export updateTableNoPosition(table tbl) =>
    table.set_bgcolor(tbl, color.rgb(255, 0, 0))
    table.cell(tbl, 0, 0, "No")
    table.cell(tbl, 1, 0, "entrar...")
