// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TFlab

//@version=6

// @description TODO: add library description here
library("Correlation_HeatMap_Matrix_Data_TradingFinder", overlay = false)

export CorrelationColor(float corr) =>
    s1 = corr >= -1.0 and corr < -0.8
    s2 = corr >= -0.8 and corr < -0.6
    s3 = corr >= -0.6 and corr < -0.4
    s4 = corr >= -0.4 and corr < -0.2
    s5 = corr >= -0.2 and corr <  0.0
    s6 = corr >=  0.0 and corr <  0.2
    s7 = corr >=  0.2 and corr <  0.4
    s8 = corr >=  0.4 and corr <  0.6
    s9 = corr >=  0.6 and corr <  0.8
    s10 = corr >= 0.8 and corr <  0.9
    s11 = corr >= 0.9 and corr <= 1.0

    c1  = color.from_gradient(corr, -1.0, -0.8, #990000, #cc0000)
    c2  = color.from_gradient(corr, -0.8, -0.6, #cc0000, #ff6600)
    c3  = color.from_gradient(corr, -0.6, -0.4, #ff6600, #ffcc00)
    c4  = color.from_gradient(corr, -0.4, -0.2, #ffcc00, #ccff66)
    c5  = color.from_gradient(corr, -0.2,  0.0, #ccff66, #66ff66)
    c6  = color.from_gradient(corr,  0.0,  0.2, #66ff66, #66ffcc)
    c7  = color.from_gradient(corr,  0.2,  0.4, #66ffcc, #33ccff)
    c8  = color.from_gradient(corr,  0.4,  0.6, #33ccff, #3399ff)
    c9  = color.from_gradient(corr,  0.6,  0.8, #3399ff, #0066ff)
    c10 = color.from_gradient(corr,  0.8,  0.9, #0066ff, #4902bb)
    c11 = color.from_gradient(corr,  0.9,  1.0, #4902bb, #410280)

    s1 ? c1 : s2 ? c2 : s3 ? c3 : s4 ? c4 : s5 ? c5 : s6 ? c6 : s7 ? c7 : s8 ? c8 : s9 ? c9 : s10 ? c10 : c11
	
export CorrelationTextColor(float corr) =>
    s1 = corr >= -1.0 and corr < -0.8
    s2 = corr >= -0.8 and corr < -0.6
    s3 = corr >= -0.6 and corr < -0.4
    s4 = corr >= -0.4 and corr < -0.2
    s5 = corr >= -0.2 and corr <  0.0
    s6 = corr >=  0.0 and corr <  0.2
    s7 = corr >=  0.2 and corr <  0.4
    s8 = corr >=  0.4 and corr <  0.6
    s9 = corr >=  0.6 and corr <  0.8
    s10 = corr >= 0.8 and corr <  0.9
    s11 = corr >= 0.9 and corr <= 1.0
	s1 or s2 or s3 or s10 or s11 ? #F0F0F0 : #2E2E2E


Corr(Sx, Sy, y) =>
    c = ta.correlation(Sx, Sy, y)
    c

export Data_Matrix(int Corr_Period, string Sym_1, string Sym_2, string Sym_3, string Sym_4, string Sym_5, string Sym_6, string Sym_7, string Sym_8, string Sym_9, string Sym_10, string Sym_11, string Sym_12, string Sym_13, string Sym_14, string Sym_15, string Sym_16, string Sym_17, string Sym_18, string Sym_19, string Sym_20) => 
	Sym_1_D  = request.security(Sym_1 , timeframe.period, close)
	Sym_2_D  = request.security(Sym_2 , timeframe.period, close)
	Sym_3_D  = request.security(Sym_3 , timeframe.period, close)
	Sym_4_D  = request.security(Sym_4 , timeframe.period, close)
	Sym_5_D  = request.security(Sym_5 , timeframe.period, close)
	Sym_6_D  = request.security(Sym_6 , timeframe.period, close)
	Sym_7_D  = request.security(Sym_7 , timeframe.period, close)
	Sym_8_D  = request.security(Sym_8 , timeframe.period, close)
	Sym_9_D  = request.security(Sym_9 , timeframe.period, close)
	Sym_10_D = request.security(Sym_10, timeframe.period, close)
	Sym_11_D = request.security(Sym_11, timeframe.period, close)
	Sym_12_D = request.security(Sym_12, timeframe.period, close)
	Sym_13_D = request.security(Sym_13, timeframe.period, close)
	Sym_14_D = request.security(Sym_14, timeframe.period, close)
	Sym_15_D = request.security(Sym_15, timeframe.period, close)
	Sym_16_D = request.security(Sym_16, timeframe.period, close)
	Sym_17_D = request.security(Sym_17, timeframe.period, close)
	Sym_18_D = request.security(Sym_18, timeframe.period, close)
	Sym_19_D = request.security(Sym_19, timeframe.period, close)
	Sym_20_D = request.security(Sym_20, timeframe.period, close)
    SYM_1_1  = Corr(Sym_1_D , Sym_1_D , Corr_Period)
    SYM_1_2  = Corr(Sym_1_D , Sym_2_D , Corr_Period)
    SYM_1_3  = Corr(Sym_1_D , Sym_3_D , Corr_Period)
    SYM_1_4  = Corr(Sym_1_D , Sym_4_D , Corr_Period)
    SYM_1_5  = Corr(Sym_1_D , Sym_5_D , Corr_Period)
    SYM_1_6  = Corr(Sym_1_D , Sym_6_D , Corr_Period)
    SYM_1_7  = Corr(Sym_1_D , Sym_7_D , Corr_Period)
    SYM_1_8  = Corr(Sym_1_D , Sym_8_D , Corr_Period)
    SYM_1_9  = Corr(Sym_1_D , Sym_9_D , Corr_Period)
    SYM_1_10 = Corr(Sym_1_D , Sym_10_D, Corr_Period)
    SYM_1_11 = Corr(Sym_1_D , Sym_11_D, Corr_Period)
    SYM_1_12 = Corr(Sym_1_D , Sym_12_D, Corr_Period)
    SYM_1_13 = Corr(Sym_1_D , Sym_13_D, Corr_Period)
    SYM_1_14 = Corr(Sym_1_D , Sym_14_D, Corr_Period)
    SYM_1_15 = Corr(Sym_1_D , Sym_15_D, Corr_Period)
    SYM_1_16 = Corr(Sym_1_D , Sym_16_D, Corr_Period)
    SYM_1_17 = Corr(Sym_1_D , Sym_17_D, Corr_Period)
    SYM_1_18 = Corr(Sym_1_D , Sym_18_D, Corr_Period)
    SYM_1_19 = Corr(Sym_1_D , Sym_19_D, Corr_Period)
    SYM_1_20 = Corr(Sym_1_D , Sym_20_D, Corr_Period)
    SYM_2_2  = Corr(Sym_2_D , Sym_2_D , Corr_Period)
    SYM_2_3  = Corr(Sym_2_D , Sym_3_D , Corr_Period)
    SYM_2_4  = Corr(Sym_2_D , Sym_4_D , Corr_Period)
    SYM_2_5  = Corr(Sym_2_D , Sym_5_D , Corr_Period)
    SYM_2_6  = Corr(Sym_2_D , Sym_6_D , Corr_Period)
    SYM_2_7  = Corr(Sym_2_D , Sym_7_D , Corr_Period)
    SYM_2_8  = Corr(Sym_2_D , Sym_8_D , Corr_Period)
    SYM_2_9  = Corr(Sym_2_D , Sym_9_D , Corr_Period)
    SYM_2_10 = Corr(Sym_2_D , Sym_10_D, Corr_Period)
    SYM_2_11 = Corr(Sym_2_D , Sym_11_D, Corr_Period)
    SYM_2_12 = Corr(Sym_2_D , Sym_12_D, Corr_Period)
    SYM_2_13 = Corr(Sym_2_D , Sym_13_D, Corr_Period)
    SYM_2_14 = Corr(Sym_2_D , Sym_14_D, Corr_Period)
    SYM_2_15 = Corr(Sym_2_D , Sym_15_D, Corr_Period)
    SYM_2_16 = Corr(Sym_2_D , Sym_16_D, Corr_Period)
    SYM_2_17 = Corr(Sym_2_D , Sym_17_D, Corr_Period)
    SYM_2_18 = Corr(Sym_2_D , Sym_18_D, Corr_Period)
    SYM_2_19 = Corr(Sym_2_D , Sym_19_D, Corr_Period)
    SYM_2_20 = Corr(Sym_2_D , Sym_20_D, Corr_Period)
    SYM_3_3  = Corr(Sym_3_D , Sym_3_D , Corr_Period)
    SYM_3_4  = Corr(Sym_3_D , Sym_4_D , Corr_Period)
    SYM_3_5  = Corr(Sym_3_D , Sym_5_D , Corr_Period)
    SYM_3_6  = Corr(Sym_3_D , Sym_6_D , Corr_Period)
    SYM_3_7  = Corr(Sym_3_D , Sym_7_D , Corr_Period)
    SYM_3_8  = Corr(Sym_3_D , Sym_8_D , Corr_Period)
    SYM_3_9  = Corr(Sym_3_D , Sym_9_D , Corr_Period)
    SYM_3_10 = Corr(Sym_3_D , Sym_10_D, Corr_Period)
    SYM_3_11 = Corr(Sym_3_D , Sym_11_D, Corr_Period)
    SYM_3_12 = Corr(Sym_3_D , Sym_12_D, Corr_Period)
    SYM_3_13 = Corr(Sym_3_D , Sym_13_D, Corr_Period)
    SYM_3_14 = Corr(Sym_3_D , Sym_14_D, Corr_Period)
    SYM_3_15 = Corr(Sym_3_D , Sym_15_D, Corr_Period)
    SYM_3_16 = Corr(Sym_3_D , Sym_16_D, Corr_Period)
    SYM_3_17 = Corr(Sym_3_D , Sym_17_D, Corr_Period)
    SYM_3_18 = Corr(Sym_3_D , Sym_18_D, Corr_Period)
    SYM_3_19 = Corr(Sym_3_D , Sym_19_D, Corr_Period)
    SYM_3_20 = Corr(Sym_3_D , Sym_20_D, Corr_Period)
    SYM_4_4  = Corr(Sym_4_D , Sym_4_D , Corr_Period)
    SYM_4_5  = Corr(Sym_4_D , Sym_5_D , Corr_Period)
    SYM_4_6  = Corr(Sym_4_D , Sym_6_D , Corr_Period)
    SYM_4_7  = Corr(Sym_4_D , Sym_7_D , Corr_Period)
    SYM_4_8  = Corr(Sym_4_D , Sym_8_D , Corr_Period)
    SYM_4_9  = Corr(Sym_4_D , Sym_9_D , Corr_Period)
    SYM_4_10 = Corr(Sym_4_D , Sym_10_D, Corr_Period)
    SYM_4_11 = Corr(Sym_4_D , Sym_11_D, Corr_Period)
    SYM_4_12 = Corr(Sym_4_D , Sym_12_D, Corr_Period)
    SYM_4_13 = Corr(Sym_4_D , Sym_13_D, Corr_Period)
    SYM_4_14 = Corr(Sym_4_D , Sym_14_D, Corr_Period)
    SYM_4_15 = Corr(Sym_4_D , Sym_15_D, Corr_Period)
    SYM_4_16 = Corr(Sym_4_D , Sym_16_D, Corr_Period)
    SYM_4_17 = Corr(Sym_4_D , Sym_17_D, Corr_Period)
    SYM_4_18 = Corr(Sym_4_D , Sym_18_D, Corr_Period)
    SYM_4_19 = Corr(Sym_4_D , Sym_19_D, Corr_Period)
    SYM_4_20 = Corr(Sym_4_D , Sym_20_D, Corr_Period)
    SYM_5_5  = Corr(Sym_5_D , Sym_5_D , Corr_Period)
    SYM_5_6  = Corr(Sym_5_D , Sym_6_D , Corr_Period)
    SYM_5_7  = Corr(Sym_5_D , Sym_7_D , Corr_Period)
    SYM_5_8  = Corr(Sym_5_D , Sym_8_D , Corr_Period)
    SYM_5_9  = Corr(Sym_5_D , Sym_9_D , Corr_Period)
    SYM_5_10 = Corr(Sym_5_D , Sym_10_D, Corr_Period)
    SYM_5_11 = Corr(Sym_5_D , Sym_11_D, Corr_Period)
    SYM_5_12 = Corr(Sym_5_D , Sym_12_D, Corr_Period)
    SYM_5_13 = Corr(Sym_5_D , Sym_13_D, Corr_Period)
    SYM_5_14 = Corr(Sym_5_D , Sym_14_D, Corr_Period)
    SYM_5_15 = Corr(Sym_5_D , Sym_15_D, Corr_Period)
    SYM_5_16 = Corr(Sym_5_D , Sym_16_D, Corr_Period)
    SYM_5_17 = Corr(Sym_5_D , Sym_17_D, Corr_Period)
    SYM_5_18 = Corr(Sym_5_D , Sym_18_D, Corr_Period)
    SYM_5_19 = Corr(Sym_5_D , Sym_19_D, Corr_Period)
    SYM_5_20 = Corr(Sym_5_D , Sym_20_D, Corr_Period)
    SYM_6_6  = Corr(Sym_6_D , Sym_6_D , Corr_Period)
    SYM_6_7  = Corr(Sym_6_D , Sym_7_D , Corr_Period)
    SYM_6_8  = Corr(Sym_6_D , Sym_8_D , Corr_Period)
    SYM_6_9  = Corr(Sym_6_D , Sym_9_D , Corr_Period)
    SYM_6_10 = Corr(Sym_6_D , Sym_10_D, Corr_Period)
    SYM_6_11 = Corr(Sym_6_D , Sym_11_D, Corr_Period)
    SYM_6_12 = Corr(Sym_6_D , Sym_12_D, Corr_Period)
    SYM_6_13 = Corr(Sym_6_D , Sym_13_D, Corr_Period)
    SYM_6_14 = Corr(Sym_6_D , Sym_14_D, Corr_Period)
    SYM_6_15 = Corr(Sym_6_D , Sym_15_D, Corr_Period)
    SYM_6_16 = Corr(Sym_6_D , Sym_16_D, Corr_Period)
    SYM_6_17 = Corr(Sym_6_D , Sym_17_D, Corr_Period)
    SYM_6_18 = Corr(Sym_6_D , Sym_18_D, Corr_Period)
    SYM_6_19 = Corr(Sym_6_D , Sym_19_D, Corr_Period)
    SYM_6_20 = Corr(Sym_6_D , Sym_20_D, Corr_Period)
    SYM_7_7  = Corr(Sym_7_D , Sym_7_D , Corr_Period)
    SYM_7_8  = Corr(Sym_7_D , Sym_8_D , Corr_Period)
    SYM_7_9  = Corr(Sym_7_D , Sym_9_D , Corr_Period)
    SYM_7_10 = Corr(Sym_7_D , Sym_10_D, Corr_Period)
    SYM_7_11 = Corr(Sym_7_D , Sym_11_D, Corr_Period)
    SYM_7_12 = Corr(Sym_7_D , Sym_12_D, Corr_Period)
    SYM_7_13 = Corr(Sym_7_D , Sym_13_D, Corr_Period)
    SYM_7_14 = Corr(Sym_7_D , Sym_14_D, Corr_Period)
    SYM_7_15 = Corr(Sym_7_D , Sym_15_D, Corr_Period)
    SYM_7_16 = Corr(Sym_7_D , Sym_16_D, Corr_Period)
    SYM_7_17 = Corr(Sym_7_D , Sym_17_D, Corr_Period)
    SYM_7_18 = Corr(Sym_7_D , Sym_18_D, Corr_Period)
    SYM_7_19 = Corr(Sym_7_D , Sym_19_D, Corr_Period)
    SYM_7_20 = Corr(Sym_7_D , Sym_20_D, Corr_Period)
    SYM_8_8  = Corr(Sym_8_D , Sym_8_D , Corr_Period)
    SYM_8_9  = Corr(Sym_8_D , Sym_9_D , Corr_Period)
    SYM_8_10 = Corr(Sym_8_D , Sym_10_D, Corr_Period)
    SYM_8_11 = Corr(Sym_8_D , Sym_11_D, Corr_Period)
    SYM_8_12 = Corr(Sym_8_D , Sym_12_D, Corr_Period)
    SYM_8_13 = Corr(Sym_8_D , Sym_13_D, Corr_Period)
    SYM_8_14 = Corr(Sym_8_D , Sym_14_D, Corr_Period)
    SYM_8_15 = Corr(Sym_8_D , Sym_15_D, Corr_Period)
    SYM_8_16 = Corr(Sym_8_D , Sym_16_D, Corr_Period)
    SYM_8_17 = Corr(Sym_8_D , Sym_17_D, Corr_Period)
    SYM_8_18 = Corr(Sym_8_D , Sym_18_D, Corr_Period)
    SYM_8_19 = Corr(Sym_8_D , Sym_19_D, Corr_Period)
    SYM_8_20 = Corr(Sym_8_D , Sym_20_D, Corr_Period)
    SYM_9_9  = Corr(Sym_9_D , Sym_9_D , Corr_Period)
    SYM_9_10 = Corr(Sym_9_D , Sym_10_D, Corr_Period)
    SYM_9_11 = Corr(Sym_9_D , Sym_11_D, Corr_Period)
    SYM_9_12 = Corr(Sym_9_D , Sym_12_D, Corr_Period)
    SYM_9_13 = Corr(Sym_9_D , Sym_13_D, Corr_Period)
    SYM_9_14 = Corr(Sym_9_D , Sym_14_D, Corr_Period)
    SYM_9_15 = Corr(Sym_9_D , Sym_15_D, Corr_Period)
    SYM_9_16 = Corr(Sym_9_D , Sym_16_D, Corr_Period)
    SYM_9_17 = Corr(Sym_9_D , Sym_17_D, Corr_Period)
    SYM_9_18 = Corr(Sym_9_D , Sym_18_D, Corr_Period)
    SYM_9_19 = Corr(Sym_9_D , Sym_19_D, Corr_Period)
    SYM_9_20 = Corr(Sym_9_D , Sym_20_D, Corr_Period)
    SYM_10_10 = Corr(Sym_10_D , Sym_10_D, Corr_Period)
    SYM_10_11 = Corr(Sym_10_D , Sym_11_D, Corr_Period)
    SYM_10_12 = Corr(Sym_10_D , Sym_12_D, Corr_Period)
    SYM_10_13 = Corr(Sym_10_D , Sym_13_D, Corr_Period)
    SYM_10_14 = Corr(Sym_10_D , Sym_14_D, Corr_Period)
    SYM_10_15 = Corr(Sym_10_D , Sym_15_D, Corr_Period)
    SYM_10_16 = Corr(Sym_10_D , Sym_16_D, Corr_Period)
    SYM_10_17 = Corr(Sym_10_D , Sym_17_D, Corr_Period)
    SYM_10_18 = Corr(Sym_10_D , Sym_18_D, Corr_Period)
    SYM_10_19 = Corr(Sym_10_D , Sym_19_D, Corr_Period)
    SYM_10_20 = Corr(Sym_10_D , Sym_20_D, Corr_Period)
    SYM_11_11 = Corr(Sym_11_D , Sym_11_D, Corr_Period)
    SYM_11_12 = Corr(Sym_11_D , Sym_12_D, Corr_Period)
    SYM_11_13 = Corr(Sym_11_D , Sym_13_D, Corr_Period)
    SYM_11_14 = Corr(Sym_11_D , Sym_14_D, Corr_Period)
    SYM_11_15 = Corr(Sym_11_D , Sym_15_D, Corr_Period)
    SYM_11_16 = Corr(Sym_11_D , Sym_16_D, Corr_Period)
    SYM_11_17 = Corr(Sym_11_D , Sym_17_D, Corr_Period)
    SYM_11_18 = Corr(Sym_11_D , Sym_18_D, Corr_Period)
    SYM_11_19 = Corr(Sym_11_D , Sym_19_D, Corr_Period)
    SYM_11_20 = Corr(Sym_11_D , Sym_20_D, Corr_Period)
    SYM_12_12 = Corr(Sym_12_D , Sym_12_D, Corr_Period)
    SYM_12_13 = Corr(Sym_12_D , Sym_13_D, Corr_Period)
    SYM_12_14 = Corr(Sym_12_D , Sym_14_D, Corr_Period)
    SYM_12_15 = Corr(Sym_12_D , Sym_15_D, Corr_Period)
    SYM_12_16 = Corr(Sym_12_D , Sym_16_D, Corr_Period)
    SYM_12_17 = Corr(Sym_12_D , Sym_17_D, Corr_Period)
    SYM_12_18 = Corr(Sym_12_D , Sym_18_D, Corr_Period)
    SYM_12_19 = Corr(Sym_12_D , Sym_19_D, Corr_Period)
    SYM_12_20 = Corr(Sym_12_D , Sym_20_D, Corr_Period)
    SYM_13_13 = Corr(Sym_13_D , Sym_13_D, Corr_Period)
    SYM_13_14 = Corr(Sym_13_D , Sym_14_D, Corr_Period)
    SYM_13_15 = Corr(Sym_13_D , Sym_15_D, Corr_Period)
    SYM_13_16 = Corr(Sym_13_D , Sym_16_D, Corr_Period)
    SYM_13_17 = Corr(Sym_13_D , Sym_17_D, Corr_Period)
    SYM_13_18 = Corr(Sym_13_D , Sym_18_D, Corr_Period)
    SYM_13_19 = Corr(Sym_13_D , Sym_19_D, Corr_Period)
    SYM_13_20 = Corr(Sym_13_D , Sym_20_D, Corr_Period)
    SYM_14_14 = Corr(Sym_14_D , Sym_14_D, Corr_Period)
    SYM_14_15 = Corr(Sym_14_D , Sym_15_D, Corr_Period)
    SYM_14_16 = Corr(Sym_14_D , Sym_16_D, Corr_Period)
    SYM_14_17 = Corr(Sym_14_D , Sym_17_D, Corr_Period)
    SYM_14_18 = Corr(Sym_14_D , Sym_18_D, Corr_Period)
    SYM_14_19 = Corr(Sym_14_D , Sym_19_D, Corr_Period)
    SYM_14_20 = Corr(Sym_14_D , Sym_20_D, Corr_Period)
    SYM_15_15 = Corr(Sym_15_D , Sym_15_D, Corr_Period)
    SYM_15_16 = Corr(Sym_15_D , Sym_16_D, Corr_Period)
    SYM_15_17 = Corr(Sym_15_D , Sym_17_D, Corr_Period)
    SYM_15_18 = Corr(Sym_15_D , Sym_18_D, Corr_Period)
    SYM_15_19 = Corr(Sym_15_D , Sym_19_D, Corr_Period)
    SYM_15_20 = Corr(Sym_15_D , Sym_20_D, Corr_Period)
    SYM_16_16 = Corr(Sym_16_D , Sym_16_D, Corr_Period)
    SYM_16_17 = Corr(Sym_16_D , Sym_17_D, Corr_Period)
    SYM_16_18 = Corr(Sym_16_D , Sym_18_D, Corr_Period)
    SYM_16_19 = Corr(Sym_16_D , Sym_19_D, Corr_Period)
    SYM_16_20 = Corr(Sym_16_D , Sym_20_D, Corr_Period)
    SYM_17_17 = Corr(Sym_17_D , Sym_17_D, Corr_Period)
    SYM_17_18 = Corr(Sym_17_D , Sym_18_D, Corr_Period)
    SYM_17_19 = Corr(Sym_17_D , Sym_19_D, Corr_Period)
    SYM_17_20 = Corr(Sym_17_D , Sym_20_D, Corr_Period)
    SYM_18_18 = Corr(Sym_18_D , Sym_18_D, Corr_Period)
    SYM_18_19 = Corr(Sym_18_D , Sym_19_D, Corr_Period)
    SYM_18_20 = Corr(Sym_18_D , Sym_20_D, Corr_Period)
    SYM_19_19 = Corr(Sym_19_D , Sym_19_D, Corr_Period)
    SYM_19_20 = Corr(Sym_19_D , Sym_20_D, Corr_Period)
    SYM_20_20 = Corr(Sym_20_D , Sym_20_D, Corr_Period)
	// [Sym_1_D, Sym_2_D, Sym_3_D, Sym_4_D, Sym_5_D, Sym_6_D, Sym_7_D, Sym_8_D, Sym_9_D, Sym_10_D, Sym_11_D, Sym_12_D, Sym_13_D, Sym_14_D, Sym_15_D, Sym_16_D, Sym_17_D, Sym_18_D, Sym_19_D, Sym_20_D]

    [SYM_1_1 ,SYM_1_2 ,SYM_1_3 ,SYM_1_4 ,SYM_1_5 ,SYM_1_6 ,SYM_1_7 ,SYM_1_8 ,SYM_1_9 ,SYM_1_10,SYM_1_11,SYM_1_12,SYM_1_13,SYM_1_14,SYM_1_15,SYM_1_16,SYM_1_17,SYM_1_18,SYM_1_19,SYM_1_20,
 SYM_2_2  , SYM_2_3  , SYM_2_4  , SYM_2_5  , SYM_2_6  , SYM_2_7  , SYM_2_8  , SYM_2_9  , SYM_2_10 , SYM_2_11 , SYM_2_12 , SYM_2_13, SYM_2_14, SYM_2_15, SYM_2_16, SYM_2_17, SYM_2_18, SYM_2_19, SYM_2_20,
 SYM_3_3  , SYM_3_4  , SYM_3_5  , SYM_3_6  , SYM_3_7  , SYM_3_8  , SYM_3_9  , SYM_3_10 , SYM_3_11 , SYM_3_12 , SYM_3_13 , SYM_3_14, SYM_3_15, SYM_3_16, SYM_3_17, SYM_3_18, SYM_3_19, SYM_3_20,
 SYM_4_4  , SYM_4_5  , SYM_4_6  , SYM_4_7  , SYM_4_8  , SYM_4_9  , SYM_4_10 , SYM_4_11 , SYM_4_12 , SYM_4_13 , SYM_4_14 , SYM_4_15, SYM_4_16, SYM_4_17, SYM_4_18, SYM_4_19, SYM_4_20,
 SYM_5_5  , SYM_5_6  , SYM_5_7  , SYM_5_8  , SYM_5_9  , SYM_5_10 , SYM_5_11 , SYM_5_12 , SYM_5_13 , SYM_5_14 , SYM_5_15 , SYM_5_16, SYM_5_17, SYM_5_18, SYM_5_19, SYM_5_20,
 SYM_6_6  , SYM_6_7  , SYM_6_8  , SYM_6_9  , SYM_6_10 , SYM_6_11 , SYM_6_12 , SYM_6_13 , SYM_6_14 , SYM_6_15 , SYM_6_16 , SYM_6_17, SYM_6_18, SYM_6_19, SYM_6_20,
 SYM_7_7  , SYM_7_8  , SYM_7_9  , SYM_7_10 , SYM_7_11 , SYM_7_12 , SYM_7_13 , SYM_7_14 , SYM_7_15 , SYM_7_16 , SYM_7_17 , SYM_7_18, SYM_7_19, SYM_7_20,
 SYM_8_8  , SYM_8_9  , SYM_8_10 , SYM_8_11 , SYM_8_12 , SYM_8_13 , SYM_8_14 , SYM_8_15 , SYM_8_16 , SYM_8_17 , SYM_8_18 , SYM_8_19, SYM_8_20,
 SYM_9_9  , SYM_9_10 , SYM_9_11 , SYM_9_12 , SYM_9_13 , SYM_9_14 , SYM_9_15 , SYM_9_16 , SYM_9_17 , SYM_9_18 , SYM_9_19 , SYM_9_20,
 SYM_10_10, SYM_10_11, SYM_10_12, SYM_10_13, SYM_10_14, SYM_10_15, SYM_10_16, SYM_10_17, SYM_10_18, SYM_10_19, SYM_10_20,
 SYM_11_11, SYM_11_12, SYM_11_13, SYM_11_14, SYM_11_15, SYM_11_16, SYM_11_17, SYM_11_18, SYM_11_19, SYM_11_20,
 SYM_12_12, SYM_12_13, SYM_12_14, SYM_12_15, SYM_12_16, SYM_12_17, SYM_12_18, SYM_12_19, SYM_12_20,
 SYM_13_13, SYM_13_14, SYM_13_15, SYM_13_16, SYM_13_17, SYM_13_18, SYM_13_19, SYM_13_20,
 SYM_14_14, SYM_14_15, SYM_14_16, SYM_14_17, SYM_14_18, SYM_14_19, SYM_14_20,
 SYM_15_15, SYM_15_16, SYM_15_17, SYM_15_18, SYM_15_19, SYM_15_20,
 SYM_16_16, SYM_16_17, SYM_16_18, SYM_16_19, SYM_16_20,
 SYM_17_17, SYM_17_18, SYM_17_19, SYM_17_20,
 SYM_18_18, SYM_18_19, SYM_18_20,
 SYM_19_19, SYM_19_20,
 SYM_20_20]