//@version=6

// @description Provides a parsing library that indicator authors can use in order to parse Quick Inputs Levels. 
library("QuickInputsLevelParser", true)

int SECTION_LVN = 0
int SECTION_LVN_ZONE = 1
int SECTION_SUPPLY = 2
int SECTION_SUPPLY_ZONE = 3
int SECTION_VS = 4
int SECTION_VAH = 5
int SECTION_VAL = 6
int SECTION_POC = 7
int SECTION_MISC_ZONES = 8
int SECTION_MISC_LINES = 9
int SECTION_FBO = 10
int SECTION_FBD = 11
int SECTION_MAJOR_LEVEL = 12
int SECTION_MSUP = 13
int SECTION_MMSUP = 14
int SECTION_MSUPZ = 15
int SECTION_MMSUPZ = 16
int SECTION_MRES = 17
int SECTION_MMRES = 18
int SECTION_MRESZ = 19
int SECTION_MMRESZ = 20
int SECTION_SHLVL = 21
int SECTION_SHSUP = 22
int SECTION_SHRES = 23

export type zoneRange
    float high
    float low

export type QILevels
    array<float> lvnLines
    array<zoneRange> lvnZones
    array<float> supplyLines
    array<zoneRange> supplyZones
    array<float> vses
    array<float> vahs
    array<float> vals
    array<float> pocs
    array<zoneRange> miscZones
    array<float> miscLines
    array<float> fbos
    array<float> fbds
    array<float> majorLevels
    array<float> mansupLines
    array<float> mansupmajLines
    array<zoneRange> mansupZones
    array<zoneRange> mansupmajZones
    array<float> manresLines
    array<float> manresmajLines
    array<zoneRange> manresZones
    array<zoneRange> manresmajZones
    array<float> smashLvls
    array<float> smashSups
    array<float> smashRess


// @function Parses the string content and returns the `Quick Inputs Levels` found within.
// @param s The string to parse.
// @returns The parsed WTD levels.
export parseLevels(string s) =>
    array<float> lvnLines = array.new<float>()
    array<zoneRange> lvnZones = array.new<zoneRange>()
    array<float> supplyLines = array.new<float>()
    array<zoneRange> supplyZones = array.new<zoneRange>()
    array<float> vses = array.new<float>()
    array<float> vahs = array.new<float>()
    array<float> vals = array.new<float>()
    array<float> pocs = array.new<float>()
    array<zoneRange> miscZones = array.new<zoneRange>()
    array<float> miscLines = array.new<float>()
    array<float> fbos = array.new<float>()
    array<float> fbds = array.new<float>()
    array<float> majorLevels = array.new<float>()
    array<float> mansupLines = array.new<float>()
    array<float> mansupmajLines = array.new<float>()
    array<zoneRange> mansupZones = array.new<zoneRange>()
    array<zoneRange> mansupmajZones = array.new<zoneRange>()
    array<float> manresLines = array.new<float>()
    array<float> manresmajLines = array.new<float>()
    array<zoneRange> manresZones = array.new<zoneRange>()
    array<zoneRange> manresmajZones = array.new<zoneRange>()
    array<float> smashLvls = array.new<float>()
    array<float> smashSups = array.new<float>()
    array<float> smashRess = array.new<float>()

    // used for parsing ranges
    float previousHigh = 0

    currentSection = -1
    lines = str.split(s, "\n")
    numLines = array.size(lines)
    for n = 0 to (numLines > 0 ? numLines - 1 : na)
        string l = str.trim(array.get(lines, n))

        if str.length(l) == 0
            continue
        
        if l == "[LVN]"
            currentSection := SECTION_LVN
        else if l == "[LVN ZONES]"
            currentSection := SECTION_LVN_ZONE
        else if l == "[SUPPLY]"
            currentSection := SECTION_SUPPLY
        else if l == "[SUPPLY LINES]"
            currentSection := SECTION_SUPPLY
        else if l == "[SUPPLY ZONES]"
            currentSection := SECTION_SUPPLY_ZONE
        else if l == "[VS]"
            currentSection := SECTION_VS
        else if l == "[VAH]"
            currentSection := SECTION_VAH
        else if l == "[VAL]"
            currentSection := SECTION_VAL
        else if l == "[POC]"
            currentSection := SECTION_POC
        else if l == "[MISC ZONES]" or l == "[HTF ZONES]"
            currentSection := SECTION_MISC_ZONES
        else if l == "[MISC LINES]" or l == "[HTF LINES]"
            currentSection := SECTION_MISC_LINES
        else if l == "[FBO]"
            currentSection := SECTION_FBO
        else if l == "[FBD]"
            currentSection := SECTION_FBD
        else if l == "[MAJOR LEVELS]" or l == "[SPECIAL LINES]"
            currentSection := SECTION_MAJOR_LEVEL
        else if l == "[MSUP]"
            currentSection := SECTION_MSUP
        else if l == "[MMSUP]"
            currentSection := SECTION_MMSUP
        else if l == "[MSUPZ]"
            currentSection := SECTION_MSUPZ
        else if l == "[MMSUPZ]"
            currentSection := SECTION_MMSUPZ
        else if l == "[MRES]"
            currentSection := SECTION_MRES
        else if l == "[MMRES]"
            currentSection := SECTION_MMRES
        else if l == "[MRESZ]"
            currentSection := SECTION_MRESZ
        else if l == "[MMRESZ]"
            currentSection := SECTION_MMRESZ 
        else if l == "[SHLVL]"
            currentSection := SECTION_SHLVL
        else if l == "[SHSUP]"
            currentSection := SECTION_SHSUP
        else if l == "[SHRES]"
            currentSection := SECTION_SHRES   
        else
            float value = str.tonumber(l)

            if value <= 0
                continue

            if currentSection == SECTION_LVN
                array.push(lvnLines, value)
            else if currentSection == SECTION_LVN_ZONE
                if previousHigh == 0
                    previousHigh := value
                else
                    array.push(lvnZones, zoneRange.new(previousHigh, value))
                    previousHigh := 0
            else if currentSection == SECTION_SUPPLY
                array.push(supplyLines, value)
            else if currentSection == SECTION_SUPPLY_ZONE
                if previousHigh == 0
                    previousHigh := value
                else
                    array.push(supplyZones, zoneRange.new(previousHigh, value))
                    previousHigh := 0
            else if currentSection == SECTION_VS
                array.push(vses, value)
            else if currentSection == SECTION_VAH
                array.push(vahs, value)
            else if currentSection == SECTION_VAL
                array.push(vals, value)
            else if currentSection == SECTION_POC
                array.push(pocs, value)
            else if currentSection == SECTION_MISC_ZONES
                if previousHigh == 0
                    previousHigh := value
                else
                    array.push(miscZones, zoneRange.new(previousHigh, value))
                    previousHigh := 0
            else if currentSection == SECTION_MISC_LINES
                array.push(miscLines, value)
            else if currentSection == SECTION_FBO
                array.push(fbos, value)
            else if currentSection == SECTION_FBD
                array.push(fbds, value)
            else if currentSection == SECTION_MAJOR_LEVEL
                array.push(majorLevels, value)
            else if currentSection == SECTION_MSUP
                array.push(mansupLines, value)
            else if currentSection == SECTION_MMSUP
                array.push(mansupmajLines, value)   
            else if currentSection == SECTION_MRES
                array.push(manresLines, value)
            else if currentSection == SECTION_MMRES
                array.push(manresmajLines, value) 
            else if currentSection == SECTION_MSUPZ
                if previousHigh == 0
                    previousHigh := value
                else
                    array.push(mansupZones, zoneRange.new(previousHigh, value))
                    previousHigh := 0
            else if currentSection == SECTION_MMSUPZ
                if previousHigh == 0
                    previousHigh := value
                else
                    array.push(mansupmajZones, zoneRange.new(previousHigh, value))
                    previousHigh := 0
            else if currentSection == SECTION_MRESZ
                if previousHigh == 0
                    previousHigh := value
                else
                    array.push(manresZones, zoneRange.new(previousHigh, value))
                    previousHigh := 0
            else if currentSection == SECTION_MMRESZ
                if previousHigh == 0
                    previousHigh := value
                else
                    array.push(manresmajZones, zoneRange.new(previousHigh, value))
                    previousHigh := 0
            else if currentSection == SECTION_SHLVL
                array.push(smashLvls, value)
            else if currentSection == SECTION_SHRES
                array.push(smashRess, value)   
            else if currentSection == SECTION_SHSUP
                array.push(smashSups, value)
            else
                log.error("invalid section: {}", currentSection)

    QILevels.new(lvnLines, lvnZones, supplyLines, supplyZones, vses, vahs, vals, pocs, miscZones, miscLines, fbos, fbds, majorLevels, mansupLines, mansupmajLines, mansupZones, mansupmajZones, manresLines, manresmajLines, manresZones, manresmajZones, smashLvls, smashSups, smashRess)
