// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © know3daysm

//@version=6

// @description defines commonly used utility functions and constants
library("Util")

//@enum     	Enum of trade direction
export enum TradeDir
    long    = "L"
    short   = "S"

// @UDT			Data of an open trade
export type trade
	string		id
	TradeDir	direction
	float		entry_price
	float		shares
	int			bars_open

// @function 	Calculate number of shares for a trade 
// @param 		entry_price 
// @param		stop 		stop loss price
// @param		fund 		amount of fund to put in this trade
// @param		riskPerc	percentage of fund to be risked in this trade. Default is 5%
// @returns 	number of shares
export calc_shares(float entry_price, float stop, float fund, float riskPerc = 5) =>
    size1 = fund/entry_price
    size2 = stop == entry_price ? size1 : fund * riskPerc/100 / math.abs(entry_price-stop)
    
    math.floor(math.min(size1, size2))


// @function 	Returns if a trade with the specific ID is already open
// @param 		trade_id
// @returns 	true/false
export trade_exist(string trade_id) =>
    ret = false
    for i = 0 to strategy.opentrades - 1
        if strategy.opentrades.entry_id(i) == trade_id
            ret := true
			break
    ret
