// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © robbatt

//@version=5

// @description This is a convenience lib that bundles different setter functions allowing to update all coordinates and of line/box in one call, and coordinates and text for label.
library("lib_set", overlay = true)


//@function Updates a label object with new data (equals redrawing it)
//@param x reassigns the x coordinate, optional param, no effect if x = na (same as draw(extend_only = true) for Line objects). Avoiding to reassign x can prevent errors for invalid params passed to set_x***
//@param y reassigns the y coordinate
//@param txt reassigns the label text
//@param tooltip reassigns the label tooltip
export method set_xy_text(label this, int x = na, float y, string txt = '', string tooltip = '') =>
	if not na(this)
		if na(x)
			this.set_y(y)
		else
			this.set_xy(x,y)
		if txt != ''
			this.set_text(txt)
		if tooltip != ''
			this.set_tooltip(tooltip)
	this
	
//@function Updates a line object with new data (equals redrawing it)
//@param x1 reassigns the x1 coordinate, optional param, no effect if x1 = na (same as draw(extend_only = true) for Line objects). Avoiding to reassign x1 can prevent errors for invalid params passed to set_x***
//@param y1 reassigns the y1 coordinate
//@param x2 reassigns the x2 coordinate
//@param y2 reassigns the y2 coordinate
export method set_xy1_xy2(line this, int x1 = na, float y1, int x2, float y2) =>
	if not na(this)
		if na(x1)
			this.set_y1(y1)
		else
			this.set_xy1(x1,y1)
		this.set_xy2(x2,y2)
	this
		
//@function Updates a box object with new data (equals redrawing it)
//@param left reassigns the left coordinate, optional param, no effect if left = na (same as draw(extend_only = true) for Box objects). Avoiding to reassign 'left' can prevent errors for invalid params passed to set_x***
//@param top reassigns the top coordinate
//@param right reassigns the right coordinate
//@param bottom reassigns the bottom coordinate
export method set_left_top_right_bottom(box this, int left = na, float top, int right, float bottom) =>
	if not na(this)
		if na(left)
			this.set_top(top)
		else
			this.set_lefttop(left,top)
		this.set_rightbottom(right,bottom)
	this
		

var line l = line.new(chart.point.now(high), chart.point.now(open))
var box b = box.new(chart.point.now(low), chart.point.now(low), bgcolor = na)
var label lb = label.new(chart.point.now(low), style = label.style_label_up)

var line l_ext = line.new(chart.point.now(high), chart.point.now(open), color= color.orange, width = 3)
var box b_ext = box.new(chart.point.now(low), chart.point.now(hl2), bgcolor = na, border_color = color.orange)
var label lb_ext = label.new(chart.point.now(high), color = color.orange)


if barstate.islast
	// setting all coordinates
	b.set_left_top_right_bottom(bar_index[3], high[3], bar_index, low)
	l.set_xy1_xy2(bar_index[3], high[3], bar_index, low)
	lb.set_xy_text(bar_index, low, 'example\nupdated\n(x1,y1,x2,y2)', 'test tooltip')

	// extending only (excluding x1/left coordinate)
	b_ext.set_left_top_right_bottom(na, high[5], bar_index, hl2)
	l_ext.set_xy1_xy2(na, hlc3, bar_index, hlc3)
	lb_ext.set_xy_text(bar_index, high[5], 'example\nextended\n(y1,x2,y2)')