//@version=6
indicator("Logical Level Pro Lite", shorttitle="LLP Lite", overlay=true, max_lines_count=50)

// Configuración
paso = input.float(10, "Separación entre niveles", minval=0.25)
cantidad = input.int(5, "Cantidad de niveles arriba/abajo", minval=1)

colorLinea = input.color(color.gray, "Color de líneas")
grosor = input.int(1, "Grosor de línea", minval=1, maxval=4)

// Guardar líneas
var line[] niveles = array.new_line()

// Crear líneas una sola vez
if barstate.isfirst
    for i = 0 to (cantidad * 2)
        array.push(niveles, line.new(na, na, na, na, extend=extend.right))

// Precio base
base = math.round(close / paso) * paso

// Actualizar niveles
for i = -cantidad to cantidad
    nivel = base + (i * paso)
    
    linea = array.get(niveles, i + cantidad)
    
    line.set_xy1(linea, bar_index, nivel)
    line.set_xy2(linea, bar_index + 1, nivel)
    line.set_color(linea, colorLinea)
    line.set_width(linea, grosor)
