//@version=5
library("pseudorenko", overlay=true)

// Function to calculate and return the Pseudo-Renko Stabilized close price
export pseudo_renko(float val, float sensitivity = 1.0, int length = 7) =>
    // Initialize variables
    varip  float lastRenkoClose = val  // Store the closing price of the last Renko brick
    varip  int   renkoDirection = 0      // Store the direction of the current Renko brick (1 for up, -1 for down)
    varip  int   brickCount     = na       // Keep track of the number of completed Renko bricks
    lastRenkoClose := nz(lastRenkoClose, val) 
    renkoDirection := nz(renkoDirection, 0)
    brickCount     := nz(brickCount, 10)
    maxcount        = ta.max(brickCount)
    countmod        = (maxcount/2 + brickCount/2)/maxcount

    // Calculate dynamic brick size based on volatility of the input value
    brickSize = math.max(val/1000,ta.sma(
          ta.highest(ta.sma(ta.highest(val,length),length) 
          - ta.sma(ta.lowest(val,length), length),length),length)
          * sensitivity
          * countmod
          )
    brickSize /= math.abs(ta.ema(val / val[1] - 1, length)) / math.abs(ta.sma(val / val[1] - 1, length * 2))

    // Calculate Renko bricks
    if barstate.isnew // Only calculate on new bars
        // Check for uptrend
        if val > lastRenkoClose + brickSize
            renkoDirection := 1
            brickCount := math.floor((val - lastRenkoClose) / brickSize) 
            lastRenkoClose := lastRenkoClose + brickCount * brickSize
        // Check for downtrend
        else if val < lastRenkoClose - brickSize
            renkoDirection := -1
            brickCount := math.floor((lastRenkoClose - val) / brickSize)
            lastRenkoClose := lastRenkoClose - brickCount * brickSize

    // Return the Renko close and direction
    [lastRenkoClose, renkoDirection]



// // Example of how to use the library function in a separate script

// //@version=5
// indicator("Example of Pseudo-Renko Stabilizer Library", overlay=true)

// Get the Renko close and direction from the library function
[renkoClose, renkoDirection] = pseudo_renko(ta.ema(open/2+close/2,input(3)),input(10,"senitivity")/2,input(5,"length"))

// Plot the Renko close values as a step line
plot(renkoClose, title="Renko Close", style=plot.style_line, color=renkoDirection == 1 ? color.green : color.red) 