// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © FFriZz

//@version=5
// @description - Log methods that return input value for code readbility and cleaness.
library("Log", overlay = true)
import FFriZz/BoxLine_Lib/10 as BL


// @function level
// @param input ``string` - input value
// @param string type - input type
// @return string
method level(string input, string type, int level, string msg) =>
    _index = bar_index
    _time = time
    _str = "[time: {0}, bar_index: {1}]\ntype: {2}\nlog: {3}\n--------\n{4}\n"
    switch level
        1 => log.info(_str, _time, _index, type, msg, input)
        2 => log.warning(_str, _time, _index, type, msg, input)
        3 => log.error(_str, _time, _index, type, msg, input)
    input

// @function str
// @param input `float - float value
// @return string
export method str(float  input) => str.tostring(input)
// @function str
// @param input `int - int value
// @return string
export method str(int    input) => str.tostring(input)
// @function str
// @param input `bool - bool value
// @return string
export method str(bool   input) => str.tostring(input)
// @function str
// @param input ``string` - string value
// @return string
export method str(string input) => str.tostring(input)

// @function str
// @param input `linefill - linefill object
// @return string
export method str(linefill input) =>
    _1 = linefill.get_line1(input)
    _2 = linefill.get_line2(input)
    [X,Y,XX,YY] = BL.LineXY(_1)
    [x,y,xx,yy] = BL.LineXY(_2)
    str.format('line1 [\nx1: {0}\ny1: {1}\nx2: {2}\ny2: {3}]\nline2 [\nx1: {4}\ny1: {5}\nx2: {6}\ny2: {7}]',X,Y,XX,YY,x,y,xx,yy)
     
// @function str
// @param input `line - line object
// @return string
export method str(line  input) => 
    [x,y,xx,yy] = BL.LineXY(input)
    str.format('x1: {0}\ny1: {1}\nx2: {2}\ny2: {3}',x,y,xx,yy)

// @function str
// @param input `box - box object
// @return string
export method str(box input) => 
    [L,T,R,B] = BL.BoxXY(input)
    str.format('left: {0}\ntop: {1}\nright: {2}\nbottom: {3}',L,T,R,B)

// @function str
// @param input `label - label object
// @return string
export method str(label input) => 
    [x,y,t] = BL.LabelXY(input)
    str.format('x: {0}\ny: {1}\ntext: {2}',x,y,t)

// @function str
// @param input `chart.point - chart.point object
// @return string
export method str(chart.point input) => 
    out = if not na(input)
        _time  = input.time
        _index = input.index
        _price = input.price
        str.format('time: {0}\nbar_index: {1}\nprice: {2}',_time,_index,_price)

// @function str
// @param input `array<float>` - array of floats
// @return string
export method str(array<float>  input) => str.tostring(input)
// @function str
// @param input `array<int>` - array of ints
// @return string
export method str(array<int>    input) => str.tostring(input)
// @function str
// @param input `array<bool>` - array of bools
// @return string
export method str(array<bool>   input) => str.tostring(input)
// @function str
// @param input `array<string>` - array of strings
// @return string
export method str(array<string> input) => str.tostring(input)

// @function str
// @param input `array<linefill>` - array of linefill objects
// @return string
export method str(array<linefill> input) =>
    a_str = array.new<string>()
    m_str = matrix.new<string>()
    a_size = array.size(input)
    
    for i = 0 to a_size > 0 ? a_size-1 : na

        lf = array.get(input,i)
        _1 = linefill.get_line1(lf)
        _2 = linefill.get_line2(lf)
        
        [X,Y,XX,YY] = BL.LineXY(_1)
        [x,y,xx,yy] = BL.LineXY(_2)
        
        a_str.push(
         str.format('\nline1 [\nx1: {0}\ny1: {1}\nx2: {2}\ny2: {3}]\nline2 [\nx1: {4}\ny1: {5}\nx2: {6}\ny2: {7}\n]',X,Y,XX,YY,x,y,xx,yy,i)
         )
    
    str.tostring(a_str)

// @function str
// @param input `array<line>` - array of line objects
// @return string
export method str(array<line> input) => 
    a_str = array.new<string>() 
    a_size = array.size(input)
    
    for i = 0 to a_size > 0 ? a_size-1 : na 
        
        line = array.get(input,i)
        [x,y,xx,yy] = BL.LineXY(line)

        a_str.push(str.format('\nx1: {0}\ny1: {1}\nx2: {2}\ny2: {3}\n({4})',x,y,xx,yy,i))
    
    str.tostring(a_str)

// @function str
// @param input `array<box>` - array of box objects
// @return string
export method str(array<box> input) => 
    a_str = array.new<string>()
    a_size = array.size(input)
    
    for i = 0 to a_size > 0 ? a_size-1 : na
        
        box = array.get(input,i)
        [L,T,R,B] = BL.BoxXY(box)

        a_str.push(str.format('\nleft: {0}\ntop: {1}\nright: {2}\nbottom: {3}\n({4})\n',L,T,R,B,i)) 
    
    str.tostring(a_str)

// @function str
// @param input `array<label>` - array of label objects
// @return string
export method str(array<label> input) => 
    a_str = array.new<string>()
    a_size = array.size(input)
    
    for i = 0 to a_size > 0 ? a_size-1 : na
        
        label = array.get(input,i)
        [x,y,t] = BL.LabelXY(label)

        a_str.push(str.format('\nx: {0}\ny: {1}\ntext: {2}\n({4})\n',x,y,t,i))
    
    str.tostring(a_str)

// @function str
// @param input `array<chart.point>` - array of chart.point objects
// @return string
export method str(array<chart.point> input) => 
    a_str = array.new<string>()
    a_size = array.size(input)
    
    for i = 0 to a_size > 0 ? a_size-1 : na
        
        cp = array.get(input,i)
        if not na(cp)
            _time  = cp.time
            _index = cp.index
            _price = cp.price

            a_str.push(str.format('\ntime: {0}\nbar_index: {1}\nprice: {2}\n({3})\n',_time,_index,_price,i))

    str.tostring(a_str)

// @function str
// @param input `matrix<float>` - matrix of floats
// @return string
export method str(matrix<float>  input) => str.tostring(input,'0.00')

// @function str
// @param input `matrix<int>` - matrix of ints
// @return string
export method str(matrix<int> 	 input) => str.tostring(input,'00')
// @function str
// @param input `matrix<bool>` - matrix of bools
// @return string
export method str(matrix<bool>   input) => str.tostring(input)
// @function str
// @param input `matrix<string>` - matrix of strings
// @return string
export method str(matrix<string> input) => str.tostring(input)

// @function str
// @param input `matrix<linefill>` - matrix of linefill objects
// @return string
export method str(matrix<linefill> input) =>
    m_str = matrix.new<string>()
    m_rows = matrix.rows(input)
    m_cols = matrix.columns(input)
    
    for r = 0 to m_rows > 0 ? m_rows-1 : na
        a_str = array.new<string>()
        
        for c = 0 to m_cols > 0 ? m_cols-1 : na
            lf = matrix.get(input,r,c)
            _1 = linefill.get_line1(lf)
            _2 = linefill.get_line2(lf)
            
            [X,Y,XX,YY] = BL.LineXY(_1)
            [x,y,xx,yy] = BL.LineXY(_2)
            a_str.push(
             str.format('\nline1 [\nx1: {0}\ny1: {1}\nx2: {2}\ny2: {3}]\nline2 [\nx1: {4}\ny1: {5}\nx2: {6}\ny2: {7}\n]({8}:{9})\n',X,Y,XX,YY,x,y,xx,yy,r,c)
             )
        
        matrix.add_row(m_str,r,a_str)
    str.tostring(m_str)

// @function str
// @param input `matrix<line>` - matrix of line objects
// @return string
export method str(matrix<line> input) => 
    m_str = matrix.new<string>()
    m_rows = matrix.rows(input)
    m_cols = matrix.columns(input)
    
    for r = 0 to m_rows > 0 ? m_rows-1 : na
        a_str = array.new<string>()
        
        for c = 0 to m_cols > 0 ? m_cols-1 : na
            line = matrix.get(input,r,c)
            [x,y,xx,yy] = BL.LineXY(line)
            a_str.push(
             str.format('\nx1: {0}\ny1: {1}\nx2: {2}\ny2: {3}\n({4}:{5})\n',x,y,xx,yy,r,c)
             )
            
        matrix.add_row(m_str,r,a_str)	
    str.tostring(m_str)

// @function str
// @param input `matrix<box>` - matrix of box objects
// @return string
export method str(matrix<box> input) => 
    m_str = matrix.new<string>()
    m_rows = matrix.rows(input)
    m_cols = matrix.columns(input)
    
    for r = 0 to m_rows > 0 ? m_rows-1 : na
        a_str = array.new<string>()
        
        for c = 0 to m_cols > 0 ? m_cols-1 : na
            box = matrix.get(input,r,c)
            [L,T,R,B] = BL.BoxXY(box)
            a_str.push(
             str.format('\nleft: {0}\ntop: {1}\nright: {2}\nbottom: {3}\n({4}:{5})\n',L,T,R,B,r,c)
             )

        matrix.add_row(m_str,r,a_str)
    str.tostring(m_str)

// @function str
// @param input `matrix<label>` - matrix of label objects
// @return string
export method str(matrix<label> input) => 
    m_str  = matrix.new<string>()
    m_rows = matrix.rows(input)
    m_cols = matrix.columns(input)
    
    for r = 0 to m_rows > 0 ? m_rows-1 : na
        a_str = array.new<string>()
        
        for c = 0 to m_cols > 0 ? m_cols-1 : na
            label = matrix.get(input,r,c)
            [x,y,t] = BL.LabelXY(label)
            a_str.push(
             str.format('\nx: {0}\ny: {1}\ntext: {2}\n({3}:{4})\n',x,y,t,r,c)
             )

        matrix.add_col(m_str,r,a_str)	
    str.tostring(m_str)

// @function str
// @param input `matrix<chart.point>` - matrix of chart.point objects
// @return string
export method str(matrix<chart.point> input) =>
    m_str  = matrix.new<string>()
    m_rows = matrix.rows(input)
    m_cols = matrix.columns(input)
    
    for r = 0 to m_rows > 0 ? m_rows-1 : na
        a_str = array.new<string>()
        
        for c = 0 to m_cols > 0 ? m_cols-1 : na
            cp = matrix.get(input,r,c)
            if not na(cp)
                _time  = cp.time
                _index = cp.index
                _price = cp.price

                a_str.push(
                 str.format('\ntime: {0}\nbar_index: {1}\nprice: {2}\n({3}:{4})\n',_time,_index,_price,r,c)
                 )

        matrix.add_col(m_str,r,a_str)	
    str.tostring(m_str)


// @function info
// @param input `any` - input value
// @param string msg - message to log
// @param int level - log level
// @param string type - input type
// @return any
info(input, string msg, int level, string type) => 
    str(input).level(type, level, msg)
    input


// @function Logs the input value with the 'info' log level.
// @param input `chart.point - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method info(chart.point input, string msg=na) => info(input, msg, 1, 'chart.point')


// @function Logs the input value with the 'info' log level.
// @param input `float - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method info(float input, string msg=na) => info(input, msg, 1, 'float')

// @function Logs the input value with the 'info' log level.
// @param input `int - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method info(int input, string msg=na) => info(input, msg, 1, 'int')

// @function Logs the input value with the 'info' log level.
// @param input `bool - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method info(bool input, string msg=na) => info(input, msg, 1, 'bool')

// @function Logs the input value with the 'info' log level.
// @param input ``string` - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method info(string input, string msg=na) => info(input, msg, 1, 'string')

// @function Logs the input value with the 'info' log level.
// @param input `linefill - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method info(linefill input, string msg=na) => info(input, msg, 1, 'linefill')

// @function Logs the input value with the 'info' log level.
// @param input `line - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method info(line input, string msg=na) => info(input, msg, 1, 'line')

// @function Logs the input value with the 'info' log level.
// @param input `box - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method info(box input, string msg=na) => info(input, msg, 1, 'box')

// @function Logs the input value with the 'info' log level.
// @param input `label - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method info(label input, string msg=na) => info(input, msg, 1, 'label')

// @function Logs the input array with the 'info' log level.
// @param input `array<chart.point>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method info(array<chart.point> input, string msg=na) => info(input, msg, 1, 'array<chart.point>')

// @function Logs the input array with the 'info' log level.
// @param input `array<float>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method info(array<float> input, string msg=na) => info(input, msg, 1, 'array<float>')

// @function Logs the input array with the 'info' log level.
// @param input `array<int>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method info(array<int> input, string msg=na) => info(input, msg, 1, 'array<int>')

// @function Logs the input array with the 'info' log level.
// @param input `array<bool>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method info(array<bool> input, string msg=na) => info(input, msg, 1, 'array<bool>')

// @function Logs the input array with the 'info' log level.
// @param input `array<string>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method info(array<string> input, string msg=na) => info(input, msg, 1, 'array<string>')

// @function Logs the input array with the 'info' log level.
// @param input `array<linefill>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method info(array<linefill> input, string msg=na) => info(input, msg, 1, 'array<linefill>')

// @function Logs the input array with the 'info' log level.
// @param input `array<line>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method info(array<line> input, string msg=na) => info(input, msg, 1, 'array<line>')

// @function Logs the input array with the 'info' log level.
// @param input `array<box>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method info(array<box> input, string msg=na) => info(input, msg, 1, 'array<box>')

// @function Logs the input array with the 'info' log level.
// @param input `array<label>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method info(array<label> input, string msg=na) => info(input, msg, 1, 'array<label>')

// @function Logs the input matrix with the 'info' log level.
// @param input `matrix<chart.point>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method info(matrix<chart.point> input, string msg=na) => info(input, msg, 1, 'matrix<chart.point>')

// @function Logs the input matrix with the 'info' log level.
// @param input `matrix<float>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method info(matrix<float> input, string msg=na) => info(input, msg, 1, 'matrix<float>')

// @function Logs the input matrix with the 'info' log level.
// @param input `matrix<int>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method info(matrix<int> input, string msg=na) => info(input, msg, 1, 'matrix<int>')

// @function Logs the input matrix with the 'info' log level.
// @param input `matrix<bool>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method info(matrix<bool> input, string msg=na) => info(input, msg, 1, 'matrix<bool>')

// @function Logs the input matrix with the 'info' log level.
// @param input `matrix<string>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method info(matrix<string> input, string msg=na) => info(input, msg, 1, 'matrix<string>')

// @function Logs the input matrix with the 'info' log level.
// @param input `matrix<linefill>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method info(matrix<linefill> input, string msg=na) => info(input, msg, 1, 'matrix<linefill>')

// @function Logs the input matrix with the 'info' log level.
// @param input `matrix<line>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method info(matrix<line> input, string msg=na) => info(input, msg, 1, 'matrix<line>')

// @function Logs the input matrix with the 'info' log level.
// @param input `matrix<box>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method info(matrix<box> input, string msg=na) => info(input, msg, 1, 'matrix<box>')

// @function Logs the input matrix with the 'info' log level.
// @param input `matrix<label>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method info(matrix<label> input, string msg=na) => info(input, msg, 1, 'matrix<label>')


// @function warn
// @param input `any` - input value
// @param string msg - message to log
// @param int level - log level
// @param string type - input type
// @return any
warn(input, string msg, int level, string type) => 
    str(input).level(type, level, msg)
    input


// @function Logs the input value with the 'warning' log level.
// @param input `chart.point - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method warn(chart.point input, string msg=na) => warn(input, msg, 2, 'chart.point')

// @function Logs the input value with the 'warning' log level.
// @param input `float - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method warn(float input, string msg=na) => warn(input, msg, 2, 'float')

// @function Logs the input value with the 'warning' log level.
// @param input `int - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method warn(int input, string msg=na) => warn(input, msg, 2, 'int')

// @function Logs the input value with the 'warning' log level.
// @param input `bool - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method warn(bool input, string msg=na) => warn(input, msg, 2, 'bool')

// @function Logs the input value with the 'warning' log level.
// @param input ``string` - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method warn(string input, string msg=na) => warn(input, msg, 2, 'string')

// @function Logs the input value with the 'warning' log level.
// @param input `linefill - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method warn(linefill input, string msg=na) => warn(input, msg, 2, 'linefill')

// @function Logs the input value with the 'warning' log level.
// @param input `line - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method warn(line input, string msg=na) => warn(input, msg, 2, 'line')

// @function Logs the input value with the 'warning' log level.
// @param input `box - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method warn(box input, string msg=na) => warn(input, msg, 2, 'box')

// @function Logs the input value with the 'warning' log level.
// @param input `label - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method warn(label input, string msg=na) => warn(input, msg, 2, 'label')

// @function Logs the input array with the 'warning' log level.
// @param input `array<chart.point>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method warn(array<chart.point> input, string msg=na) => warn(input, msg, 2, 'array<chart.point>')

// @function Logs the input array with the 'warning' log level.
// @param input `array<float>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method warn(array<float> input, string msg=na) => warn(input, msg, 2, 'array<float>')

// @function Logs the input array with the 'warning' log level.
// @param input `array<int>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method warn(array<int> input, string msg=na) => warn(input, msg, 2, 'array<int>')

// @function Logs the input array with the 'warning' log level.
// @param input `array<bool>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method warn(array<bool> input, string msg=na) => warn(input, msg, 2, 'array<bool>')

// @function Logs the input array with the 'warning' log level.
// @param input `array<string>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method warn(array<string> input, string msg=na) => warn(input, msg, 2, 'array<string>')

// @function Logs the input array with the 'warning' log level.
// @param input `array<linefill>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method warn(array<linefill> input, string msg=na) => warn(input, msg, 2, 'array<linefill>')

// @function Logs the input array with the 'warning' log level.
// @param input `array<line>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method warn(array<line> input, string msg=na) => warn(input, msg, 2, 'array<line>')

// @function Logs the input array with the 'warning' log level.
// @param input `array<box>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method warn(array<box> input, string msg=na) => warn(input, msg, 2, 'array<box>')

// @function Logs the input array with the 'warning' log level.
// @param input `array<label>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method warn(array<label> input, string msg=na) => warn(input, msg, 2, 'array<label>')

// @function Logs the input matrix with the 'warning' log level.
// @param input `matrix<chart.point>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method warn(matrix<chart.point> input, string msg=na) => warn(input, msg, 2, 'matrix<chart.point>')

// @function Logs the input matrix with the 'warning' log level.
// @param input `matrix<float>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method warn(matrix<float> input, string msg=na) => warn(input, msg, 2, 'matrix<float>')

// @function Logs the input matrix with the 'warning' log level.
// @param input `matrix<int>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method warn(matrix<int> input, string msg=na) => warn(input, msg, 2, 'matrix<int>')

// @function Logs the input matrix with the 'warning' log level.
// @param input `matrix<bool>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method warn(matrix<bool> input, string msg=na) => warn(input, msg, 2, 'matrix<bool>')

// @function Logs the input matrix with the 'warning' log level.
// @param input `matrix<string>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method warn(matrix<string> input, string msg=na) => warn(input, msg, 2, 'matrix<string>')

// @function Logs the input matrix with the 'warning' log level.
// @param input `matrix<linefill>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method warn(matrix<linefill> input, string msg=na) => warn(input, msg, 2, 'matrix<linefill>')

// @function Logs the input matrix with the 'warning' log level.
// @param input `matrix<line>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method warn(matrix<line> input, string msg=na) => warn(input, msg, 2, 'matrix<line>')

// @function Logs the input matrix with the 'warning' log level.
// @param input `matrix<box>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method warn(matrix<box> input, string msg=na) => warn(input, msg, 2, 'matrix<box>')

// @function Logs the input matrix with the 'warning' log level.
// @param input `matrix<label>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method warn(matrix<label> input, string msg=na) => warn(input, msg, 2, 'matrix<label>')


// @function error
// @param input `any` - input value
// @param string msg - message to log
// @param int level - log level
// @param string type - input type
// @return any
error(input, string msg, int level, string type) => 
    str(input).level(type, level, msg)
    input


// @function Logs the input value with the 'error' log level.
// @param input `chart.point - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method error(chart.point input, string msg=na) => error(input, msg, 3, 'chart.point')

// @function Logs the input value with the 'error' log level.
// @param input `float - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method error(float input, string msg=na) => error(input, msg, 3, 'float')

// @function Logs the input value with the 'error' log level.
// @param input `int - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method error(int input, string msg=na) => error(input, msg, 3, 'int')

// @function Logs the input value with the 'error' log level.
// @param input `bool - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method error(bool input, string msg=na) => error(input, msg, 3, 'bool')

// @function Logs the input value with the 'error' log level.
// @param input ``string` - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method error(string input, string msg=na) => error(input, msg, 3, 'string')

// @function Logs the input value with the 'error' log level.
// @param input `linefill - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method error(linefill input, string msg=na) => error(input, msg, 3, 'linefill')

// @function Logs the input value with the 'error' log level.
// @param input `line - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method error(line input, string msg=na) => error(input, msg, 3, 'line')

// @function Logs the input value with the 'error' log level.
// @param input `box - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method error(box input, string msg=na) => error(input, msg, 3, 'box')

// @function Logs the input value with the 'error' log level.
// @param input `label - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input value.
export method error(label input, string msg=na) => error(input, msg, 3, 'label')

// @function Logs the input array with the 'error' log level.
// @param input `array<chart.point>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method error(array<chart.point> input, string msg=na) => error(input, msg, 3, 'array<chart.point>')

// @function Logs the input array with the 'error' log level.
// @param input `array<float>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method error(array<float> input, string msg=na) => error(input, msg, 3, 'array<float>')

// @function Logs the input array with the 'error' log level.
// @param input `array<int>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method error(array<int> input, string msg=na) => error(input, msg, 3, 'array<int>')

// @function Logs the input array with the 'error' log level.
// @param input `array<bool>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method error(array<bool> input, string msg=na) => error(input, msg, 3, 'array<bool>')

// @function Logs the input array with the 'error' log level.
// @param input `array<string>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method error(array<string> input, string msg=na) => error(input, msg, 3, 'array<string>')

// @function Logs the input array with the 'error' log level.
// @param input `array<linefill>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method error(array<linefill> input, string msg=na) => error(input, msg, 3, 'array<linefill>')

// @function Logs the input array with the 'error' log level.
// @param input `array<line>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method error(array<line> input, string msg=na) => error(input, msg, 3, 'array<line>')

// @function Logs the input array with the 'error' log level.
// @param input `array<box>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method error(array<box> input, string msg=na) => error(input, msg, 3, 'array<box>')

// @function Logs the input array with the 'error' log level.
// @param input `array<label>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input array.
export method error(array<label> input, string msg=na) => error(input, msg, 3, 'array<label>')

// @function Logs the input matrix with the 'error' log level.
// @param input `matrix<chart.point>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method error(matrix<chart.point> input, string msg=na) => error(input, msg, 3, 'matrix<chart.point>')

// @function Logs the input matrix with the 'error' log level.
// @param input `matrix<float>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method error(matrix<float> input, string msg=na) => error(input, msg, 3, 'matrix<float>')

// @function Logs the input matrix with the 'error' log level.
// @param input `matrix<int>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method error(matrix<int> input, string msg=na) => error(input, msg, 3, 'matrix<int>')

// @function Logs the input matrix with the 'error' log level.
// @param input `matrix<bool>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method error(matrix<bool> input, string msg=na) => error(input, msg, 3, 'matrix<bool>')

// @function Logs the input matrix with the 'error' log level.
// @param input `matrix<string>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method error(matrix<string> input, string msg=na) => error(input, msg, 3, 'matrix<string>')

// @function Logs the input matrix with the 'error' log level.
// @param input `matrix<linefill>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method error(matrix<linefill> input, string msg=na) => error(input, msg, 3, 'matrix<linefill>')

// @function Logs the input matrix with the 'error' log level.
// @param input `matrix<line>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method error(matrix<line> input, string msg=na) => error(input, msg, 3, 'matrix<line>')

// @function Logs the input matrix with the 'error' log level.
// @param input `matrix<box>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method error(matrix<box> input, string msg=na) => error(input, msg, 3, 'matrix<box>')

// @function Logs the input matrix with the 'error' log level.
// @param input `matrix<label>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @returns The input matrix.
export method error(matrix<label> input, string msg=na) => error(input, msg, 3, 'matrix<label>')


// @function log
// @param input `any` - input value
// @param string msg - message to log
// @param int level - log level
// @param string type - input type
// @return any
log(input, string msg, int level, string type) => 
    str(input).level(type, level, msg)
    input


// @function Logs the input value with the specified log level.
// @param input `chart.point - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input value.
export method log(chart.point input, string msg=na, int level=1) => log(input, msg, level, 'chart.point')
   
// @function Logs the input value with the specified log level.
// @param input `float - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input value.
export method log(float input, string msg=na, int level=1) => log(input, msg, level, 'float')
   
// @function Logs the input value with the specified log level.
// @param input `int - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input value.
export method log(int input, string msg=na, int level=1) => log(input, msg, level, 'int')
   
// @function Logs the input value with the specified log level.
// @param input `bool - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input value.
export method log(bool input, string msg=na, int level=1) => log(input, msg, level, 'bool')
   
// @function Logs the input value with the specified log level.
// @param input ``string` - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input value.
export method log(string input, string msg=na, int level=1) => log(input, msg, level, 'string')
   
// @function Logs the input value with the specified log level.
// @param input `linefill - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input value.
export method log(linefill input, string msg=na, int level=1) => log(input, msg, level, 'linefill')
   
// @function Logs the input value with the specified log level.
// @param input `line - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input value.
export method log(line input, string msg=na, int level=1) => log(input, msg, level, 'line')
   
// @function Logs the input value with the specified log level.
// @param input `box - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input value.
export method log(box input, string msg=na, int level=1) => log(input, msg, level, 'box')
   
// @function Logs the input value with the specified log level.
// @param input `label - The input value to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input value.
export method log(label input, string msg=na, int level=1) => log(input, msg, level, 'label')
   
// @function Logs the input array with the specified log level.
// @param input `array<chart.point>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input array.
export method log(array<chart.point> input, string msg=na, int level=1) => log(input, msg, level, 'array<chart.point>')
   
// @function Logs the input array with the specified log level.
// @param input `array<float>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input array.
export method log(array<float> input, string msg=na, int level=1) => log(input, msg, level, 'array<float>')
   
// @function Logs the input array with the specified log level.
// @param input `array<int>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input array.
export method log(array<int> input, string msg=na, int level=1) => log(input, msg, level, 'array<int>')
   
// @function Logs the input array with the specified log level.
// @param input `array<bool>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input array.
export method log(array<bool> input, string msg=na, int level=1) => log(input, msg, level, 'array<bool>')
   
// @function Logs the input array with the specified log level.
// @param input `array<string>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input array.
export method log(array<string> input, string msg=na, int level=1) => log(input, msg, level, 'array<string>')
   
// @function Logs the input array with the specified log level.
// @param input `array<linefill>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input array.
export method log(array<linefill> input, string msg=na, int level=1) => log(input, msg, level, 'array<linefill>')
   
// @function Logs the input array with the specified log level.
// @param input `array<line>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input array.
export method log(array<line> input, string msg=na, int level=1) => log(input, msg, level, 'array<line>')
   
// @function Logs the input array with the specified log level.
// @param input `array<box>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input array.
export method log(array<box> input, string msg=na, int level=1) => log(input, msg, level, 'array<box>')
   
// @function Logs the input array with the specified log level.
// @param input `array<label>` - The input array to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input array.
export method log(array<label> input, string msg=na, int level=1) => log(input, msg, level, 'array<label>')
   
// @function Logs the input matrix with the specified log level.
// @param input `matrix<chart.point>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input matrix.
export method log(matrix<chart.point> input, string msg=na, int level=1) => log(input, msg, level, 'matrix<chart.point>')
   
// @function Logs the input matrix with the specified log level.
// @param input `matrix<float>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input matrix.
export method log(matrix<float> input, string msg=na, int level=1) => log(input, msg, level, 'matrix<float>')
   
// @function Logs the input matrix with the specified log level.
// @param input `matrix<int>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input matrix.
export method log(matrix<int> input, string msg=na, int level=1) => log(input, msg, level, 'matrix<int>')
   
// @function Logs the input matrix with the specified log level.
// @param input `matrix<bool>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input matrix.
export method log(matrix<bool> input, string msg=na, int level=1) => log(input, msg, level, 'matrix<bool>')
   
// @function Logs the input matrix with the specified log level.
// @param input `matrix<string>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input matrix.
export method log(matrix<string> input, string msg=na, int level=1) => log(input, msg, level, 'matrix<string>')
   
// @function Logs the input matrix with the specified log level.
// @param input `matrix<linefill>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input matrix.
export method log(matrix<linefill> input, string msg=na, int level=1) => log(input, msg, level, 'matrix<linefill>')
   
// @function Logs the input matrix with the specified log level.
// @param input `matrix<line>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input matrix.
export method log(matrix<line> input, string msg=na, int level=1) => log(input, msg, level, 'matrix<line>')
   
// @function Logs the input matrix with the specified log level.
// @param input `matrix<box>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input matrix.
export method log(matrix<box> input, string msg=na, int level=1) => log(input, msg, level, 'matrix<box>')
   
// @function Logs the input matrix with the specified log level.
// @param input `matrix<label>` - The input matrix to log.
// @param msg `string` - The message to log. Default is an empty string.
// @param level `int` - The log level (1 - info, 2 - warning, 3 - error). Default is 1.
// @returns The input matrix.
export method log(matrix<label> input, string msg=na, int level=1) => log(input, msg, level, 'matrix<label>')
   


// Testing
// if barstate.islast
//     cp = chart.point.new(time, bar_index, high).info('chart point test instance')
//     int = (1).info()
//     float = (1.1).info()
//     bool = (true).info()
//     string = ("test").info()
//     line = line.new(bar_index-10, close, bar_index, close).info()
//     box = box.new(bar_index-10, high, bar_index, low).info()
//     label = label.new(bar_index, high, "test").info()
//     lf = linefill.new(line, line.copy(line), color.red).info()

//     acp = array.from(cp, cp, cp, cp).warn()
//     afloat = array.from(232.3,2342.4,3.3,2.2,1.1).warn()
//     aint = array.from(1,2,3,4,5).warn()
//     abool = array.from(true,false,true,false,true).warn()
//     astring = array.from("1","2","3","4","5").warn()
//     aline = array.from(line, line, line, line).warn()
//     abox = array.from(box, box, box, box).warn()
//     alabel = array.from(label, label, label, label).warn()
//     alinefill = array.from(lf, lf, lf, lf).warn()

//     mcp = matrix.new<chart.point>(5, 2, cp).error()
//     mfloat = matrix.new<float>(5, 2, float).error()
//     mint = matrix.new<int>(5, 2, int).error()
//     mbool = matrix.new<bool>(5, 2, bool).error()
//     mstring = matrix.new<string>(5, 2, string).error()
//     mline = matrix.new<line>(5, 2, line).error()
//     mbox = matrix.new<box>(5, 2, box).error()
//     mlabel = matrix.new<label>(5, 2, label).error()
//     mlinefill = matrix.new<linefill>(5, 2, lf).error()





