// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © rajabitt2

//@version=5

// @description TODO: add library description here
library(title = "time_zone_corrector")

export timeZoneCorrector() =>
	// Simulate switch-case structure using ternary operators
	if(syminfo.timezone == "America/New_York")
		-8
	else if(syminfo.timezone == "America/Chicago")
		-9
	else if(syminfo.timezone == "America/Chicago")
		-9
	else if(syminfo.timezone == "America/Los_Angeles")
		-11
	else if(syminfo.timezone == "America/Sao_Paulo")
		-6
	else if(syminfo.timezone == "America/Argentina/Buenos_Aires")
		-6
	else if(syminfo.timezone == "America/Toronto")
		-8
	else if(syminfo.timezone == "America/Mexico_City")
		-9
	else if(syminfo.timezone == "America/Bogota")
		-8
	else if(syminfo.timezone == "America/Lima")
		-8
	else if(syminfo.timezone == "America/Caracas")
		-7
	else if(syminfo.timezone == "America/Santiago")
		-6
	else if(syminfo.timezone == "America/Montevideo")
		-6
	else if(syminfo.timezone == "America/Phoenix")
		-10
	else if(syminfo.timezone == "America/Denver")
		-9
	else if(syminfo.timezone == "America/Edmonton")
		-10
	else if(syminfo.timezone == "America/Vancouver")
		-11
	else if(syminfo.timezone == "America/Winnipeg")
		-9
	else if(syminfo.timezone == "America/Halifax")
		-7
	else if(syminfo.timezone == "America/Anchorage")
		-11
	else if(syminfo.timezone == "America/St_Johns")
		-6
	else if(syminfo.timezone == "America/Guatemala")
		-9
	else if(syminfo.timezone == "America/Managua")
		-9
	else if(syminfo.timezone == "America/El_Salvador")
		-9
	else if(syminfo.timezone == "America/Costa_Rica")
		-9
	else if(syminfo.timezone == "America/Port_of_Spain")
		-7
	else if(syminfo.timezone == "America/Kingston")
		-8
	else if(syminfo.timezone == "America/Panama")
		-8
	else if(syminfo.timezone == "America/Bermuda")
		-7
	else if(syminfo.timezone == "America/Barbados")
		-7
	else if(syminfo.timezone == "America/Havana")
		-8
	else if(syminfo.timezone == "America/Dominica")
		-7
	else if(syminfo.timezone == "America/Grenada")
		-7
	else if(syminfo.timezone == "America/Santo_Domingo")
		-7
	else if(syminfo.timezone == "America/Port-au-Prince")
		-8
	else if(syminfo.timezone == "America/Cayman")
		-8
	else if(syminfo.timezone == "America/Tegucigalpa")
		-9
	else if(syminfo.timezone == "America/Belize")
		-9
	else if(syminfo.timezone == "America/Nassau")
		-8
	else if(syminfo.timezone == "America/Puerto_Rico")
		-7
	else if(syminfo.timezone == "America/Jamaica")
		-8
	else if(syminfo.timezone == "America/Curacao")
		-7
	else if(syminfo.timezone == "America/Aruba")
		-7
	else if(syminfo.timezone == "America/Martinique")
		-7
	else if(syminfo.timezone == "America/Guadeloupe")
		-7
	else if(syminfo.timezone == "America/St_Barthelemy")
		-7
	else if(syminfo.timezone == "America/St_Kitts")
		-7
	else if(syminfo.timezone == "America/St_Lucia")
		-7
	else if(syminfo.timezone == "America/St_Vincent")
		-7
	else if(syminfo.timezone == "America/Antigua")
		-7
	else if(syminfo.timezone == "America/Anguilla")
		-7
	else if(syminfo.timezone == "America/Moncton")
		-7
	else if(syminfo.timezone == "America/Iqaluit")
		-8
	else if(syminfo.timezone == "America/Whitehorse")
		-10
	else if(syminfo.timezone == "America/Yellowknife")
		-10
	else if(syminfo.timezone == "America/Inuvik")
		-10
	else if(syminfo.timezone == "America/Rainy_River")
		-9
	else if(syminfo.timezone == "America/Resolute")
		-9
	else if(syminfo.timezone == "merica/Rankin_Inlet")
		-9
	else if(syminfo.timezone == "America/Pangnirtung")
		-8
	else if(syminfo.timezone == "America/Cambridge_Bay")
		-10
	else if(syminfo.timezone == "America/Coral_Harbour")
		-6
	else if(syminfo.timezone == "America/Goose_Bay")
		-7
	else if(syminfo.timezone == "America/Blanc-Sablon")
		-7
	else if(syminfo.timezone == "America/Atikokan")
		-8
	else if(syminfo.timezone == "America/Thule")
		-7
	else if(syminfo.timezone == "America/Godthab")
		-6
	else if(syminfo.timezone == "Europe/London")
		-3
	else if(syminfo.timezone == "Europe/Paris")
		-2
	else if(syminfo.timezone == "Europe/Berlin")
		-2
	else if(syminfo.timezone == "Europe/Moscow")
		0
	else if(syminfo.timezone == "Europe/Istanbul")
		0
	else if(syminfo.timezone == "Europe/Zurich")
		-2
	else if(syminfo.timezone == "Europe/Madrid")
		-2
	else if(syminfo.timezone == "Europe/Luxembourg")
		-2
	else if(syminfo.timezone == "Europe/Monaco")
		-2
	else if(syminfo.timezone == "Europe/Malta")
		-2
	else if(syminfo.timezone == "Europe/Amsterdam")
		-2
	else if(syminfo.timezone == "Europe/Brussels")
		-2
	else if(syminfo.timezone == "Europe/Oslo")
		-2
	else if(syminfo.timezone == "Europe/Copenhagen")
		-2
	else if(syminfo.timezone == "Europe/Stockholm")
		-2
	else if(syminfo.timezone == "Europe/Helsinki")
		-1
	else if(syminfo.timezone == "Europe/Rome")
		-2
	else if(syminfo.timezone == "Europe/Vienna")
		-2
	else if(syminfo.timezone == "Europe/Prague")
		-2
	else if(syminfo.timezone == "Europe/Bratislava")
		-2
	else if(syminfo.timezone == "Europe/Warsaw")
		-2
	else if(syminfo.timezone == "Europe/Budapest")
		-2
	else if(syminfo.timezone == "Europe/Bucharest")
		-1
	else if(syminfo.timezone == "Europe/Sofia")
		-1
	else if(syminfo.timezone == "Europe/Belgrade")
		-2
	else if(syminfo.timezone == "Europe/Lisbon")
		-3
	else if(syminfo.timezone == "Europe/Athens")
		-1
	else if(syminfo.timezone == "Europe/Chisinau")
		-1
	else if(syminfo.timezone == "Europe/Zagreb")
		-2
	else if(syminfo.timezone == "Europe/Tallinn")
		-1
	else if(syminfo.timezone == "Europe/Riga")
		-1
	else if(syminfo.timezone == "Europe/Vilnius")
		-1
	else if(syminfo.timezone == "Europe/Ljubljana")
		-2
	else if(syminfo.timezone == "Europe/Sarajevo")
		-2
	else if(syminfo.timezone == "Europe/Podgorica")
		-2
	else if(syminfo.timezone == "Europe/Skopje")
		-2
	else if(syminfo.timezone == "Europe/Tirane")
		-2
	else if(syminfo.timezone == "Europe/Kiev")
		-1
	else if(syminfo.timezone == "Europe/Uzhgorod")
		-1
	else if(syminfo.timezone == "Europe/Zaporozhye")
		-1
	else if(syminfo.timezone == "Europe/Chita")
		6
	else if(syminfo.timezone == "Europe/Novosibirsk")
		4
	else if(syminfo.timezone == "Europe/Omsk")
		3
	else if(syminfo.timezone == "Europe/Krasnoyarsk")
		4
	else if(syminfo.timezone == "Europe/Irkutsk")
		5
	else if(syminfo.timezone == "Europe/Yakutsk")
		6
	else if(syminfo.timezone == "Europe/Vladivostok")
		7
	else if(syminfo.timezone == "Europe/Kamchatka")
		9
	else if(syminfo.timezone == "Europe/Chita")
		6
	else if(syminfo.timezone == "Asia/Tokyo")
		6
	else if(syminfo.timezone == "Asia/Hong_Kong")
		5
	else if(syminfo.timezone == "Asia/Shanghai")
		5
	else if(syminfo.timezone == "Asia/Singapore")
		5
	else if(syminfo.timezone == "Asia/Seoul")
		6
	else if(syminfo.timezone == "Asia/Kuala_Lumpur")
		5
	else if(syminfo.timezone == "Asia/Manila")
		5
	else if(syminfo.timezone == "Asia/Jakarta")
		4
	else if(syminfo.timezone == "Asia/Bangkok")
		4
	else if(syminfo.timezone == "Asia/Taipei")
		5
	else if(syminfo.timezone == "Asia/Ho_Chi_Minh")
		4
	else if(syminfo.timezone == "Asia/Almaty")
		3
	else if(syminfo.timezone == "Asia/Colombo")
		2
	else if(syminfo.timezone == "Asia/Kolkata")
		2
	else if(syminfo.timezone == "Asia/Karachi")
		2
	else if(syminfo.timezone == "Asia/Dubai")
		1
	else if(syminfo.timezone == "Asia/Muscat")
		1
	else if(syminfo.timezone == "Asia/Tehran")
		0
	else if(syminfo.timezone == "Asia/Baghdad")
		0
	else if(syminfo.timezone == "Asia/Riyadh")
		0
	else if(syminfo.timezone == "Asia/Jerusalem")
		-1
	else if(syminfo.timezone == "Asia/Amman")
		-1
	else if(syminfo.timezone == "Asia/Beirut")
		-1
	else if(syminfo.timezone == "Asia/Damascus")
		-1
	else if(syminfo.timezone == "Asia/Istanbul")
		0
	else if(syminfo.timezone == "Asia/Kuwait")
		0
	else if(syminfo.timezone == "Asia/Manama")
		0
	else if(syminfo.timezone == "Asia/Doha")
		0
	else if(syminfo.timezone == "Asia/Kathmandu")
		3
	else if(syminfo.timezone == "Asia/Yangon")
		3
	else if(syminfo.timezone == "Asia/Baku")
		1
	else if(syminfo.timezone == "Asia/Tbilisi")
		1
	else if(syminfo.timezone == "Asia/Yerevan")
		1
	else if(syminfo.timezone == "Asia/Dushanbe")
		2
	else if(syminfo.timezone == "Asia/Tashkent")
		2
	else if(syminfo.timezone == "Asia/Ashgabat")
		2
	else if(syminfo.timezone == "Asia/Kabul")
		1
	else if(syminfo.timezone == "Asia/Samarkand")
		2
	else if(syminfo.timezone == "Asia/Novosibirsk")
		4
	else if(syminfo.timezone == "Asia/Omsk")
		3
	else if(syminfo.timezone == "Asia/Krasnoyarsk")
		4
	else if(syminfo.timezone == "Asia/Irkutsk")
		5
	else if(syminfo.timezone == "Asia/Yakutsk")
		6
	else if(syminfo.timezone == "Asia/Vladivostok")
		7
	else if(syminfo.timezone == "Asia/Kamchatka")
		9
	else if(syminfo.timezone == "Asia/Chita")
		6
	else if(syminfo.timezone == "Asia/Ulaanbaatar")
		5
	else if(syminfo.timezone == "Asia/Hovd")
		4
	else if(syminfo.timezone == "Asia/Choibalsan")
		5
	else if(syminfo.timezone == "Asia/Barnaul")
		4
	else if(syminfo.timezone == "Asia/Tomsk")
		4
	else if(syminfo.timezone == "Asia/Brisbane")
		7
	else if(syminfo.timezone == "Asia/Sydney")
		7
	else if(syminfo.timezone == "Asia/Melbourne")
		7
	else if(syminfo.timezone == "Asia/Hobart")
		8
	else if(syminfo.timezone == "Asia/Adelaide")
		6
	else if(syminfo.timezone == "Asia/Darwin")
		6
	else if(syminfo.timezone == "Asia/Perth")
		5
	else if(syminfo.timezone == "Asia/Eucla")
		2
	else if(syminfo.timezone == "Asia/Christmas")
		11
	else if(syminfo.timezone == "Asia/Cocos")
		3
	else if(syminfo.timezone == "Asia/Lord_Howe")
		7
	else if(syminfo.timezone == "Asia/Norfolk")
		8
	else if(syminfo.timezone == "Asia/Macquarie")
		8
	else if(syminfo.timezone == "Asia/Pago_Pago")
		-14
	else if(syminfo.timezone == "Asia/Tahiti")
		-13
	else if(syminfo.timezone == "Asia/Noumea")
		8
	else if(syminfo.timezone == "Asia/Nauru")
		9
	else if(syminfo.timezone == "Asia/Wallis")
		9
	else if(syminfo.timezone == "Asia/Fakaofo")
		-13
	else if(syminfo.timezone == "Asia/Apia")
		10
	else if(syminfo.timezone == "Asia/Tongatapu")
		10
	else if(syminfo.timezone == "Asia/Kiritimati")
		11
	else if(syminfo.timezone == "Asia/Chatham")
		11
	else if(syminfo.timezone == "Etc/UTC")
		-3
	else 
		3