// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © aybarsm

//@version=6

// @description Library for general purpose position helpers
library("ToolsPos", overlay = false)
import aybarsm/ToolsFluent/6 as ToolsFluent

//@enum An enumeration of named values representing buy and sell position states.
//@field buy Represents a "Buy" position state.
//@field sell Represents a "Sell" position state.
export enum PosState
	buy = 'buy'
	sell = 'sell'

//@enum An enumeration of named values representing pos actions.
//@field tp Represents a take-profit action
//@field re Represents a re-entry action
export enum PosActionType
	tp = 'tp'
	re = 're'

//@type PosTPInfo - Position Action info object 
//@field price float Action price
//@field when int Action bar time UNIX. Default: time
//@field index int Action bar index. Default: bar_index
//@field markPrice float Action mark price. Default: na
//@field markWhen int Action mark bar time UNIX. Default: na
//@field markIndex int Action mark bar index. Default: na
export type PosAction
    PosActionType actionType
	float price
	int when = time
    int index = bar_index
    float markPrice = na
	int markWhen = na
    int markIndex = na

//@type PosInfo - Position info object 
//@field state <PosState> Position state. Default: na
//@field price float Entry price. Default: na
//@field when int Entry bar time UNIX. Default: time
//@field index int Entry bar index. Default: bar_index
//@field tp PosAction[] Take profit info. Default: na
//@field re PosAction[] Re-entry info. Default: na
//@field markPrice float Mark price. Default: na
//@field markWhen int Mark bar time UNIX. Default: na
//@field markIndex int Mark bar index. Default: na
export type PosInfo
	PosState state = na
	float price = na
	int when = time
    int index = bar_index
	array<PosAction> tp = na
	array<PosAction> re = na
    float markPrice = na
	int markWhen = na
    int markIndex = na

// @function modifies PosInfo object for new position entry
// @param state <PosState> Position state
// @param price float Entry price
// @param when int Entry bar time UNIX. Default: time
// @param index int Entry bar index. Default: bar_index
// @param markPrice float Mark price. Default: na
// @param markWhen int Mark bar time UNIX. Default: na
// @param markIndex int Mark bar index. Default: na
export method enter(PosInfo this, PosState state, float price, int when = time, int index = bar_index, float markPrice = na, int markWhen = na, int markIndex = na) =>
    this.state := state
    this.price := price
    this.when := when
    this.index := index
    this.tp := array.new<PosAction>()
    this.re := array.new<PosAction>()
    this.markPrice := markPrice
    this.markWhen := markWhen
    this.markIndex := markIndex

// @function modifies PosInfo object for action take-profit/re-entry
// @param type <PosActionType> Pos ActionType
// @param price float Action price
// @param when int Action bar time UNIX. Default: time
// @param index int Action bar index. Default: bar_index
// @param markPrice float Mark price. Default: na
// @param markWhen int Mark bar time UNIX. Default: na
// @param markIndex int Mark bar index. Default: na
export method action(PosInfo this, PosActionType actionType, float price, int when = time, int index = bar_index, float markPrice = na, int markWhen = na, int markIndex = na) =>
    PosAction newPosAction = PosAction.new(actionType, price, when, index, markPrice, markWhen, markIndex)
    
    if actionType == PosActionType.tp
        if na(this.tp)
            this.tp := array.new<PosAction>()        
        this.tp.push(newPosAction)
    
    if actionType == PosActionType.re
        if na(this.re)
            this.re := array.new<PosAction>()
        this.re.push(newPosAction)

// @function resets PosInfo object exit
export method reset(PosInfo this) =>
    this.state := na
    this.price := na
    this.when := na
    this.index := na
    this.tp := na
    this.re := na
    this.markPrice := na
    this.markWhen := na
    this.markIndex := na

// @function resets PosInfo object exit
export method exit(PosInfo this) =>
    this.reset()