// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Patarla1

//@version=5
library("TRIG", overlay=true)

// -----------------------------------------
// Constant: PI
// The mathematical constant PI (approximately 3.14159).
// -----------------------------------------
PI_VALUE = 3.141592653589793238  // Corrected constant name

// -----------------------------------------
// Function: degreesToRadians
// Purpose: Convert an angle from degrees to radians.
// Inputs:
//    degrees (float): The angle in degrees.
// Returns: The angle in radians (float).
// -----------------------------------------
export degreesToRadians(float degrees) =>
    degrees * PI_VALUE / 180.0

// -----------------------------------------
// Function: radiansToDegrees
// Purpose: Convert an angle from radians to degrees.
// Inputs:
//    radians (float): The angle in radians.
// Returns: The angle in degrees (float).
// -----------------------------------------
export radiansToDegrees(float radians) =>
    radians * 180.0 / PI_VALUE

// -----------------------------------------
// Function: rt_get_angleAlphaFromLine
// Purpose: Calculate angle α of a right triangle where the line segment 
//          defined by the input coordinates is the hypotenuse.
// Inputs:
//    x1 (int):  x-coordinate (bar index) of the first point.
//    y1 (float): y-coordinate (price) of the first point.
//    x2 (int):  x-coordinate (bar index) of the second point.
//    y2 (float): y-coordinate (price) of the second point.
//    inDegrees (bool): If true, return the angle in degrees. Otherwise, return in radians (default=false).
// Returns: Angle α in degrees or radians (float).
// -----------------------------------------
export rt_get_angleAlphaFromLine(int x1, float y1, int x2, float y2, bool inDegrees = false) =>
    var float deltaX = x2 - x1
	var float deltaY = y2 - y1
	var float angle = 0.0

    if deltaY != 0 and deltaX != 0
        angle := math.atan(deltaY / deltaX)

    if inDegrees
        radiansToDegrees(angle)
    else
        angle

// -----------------------------------------
// Function: rt_get_angleBetaFromLine

// Returns: Angle β in degrees or radians (float).
// -----------------------------------------
export rt_get_angleBetaFromLine(int x1, float y1, int x2, float y2) =>
    90 - rt_get_angleAlphaFromLine(x1, y1, x2, y2, true)