// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © aybarsm

//@version=6
library('ToolsNotification', overlay = true)

export notify(
    string value, 
    string pos = position.top_right, 
    int width = 25,
    int height = 25,
    color textColor = color.white,
    string alignV = text.align_center, 
    string alignH = text.align_center,
    string textSize = size.normal,
    color backgroundColor = color.yellow,
    string tooltip = na,
    string fontFamily = font.family_default
) =>
    var notification = table.new(position = pos, columns = 1, rows = 1)
    table.cell(
        table_id = notification, 
        column = 0, 
        row = 0, 
        text = value, 
        width = width,
        height = height,
        text_color = textColor,
        text_valign = alignV, 
        text_halign = alignH,
        text_size = textSize,
        bgcolor = backgroundColor,
        tooltip = tooltip,
        text_font_family = fontFamily
    )
