// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Fenomentn
// Based on "MarketStructure" by mickes (https://www.tradingview.com/script/tqFlUGel-MarketStructure/), used under Mozilla Public License 2.0.

//@version=6
library("MarketStructure", overlay=true)

// @description Enhanced version of mickes' MarketStructure library with volatility-based pivot filtering, trend strength metric, dynamic label sizing, and customizable visualization styles.


//@type Holds drawings for a structure break.
//@field Line The line object.
//@field Label The label object.
export type StructureBreak
    line Line
    label Label
//@type Holds all the values for a found pivot.
//@field Price The price of the pivot.
//@field BarIndex The bar_index where the pivot occured.
//@field Time The time where the pivot occured.
//@field Type The type of the pivot (-1 = low, 1 = high).
//@field BreakOfStructureBroken Sets to true if a break of structure has happened.
//@field LiquidityBroken Sets to true if a liquidity of the price level has happened.
//@field ChangeOfCharacterBroken Sets to true if a change of character has happened.
export type Pivot
    float Price
    int BarIndex
    int Time
    int Type // -1 = low, 1 = high
    bool BreakOfStructureBroken
    bool LiquidityBroken
    bool ChangeOfCharacterBroken
//@type Enum for the type of market structure.
//@field Intenal represents the internal (orderflow) market structure.
//@field Swing represents the swing market structure.
export enum Type
    Internal = "internal"
    Swing = "swing"
//@type Holds all the values for the market structure.
//@field LeftLength Define the left length of the pivots used.
//@field RightLength Define the right length of the pivots used.
//@field Type Set the type of the market structure. Two types can be used, 'internal' and 'swing' (0 = internal, 1 = swing).
//@field Trend This will be set internally and can be -1 = downtrend, 1 = uptrend.
//@field EqualPivotsFactor Set how the limits are for an equal pivot. This is a factor of the Average True Length (ATR) of length 14. If a low pivot is considered to be equal if it doesn't break the low pivot (is at a lower value) and is inside the previous low pivot + this limit.
//@field ExtendEqualPivotsZones Set to true if you want the equal pivots zones to be extended.
//@field ExtendEqualPivotsStyle Set the style of equal pivot zones.
//@field ExtendEqualPivotsColor Set the color of equal pivot zones.
//@field EqualHighs Holds the boxes for zones that contains equal highs.
//@field EqualLows Holds the boxes for zones that contains equal lows.
//@field BreakOfStructures Holds all the break of structures within the trend (before a change of character).
//@field Pivots All the pivots in the current trend, added with the latest first, this is cleared when the trend changes.
export type Structure
    int LeftLength
    int RightLength
    Type Type
    int Trend // -1 = downtrend, 1 = uptrend
    float EqualPivotsFactor
    bool ExtendEqualPivotsZones
    string ExtendEqualPivotsStyle
    color ExtendEqualPivotsColor
    array<box> EqualHighs
    array<box> EqualLows
    array<StructureBreak> BreakOfStructures
    array<Pivot> Pivots // All the pivots in the current trend, added with the latest first, this is cleared when the trend changes
//@type Holds all the values for liquidity.
//@field LiquidityPivotsHigh All high pivots for liquidity.
//@field LiquidityPivotsLow All low pivots for liquidity.
//@field LiquidityConfirmationBars The number of bars to confirm that a liquidity is valid.
//@field LiquidityPivotsLookback A number of pivots to look back for.
export type Liquidity
    array<Pivot> LiquidityPivotsHigh
    array<Pivot> LiquidityPivotsLow
    int LiquidityConfirmationBars
    int LiquidityPivotsLookback
//@type Holds all the values for the general price action and the market structures.
//@field Liqudity Placeholder for all objects used for liquidity.
//@field Swing Placeholder for all objects used for the swing market structure.
//@field Internal Placeholder for all objects used for the internal market structure.
export type PriceAction
    Liquidity Liquidity

    Structure Swing
    Structure Internal

_atr = ta.atr(14)

Liquidation(Liquidity liquidity, Pivot pivot) =>
    switch pivot.Type
        -1 =>
            if low[liquidity.LiquidityConfirmationBars] <= pivot.Price and close[liquidity.LiquidityConfirmationBars] >= pivot.Price
                if liquidity.LiquidityConfirmationBars > 0
                    confirmed = true
                    for i = liquidity.LiquidityConfirmationBars - 1 to 0
                        if close[i] < pivot.Price
                            confirmed := false
                            break
                    confirmed
                else
                    true
        1 =>
            if high[liquidity.LiquidityConfirmationBars] >= pivot.Price and close[liquidity.LiquidityConfirmationBars] <= pivot.Price
                if liquidity.LiquidityConfirmationBars > 0
                    confirmed = true
                    for i = liquidity.LiquidityConfirmationBars - 1 to 0
                        if close[i] > pivot.Price
                            confirmed := false
                            break
                    confirmed
                else
                    true
method VisualizeLiquidations(array<Pivot> pivots, Liquidity liquidity) =>
    for pivot in pivots
        if bar_index < pivot.BarIndex + liquidity.LiquidityConfirmationBars + 1
            continue // only continue if the pivot was at a bar after prIce can take tHe liquidity
        if not pivot.LiquidityBroken
            if Liquidation(liquidity, pivot)
                limitLine = line.new(pivot.BarIndex, pivot.Price, bar_index - liquidity.LiquidityConfirmationBars, pivot.Price, color = #e65100, style = line.style_dotted)
                breakLine = switch pivot.Type
                    -1 => line.new(pivot.BarIndex, low[liquidity.LiquidityConfirmationBars], bar_index - liquidity.LiquidityConfirmationBars, low[liquidity.LiquidityConfirmationBars], color = na)
                    1 => line.new(pivot.BarIndex, high[liquidity.LiquidityConfirmationBars], bar_index - liquidity.LiquidityConfirmationBars, high[liquidity.LiquidityConfirmationBars], color = na)
                linefill.new(limitLine, breakLine, color.new(color.orange, 80))
                switch pivot.Type
                    -1 => label.new(bar_index - liquidity.LiquidityConfirmationBars - ((bar_index - liquidity.LiquidityConfirmationBars - pivot.BarIndex) / 2), pivot.Price, "$$$", color = color(na), textcolor = color.new(color.orange, 30), size = size.tiny, style = label.style_label_up)
                    1 => label.new(bar_index - liquidity.LiquidityConfirmationBars - ((bar_index - liquidity.LiquidityConfirmationBars - pivot.BarIndex) / 2), pivot.Price, "$$$", color = color(na), textcolor = color.new(color.orange, 30), size = size.tiny)
                pivot.LiquidityBroken := true
            else
                switch pivot.Type
                    -1 =>
                        if close < pivot.Price // invalid liquidation
                            pivot.LiquidityBroken := true
                    1 =>
                        if close > pivot.Price // invalid liquidation
                            pivot.LiquidityBroken := true
// @function Will draw liquidity.
// @param liquidity The 'PriceAction.Liquidity' object.
export Liqudity(Liquidity liquidity) =>
    if barstate.isconfirmed // only if the bar is closed
        liquidity.LiquidityPivotsHigh.VisualizeLiquidations(liquidity)
        liquidity.LiquidityPivotsLow.VisualizeLiquidations(liquidity)
    pivotHigh = ta.pivothigh(1, 1)
    pivotLow = ta.pivotlow(1, 1)
    if not na(pivotHigh)
        if liquidity.LiquidityPivotsHigh.size() >= liquidity.LiquidityPivotsLookback
            liquidity.LiquidityPivotsHigh.pop()
        liquidity.LiquidityPivotsHigh.unshift(Pivot.new(pivotHigh, bar_index - 1, 1))
    if not na(pivotLow)
        if liquidity.LiquidityPivotsLow.size() >= liquidity.LiquidityPivotsLookback
            liquidity.LiquidityPivotsLow.pop()
        liquidity.LiquidityPivotsLow.unshift(Pivot.new(pivotLow, bar_index - 1, -1))
Alert(string message) =>
    alert(message, alert.freq_once_per_bar_close)
method BrokenByBar(Pivot pivot) =>
    broken = false
    for i = 1 to bar_index - 1 - pivot.BarIndex
        switch pivot.Type
            1 =>
                if low[i] > pivot.Price
                    broken := true
                    break
            -1 =>
                if high[i] < pivot.Price
                    broken := true
                    break
    broken
method BrokenByBar(box zone, int type) =>
    broken = false
    for i = 1 to bar_index - 1 - zone.get_left()
        switch type
            1 =>
                if low[i] > zone.get_top()
                    broken := true
                    break
            -1 =>
                if high[i] < zone.get_bottom()
                    broken := true
                    break
    broken
InLimits(float highLimit, float lowLimit, float price) =>
    price >= lowLimit and price <= highLimit
// @function Sets the pivots in the structure.
// @param Structure The market structure value to modify.
export Pivot(Structure structure) =>
    pivotHigh = ta.pivothigh(structure.LeftLength, structure.RightLength)
    pivotLow = ta.pivotlow(structure.LeftLength, structure.RightLength)

    if not na(pivotHigh)
        if structure.Pivots.size() > 5
            structure.Pivots.pop()
        structure.Pivots.unshift(Pivot.new(pivotHigh, bar_index - structure.RightLength, time[structure.RightLength], 1))
    if not na(pivotLow)
        if structure.Pivots.size() > 5
            structure.Pivots.pop()
        structure.Pivots.unshift(Pivot.new(pivotLow, bar_index - structure.RightLength, time[structure.RightLength], -1))
// @function Draws labels for the pivots found.
// @param Structure The market structure value to modify.
export PivotLabels(Structure structure) =>
    txt = ""
    for pivot in structure.Pivots
        if pivot.BarIndex == bar_index - structure.RightLength
            for i = 1 to structure.Pivots.size() - 1
                if structure.Pivots.size() == 1
                    break // previous trend pivots high/low
                previousPivot = structure.Pivots.get(i)
                if previousPivot.Type != pivot.Type or previousPivot.BarIndex == pivot.BarIndex
                    continue
                if pivot.Price == previousPivot.Price
                    txt := "EQ"
                else if pivot.Price > previousPivot.Price
                    txt := "H"
                else if pivot.Price < previousPivot.Price
                    txt := "L"
                break
            transparency = switch structure.Type
                Type.Internal => 60
                Type.Swing => 20
            switch pivot.Type
                -1 => txt += "L", label.new(pivot.BarIndex, pivot.Price, txt, color = color(na), textcolor = color.new(color.teal, transparency), style = label.style_label_up, size = size.tiny)
                1 => txt += "H", label.new(pivot.BarIndex, pivot.Price, txt, color = color(na), textcolor = color.new(color.red, transparency), size = size.tiny)
// @function Draws the boxes for equal highs/lows. Also creates labels for the pivots included.
// @param Structure The market structure value to modify.
export EqualHighOrLow(Structure structure) =>
    retestHigh = high < high[1] and high[1] > high[2]
    retestLow = low > low[1] and low[1] < low[2]
    // go through previously created zones to add to
    if retestHigh
        for equalPivot in structure.EqualHighs
            price = high[1]
            lowLimit = equalPivot.get_bottom() - (_atr * (structure.EqualPivotsFactor / 100.))
            highLimit = equalPivot.get_top()
            if InLimits(highLimit, lowLimit, price)
                if not equalPivot.BrokenByBar(1)
                    if price < equalPivot.get_bottom() //equalPivot.get_top()
                        equalPivot.set_rightbottom(bar_index - 1, price)
                    else
                        equalPivot.set_right(bar_index - 1)
                        equalPivot.set_top(price)
                    label.new(bar_index - 1, price, style = structure.ExtendEqualPivotsStyle, color = color.new(structure.ExtendEqualPivotsColor, 70), size = size.tiny)
                    Alert("Added bar to existing equal high")
    if retestLow
        for equalPivot in structure.EqualLows
            price = low[1]
            lowLimit = equalPivot.get_bottom()
            highLimit = equalPivot.get_top() + (_atr * (structure.EqualPivotsFactor / 100.))
            if InLimits(highLimit, lowLimit, price)
                if not equalPivot.BrokenByBar(-1)
                    if price < equalPivot.get_bottom()
                        equalPivot.set_rightbottom(bar_index - 1, price)
                    else
                        equalPivot.set_right(bar_index - 1)
                        equalPivot.set_top(price)
                    label.new(bar_index - 1, price, style = structure.ExtendEqualPivotsStyle, color = color.new(structure.ExtendEqualPivotsColor, 70), size = size.tiny)
                    Alert("Added bar to existing equal low")
    // create new zones
    for pivot in structure.Pivots
        price = 0., lowLimit = 0., highLimit = 0.
        switch pivot.Type
            -1 =>
                if not retestLow
                    continue
                price := low[1]
                lowLimit := pivot.Price
                highLimit := pivot.Price + (_atr * (structure.EqualPivotsFactor / 100.))
            1 =>
                if not retestHigh
                    continue
                price := high[1]
                lowLimit := pivot.Price - (_atr * (structure.EqualPivotsFactor / 100.))
                highLimit := pivot.Price
        if InLimits(highLimit, lowLimit, price)
            if not pivot.BrokenByBar()
                left = pivot.BarIndex, right = bar_index - 1, top = math.max(price, pivot.Price), bottom = math.min(price, pivot.Price)
                exactSamePivotPrice = pivot.Price == price
                equalPivotsBox = box.new(left, top, right, bottom, bgcolor = color.new(structure.ExtendEqualPivotsColor, 70), text = "Equal low", text_color = structure.ExtendEqualPivotsColor, border_width = exactSamePivotPrice ? 1 : 0, border_color = structure.ExtendEqualPivotsColor, extend = structure.ExtendEqualPivotsZones ? extend.right : extend.none)
                label.new(bar_index - 1, price, style = structure.ExtendEqualPivotsStyle, color = color.new(structure.ExtendEqualPivotsColor, 70), size = size.tiny)
                label.new(pivot.BarIndex, pivot.Price, style = structure.ExtendEqualPivotsStyle, color = color.new(structure.ExtendEqualPivotsColor, 70), size = size.tiny)
                switch pivot.Type
                    -1 =>
                        equalPivotsBox.set_text("Equal low")
                        structure.EqualLows.unshift(equalPivotsBox)
                        Alert("Equal low appeared")
                    1 =>
                        equalPivotsBox.set_text("Equal high")
                        structure.EqualHighs.unshift(equalPivotsBox)
                        Alert("Equal high appeared")
// @function Will create lines when a break of strycture occures.
// @param Structure The market structure value to modify.
// @returns A boolean that represents if a break of structure was found or not.
export BreakOfStructure(Structure structure) =>
    var alerMessageFormat = "BOS to {0} on {1} MS, timeframe {2}"
    breakOfStructureOccured = false
    lineStyle = switch structure.Type
        Type.Swing => line.style_solid
        Type.Internal => line.style_dotted
    for pivot in structure.Pivots
        if structure.Trend == 1 and pivot.Type == 1 and close > pivot.Price and not pivot.BreakOfStructureBroken
            create = true
            for breakOfStructure in structure.BreakOfStructures
                barIndex = breakOfStructure.Line.get_x1()
                if barIndex > pivot.BarIndex
                    price = breakOfStructure.Line.get_y1()
                    if price < pivot.Price
                        breakOfStructure.Line.delete() // remove previous BOS lines
                        breakOfStructure.Label.delete()
                    else // dont create the bos if there was an earlier one with a lower price
                        create := false
                        break
            if create
                structure.BreakOfStructures.unshift(StructureBreak.new(
                  line.new(pivot.BarIndex, pivot.Price, bar_index, pivot.Price, color = #388e3c, style = lineStyle),
                  label.new(bar_index - ((bar_index - pivot.BarIndex) / 2), pivot.Price, "", color = color(na), textcolor = #388e3c, size = size.tiny)))
                pivot.BreakOfStructureBroken := true
                switch structure.Type
                    Type.Internal => Alert(str.format(alerMessageFormat, "Bull", "internal", timeframe.period))
                    Type.Swing => Alert(str.format(alerMessageFormat, "Bull", "swing", timeframe.period))
                breakOfStructureOccured := true
                break
        else if structure.Trend == -1 and pivot.Type == -1 and close < pivot.Price and not pivot.BreakOfStructureBroken
            create = true
            for breakOfStructure in structure.BreakOfStructures
                barIndex = breakOfStructure.Line.get_x1()
                if barIndex > pivot.BarIndex
                    price = breakOfStructure.Line.get_y1()
                    if price > pivot.Price
                        breakOfStructure.Line.delete() // remove previous BOS lines
                        breakOfStructure.Label.delete()
                    else // dont create the bos if there was an earlier one with a lower price
                        create := false
                        break
            if create
                structure.BreakOfStructures.unshift(StructureBreak.new(
                  line.new(pivot.BarIndex, pivot.Price, bar_index, pivot.Price, color = #b22833, style = lineStyle),
                  label.new(bar_index - ((bar_index - pivot.BarIndex) / 2), pivot.Price, "", color = color(na), textcolor = #b22833, style = label.style_label_up, size = size.tiny)))
                pivot.BreakOfStructureBroken := true
                switch structure.Type
                    Type.Internal => Alert(str.format(alerMessageFormat, "Bear", "internal", timeframe.period))
                    Type.Swing => Alert(str.format(alerMessageFormat, "Bear", "swing", timeframe.period))
                breakOfStructureOccured := true
                break
    breakOfStructureOccured
// @function Will create lines when a change of character occures. This line will have a label with "MSF" or "MSF+".
// @param Structure The market structure value to modify.
// @returns A boolean that represents if a change of character was found or not.
export ChangeOfCharacter(Structure structure) =>
    var alerMessageFormat = "{0} to {1} on {2} MS, timeframe {3}"
    changeOfCharacterOccured = false
    lineStyle = switch structure.Type
        Type.Internal => line.style_dashed
        Type.Swing => line.style_solid
    for pivot in structure.Pivots
        if structure.Trend <= 0 and pivot.Type == 1 and close > pivot.Price and close[1] < pivot.Price and not(pivot.ChangeOfCharacterBroken)
            pivot.ChangeOfCharacterBroken := true
            txt = "MSF"
            if structure.Pivots.size() >= 2 and structure.Trend != 0 // need at leased 2 pivots
                for i = 0 to structure.Pivots.size() - 2
                    latestPivot = structure.Pivots.get(i)
                    if latestPivot.Type == -1
                        for j = i + 1 to structure.Pivots.size() - 2
                            nextLatestPivot = structure.Pivots.get(j)
                            if nextLatestPivot.Type == -1
                                if latestPivot.Price > nextLatestPivot.Price
                                    txt := "MSF+"
                                break
                        break
            line.new(pivot.BarIndex, pivot.Price, bar_index, pivot.Price, color = #1848cc, style = lineStyle)
            label.new(bar_index - ((bar_index - pivot.BarIndex) / 2), pivot.Price, txt, color = color(na), textcolor = #1848cc, size = size.tiny)
            
            structure.Trend := 1
            structure.EqualHighs.clear(), structure.EqualLows.clear()
            structure.BreakOfStructures.clear()
            // Keep all the pivots 'within' the pivot and the break for MSFs, disable all for BOSs
            remove = array.new<int>()
            for [i, p] in structure.Pivots
                if p.BarIndex <= pivot.BarIndex
                    remove.push(i)
                else
                    p.BreakOfStructureBroken := true
            for [i, r] in remove
                structure.Pivots.remove(r - i)
            for p in structure.Pivots
                if p.BarIndex != pivot.BarIndex // set all pivots to breakable
                    p.ChangeOfCharacterBroken := false
            switch structure.Type
                Type.Internal => Alert(str.format(alerMessageFormat, txt, "Bull", "internal", timeframe.period))
                Type.Swing => Alert(str.format(alerMessageFormat, txt, "Bull", "swing", timeframe.period))
            changeOfCharacterOccured := true
            break
        else if structure.Trend >= 0 and pivot.Type == -1 and close < pivot.Price and close[1] > pivot.Price and not(pivot.ChangeOfCharacterBroken)
            pivot.ChangeOfCharacterBroken := true
            txt = "MSF"
            if structure.Pivots.size() >= 2 and structure.Trend != 0 // need at leased 2 pivots
                for i = 0 to structure.Pivots.size() - 2
                    latestPivot = structure.Pivots.get(i)
                    if latestPivot.Type == 1
                        for j = i + 1 to structure.Pivots.size() - 2
                            nextLatestPivot = structure.Pivots.get(j)
                            if nextLatestPivot.Type == 1
                                if latestPivot.Price < nextLatestPivot.Price
                                    txt := "MSF+"
                                break
                        break
            line.new(pivot.BarIndex, pivot.Price, bar_index, pivot.Price, color = #e65100, style = lineStyle)
            label.new(bar_index - ((bar_index - pivot.BarIndex) / 2), pivot.Price, txt, color = color(na), textcolor = color.new(#e65100, 30), style = label.style_label_up, size = size.tiny)
            
            structure.Trend := -1
            structure.EqualHighs.clear(), structure.EqualLows.clear()
            structure.BreakOfStructures.clear()
            // Keep all the pivots 'within' the pivot and the break for MSFs, disable all for BOSs
            remove = array.new<int>()
            for [i, p] in structure.Pivots
                if p.BarIndex <= pivot.BarIndex
                    remove.push(i)
                else
                    p.BreakOfStructureBroken := true
            for [i, r] in remove
                structure.Pivots.remove(r - i)
            for p in structure.Pivots
                if p.BarIndex != pivot.BarIndex // set all pivots to breakable
                    p.ChangeOfCharacterBroken := false
            switch structure.Type
                Type.Internal => Alert(str.format(alerMessageFormat, txt, "Bear", "internal", timeframe.period))
                Type.Swing => Alert(str.format(alerMessageFormat, txt, "Bear", "swing", timeframe.period))
            changeOfCharacterOccured := true
            break
    changeOfCharacterOccured
// @function Will create a box with a background for between the latest high and low pivots. This can be used as the current trading range (if the pivots broke strucure somehow).
export VisualizeCurrent(Structure structure) =>
    var tradingRange = box.new(bar_index, high, bar_index, high, extend = extend.right, border_width = 0, bgcolor = color.new(color.gray, 93))
    Pivot latestHighPivot = na, Pivot latestLowPivot = na
    for pivot in structure.Pivots
        switch pivot.Type
            -1 =>
                if na(latestLowPivot)
                    latestLowPivot := pivot
            1 =>
                if na(latestHighPivot)
                    latestHighPivot := pivot
    if not na(latestHighPivot) and structure.RightLength == bar_index - latestHighPivot.BarIndex
        tradingRange.set_lefttop(bar_index - (bar_index - latestHighPivot.BarIndex), high[bar_index - latestHighPivot.BarIndex])
    if not na(latestLowPivot) and structure.RightLength == bar_index - latestLowPivot.BarIndex
        tradingRange.set_rightbottom(bar_index - (bar_index - latestLowPivot.BarIndex), low[bar_index - latestLowPivot.BarIndex])