// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © truenomic

//@version=6
indicator("Spot vs. Derivatives Basis", format=format.percent, precision=3, overlay=false)

// User Input: Price Source
source = input.source(close, "Price Source")

// Smoothing Options
smoothing_type = input.string("None", "Smoothing Type", options=["None", "SMA", "EMA", "WMA", "VWMA"])
smoothing_length = input.int(14, "Smoothing Length", minval=1)

usehighlight = input(false, title = "Highlight major extremes?")

// User Inputs for Each Exchange and Pair

// Binance
use_binance_usd_spot   = input.bool(true, "Binance BTC/USD Spot", group = "Spot")
use_binance_usdt_spot  = input.bool(true, "Binance BTC/USDT Spot", group = "Spot")
use_binance_usdc_spot  = input.bool(true, "Binance BTC/USDC Spot", group = "Spot")
use_binance_usd_swap   = input.bool(true, "Binance BTC/USD Perp", group = "Derivatives")
use_binance_usdt_swap  = input.bool(true, "Binance BTC/USDT Perp", group = "Derivatives")
use_binance_usdc_swap  = input.bool(true, "Binance BTC/USDC Perp", group = "Derivatives")

// Coinbase
use_coinbase_usd_spot  = input.bool(true, "Coinbase BTC/USD Spot", group = "Spot")
use_coinbase_usdt_spot = input.bool(true, "Coinbase BTC/USDT Spot", group = "Spot")
use_coinbase_usdc_spot = input.bool(true, "Coinbase BTC/USDC Spot", group = "Spot")
use_coinbase_usdc_swap = input.bool(true, "Coinbase BTC/USDC Perp", group = "Derivatives")

// Kraken
use_kraken_usd_spot    = input.bool(true, "Kraken BTC/USD Spot", group = "Spot")
use_kraken_usdt_spot   = input.bool(true, "Kraken BTC/USDT Spot", group = "Spot")
use_kraken_usdc_spot   = input.bool(true, "Kraken BTC/USDC Spot", group = "Spot")
use_kraken_usd_swap    = input.bool(true, "Kraken BTC/USD Perp", group = "Derivatives")

// Bybit
use_bybit_usdt_spot    = input.bool(true, "Bybit BTC/USDT Spot", group = "Spot")
use_bybit_usdc_spot    = input.bool(true, "Bybit BTC/USDC Spot", group = "Spot")
use_bybit_usd_swap     = input.bool(true, "Bybit BTC/USD Perp", group = "Derivatives")
use_bybit_usdt_swap    = input.bool(true, "Bybit BTC/USDT Perp", group = "Derivatives")
use_bybit_usdc_swap    = input.bool(true, "Bybit BTC/USDC Perp", group = "Derivatives")

// OKX
use_okx_usdt_spot      = input.bool(true, "OKX BTC/USDT Spot", group = "Spot")
use_okx_usdc_spot      = input.bool(true, "OKX BTC/USDC Spot", group = "Spot")
use_okx_usd_swap       = input.bool(true, "OKX BTC/USD Perp", group = "Derivatives")
use_okx_usdt_swap      = input.bool(true, "OKX BTC/USDT Perp", group = "Derivatives")
use_okx_usdc_swap      = input.bool(true, "OKX BTC/USDC Perp", group = "Derivatives")

// BitMEX
use_bitmex_usdt_spot   = input.bool(true, "BitMEX BTC/USDT Spot", group = "Spot")
use_bitmex_usd_swap    = input.bool(true, "BitMEX BTC/USD Perp", group = "Derivatives")
use_bitmex_usdt_swap   = input.bool(true, "BitMEX BTC/USDT Perp", group = "Derivatives")

// Bitfinex
use_bitfinex_usdt_spot = input.bool(true, "Bitfinex BTC/USDT Spot", group = "Spot")
use_bitfinex_usd_spot  = input.bool(true, "Bitfinex BTC/USD Spot", group = "Spot")

// Stablecoin Prices
usdtusd  = request.security("Coinbase:USDTUSD", timeframe.period, source)
usdtusdc = request.security("Coinbase:USDTUSDC", timeframe.period, source)

// Spot Prices
binance_usd_spot   = use_binance_usd_spot  ? request.security("Binance:BTCUSD", timeframe.period, source) : na
binance_usdt_spot  = use_binance_usdt_spot ? request.security("Binance:BTCUSDT", timeframe.period, source) * usdtusd : na
binance_usdc_spot  = use_binance_usdc_spot ? request.security("Binance:BTCUSDC", timeframe.period, source) * (usdtusd * usdtusdc) : na

coinbase_usd_spot  = use_coinbase_usd_spot ? request.security("Coinbase:BTCUSD", timeframe.period, source) : na
coinbase_usdt_spot = use_coinbase_usdt_spot ? request.security("Coinbase:BTCUSDT", timeframe.period, source) * usdtusd : na
coinbase_usdc_spot = use_coinbase_usdc_spot ? request.security("Coinbase:BTCUSDC", timeframe.period, source) * (usdtusd * usdtusdc) : na

kraken_usd_spot    = use_kraken_usd_spot  ? request.security("Kraken:BTCUSD", timeframe.period, source) : na
kraken_usdt_spot   = use_kraken_usdt_spot ? request.security("Kraken:BTCUSDT", timeframe.period, source) * usdtusd : na
kraken_usdc_spot   = use_kraken_usdc_spot ? request.security("Kraken:BTCUSDC", timeframe.period, source) * (usdtusd * usdtusdc) : na

bybit_usdt_spot    = use_bybit_usdt_spot  ? request.security("Bybit:BTCUSDT", timeframe.period, source) * usdtusd : na
bybit_usdc_spot    = use_bybit_usdc_spot  ? request.security("Bybit:BTCUSDC", timeframe.period, source) * (usdtusd * usdtusdc) : na

okx_usdt_spot      = use_okx_usdt_spot  ? request.security("Okx:BTCUSDT", timeframe.period, source) * usdtusd : na
okx_usdc_spot      = use_okx_usdc_spot  ? request.security("Okx:BTCUSDC", timeframe.period, source) * (usdtusd * usdtusdc) : na

bitmex_usdt_spot   = use_bitmex_usdt_spot ? request.security("Bitmex:BTCUSDT", timeframe.period, source) * usdtusd : na

bitfinex_usdt_spot = use_bitfinex_usdt_spot ? request.security("Bitfinex:BTCUST", timeframe.period, source) * usdtusd : na
bitfinex_usd_spot  = use_bitfinex_usd_spot ? request.security("Bitfinex:BTCUSD", timeframe.period, source) : na

// Derivatives Prices
binance_usd_swap   = use_binance_usd_swap  ? request.security("Binance:BTCUSD.P", timeframe.period, source) : na
binance_usdt_swap  = use_binance_usdt_swap ? request.security("Binance:BTCUSDT.P", timeframe.period, source) * usdtusd : na
binance_usdc_swap  = use_binance_usdc_swap ? request.security("Binance:BTCUSDC.P", timeframe.period, source) * (usdtusd * usdtusdc) : na

coinbase_usdc_swap = use_coinbase_usdc_swap ? request.security("Coinbase:BTCUSDC.P", timeframe.period, source) * (usdtusd * usdtusdc) : na

bybit_usd_swap     = use_bybit_usd_swap  ? request.security("Bybit:BTCUSD.P", timeframe.period, source) : na
bybit_usdt_swap    = use_bybit_usdt_swap ? request.security("Bybit:BTCUSDT.P", timeframe.period, source) * usdtusd : na
bybit_usdc_swap    = use_bybit_usdc_swap ? request.security("Bybit:BTCUSDC.P", timeframe.period, source) * (usdtusd * usdtusdc) : na

okx_usd_swap       = use_okx_usd_swap  ? request.security("Okx:BTCUSD.P", timeframe.period, source) : na
okx_usdt_swap      = use_okx_usdt_swap ? request.security("Okx:BTCUSDT.P", timeframe.period, source) * usdtusd : na
okx_usdc_swap      = use_okx_usdc_swap ? request.security("Okx:BTCUSDC.P", timeframe.period, source) * (usdtusd * usdtusdc) : na

kraken_usd_swap    = use_kraken_usd_swap ? request.security("Kraken:BTCUSD.P", timeframe.period, source) : na

bitmex_usd_swap    = use_bitmex_usd_swap ? request.security("Bitmex:BTCUSD.P", timeframe.period, source) : na
bitmex_usdt_swap   = use_bitmex_usdt_swap ? request.security("Bitmex:BTCUSDT.P", timeframe.period, source) * usdtusd : na

// Compute Average
spot_exchanges = array.from(binance_usd_spot, binance_usdt_spot, binance_usdc_spot, coinbase_usd_spot, coinbase_usdt_spot, coinbase_usdc_spot, kraken_usd_spot, kraken_usdt_spot, kraken_usdc_spot, bybit_usdt_spot, bybit_usdc_spot, okx_usdt_spot, okx_usdc_spot, bitmex_usdt_spot, bitfinex_usdt_spot, bitfinex_usd_spot)
deriv_exchanges = array.from(binance_usd_swap, binance_usdt_swap, binance_usdc_swap, coinbase_usdc_swap, bybit_usd_swap, bybit_usdt_swap, bybit_usdc_swap, okx_usd_swap, okx_usdt_swap, okx_usdc_swap, kraken_usd_swap, bitmex_usd_swap, bitmex_usdt_swap)

avg_spot = array.avg(spot_exchanges)
avg_derivs = array.avg(deriv_exchanges)

// Basis Calculation
basis = avg_spot > 0 and not na(avg_spot) and not na(avg_derivs) ? ((avg_derivs / avg_spot) - 1) * 100 : na

// Apply Smoothing
basis_smoothed = 
     smoothing_type == "SMA"  ? ta.sma(basis, smoothing_length)  :
     smoothing_type == "EMA"  ? ta.ema(basis, smoothing_length)  :
     smoothing_type == "WMA"  ? ta.wma(basis, smoothing_length)  :
     smoothing_type == "VWMA" ? ta.vwma(basis, smoothing_length) :
     basis

plot(basis_smoothed, style=plot.style_columns, linewidth=1, color= basis_smoothed > 0 ? color.new(#f23645, 0) : color.new(#4caf50, 0), title="Basis")

hline(0.1, linestyle = hline.style_dotted, linewidth = 1, color = color.new(#2e2e2e, 20), title = "Baseline")
hline(-0.1, linestyle = hline.style_dotted, linewidth = 1, color = color.new(#2e2e2e, 20), title = "Baseline")

bgcolor(usehighlight ? (basis_smoothed < -0.1 ? color.new(#4caf50, 90) : basis_smoothed > 0.1 ? color.new(#f23645, 90) : na) : na )