// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © RozaniGhani-RG

//@version=5

// @description Timeframe comparison for higher and lower timeframe
library('TimeframeComparison', true)

// @function timeframe multiplier in minutes
// @returns float value
export minMult() =>
	timeframe.multiplier * (
	 timeframe.isseconds ? 1. / 60. :
	 timeframe.isminutes ? 1.       :
	 timeframe.isdaily   ? 1440.    :
	 timeframe.isweekly  ? 10080.   :
	 timeframe.ismonthly ? 43800.   : na)

// @function request security for timeframe multiplier in minutes
// @param    TF   string value
// @param   exp   float value
// @returns request.security()
method minRequest(string TF = na, float exp = na) =>
    ref = TF == '' ? str.tostring(timeframe.multiplier) : TF
    val = request.security(syminfo.tickerid, ref, exp)
    val

//#region ———————————————————— Example Code
// Inputs
selectedTF  = input.timeframe  ('', 'Select Timeframe')
posY        = input.string(  'top', 'Position Table', inline = '0', options = ['top',  'middle', 'bottom'])
posX        = input.string('right',               '', inline = '0', options = ['left', 'center', 'right'])

// Variables
currentMin  = minMult()
selectedMin = selectedTF.minRequest(minMult())

warningTF  = selectedTF ==          '' ? '' :
             currentMin >  selectedMin ? '⚠️ CURRENT > SELECT\n1) REDUCE CURRENT TF\nOR\n2) INCREASE SELECT TF':
             selectedTF
displayTF  = selectedTF == '' ? 'SAME' : selectedTF
warnIcon   = currentMin >  selectedMin ? '⚠️ ' : ''
var tbl    = table.new(posY + '_' + posX, 2, 3, chart.bg_color, chart.fg_color, 1, chart.fg_color, 1)

// Constructs
if barstate.islast

    tbl.cell(0, 0, 'CURRENT',            text_color = chart.fg_color)
    tbl.cell(1, 0, timeframe.period,     text_color = chart.fg_color)
    tbl.cell(0, 1, 'SELECT',             text_color = chart.fg_color)
    tbl.cell(1, 1, warnIcon + displayTF, text_color = chart.fg_color)

    if currentMin > selectedMin
        tbl.cell(1, 2, warningTF,        text_color = color.red, text_halign = text.align_left)
//#endregion