// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © QuantChook

//@version=6
indicator("2 Asset Optimal Portfolio")

//Inputs
asset1=input.symbol("BTCUSD","Asset 1",group="Assets")
asset2=input.symbol("BTCUSD","Asset 2",group="Assets")

lookBack=input.int(365,"Look Back Length",group="Asset Settings")
src=input(close,"Source",group="Asset Settings")
ratio=input.string("Sharpe","Ratio",options=["Sharpe", "Sortino"],group="Asset Settings")
asset1percent=input.float(1,"% of Asset 1",minval=0,maxval=1,group="Asset Settings",step=0.01)

close1 = request.security(asset1, timeframe.period, src)
close2 = request.security(asset2, timeframe.period, src)

//Asset Stats
DailyRateOfChange1 =close1/close1[1]-1
DailyRateOfChange2 =close2/close2[1]-1

returns1=array.new_float(0)
returns2=array.new_float(0)
returnsp=array.new_float(0)

positiveReturns1=array.new_float(0)
negativeReturns1=array.new_float(0)
positiveReturns2=array.new_float(0)
negativeReturns2=array.new_float(0)

//Inserting return values into returns arrays.
for i = 0 to lookBack
    array.push(returns1,DailyRateOfChange1[i])
    array.push(returns2,DailyRateOfChange2[i])

    if DailyRateOfChange1[i]<=0
        array.push(negativeReturns1,DailyRateOfChange1[i])
    else 
        array.push(positiveReturns1,DailyRateOfChange1[i])

    if DailyRateOfChange2[i]<=0
        array.push(negativeReturns2,DailyRateOfChange2[i])
    else 
        array.push(positiveReturns2,DailyRateOfChange2[i])

//Standard Deviations, Expected Returns and Downside Standard Deviation Calculations
ExpectedReturns1=array.avg(returns1)
ExpectedReturns2=array.avg(returns2)

StandardDeviation1 = array.stdev(returns1)
StandardDeviation2 = array.stdev(returns2)

DownSideStandardDeviation1= array.stdev(negativeReturns1)
UpSideStandardDeviation1= array.stdev(positiveReturns1)
DownSideStandardDeviation2= array.stdev(negativeReturns2)
UpSideStandardDeviation2= array.stdev(positiveReturns2)
corr12=ta.correlation(DailyRateOfChange1,DailyRateOfChange2,lookBack)

//Portfolio Stats 

pExpectedReturn=(ExpectedReturns1 * asset1percent)+(ExpectedReturns2*(1-asset1percent))
pStandardDeviation=math.sqrt(math.pow(asset1percent*StandardDeviation1,2)+math.pow((1-asset1percent)*StandardDeviation2,2)+(2*asset1percent*(1-asset1percent)*StandardDeviation1*StandardDeviation2*corr12))
pDownsideDeviation=math.sqrt(math.pow(asset1percent*DownSideStandardDeviation1,2)+math.pow((1-asset1percent)*DownSideStandardDeviation2,2)+(2*asset1percent*(1-asset1percent)*DownSideStandardDeviation1*DownSideStandardDeviation2*corr12))

//Calculations
Sharpe= math.round(pExpectedReturn / pStandardDeviation * math.sqrt(lookBack), 2)
Sortino=math.round(pExpectedReturn / pDownsideDeviation * math.sqrt(lookBack), 2)
//Omega=array.sum(positiveReturns)/array.sum(negativeReturns)*(-1)
plottype=ratio=="Sharpe"?Sharpe:Sortino
plot(plottype,color=color.red)