// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © aybarsm

//@version=6

// @description Library for generic tools for price related actions
library('ToolsPrice', overlay = false)

//@enum An enumeration of named values representing price source.
//@field open Represents the "Open" price.
//@field high Represents the "High" price.
//@field low Represents the "Low" price.
//@field close Represents the "Close" price.
//@field hl2 Represents the "(High + Low)/2" price.
//@field hlc3 Represents the "(High + Low + Close)/3" price.
//@field ohlc4 Represents the "(Open + High + Low + Close)/4" price.
//@field hlcc4 Represents the "(High + Low + Close + Close)/4" price.
export enum PriceSource
    open = 'Open'
    high = 'High'
    low = 'Low'
    close = 'Close'
    hl2 = '(H + L)/2'
    hlc3 = '(H + L + C)/3'
    ohlc4 = '(O + H + L + C)/4'
    hlcc4 = '(H + L + C + C)/4'

// @function Returns series float according to provided PriceSource enum
// @param src PriceSource enum
// @returns Series float
export getPriceBySource(PriceSource src) =>
    switch src
        PriceSource.open => open
        PriceSource.high => high
        PriceSource.low => low
        PriceSource.close => close
        PriceSource.hl2 => hl2
        PriceSource.hlc3 => hlc3
        PriceSource.ohlc4 => ohlc4
        PriceSource.hlcc4 => hlcc4