// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © alejandroveronn

//@version=6
indicator("SPX Levels Adjusted to ES1!", overlay=true)

// Only run on ES1!
is_ES1 = syminfo.ticker == "ES1!"

// Set levels to watch.
spx_level_1 = input.float(5000, "SPX Level 1")
spx_level_2 = input.float(4950, "SPX Level 2")
spx_level_3 = input.float(4900, "SPX Level 3")

// Request Actual prices
spx_price = is_ES1 ? request.security("SPX", "1", close) : na
es_price = close

// Spread between SPX and ES1!
spread = is_ES1 ? spx_price - es_price : na

// Levels
adjusted_1 = is_ES1 ? spx_level_1 - spread : na
adjusted_2 = is_ES1 ? spx_level_2 - spread : na
adjusted_3 = is_ES1 ? spx_level_3 - spread : na

// Mostrar el spread en el encabezado del gráfico
plot(spread, title="SPX - ES1! Spread", color=color.orange, linewidth=1, display=display.status_line)

// Draw horizontal lines
var line line1 = na
var line line2 = na
var line line3 = na

var label label1 = na
var label label2 = na
var label label3 = na

if bar_index > 1 and is_ES1
    if (na(line1))
        line1 := line.new(x1=bar_index, y1=adjusted_1, x2=bar_index + 1, y2=adjusted_1, color=color.green, extend=extend.right, width=1)
        label1 := label.new(x=bar_index + 5, y=adjusted_1, text="SPX Level " + str.tostring(spx_level_1), style=label.style_label_left, size=size.small, textcolor=color.white, color=color.green)
    else
        line.set_y1(line1, adjusted_1)
        line.set_y2(line1, adjusted_1)
        label.set_y(label1, adjusted_1)
        label.set_text(label1, "SPX Level " + str.tostring(spx_level_1))
        label.set_x(label1, bar_index + 5)

    if (na(line2))
        line2 := line.new(x1=bar_index, y1=adjusted_2, x2=bar_index + 1, y2=adjusted_2, color=color.blue, extend=extend.right, width=1)
        label2 := label.new(x=bar_index + 5, y=adjusted_2, text="SPX Level " + str.tostring(spx_level_2), style=label.style_label_left, size=size.small, textcolor=color.white, color=color.blue)
    else
        line.set_y1(line2, adjusted_2)
        line.set_y2(line2, adjusted_2)
        label.set_y(label2, adjusted_2)
        label.set_text(label2, "SPX Level " + str.tostring(spx_level_2))
        label.set_x(label2, bar_index + 5)

    if (na(line3))
        line3 := line.new(x1=bar_index, y1=adjusted_3, x2=bar_index + 1, y2=adjusted_3, color=color.red, extend=extend.right, width=1)
        label3 := label.new(x=bar_index + 5, y=adjusted_3, text="SPX Level " + str.tostring(spx_level_3), style=label.style_label_left, size=size.small, textcolor=color.white, color=color.red)
    else
        line.set_y1(line3, adjusted_3)
        line.set_y2(line3, adjusted_3)
        label.set_y(label3, adjusted_3)
        label.set_text(label3, "SPX Level " + str.tostring(spx_level_3))
        label.set_x(label3, bar_index + 5)

    // Informative Label
    if bar_index % 50 == 0  // Do not saturate
        label.new(bar_index, high, text="Spread: " + str.tostring(spread, format.mintick), style=label.style_label_left, size=size.small, color=color.gray, textcolor=color.white)
