// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © MarioLuis_GarciaC

//@version=5

// @description TODO: add library description here
library(title = "CandlestickepatternsClase3", overlay = true)

//@ return true if bullish candle engulfing detected
export bullish_engulfing() =>
	b_e = close[1] < open[1] and close >= high[1]


//@ return true if bearish candle engulfing detected
export bearish_engulfing() =>
	bearish_e = close[1] > open[1] and close <= low[1]

