//@version=6
// © GeorgeIsaac

indicator(title="MAs", shorttitle="ZFT Classic", overlay=true)

// Input lengths
Length1 = input.int(20, minval=1, title="SMA 20 Length")
Length2 = input.int(50, minval=1, title="SMA 50 Length")
Length3 = input.int(100, minval=1, title="SMA 100 Length")

// Source price
xPrice = close

// Moving Averages
xMA20  = ta.sma(xPrice, Length1)
xMA50  = ta.sma(xPrice, Length2)
xMA100 = ta.sma(xPrice, Length3)

// Plotting the MAs
plot(xMA20,  color=color.new(#FF5252, 0), linewidth=1, title="SMA 20")
plot(xMA50,  color=color.new(#FF9800, 0), linewidth=1, title="SMA 50")
plot(xMA100, color=color.new(#2196F3, 0), linewidth=1, title="SMA 100")
