// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © RicardoSantos

//@version=6

// @description Properties and data for the celestial objects in the Solar System.
library(title='MathConstantsSolarSystem')

// Reference:
// - http://semi.gurroa.cz/Astro/Orbital_Resonance_and_Solar_Cycles.pdf
// - https://nssdc.gsfc.nasa.gov/planetary/factsheet/
// - https://astrolibrary.org/zodiac-text-characters/
// - https://en.wikipedia.org/wiki/List_of_exceptional_asteroids#Landmark_asteroids
// - https://www.telescopenerd.com/celestial-objects/kuiper-belt.htm
// - https://phys.libretexts.org/Bookshelves/Astronomy__Cosmology/Big_Ideas_in_Cosmology_(Coble_et_al.)/01%3A_Size_and_Scope/1.02%3A_Our_Solar_System

//#region Lists of names.

// @enum List of celestial objects in the solar system.
export enum OBJ
	B00 = 'Sun'
	B01 = 'Mercury'
	B02 = 'Venus'
	B03 = 'Earth'
	B04 = 'Moon'
	B05 = 'EMB' // Earth Moon Barycenter
	B06 = 'Mars'
	B07 = 'Asteroids(Ceres)'
	B08 = 'Asteroids(Sum)'
	B09 = 'Jupiter'
	B10 = 'Saturn'
	B11 = 'Uranus'
	B12 = 'Neptune'
	B13 = 'Pluto'
	B14 = 'Kuiper Belt'

// @enum List of planets in the solar system.
export enum PLANETS
	B01 = 'Mercury'
	B02 = 'Venus'
	B03 = 'Earth'
	B06 = 'Mars'
	B09 = 'Jupiter'
	B10 = 'Saturn'
	B11 = 'Uranus'
	B12 = 'Neptune'

// @enum List of exceptional asteroids in the Asteroid belt.
export enum ASTEROIDS
	A01 = 'Ceres'
	A02 = 'Pallas'
	A03 = 'Juno'
	A04 = 'Vesta'
	A05 = 'Hebe'
	A06 = 'Iris'
	A07 = 'Hygiea'
	A08 = 'Eunomia'
	A09 = 'Psyche'
	A10 = 'Amphitrite'
	A11 = 'Euphrosyne'
	A12 = 'Europa'
	A13 = 'Cybelle'
	A14 = 'Sylvia'
	A15 = 'Thisbe'
	A16 = 'Camilla'
	A17 = 'Bamberga'
	A18 = 'Davida'
	A19 = 'Herculina'
	A20 = 'Interamnia'

//#endregion
//#region	Emoji and text character related to the solar system, planets and celestial bodies.

export const string EMO_GALAXY = '🌌'
export const string EMO_RINGPLANET = '🪐'
export const string EMO_MOON_CRESCENT = '🌙'
export const string EMO_MOON_FULL = '🌕'
export const string EMO_MOON_NEW = '🌑'
export const string EMO_MOON_WAXING_CRESCENT = '🌒'
export const string EMO_MOON_FIRST_QUARTER = '🌓'
export const string EMO_MOON_LAST_QUARTER = '🌗'
export const string EMO_MOON_WANING_CRESCENT = '🌘'
export const string EMO_MOON_WAXING_GIBBOUS = '🌔'
export const string EMO_MOON_WANING_GIBBOUS = '🌖'

export const string CR_SUN = '⨀'
export const string CR_MERCURY = '☿'
export const string CR_VENUS = '♀'
export const string CR_EARTH = '⨁'
export const string CR_MARS = '♂'
export const string CR_JUPITER = '♃'
export const string CR_SATURN = '♄'
export const string CR_URANUS = '♅'
export const string CR_URANUS_ALT = '⛢'
export const string CR_NEPTUNE = '♆'
export const string CR_PLUTO_ALT = '♇'
export const string CR_CHIRON = '⚷'
export const string CR_CERES = '⚳'
export const string CR_JUNO = '⚵'
export const string CR_PALLAS = '⚴'
export const string CR_VESTA = '⚶'

export const string CR_ZODIAC_ARIES = '♈'
export const string CR_ZODIAC_TAURUS = '♉'
export const string CR_ZODIAC_GEMINI = '♊'
export const string CR_ZODIAC_CANCER = '♋'
export const string CR_ZODIAC_LEO = '♌'
export const string CR_ZODIAC_VIRGO = '♍'
export const string CR_ZODIAC_LIBRA = '♎'
export const string CR_ZODIAC_SCORPIO = '♏'
export const string CR_ZODIAC_SAGITTARIUS = '♐'
export const string CR_ZODIAC_CAPRICORN = '♑'
export const string CR_ZODIAC_AQUARIUS = '♒'
export const string CR_ZODIAC_PISCES = '♓'

//#endregion
//#region Properties of Celestial objects in the solar system.

//@variable Celestial object body mass, `kg`.
export const float SUN_MASS = 1.98843966345011E+30
//@variable Celestial object diameter, `km`.
export const float SUN_DIAMETER = 1392000.0
// @variable Celestial object mean radius, `m`.
export const float SUN_RADIUS = 6.96 * 10.0e8
//@variable Celestial object spin.
export const float SUN_SPIN_D = 25.38
//@variable Celestial object spin.
export const float SUN_SPIN_H = 609.12

//@variable Celestial object body mass, `kg`.
export const float MERCURY_MASS = 3.30108185047166E+23
//@variable Celestial object diameter, `km`.
export const float MERCURY_DIAMETER = 4879.0
// @variable Celestial object mean radius, `m`.
export const float MERCURY_RADIUS = 2.43 * 10.0e6
//@variable Celestial object density, `kg/m3`.
export const float MERCURY_DENSITY = 5429.0
//@variable Celestial object gravity, `m/s2`.
export const float MERCURY_GRAVITY = 3.7
//@variable Celestial object escape velocity, `km/s`.
export const float MERCURY_ESCAPE_VELOCITY = 4.3
//@variable Celestial object length of day, `h`.
export const float MERCURY_ROTATION_PERIOD = 1407.6
//@variable Celestial object length of day, `h`.
export const float MERCURY_DAY_LENGTH = 4222.6
//@variable Celestial object average orbit period.
export const float MERCURY_AVG_ORB_D = 87.96934
//@variable Celestial object average orbit period.
export const float MERCURY_AVG_ORB_Y = 0.24084
//@variable Celestial object orbital velocity, `km/s`.
export const float MERCURY_ORB_VELOCITY = 47.4
//@variable Celestial object orbital inclination, `ª` degrees.
export const float MERCURY_ORB_INCLINATION = 7.0
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float MERCURY_ORB_ECCENTRICITY = 0.206
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float MERCURY_ORB_OBLIQUITY = 0.034
//@variable Celestial object mean temperature, `ª` celsius.
export const float MERCURY_AVG_TEMPERATURE = 167.0
//@variable Celestial object surface pressure, `` bars.
export const float MERCURY_SURFACE_PRESSURE = 0.0
//@variable Celestial object number of moons.
export const int MERCURY_NMOONS = 0
//@variable Celestial object has ring system?.
export const bool MERCURY_HAS_RING = false
//@variable Celestial object has magnetic field?.
export const bool MERCURY_HAS_MAGNETIC_FIELD = true
//@variable Celestial object spin.
export const float MERCURY_SPIN_D = 25.38
//@variable Celestial object spin.
export const float MERCURY_SPIN_H = 1407.5088
// @variable Distance to the Sun, `km`.
export const float MERCURY_DSUN_AVG_KM = 57.9 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float MERCURY_DSUN_AVG_AU = 0.38709893
// @variable Distance to the Sun, `km`.
export const float MERCURY_DSUN_PERIHELION_KM = 46.0 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float MERCURY_DSUN_PERIHELION_AU = 0.3074890352
// @variable Distance to the Sun, `km`.
export const float MERCURY_DSUN_APHELION_KM = 69.8 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float MERCURY_DSUN_APHELION_AU = 0.4667065166
// @variable Distance to the Sun, `LY`.
export const float MERCURY_DSUN_AVG_LY = 0.0536567
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float MERCURY_FX_SUN_TFP = 3.15139
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float MERCURY_FX_SUN_TFA = 0.90141
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float MERCURY_FX_SUN_GFP = 20715.25259
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float MERCURY_FX_SUN_GFA = 8993.02017

//@variable Celestial object body mass.
export const float VENUS_MASS = 4.86737884430283E+24
//@variable Celestial object diameter, `km`.
export const float VENUS_DIAMETER = 12.104
// @variable Celestial object mean radius, `m`.
export const float VENUS_RADIUS = 6.06 * 10.0e6
//@variable Celestial object density, `kg/m3`.
export const float VENUS_DENSITY = 5243.0
//@variable Celestial object gravity, `m/s2`.
export const float VENUS_GRAVITY = 8.9
//@variable Celestial object escape velocity, `km/s`.
export const float VENUS_ESCAPE_VELOCITY = 10.4
//@variable Celestial object length of day, `h`.
export const float VENUS_ROTATION_PERIOD = -5832.5
//@variable Celestial object length of day, `h`.
export const float VENUS_DAY_LENGTH = 2802
//@variable Celestial object average orbit period.
export const float VENUS_AVG_ORB_D = 224.70069
//@variable Celestial object average orbit period.
export const float VENUS_AVG_ORB_Y = 0.61518
//@variable Celestial object orbital velocity, `km/s`.
export const float VENUS_ORB_VELOCITY = 35.0
//@variable Celestial object orbital inclination, `ª` degrees.
export const float VENUS_ORB_INCLINATION = 3.4
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float VENUS_ORB_ECCENTRICITY = 0.007
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float VENUS_ORB_OBLIQUITY = 177.4
//@variable Celestial object mean temperature, `ª` celsius.
export const float VENUS_AVG_TEMPERATURE = 464.0
//@variable Celestial object surface pressure, `` bars.
export const float VENUS_SURFACE_PRESSURE = 92.0
//@variable Celestial object number of moons.
export const int VENUS_NMOONS = 0
//@variable Celestial object has ring system?.
export const bool VENUS_HAS_RING = false
//@variable Celestial object has magnetic field?.
export const bool VENUS_HAS_MAGNETIC_FIELD = false
//@variable Celestial object spin.
export const float VENUS_SPIN_D = -243.0185
//@variable Celestial object spin.
export const float VENUS_SPIN_H = -5832.444
// @variable Distance to the Sun, `km`.
export const float VENUS_DSUN_AVG_KM = 108.2 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float VENUS_DSUN_AVG_AU = 0.72333199
// @variable Distance to the Sun, `km`.
export const float VENUS_DSUN_PERIHELION_KM = 107.5 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float VENUS_DSUN_PERIHELION_AU = 0.7183698239
// @variable Distance to the Sun, `km`.
export const float VENUS_DSUN_APHELION_KM = 108.9 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float VENUS_DSUN_APHELION_AU = 0.7282889865
// @variable Distance to the Sun, `LY`.
export const float VENUS_DSUN_AVG_LY = 0.1002628
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float VENUS_FX_SUN_TFP = 3.64316
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float VENUS_FX_SUN_TFA = 3.49838
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float VENUS_FX_SUN_GFP = 55951.83789
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float VENUS_FX_SUN_GFA = 54459.40190

//@variable Celestial object body mass.
export const float EARTH_MASS = 5.97225784209252E+24
//@variable Celestial object diameter, `km`.
export const float EARTH_DIAMETER = 12756.0
// @variable Celestial object mean radius, `m`.
export const float EARTH_RADIUS = 6.37 * 10.0e6
//@variable Celestial object density, `kg/m3`.
export const float EARTH_DENSITY = 5514.0
//@variable Celestial object gravity, `m/s2`.
export const float EARTH_GRAVITY = 9.8
//@variable Celestial object escape velocity, `km/s`.
export const float EARTH_ESCAPE_VELOCITY = 11.2
//@variable Celestial object length of day, `h`.
export const float EARTH_ROTATION_PERIOD = 23.9
//@variable Celestial object length of day, `h`.
export const float EARTH_DAY_LENGTH = 24.0
//@variable Celestial object average orbit period.
export const float EARTH_AVG_ORB_D = 365.25641
//@variable Celestial object average orbit period.
export const float EARTH_AVG_ORB_Y = 1.0
//@variable Celestial object orbital velocity, `km/s`.
export const float EARTH_ORB_VELOCITY = 29.8
//@variable Celestial object orbital inclination, `ª` degrees.
export const float EARTH_ORB_INCLINATION = 0.0
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float EARTH_ORB_ECCENTRICITY = 0.017
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float EARTH_ORB_OBLIQUITY = 23.4
//@variable Celestial object mean temperature, `ª` celsius.
export const float EARTH_AVG_TEMPERATURE = 15.0
//@variable Celestial object surface pressure, `` bars.
export const float EARTH_SURFACE_PRESSURE = 1.0
//@variable Celestial object number of moons.
export const int EARTH_NMOONS = 1
//@variable Celestial object has ring system?.
export const bool EARTH_HAS_RING = false
//@variable Celestial object has magnetic field?.
export const bool EARTH_HAS_MAGNETIC_FIELD = true
//@variable Celestial object spin.
export const float EARTH_SPIN_D = 0.997258
//@variable Celestial object spin.
export const float EARTH_SPIN_H = 23.9341
// @variable Distance to the Sun, `km`.
export const float EARTH_DSUN_AVG_KM = 149.6 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float EARTH_DSUN_AVG_AU = 1.0000000001
// @variable Distance to the Sun, `km`.
export const float EARTH_DSUN_PERIHELION_KM = 147.1 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float EARTH_DSUN_PERIHELION_AU = 0.9831915115
// @variable Distance to the Sun, `km`.
export const float EARTH_DSUN_APHELION_KM = 152.1 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float EARTH_DSUN_APHELION_AU = 1.0168061579
// @variable Distance to the Sun, `LY`.
export const float EARTH_DSUN_AVG_LY = 0.1386124
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float EARTH_FX_SUN_TFP = 1.74341
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float EARTH_FX_SUN_TFA = 1.57735
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float EARTH_FX_SUN_GFP = 36647.35500
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float EARTH_FX_SUN_GFA = 34281.60905

//@variable Celestial object body mass.
export const float MOON_MASS = 7.34590000621462E+22
//@variable Celestial object diameter, `km`.
export const float MOON_DIAMETER = 3475.0
// @variable Celestial object mean radius, `m`.
export const float MOON_RADIUS = 1.7375 * 10.0e6
//@variable Celestial object density, `kg/m3`.
export const float MOON_DENSITY = 3475.0
//@variable Celestial object gravity, `m/s2`.
export const float MOON_GRAVITY = 1.6
//@variable Celestial object escape velocity, `km/s`.
export const float MOON_ESCAPE_VELOCITY = 2.4
//@variable Celestial object length of day, `h`.
export const float MOON_ROTATION_PERIOD = 655.7
//@variable Celestial object length of day, `h`.
export const float MOON_DAY_LENGTH = 708.7
//@variable Celestial object average orbit period.
export const float MOON_AVG_ORB_D = 365.2
//@variable Celestial object average orbit period.
export const float MOON_AVG_ORB_Y = 1.0
//@variable Celestial object orbital velocity, `km/s`.
export const float MOON_ORB_VELOCITY = 1.0
//@variable Celestial object orbital inclination, `ª` degrees.
export const float MOON_ORB_INCLINATION = 5.1
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float MOON_ORB_ECCENTRICITY = 0.055
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float MOON_ORB_OBLIQUITY = 6.7
//@variable Celestial object mean temperature, `ª` celsius.
export const float MOON_AVG_TEMPERATURE = -20.0
//@variable Celestial object surface pressure, `` bars.
export const float MOON_SURFACE_PRESSURE = 0.0
//@variable Celestial object number of moons.
export const int MOON_NMOONS = 0
//@variable Celestial object has ring system?.
export const bool MOON_HAS_RING = false
//@variable Celestial object has magnetic field?.
export const bool MOON_HAS_MAGNETIC_FIELD = false
//@variable Celestial object spin.
export const float MOON_SPIN_D = 27.3
//@variable Celestial object spin.
export const float MOON_SPIN_H = 655.2
// @variable Distance to Earth, `km`.
export const float MOON_DEARTH_AVG_KM = 0.384 * 10.0e6
// @variable Distance Earth, `AU`.
export const float MOON_DEARTH_AVG_AU = 0.0026
// @variable Distance to Earth at perihelium, `km`.
export const float MOON_DEARTH_PERIHELION_KM = 0.363 * 10.0e6
// @variable Distance to Earth at perihelium, `AU`.
export const float MOON_DEARTH_PERIHELION_AU = 0.0024
// @variable Distance to Earth at aphelium, `km`.
export const float MOON_DEARTH_APHELION_KM = 0.406 * 10.0e6
// @variable Distance to Earth at aphelium, `AU`.
export const float MOON_DEARTH_APHELION_AU = 0.027

//@variable Celestial object body mass.
export const float EMB_MASS = 6.04571684215467E+24
//@variable Celestial object average orbit period.
export const float EMB_AVG_ORB_D = float(na)
//@variable Celestial object average orbit period.
export const float EMB_AVG_ORB_Y = float(na)
//@variable Celestial object spin.
export const float EMB_SPIN_D = float(na)
//@variable Celestial object spin.
export const float EMB_SPIN_H = float(na)
// @variable Distance to the Sun, `AU`.
export const float EMB_DSUN_AVG_AU = float(na)
// @variable Distance to the Sun, `AU`.
export const float EMB_DSUN_PERIHELION_AU = float(na)
// @variable Distance to the Sun, `AU`.
export const float EMB_DSUN_APHELION_AU = float(na)
// @variable Distance to the Sun, `AU`.
export const float EMB_DSUN_AVG_LY = float(na)
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float EMB_FX_SUN_TFP = float(na)
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float EMB_FX_SUN_TFA = float(na)
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float EMB_FX_SUN_GFP = float(na)
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float EMB_FX_SUN_GFA = float(na)

//@variable Celestial object body mass.
export const float MARS_MASS = 6.41699593330543E+23
//@variable Celestial object diameter, `km`.
export const float MARS_DIAMETER = 6792.0
// @variable Celestial object mean radius, `m`.
export const float MARS_RADIUS = 3.37 * 10.0e6
//@variable Celestial object density, `kg/m3`.
export const float MARS_DENSITY = 3934.0
//@variable Celestial object gravity, `m/s2`.
export const float MARS_GRAVITY = 3.7
//@variable Celestial object escape velocity, `km/s`.
export const float MARS_ESCAPE_VELOCITY = 5.0
//@variable Celestial object length of day, `h`.
export const float MARS_ROTATION_PERIOD = 24.6
//@variable Celestial object length of day, `h`.
export const float MARS_DAY_LENGTH = 24.7
//@variable Celestial object average orbit period.
export const float MARS_AVG_ORB_D = 686.96000
//@variable Celestial object average orbit period.
export const float MARS_AVG_ORB_Y = 1.88076
//@variable Celestial object orbital velocity, `km/s`.
export const float MARS_ORB_VELOCITY = 24.1
//@variable Celestial object orbital inclination, `ª` degrees.
export const float MARS_ORB_INCLINATION = 1.8
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float MARS_ORB_ECCENTRICITY = 0.094
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float MARS_ORB_OBLIQUITY = 25.2
//@variable Celestial object mean temperature, `ª` celsius.
export const float MARS_AVG_TEMPERATURE = -65.0
//@variable Celestial object surface pressure, `` bars.
export const float MARS_SURFACE_PRESSURE = 0.01
//@variable Celestial object number of moons.
export const int MARS_NMOONS = 2
//@variable Celestial object has ring system?.
export const bool MARS_HAS_RING = false
//@variable Celestial object has magnetic field?.
export const bool MARS_HAS_MAGNETIC_FIELD = false
//@variable Celestial object spin.
export const float MARS_SPIN_D = 1.025957
//@variable Celestial object spin.
export const float MARS_SPIN_H = 24.6229
// @variable Distance to the Sun, `km`.
export const float MARS_DSUN_AVG_KM = 228.0 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float MARS_DSUN_AVG_AU = 1.52366231
// @variable Distance to the Sun, `km`.
export const float MARS_DSUN_PERIHELION_KM = 206.7 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float MARS_DSUN_PERIHELION_AU = 1.3810512113
// @variable Distance to the Sun, `km`.
export const float MARS_DSUN_APHELION_KM = 249.3 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float MARS_DSUN_APHELION_AU = 1.6662924910
// @variable Distance to the Sun, `LY`.
export const float MARS_DSUN_AVG_LY = 0.2111986
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float MARS_FX_SUN_TFP = 0.06758
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float MARS_FX_SUN_TFA = 0.03852
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float MARS_FX_SUN_GFP = 1995.55933
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float MARS_FX_SUN_GFA = 1371.74508

//#region Asteroid Belt:

//@variable Celestial object body mass.
export const float AB_CERES_MASS = 9.5E+20
//@variable Celestial object diameter, `km`.
export const float AB_CERES_DIAMETER = 975.0
//@variable Celestial object density, `kg/m3`.
export const float AB_CERES_DENSITY = 2.08
//@variable Celestial object mean temperature, `ª` celsius.
export const float AB_CERES_AVG_TEMPERATURE = -106.5
//@variable Celestial object average orbit period.
export const float AB_CERES_AVG_ORB_D = 1679.81900
//@variable Celestial object average orbit period.
export const float AB_CERES_AVG_ORB_Y = 4.59901
//@variable Celestial object spin.
export const float AB_CERES_SPIN_D = 0.3781
//@variable Celestial object spin.
export const float AB_CERES_SPIN_H = 9.0744
// @variable Distance to the Sun, `AU`.
export const float AB_CERES_DSUN_AVG_AU = 2.766
// @variable Distance to the Sun, `AU`.
export const float AB_CERES_DSUN_PERIHELION_AU = 2.544
// @variable Distance to the Sun, `AU`.
export const float AB_CERES_DSUN_APHELION_AU = 2.987
// @variable Distance to the Sun, `AU`.
export const float AB_CERES_DSUN_AVG_LY = float(na)

//@variable Celestial object body mass.
export const float AB_PALLAS_MASS = 204.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_JUNO_MASS = 27.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_VESTA_MASS = 259.076 * 10.0e18

//@variable Celestial object body mass.
export const float AB_HEBE_MASS = 12.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_IRIS_MASS = 14.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_HYGIEA_MASS = 87.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_EUNOMIA_MASS = 30.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_PSYCHE_MASS = 23.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_AMPHITRITE_MASS = 13.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_EUPHROSYNE_MASS = 17.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_EUROPA_MASS = 24.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_CYBELE_MASS = 15.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_SYLVIA_MASS = 14.76 * 10.0e18

//@variable Celestial object body mass.
export const float AB_THISBE_MASS = 12.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_CAMILLA_MASS = 11.2 * 10.0e18

//@variable Celestial object body mass.
export const float AB_BAMBERGA_MASS = 10.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_DAVIDA_MASS = 27.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_HERCULIA_MASS = 23.0 * 10.0e18

//@variable Celestial object body mass.
export const float AB_INTERAMNIA_MASS = 35.0 * 10.0e18

//@variable Celestial object body mass.
export const float ASTEROIDSBELT_MASS = 2.3E+21

//#endregion

//@variable Celestial object body mass.
export const float JUPITER_MASS = 1.89854616070534E+27
//@variable Celestial object diameter, `km`.
export const float JUPITER_DIAMETER = 142984.0
// @variable Celestial object mean radius, `m`.
export const float JUPITER_RADIUS = 6.99 * 10.0e7
//@variable Celestial object density, `kg/m3`.
export const float JUPITER_DENSITY = 1326.0
//@variable Celestial object gravity, `m/s2`.
export const float JUPITER_GRAVITY = 23.1
//@variable Celestial object escape velocity, `km/s`.
export const float JUPITER_ESCAPE_VELOCITY = 59.5
//@variable Celestial object length of day, `h`.
export const float JUPITER_ROTATION_PERIOD = 9.9
//@variable Celestial object length of day, `h`.
export const float JUPITER_DAY_LENGTH = 9.9
//@variable Celestial object average orbit period.
export const float JUPITER_AVG_ORB_D = 4333.28670
//@variable Celestial object average orbit period.
export const float JUPITER_AVG_ORB_Y = 11.86368
//@variable Celestial object orbital velocity, `km/s`.
export const float JUPITER_ORB_VELOCITY = 13.1
//@variable Celestial object orbital inclination, `ª` degrees.
export const float JUPITER_ORB_INCLINATION = 1.3
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float JUPITER_ORB_ECCENTRICITY = 0.049
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float JUPITER_ORB_OBLIQUITY = 3.1
//@variable Celestial object mean temperature, `ª` celsius.
export const float JUPITER_AVG_TEMPERATURE = -110.0
//@variable Celestial object surface pressure, `` bars.
export const float JUPITER_SURFACE_PRESSURE = float(na)
//@variable Celestial object number of moons.
export const int JUPITER_NMOONS = 95
//@variable Celestial object has ring system?.
export const bool JUPITER_HAS_RING = true
//@variable Celestial object has magnetic field?.
export const bool JUPITER_HAS_MAGNETIC_FIELD = true
//@variable Celestial object spin.
export const float JUPITER_SPIN_D = 0.413538021
//@variable Celestial object spin.
export const float JUPITER_SPIN_H = 9.92491
// @variable Distance to the Sun, `km`.
export const float JUPITER_DSUN_AVG_KM = 778.5 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float JUPITER_DSUN_AVG_AU = 5.20336301
// @variable Distance to the Sun, `km`.
export const float JUPITER_DSUN_PERIHELION_KM = 740.6 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float JUPITER_DSUN_PERIHELION_AU = 4.9473167719
// @variable Distance to the Sun, `km`.
export const float JUPITER_DSUN_APHELION_KM = 816.4 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float JUPITER_DSUN_APHELION_AU = 5.4574965842
// @variable Distance to the Sun, `LY`.
export const float JUPITER_DSUN_AVG_LY = 0.7212508
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float JUPITER_FX_SUN_TFP = 4.34907
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float JUPITER_FX_SUN_TFA = 3.24369
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float JUPITER_FX_SUN_GFP = 460047.70085
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float JUPITER_FX_SUN_GFA = 378354.10721

//@variable Celestial object body mass.
export const float SATURN_MASS = 5.68467023180865E+26
//@variable Celestial object diameter, `km`.
export const float SATURN_DIAMETER = 120536
// @variable Celestial object mean radius, `m`.
export const float SATURN_RADIUS = 5.85 * 10.0e7
//@variable Celestial object density, `kg/m3`.
export const float SATURN_DENSITY = 687.0
//@variable Celestial object gravity, `m/s2`.
export const float SATURN_GRAVITY = 9.0
//@variable Celestial object escape velocity, `km/s`.
export const float SATURN_ESCAPE_VELOCITY = 35.5
//@variable Celestial object length of day, `h`.
export const float SATURN_ROTATION_PERIOD = 10.7
//@variable Celestial object length of day, `h`.
export const float SATURN_DAY_LENGTH = 10.7
//@variable Celestial object average orbit period.
export const float SATURN_AVG_ORB_D = 10756.19950
//@variable Celestial object average orbit period.
export const float SATURN_AVG_ORB_Y = 29.44835
//@variable Celestial object orbital velocity, `km/s`.
export const float SATURN_ORB_VELOCITY = 9.7
//@variable Celestial object orbital inclination, `ª` degrees.
export const float SATURN_ORB_INCLINATION = 2.5
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float SATURN_ORB_ECCENTRICITY = 0.052
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float SATURN_ORB_OBLIQUITY = 26.7
//@variable Celestial object mean temperature, `ª` celsius.
export const float SATURN_AVG_TEMPERATURE = -140
//@variable Celestial object surface pressure, `` bars.
export const float SATURN_SURFACE_PRESSURE = float(na)
//@variable Celestial object number of moons.
export const int SATURN_NMOONS = 274
//@variable Celestial object has ring system?.
export const bool SATURN_HAS_RING = true
//@variable Celestial object has magnetic field?.
export const bool SATURN_HAS_MAGNETIC_FIELD = true
//@variable Celestial object spin.
export const float SATURN_SPIN_D = 0.4440092592
//@variable Celestial object spin.
export const float SATURN_SPIN_H = 10.65622
// @variable Distance to the Sun, `km`.
export const float SATURN_DSUN_AVG_KM = 1432.0 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float SATURN_DSUN_AVG_AU = 9.53707032
// @variable Distance to the Sun, `km`.
export const float SATURN_DSUN_PERIHELION_KM = 1357.6 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float SATURN_DSUN_PERIHELION_AU = 8.9937104773
// @variable Distance to the Sun, `km`.
export const float SATURN_DSUN_APHELION_KM = 1506.5 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float SATURN_DSUN_APHELION_AU =10.102270262
// @variable Distance to the Sun, `LY`.
export const float SATURN_DSUN_AVG_LY = 1.3219566
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float SATURN_FX_SUN_TFP = 0.21417
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float SATURN_FX_SUN_TFA = 0.15468
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float SATURN_FX_SUN_GFP = 41346.85480
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float SATURN_FX_SUN_GFA = 33282.95551

//@variable Celestial object body mass.
export const float URANUS_MASS = 8.68201283610302E+25
//@variable Celestial object diameter, `km`.
export const float URANUS_DIAMETER = 51118.0
// @variable Celestial object mean radius, `m`.
export const float URANUS_RADIUS = 2.33 * 10.0e7
//@variable Celestial object density, `kg/m3`.
export const float URANUS_DENSITY = 1270.0
//@variable Celestial object gravity, `m/s2`.
export const float URANUS_GRAVITY = 8.7
//@variable Celestial object escape velocity, `km/s`.
export const float URANUS_ESCAPE_VELOCITY = 21.3
//@variable Celestial object length of day, `h`.
export const float URANUS_ROTATION_PERIOD = -17.2
//@variable Celestial object length of day, `h`.
export const float URANUS_DAY_LENGTH = 17.2
//@variable Celestial object average orbit period.
export const float URANUS_AVG_ORB_D = 30707.48960
//@variable Celestial object average orbit period.
export const float URANUS_AVG_ORB_Y = 84.07104
//@variable Celestial object orbital velocity, `km/s`.
export const float URANUS_ORB_VELOCITY = 6.8
//@variable Celestial object orbital inclination, `ª` degrees.
export const float URANUS_ORB_INCLINATION = 0.8
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float URANUS_ORB_ECCENTRICITY = 0.047
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float URANUS_ORB_OBLIQUITY = 97.8
//@variable Celestial object mean temperature, `ª` celsius.
export const float URANUS_AVG_TEMPERATURE = -195.0
//@variable Celestial object surface pressure, `` bars.
export const float URANUS_SURFACE_PRESSURE = float(na)
//@variable Celestial object number of moons.
export const int URANUS_NMOONS = 28
//@variable Celestial object has ring system?.
export const bool URANUS_HAS_RING = true
//@variable Celestial object has magnetic field?.
export const bool URANUS_HAS_MAGNETIC_FIELD = true
//@variable Celestial object spin.
export const float URANUS_SPIN_D = -0.718333333
//@variable Celestial object spin.
export const float URANUS_SPIN_H = -17.23999
// @variable Distance to the Sun, `km`.
export const float URANUS_DSUN_AVG_KM = 2867.0 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float URANUS_DSUN_AVG_AU = 19.19126393
// @variable Distance to the Sun, `km`.
export const float URANUS_DSUN_PERIHELION_KM = 2732.7 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float URANUS_DSUN_PERIHELION_AU = 18.280651144
// @variable Distance to the Sun, `km`.
export const float URANUS_DSUN_APHELION_KM = 3001.4 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float URANUS_DSUN_APHELION_AU = 20.107776505
// @variable Distance to the Sun, `LY`.
export const float URANUS_DSUN_AVG_LY = 2.6601479
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float URANUS_FX_SUN_TFP = 0.00394
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float URANUS_FX_SUN_TFA = 0.00297
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float URANUS_FX_SUN_GFP = 1540.65205
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float URANUS_FX_SUN_GFA = 1275.09665

//@variable Celestial object body mass.
export const float NEPTUNE_MASS = 1.02432262501562E+26
//@variable Celestial object diameter, `km`.
export const float NEPTUNE_DIAMETER = 49528.0
// @variable Celestial object mean radius, `m`.
export const float NEPTUNE_RADIUS = 2.21 * 10.0e7
//@variable Celestial object density, `kg/m3`.
export const float NEPTUNE_DENSITY = 1638
//@variable Celestial object gravity, `m/s2`.
export const float NEPTUNE_GRAVITY = 11.0
//@variable Celestial object escape velocity, `km/s`.
export const float NEPTUNE_ESCAPE_VELOCITY = 23.5
//@variable Celestial object length of day, `h`.
export const float NEPTUNE_ROTATION_PERIOD = 16.1
//@variable Celestial object length of day, `h`.
export const float NEPTUNE_DAY_LENGTH = 16.1
//@variable Celestial object average orbit period.
export const float NEPTUNE_AVG_ORB_D = 60223.48960
//@variable Celestial object average orbit period.
export const float NEPTUNE_AVG_ORB_Y = 164.87966
//@variable Celestial object orbital velocity, `km/s`.
export const float NEPTUNE_ORB_VELOCITY = 5.4
//@variable Celestial object orbital inclination, `ª` degrees.
export const float NEPTUNE_ORB_INCLINATION = 1.8
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float NEPTUNE_ORB_ECCENTRICITY = 0.010
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float NEPTUNE_ORB_OBLIQUITY = 28.3
//@variable Celestial object mean temperature, `ª` celsius.
export const float NEPTUNE_AVG_TEMPERATURE = -200.0
//@variable Celestial object surface pressure, `` bars.
export const float NEPTUNE_SURFACE_PRESSURE = float(na)
//@variable Celestial object number of moons.
export const int NEPTUNE_NMOONS = 16
//@variable Celestial object has ring system?.
export const bool NEPTUNE_HAS_RING = true
//@variable Celestial object has magnetic field?.
export const bool NEPTUNE_HAS_MAGNETIC_FIELD = true
//@variable Celestial object spin.
export const float NEPTUNE_SPIN_D = 0.6713
//@variable Celestial object spin.
export const float NEPTUNE_SPIN_H = 16.1112
// @variable Distance to the Sun, `km`.
export const float NEPTUNE_DSUN_AVG_KM = 4515.0 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float NEPTUNE_DSUN_AVG_AU = 30.06896348
// @variable Distance to the Sun, `km`.
export const float NEPTUNE_DSUN_PERIHELION_KM = 4471.1 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float NEPTUNE_DSUN_PERIHELION_AU = 29.806522658
// @variable Distance to the Sun, `km`.
export const float NEPTUNE_DSUN_APHELION_KM = 4558.9 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float NEPTUNE_DSUN_APHELION_AU = 30.339172623
// @variable Distance to the Sun, `LY`.
export const float NEPTUNE_DSUN_AVG_LY = 4.1679324
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float NEPTUNE_FX_SUN_TFP = 0.00107
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float NEPTUNE_FX_SUN_TFA = 0.00102
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float NEPTUNE_FX_SUN_GFP = 683.92670
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float NEPTUNE_FX_SUN_GFA = 660.44589

//#region Trans Neptune Objects:
// -->
// 
// 
// 
// <--

//@variable Celestial object body mass.
export const float KB_PLUTO_MASS = 1.47073939604298E+22
//@variable Celestial object diameter, `km`.
export const float KB_PLUTO_DIAMETER = 2376.0
// @variable Celestial object mean radius, `m`.
export const float KB_PLUTO_RADIUS = 1.118 * 10.0e6
//@variable Celestial object density, `kg/m3`.
export const float KB_PLUTO_DENSITY = 1850.0
//@variable Celestial object gravity, `m/s2`.
export const float KB_PLUTO_GRAVITY = 0.7
//@variable Celestial object escape velocity, `km/s`.
export const float KB_PLUTO_ESCAPE_VELOCITY = 1.3
//@variable Celestial object length of day, `h`.
export const float KB_PLUTO_ROTATION_PERIOD = -153.0
//@variable Celestial object length of day, `h`.
export const float KB_PLUTO_DAY_LENGTH = 153.3
//@variable Celestial object average orbit period.
export const float KB_PLUTO_AVG_ORB_D = 90613.30550
//@variable Celestial object average orbit period.
export const float KB_PLUTO_AVG_ORB_Y = 248.08135
//@variable Celestial object orbital velocity, `km/s`.
export const float KB_PLUTO_ORB_VELOCITY = 4.7
//@variable Celestial object orbital inclination, `ª` degrees.
export const float KB_PLUTO_ORB_INCLINATION = 17.2
//@variable Celestial object eccentricity, a measure of how far a orbit goes from its center. The larger the eccentricity, the more elongated is the orbit, an eccentricity of 0 means the orbit is a perfect circle. 
export const float KB_PLUTO_ORB_ECCENTRICITY = 0.244
//@variable Celestial object obliquity to orbit, `ª` degrees. The angle in degrees the axis of a planet (the imaginary line running through the center of the planet from the north to south poles) is tilted relative to a line perpendicular to the planet's orbit around the Sun, north pole defined by right hand rule.
export const float KB_PLUTO_ORB_OBLIQUITY = 119.5
//@variable Celestial object mean temperature, `ª` celsius.
export const float KB_PLUTO_AVG_TEMPERATURE = -225.0
//@variable Celestial object surface pressure, `` bars.
export const float KB_PLUTO_SURFACE_PRESSURE = 0.00001
//@variable Celestial object number of moons.
export const int KB_PLUTO_NMOONS = 5
//@variable Celestial object has ring system?.
export const bool KB_PLUTO_HAS_RING = false
//@variable Celestial object has magnetic field?.
export const bool KB_PLUTO_HAS_MAGNETIC_FIELD = bool(na)
//@variable Celestial object spin.
export const float KB_PLUTO_SPIN_D = 6.38723
//@variable Celestial object spin.
export const float KB_PLUTO_SPIN_H = 153.29352
// @variable Distance to the Sun, `km`.
export const float KB_PLUTO_DSUN_AVG_KM = 5906.4 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float KB_PLUTO_DSUN_AVG_AU = 39.48168677
// @variable Distance to the Sun, `km`.
export const float KB_PLUTO_DSUN_PERIHELION_KM = 4436.4 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float KB_PLUTO_DSUN_PERIHELION_AU = 29.649274404
// @variable Distance to the Sun, `km`.
export const float KB_PLUTO_DSUN_APHELION_KM = 7375.9 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float KB_PLUTO_DSUN_APHELION_AU = 49.318952713
// @variable Distance to the Sun, `LY`.
export const float KB_PLUTO_DSUN_AVG_LY = 5.4726529

//@variable Celestial object body mass.
export const float KB_MAKEMAKE_MASS = 4.0 * 10.0e21
//@variable Celestial object diameter, `km`.
export const float KB_MAKEMAKE_DIAMETER = 1430.0
//@variable Celestial object density, `kg/m3`.
export const float KB_MAKEMAKE_DENSITY = 2000.0
//@variable Celestial object average orbit period.
export const float KB_MAKEMAKE_AVG_ORB_Y = 310.0
//@variable Celestial object mean temperature, `ª` celsius.
export const float KB_MAKEMAKE_AVG_TEMPERATURE = -243.15
//@variable Celestial object number of moons.
export const int KB_MAKEMAKE_NMOONS = 0
// @variable Distance to the Sun, `AU`.
export const float KB_MAKEMAKE_DSUN_AVG_AU = 45.0
//@variable Celestial object spin.
export const float KB_MAKEMAKE_SPIN_D = 305.0 * 365.0

//@variable Celestial object body mass.
export const float KB_HAUMEA_MASS = 4.2 * 10.0e21
//@variable Celestial object diameter, `km`.
export const float KB_HAUMEA_DIAMETER = 1960.0
//@variable Celestial object density, `kg/m3`.
export const float KB_HAUMEA_DENSITY = 2600.0 //to 3300.0
//@variable Celestial object average orbit period.
export const float KB_HAUMEA_AVG_ORB_Y = 285.0
//@variable Celestial object mean temperature, `ª` celsius.
export const float KB_HAUMEA_AVG_TEMPERATURE = -241.15
//@variable Celestial object number of moons.
export const int KB_HAUMEA_NMOONS = 2
// @variable Distance to the Sun, `AU`.
export const float KB_HAUMEA_DSUN_AVG_AU = 43.5

//@variable Celestial object body mass.
export const float KB_ORCUS_MASS = 5.47 * 10.0e20
//@variable Celestial object diameter, `km`.
export const float KB_ORCUS_DIAMETER = 900.0
//@variable Celestial object density, `kg/m3`.
export const float KB_ORCUS_DENSITY = 1400.0


//@variable Celestial object body mass.
export const float KUIPER_MASS = float(na)
//@variable Celestial object average orbit period.
export const float KUIPER_AVG_ORB_D = float(na)
//@variable Celestial object average orbit period.
export const float KUIPER_AVG_ORB_Y = float(na)
//@variable Celestial object spin.
export const float KUIPER_SPIN_D = float(na)
//@variable Celestial object spin.
export const float KUIPER_SPIN_H = float(na)
// @variable Distance to the Sun, `AU`.
export const float KUIPER_DSUN_AVG_AU = 37.0
// @variable Distance to the Sun, `AU`.
export const float KUIPER_DSUN_PERIHELION_AU = 30.0
// @variable Distance to the Sun, `AU`.
export const float KUIPER_DSUN_APHELION_AU = 44.0
// @variable Distance to the Sun, `AU`.
export const float KUIPER_DSUN_AVG_LY = float(na)
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float KUIPER_FX_SUN_TFP = float(na)
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float KUIPER_FX_SUN_TFA = float(na)
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float KUIPER_FX_SUN_GFP = float(na)
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float KUIPER_FX_SUN_GFA = float(na)

//@variable Celestial object body mass.
export const float SD_ERIS_MASS = 1.7 * 10.0e22
//@variable Celestial object diameter, `km`.
export const float SD_ERIS_DIAMETER = 2326.0
//@variable Celestial object density, `kg/m3`.
export const float SD_ERIS_DENSITY = 2300.0
//@variable Celestial object spin.
export const float SD_ERIS_SPIN_D = float(na)
// @variable Distance to the Sun, `km`.
export const float SD_ERIS_DSUN_AVG_KM = 14062.199874 * 10.0e6
// @variable Distance to the Sun, `AU`.
export const float SD_ERIS_DSUN_AVG_AU = 96.4
//@variable Celestial object number of moons.
export const int SD_ERIS_NMOONS = 1

//@variable Celestial object body mass.
export const float ScatteredDisk = float(na)

//@variable Celestial object body mass.
export const float OORTCLOUD_MASS = float(na)

//#endregion

//@variable Celestial object body mass.
export const float SOLARSYSTEM_MASS = float(na)
// @variable Distance to galatic center in Light Years.
export const float SOLARSYSTEM_DGACENTER_MIN_LY = 24000
// @variable Distance to galatic center in Light Years.
export const float SOLARSYSTEM_DGACENTER_MAX_LY = 28000
// @variable Orbital Speed in `km/h`.
export const float SOLARSYSTEM_ORBSPEED = 720000
// @variable Orbital Period in Years.
export const float SOLARSYSTEM_ORB_Y = 230000000
// @variable Effect of planet on the sun, Tidal Force at perihelium.
export const float SOLARSYSTEM_FX_SUN_TFP = 13.17379
// @variable Effect of planet on the sun, Tidal Force at aphelium.
export const float SOLARSYSTEM_FX_SUN_TFA = 9.41802
// @variable Effect of planet on the sun, Gravity Force at perihelium.
export const float SOLARSYSTEM_FX_SUN_GFP = 618929.13921
// @variable Effect of planet on the sun, Gravity Force at aphelium.
export const float SOLARSYSTEM_FX_SUN_GFA = 512678.38146

//#endregion
