// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Narayanan_R-23

//@version = 6
import TradingView/ta/9 as ta

// @description Versatilities (aka, Versatile Utilities) Pack includes:
//  - Eighteen Price Variants bundled in a Map,
//  - Nine Smoothing Variants bundled in a Map,
//  - Visualisations that indicate on both - pane and chart.
library('PineVersatilitiesBundle')

// Methods: BEGAN --

// @function Computes Several different averages using current and previous OHLC values
// @param lb - lookback distance for combining OHLC values from the past with the present
// @returns Map of Eighteen Uncommon Combinations of single and two-bar OHLC averages (rounded-to-mintick)
export price_variants(int lb = 1) =>
    op = math.round_to_mintick(open), hi = math.round_to_mintick(high)
    lo = math.round_to_mintick(low), cl = math.round_to_mintick(close)
    avrng = math.round_to_mintick(hl2), pivot = math.round_to_mintick(hlc3)
    pvtcl = math.round_to_mintick(hlcc4), avbar = math.round_to_mintick(ohlc4)
    prcMA = math.avg(math.avg(avrng, pivot, pvtcl, avbar), (2 * op + 3 * (hi + lo) + 5 * cl) / 13)
    oc2 = math.avg(op, cl), pcoc2 = math.avg(nz(cl[lb]), oc2), pooc2 = math.avg(nz(op[lb]), oc2)
    popc2 = math.avg(nz(op[lb]), nz(cl[lb])), poc3 = math.avg(math.avg(popc2, oc2), pcoc2, pooc2)
    pivot2b = math.avg(nz(cl[lb]), avrng) // two-bar pivot
    pchlc2 = math.avg(nz(cl[lb]), pivot), pcohlc2 = math.avg(nz(cl[lb]), avbar)
    phpl2 = math.avg(nz(hi[lb]), nz(lo[lb])), phplhl2 = math.avg(phpl2, avrng)
    phplpc2 = math.avg(phpl2, nz(cl[lb])), phplpcpc2 = math.avg(phplpc2, nz(cl[lb]))
    pophplpc2 = math.avg(phpl2, nz(op[lb])), avg2b = math.avg(pophplpc2, avbar)
    prcMA2b = math.avg(popc2, poc3, math.avg(pivot2b, pchlc2, pcohlc2, phpl2, phplhl2, phplpc2, phplpcpc2, pophplpc2))
    priceMA = math.avg(prcMA, avg2b, prcMA2b)
    price = math.avg(math.avg(prcMA, oc2), math.avg(pcoc2, pooc2, popc2, poc3, pivot2b), math.avg(pchlc2, pcohlc2, phpl2), math.avg(phplhl2, phplpc2, phplpcpc2, pophplpc2, avg2b), math.avg(prcMA2b, priceMA))
    
	prices_map = map.new<string, float>()

    prices_map.put('prcMA', math.round_to_mintick(prcMA)), prices_map.put('oc2', math.round_to_mintick(oc2))
	prices_map.put('pcoc2', math.round_to_mintick(pcoc2)), prices_map.put('pooc2', math.round_to_mintick(pooc2))
    prices_map.put('popc2', math.round_to_mintick(popc2)), prices_map.put('poc3', math.round_to_mintick(poc3))
    prices_map.put('pivot2b', math.round_to_mintick(pivot2b)), prices_map.put('pchlc2', math.round_to_mintick(pchlc2))
    prices_map.put('pcohlc2', math.round_to_mintick(pcohlc2)), prices_map.put('phpl2', math.round_to_mintick(phpl2))
    prices_map.put('phplhl2', math.round_to_mintick(phplhl2)), prices_map.put('phplpc2', math.round_to_mintick(phplpc2))
    prices_map.put('phplpcpc2', math.round_to_mintick(phplpcpc2)), prices_map.put('pophplpc2', math.round_to_mintick(pophplpc2))
    prices_map.put('avg2b', math.round_to_mintick(avg2b)), prices_map.put('prcMA2b', math.round_to_mintick(prcMA2b))
    prices_map.put('priceMA', math.round_to_mintick(priceMA)), prices_map.put('price', math.round_to_mintick(price))

    // [prcMA, oc2, pcoc2, pooc2, popc2, poc3, pivot2b, pchlc2, pcohlc2, phpl2, phplhl2, phplpc2, phplpcpc2, pophplpc2, avg2b, prcMA2b, priceMA, price]
    prices_map

// @function Dynamically computes Eight different MAs and returns a Map containing Nine MAs
// @param masrc source series to compute MA
// @param malen lookback distance for MA
// @param lsmaoff optional LSMA offset - default is 0
// @param almasgm optional ALMA sigma - default is 5
// @param almaoff optional ALMA offset - default is 0.5
// @param almaflr optional ALMA floor flag - default is false
// @returns Map of MAs - 'ALMA', 'EMA', 'HMA', 'LSMA', 'RMA', 'SMA', 'SWMA', 'WMA', 'ALL' (rounded-to-mintick)
export dynamic_MA(series float masrc, int malen, int lsmaoff = 0, float almasgm = 5, float almaoff = 0.5, bool almaflr = false) =>
	alma = ta.alma(masrc, malen, almaoff, almasgm, almaflr), ema = ta.ema(masrc, malen), hma = ta.hma(masrc, malen)
    lsma = ta.linreg(masrc, malen, lsmaoff), rma = ta.rma(masrc, malen), sma = ta.sma(masrc, malen), swma = ta.swma(masrc)
    wma = ta.wma(masrc, malen), avma = math.avg(alma, ema, hma, lsma, rma, sma, swma, wma)

    dyna_ma_map = map.new<string, float>()
        
	dyna_ma_map.put('ALMA', math.round_to_mintick(alma)), dyna_ma_map.put('EMA', math.round_to_mintick(ema))
	dyna_ma_map.put('HMA', math.round_to_mintick(hma)),	dyna_ma_map.put('LSMA', math.round_to_mintick(lsma))
	dyna_ma_map.put('RMA', math.round_to_mintick(rma)),	dyna_ma_map.put('SMA', math.round_to_mintick(sma))
	dyna_ma_map.put('SWMA', math.round_to_mintick(swma)), dyna_ma_map.put('WMA', math.round_to_mintick(wma))
	dyna_ma_map.put('ALL', math.round_to_mintick(avma))

	dyna_ma_map

// Methods: ENDED

// Price Calculations --
prices_map = price_variants(), price = prices_map.get('price')
price_12ma_map = dynamic_MA(price, 12), price_12alma = price_12ma_map.get('ALMA')
price_34ma_map = dynamic_MA(price, 34), price_34swma = price_34ma_map.get('SWMA')
price_ma = math.avg(price_12alma, price_34swma)

// ASROC Calculations --
roc2 = ta.roc(price, 2), roc3 = ta.roc(price, 3), roc5 = ta.roc(price, 5), roc8 = ta.roc(price, 8)
roc5_5ma = dynamic_MA(roc5, 5), roc2_2ma = dynamic_MA(roc2, 2), roc3_3ma = dynamic_MA(roc3, 3), roc8_8ma = dynamic_MA(roc8, 8)
sroc = 8 * roc5_5ma.get('EMA') + 3 * roc2_2ma.get('HMA') + 2 * roc3_3ma.get('WMA') + 5 * roc8_8ma.get('RMA')
sgnl = dynamic_MA(sroc, 5).get('SMA')

// Visualisations --
prc_clr = color.new(ta.change(price) > 0 ? color.teal : color.maroon, 23)
prc_ma_clr = color.new(ta.change(price_ma) < 0 ? color.maroon : color.teal, 78)
sroc_clr = color.new(ta.change(sroc) > 0 ? color.green : color.red, 32)
sgnl_clr = color.new(ta.change(sgnl) < 0 ? color.red : color.green, 69)

plot(price, 'Price MA', prc_clr, 2, plot.style_linebr, force_overlay = true)
plot(price_ma, '12-34 Mean MA', prc_ma_clr, 3, plot.style_linebr, force_overlay = true)
plot(sroc, 'ASRoC', sroc_clr, 3, plot.style_linebr)
plot(sgnl, 'RefLn', sgnl_clr, 2, plot.style_linebr)

hline(0, 'Zero', color.new(color.gray, 50), hline.style_solid, editable = false)

// EoF