// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © AlgoTrader_Pro

//@version=6

// @description: Multiple moving averages utilidies
library('movingAveragesUtilities', true)
import AlgoTrader_Pro/formattingUtilities/12 as fu
import AlgoTrader_Pro/dataTableUtilities/13 as du

// CONSTANTS
//----------------
color COLOR_UP = color.green
color COLOR_DOWN = color.red
color COLOR_TRANSP = color.new(color.gray, 100)
color COLOR_NEUTRAL = color.gray

int FAST_LINE_WIDTH = 1
int MEDIUM_LINE_WIDTH = 3
int SLOW_LINE_WIDTH = 5
int LOOKBACK_DIV = 5
int BARS_TO_RIGHT = 5

var GROUP_MOVING_AVERAGES = 'MOVING AVERAGES ================================'
var GROUP_DATATABLE = 'DATA TABLE ====================================='
var DATATABLE_TITLE = 'MOVING AVERAGES'
string MA_TYPE = 'Exponential'

dataTable_map = map.new<string, string>()

// INPUTS 
//-------------------
float source_input = input.source(close, 'Source', group = GROUP_MOVING_AVERAGES)
bool show_fast_mas_input = input.bool(false, 'Fast', inline = 'fast', group = GROUP_MOVING_AVERAGES)
bool show_medium_mas_input = input.bool(false, 'Medium', inline = 'medium', group = GROUP_MOVING_AVERAGES)
bool show_slow_mas_input = input.bool(true, 'Slow', inline = 'slow', group = GROUP_MOVING_AVERAGES)
int length_fast_input = input.int(50, '| Length', inline = 'fast', group = GROUP_MOVING_AVERAGES)
int length_medium_input = input.int(100, '| Length', inline = 'medium', group = GROUP_MOVING_AVERAGES)
int length_slow_input = input.int(200, '| Length', inline = 'slow', group = GROUP_MOVING_AVERAGES)
int ma_transparency_input = input.int(50, 'Transparency', minval = 0, maxval = 100, group = GROUP_MOVING_AVERAGES)
bool plot_labels_input = input.bool(true, 'Plot Labels', group = GROUP_MOVING_AVERAGES, inline = 'lbls')
string with_levels_input = input.string('with Levels', '', options = ['with Levels', 'without Levels'], group = GROUP_MOVING_AVERAGES, inline = 'lbls')
bool show_data_table_input = input.bool(true, 'Show Data Table', group = GROUP_DATATABLE)
string tableYpos_input = input.string('Middle', 'Position', inline = 'p', options = ['Top', 'Middle', 'Bottom'], group = GROUP_DATATABLE)
string tableXpos_input = input.string('Right', '', inline = 'p', options = ['Left', 'Center', 'Right'], group = GROUP_DATATABLE)
string table_textSize_input = input.string('Small', 'Text Size', options = ['Auto', 'Tiny', 'Small', 'Normal'], group = GROUP_DATATABLE)

// FUNCTIONS 
//-------------------
plot_sideLabel(bars_to_right, y, txt, label_color) =>

    label.new(x = bar_index + bars_to_right, y = y, text = txt, xloc = xloc.bar_index, yloc = yloc.price, color = COLOR_TRANSP, style = label.style_label_left, textcolor = label_color, size = size.small, textalign = text.align_left)
get_moving_averages(source, length_fast_input, length_medium_input, length_slow_input, ma_type_input) =>
    float ma_fast = 0.0
    float ma_med = 0.0
    float ma_slow = 0.0

    if ma_type_input == 'Simple'
        ma_fast := ta.sma(source, length_fast_input)
        ma_med := ta.sma(source, length_medium_input)
        ma_slow := ta.sma(source, length_slow_input)
        ma_slow
    else if ma_type_input == 'Exponential'
        ma_fast := ta.ema(source, length_fast_input)
        ma_med := ta.ema(source, length_medium_input)
        ma_slow := ta.ema(source, length_slow_input)
        ma_slow

    [ma_fast, ma_med, ma_slow]

get_color_by_direction(source, lookback, col_up, col_dn, transp) =>
    col_p = source > source[lookback] ? col_up : source < source[lookback] ? col_dn : COLOR_NEUTRAL
    col = color.new(col_p, transp)
    col
get_mas_dataTable(dataTable_map, direction_flag, comment_txt) =>

    // Define the color for the direction 
    color_1_txt__0 = str.lower(direction_flag)
    color_1_txt = switch color_1_txt__0
        'long' => 'green'
        'short' => 'red'
        'neutral' => 'yellow'

    dataTable_map.put('sub_title', '')

    dataTable_map.put('item_1', 'Direction')
    dataTable_map.put('data_1', direction_flag)
    dataTable_map.put('comment_1', comment_txt)
    dataTable_map.put('color_1', color_1_txt)



    dataTable_map

get_direction_flag(ma_fast, ma_med, ma_slow) =>

    long = ma_fast > ma_med and ma_med > ma_slow

    short = ma_fast < ma_med and ma_med < ma_slow

    direction_flag = long ? 'Long' : short ? 'Short' : 'Neutral'

    comment_txt = long ? 'All averages bullish' : short ? 'All averages bearish' : ''


    [direction_flag, comment_txt]

plot_labels(show_fast_mas_input, show_medium_mas_input, show_slow_mas_input, ma_fast, ma_med, ma_slow, fast_ma_color, medium_ma_color, slow_ma_color, include_levels) =>

    if barstate.islast

        // Delet old labels 
        for lb in label.all
            lb.delete()

        // Plot the new labels
        if show_fast_mas_input

            txt = 'MA Fast'
            txt := include_levels ? txt + ': ' + fu.toCurrencyString(ma_fast, 1) : txt
            plot_sideLabel(BARS_TO_RIGHT, ma_fast, txt, fast_ma_color)

        if show_medium_mas_input

            txt = 'MA Medium'
            txt := include_levels ? txt + ': ' + fu.toCurrencyString(ma_med, 1) : txt
            plot_sideLabel(BARS_TO_RIGHT, ma_med, txt, medium_ma_color)

        if show_slow_mas_input

            txt = 'MA Slow'
            txt := include_levels ? txt + ': ' + fu.toCurrencyString(ma_slow, 1) : txt
            plot_sideLabel(BARS_TO_RIGHT, ma_slow, txt, slow_ma_color)

get_movingAverages_color(ma_fast, ma_med, ma_slow, length_slow, length_medium, length_fast, ma_transparency) =>

    // Determine lookback periods for moving averages
    int ma_slow_lookback = int(math.round(length_slow / LOOKBACK_DIV, 0))
    int ma_medium_lookback = int(math.round(length_medium / LOOKBACK_DIV, 0))
    int ma_fast_lookback = int(math.round(length_fast / LOOKBACK_DIV, 0))

    // Get moving averages colors
    fast_ma_color = get_color_by_direction(ma_fast, ma_fast_lookback, COLOR_UP, COLOR_DOWN, ma_transparency)
    medium_ma_color = get_color_by_direction(ma_med, ma_medium_lookback, COLOR_UP, COLOR_DOWN, ma_transparency)
    slow_ma_color = get_color_by_direction(ma_slow, ma_slow_lookback, COLOR_UP, COLOR_DOWN, ma_transparency)

    [fast_ma_color, medium_ma_color, slow_ma_color]

get_movingAverages_levelsMap(ma_fast, ma_med, ma_slow) =>

    levelsMap = map.new<string, float>()

    levelsMap.put('ma_fast', ma_fast)
    levelsMap.put('ma_med', ma_med)
    levelsMap.put('ma_slow', ma_slow)

    levelsMap


// @function: 							Fetches the data for moving averages
// @param source (float): 				Source for the moving averages
// @param length_fast (int): 			Fast moving average length
// @param length_medium (int): 			Medium moving average length
// @param length_slow (int): 			Slow moving average length
// @returns: 							Returns a map with the levels, plus direction flag and the data table 
export get_movingAverages_data(float source, int length_fast, int length_medium, int length_slow) =>

    // Get Moving Averages
    [ma_fast, ma_med, ma_slow] = get_moving_averages(source, length_fast, length_medium, length_slow, MA_TYPE)

    // Get direction flag 
    [direction_flag, comment_txt] = get_direction_flag(ma_fast, ma_med, ma_slow)

    // Get the data table
    data_table_map = map.new<string, string>()
    data_table_map := get_mas_dataTable(data_table_map, direction_flag, comment_txt)

    // Get map with levels
    movingAverages_levelsMap = get_movingAverages_levelsMap(ma_fast, ma_med, ma_slow)

    [movingAverages_levelsMap, direction_flag, data_table_map]

// @function: 						Generates de color for the moving averages lines
// @param ma_fast (float): 			Moving average fast
// @param ma_med (float): 			Moving average medium
// @param ma_slow (float): 			Moving average slow
// @param length_slow (int): 		Slow moving average length
// @param length_medium (int): 		Medium moving average length
// @param length_fast (int): 		Fast moving average length
// @param ma_transparency (int): 	Transparency for the moving average line
// @returns: 						Returns three colors
export get_mas_color(float ma_fast, float ma_med, float ma_slow, int length_slow, int length_medium, int length_fast, int ma_transp) =>

    [fast_ma_color, medium_ma_color, slow_ma_color] = get_movingAverages_color(ma_fast, ma_med, ma_slow, length_slow, length_medium, length_fast, ma_transp)

    [fast_ma_color, medium_ma_color, slow_ma_color]

// CALCULATIONS
//----------------------

// Set flag for with or without levels
include_levels = switch with_levels_input
    'with Levels' => true
    'without Levels' => false

// Get Moving Averages
[ma_fast, ma_med, ma_slow] = get_moving_averages(source_input, length_fast_input, length_medium_input, length_slow_input, MA_TYPE)

// Get direction flag 
[direction_flag, comment_txt] = get_direction_flag(ma_fast, ma_med, ma_slow)

// Show the data table
if show_data_table_input
    dataTable_map := get_mas_dataTable(dataTable_map, direction_flag, comment_txt)
    du.generate_dataTable(dataTable_map, DATATABLE_TITLE, tableYpos_input, tableXpos_input, table_textSize_input)


// PLOTS
//----------------------

[fast_ma_color, medium_ma_color, slow_ma_color] = get_movingAverages_color(ma_fast, ma_med, ma_slow, length_slow_input, length_medium_input, length_fast_input, ma_transparency_input)

// Plot moving averages
plot(ma_fast, title = 'Fast MA', color = fast_ma_color, linewidth = math.max(1, FAST_LINE_WIDTH), display = show_fast_mas_input ? display.all : display.none)
plot(ma_med, title = 'Medium MA', color = medium_ma_color, linewidth = math.max(1, MEDIUM_LINE_WIDTH), display = show_medium_mas_input ? display.all : display.none)
plot(ma_slow, title = 'Slow MA', color = slow_ma_color, linewidth = math.max(1, SLOW_LINE_WIDTH), display = show_slow_mas_input ? display.all : display.none)

// Plot Labels
if plot_labels_input
    plot_labels(show_fast_mas_input, show_medium_mas_input, show_slow_mas_input, ma_fast, ma_med, ma_slow, fast_ma_color, medium_ma_color, slow_ma_color, include_levels)
