// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © Trendoscope Pty Ltd, Trendoscope®
//                                       ░▒
//                                  ▒▒▒   ▒▒
//                              ▒▒▒▒▒     ▒▒
//                      ▒▒▒▒▒▒▒░     ▒     ▒▒
//                  ▒▒▒▒▒▒           ▒     ▒▒
//             ▓▒▒▒       ▒        ▒▒▒▒▒▒▒▒▒▒▒
//   ▒▒▒▒▒▒▒▒▒▒▒ ▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
//   ▒  ▒       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
//   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒
//   ▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒
//    ▒▒▒▒▒         ▒▒▒▒▒▒▒
//                 ▒▒▒▒▒▒▒▒▒
//                ▒▒▒▒▒ ▒▒▒▒▒
//               ░▒▒▒▒   ▒▒▒▒▓      ████████╗██████╗ ███████╗███╗   ██╗██████╗  ██████╗ ███████╗ ██████╗ ██████╗ ██████╗ ███████╗
//              ▓▒▒▒▒     ▒▒▒▒      ╚══██╔══╝██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
//              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒        ██║   ██████╔╝█████╗  ██╔██╗ ██║██║  ██║██║   ██║███████╗██║     ██║   ██║██████╔╝█████╗
//             ▒▒▒▒▒       ▒▒▒▒▒       ██║   ██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██║   ██║╚════██║██║     ██║   ██║██╔═══╝ ██╔══╝
//            ▒▒▒▒▒         ▒▒▒▒▒      ██║   ██║  ██║███████╗██║ ╚████║██████╔╝╚██████╔╝███████║╚██████╗╚██████╔╝██║     ███████╗
//             ▒▒             ▒                      
//@version=6
//lib-version: 1
// @description Collection of complex data structures not generally present as part of pinescript and can be used for collection and transformation of the data
library('datastructures', overlay = true)

//@type Set implementation using map
//@field strSet map of string to bool
export type StringSet
	map<string, bool> strSet

// @function initialise StringSet
// @param this StringSet to be initialised
// @returns current object of StringSet
export method init(StringSet this) =>
    this.strSet := map.new<string, bool>()
    this

// @function add value to StringSet
// @param this StringSet object
// @value the key of stringset to be set
// @returns current object of StringSet
export method add(StringSet this, string value) =>
    if na(this.strSet)
        this.init()
    this.strSet.put(value, true)
    this

// @function clear StringSet contents
// @param this StringSet object
// @returns current object of StringSet
export method clear(StringSet this) =>
    if na(this.strSet)
        this.init()
    this.strSet.clear()
    this

// @function remove value from StringSet
// @param this StringSet object
// @value the key of stringset to be removed
// @returns current object of StringSet
export method remove(StringSet this, string value) =>
    if na(this.strSet)
        this.init()
    this.strSet.remove(value)
    this

// @function get size of the StringSet
// @param this StringSet object
// @returns size of StringSet map
export method size(StringSet this) =>
    if na(this.strSet)
        this.init()
    this.strSet.size()

// @function check if stringset is empty
// @param this StringSet object
// @returns true if empty else returns false
export method isEmpty(StringSet this) =>
    if na(this.strSet)
        this.init()
    this.strSet.size() == 0

// @function get values of the StringSet
// @param this StringSet object
// @returns values of StringSet
export method iterator(StringSet this) =>
    if na(this.strSet)
        this.init()
    this.strSet.keys()

// @function check if value is present in StringSet
// @param this StringSet object
// @returns true if Value is present. False otherwise
export method contains(StringSet this, string value) =>
    if na(this.strSet)
        this.init()
    this.strSet.contains(value)

//@type type containing map of int to int
//@field count map of int to int used for counting
export type Count
	map<int, int> count

//@type custom type to enable array of array of int
//@field values int array
export type Ints
	array<int> values

//@type custom type to enable array of array of float
//@field values float array
export type Floats
	array<float> values

//@type type containing map of int to int array
//@field vmap map of int to Ints used as counting collection
export type MapToInts
	map<int, Ints> vmap

//@type type containing map of int to float array
//@field vmap map of int to Floats used as floating stat collection
export type MapToFloats
	map<int, Floats> vmap

// @function Initialise a new map of string to Count
// @param types array of string containing map keys
// @param numberOfStates number of items to be tracked for each type
// @returns new map<string, Count>() with empty initialisation
export method initialiseCountMap(array<string> types, int numberOfStates) =>
    countMap = map.new<string, Count>()
    valueMap = map.new<int, int>()
    for i = 0 to numberOfStates > 0 ? numberOfStates - 1 : na by 1
        valueMap.put(i, 0)
    for t in types
        countMap.put(t, Count.new(valueMap.copy()))
    countMap.put('All', Count.new(valueMap))
    countMap

// @function Initialise a new map of string to Count
// @param types map containing types and configurable boolean flag
// @param numberOfStates number of items to be tracked for each type
// @returns new map<string, Count>() with empty initialisation
export method initialiseCountMap(map<string, bool> types, int numberOfStates) =>
    countMap = map.new<string, Count>()
    valueMap = map.new<int, int>()
    for i = 0 to numberOfStates > 0 ? numberOfStates - 1 : na by 1
        valueMap.put(i, 0)
    for [t, flag] in types
        if flag
            countMap.put(t, Count.new(valueMap.copy()))
    countMap.put('All', Count.new(valueMap))
    countMap

// @function get count based on primary string key and secondary int key
// @param this map of string to to Count
// @param key primary key
// @param n secondary key
// @returns derived count from map of map
export method get(map<string, Count> this, string key, int n) =>
    this.get(key).count.get(n)

// @function set count for specific primary and secondary key
// @param this map of string to to Count
// @param key primary string key
// @param n secondary int key
// @param value the new count value to be set
// @returns updated value for key and n
export method set(map<string, Count> this, string key, int n, int value) =>
    this.get(key).count.put(n, value)

// @function increment count for specific primary and secondary key
// @param this map of string to to Count
// @param key primary string key
// @param n secondary int key
// @returns incremented value
export method increment(map<string, Count> this, string key, int n) =>
    this.set(key, n, this.get(key, n) + 1)

populateMapToInts(int numberOfStates) =>
    ar = map.new<int, Ints>()
    for i = 0 to numberOfStates > 0 ? numberOfStates - 1 : na by 1
        ar.put(i, Ints.new(array.new<int>()))
    ar

populateMapToFloats(int numberOfStates) =>
    ar = map.new<int, Floats>()
    for i = 0 to numberOfStates > 0 ? numberOfStates - 1 : na by 1
        ar.put(i, Floats.new(array.new<float>()))
    ar

// @function Initialise a new map of string to Map to Ints
// @param types array of string containing map keys
// @param numberOfStates number of items to be tracked for each type
// @returns new map<string, MapToInts>() with empty initialisation
export method initialiseIntsMap(array<string> types, int numberOfStates) =>
    mp = map.new<string, MapToInts>()
    for t in types
        mp.put(t, MapToInts.new(populateMapToInts(numberOfStates)))
    mp.put('All', MapToInts.new(populateMapToInts(numberOfStates)))
    mp

// @function Initialise a new map of string to Map to Ints
// @param types map with boolean flag
// @param numberOfStates number of items to be tracked for each type
// @returns new map<string, MapToInts>() with empty initialisation
export method initialiseIntsMap(map<string, bool> types, int numberOfStates) =>
    mp = map.new<string, MapToInts>()
    for [t, flag] in types
        if flag
            mp.put(t, MapToInts.new(populateMapToInts(numberOfStates)))
    mp.put('All', MapToInts.new(populateMapToInts(numberOfStates)))
    mp

// @function get array of int associated with key and n
// @param this map of string to to MapToInts
// @param key primary string key
// @param n secondary int key
// @returns derived array of int for the given key combination
export method get(map<string, MapToInts> this, string key, int n) =>
    this.get(key).vmap.get(n).values

// @function Initialise a new map of string to Map to Floats
// @param types array of string containing map keys
// @param numberOfStates number of items to be tracked for each type
// @returns new map<string, MapToFloats>() with empty initialisation
export method initialiseFloatsMap(array<string> types, int numberOfStates) =>
    mp = map.new<string, MapToFloats>()
    for t in types
        mp.put(t, MapToFloats.new(populateMapToFloats(numberOfStates)))
    mp.put('All', MapToFloats.new(populateMapToFloats(numberOfStates)))
    mp

// @function Initialise a new map of string to Map to Floats
// @param types map with boolean flag
// @param numberOfStates number of items to be tracked for each type
// @returns new map<string, MapToFloats>() with empty initialisation
export method initialiseFloatsMap(map<string, bool> types, int numberOfStates) =>
    mp = map.new<string, MapToFloats>()
    for [t, flag] in types
        if flag
            mp.put(t, MapToFloats.new(populateMapToFloats(numberOfStates)))
    mp.put('All', MapToFloats.new(populateMapToFloats(numberOfStates)))
    mp

// @function get array of float associated with key and n
// @param this map of string to to MapToFloats
// @param key primary string key
// @param n secondary int key
// @returns derived array of float
export method get(map<string, MapToFloats> this, string key, int n) =>
    this.get(key).vmap.get(n).values


// @function Initialise map of two dimentional Ints based on types and number of states
// @param types types array for which a new Map to Ints to be created
// @param numberOfStates number of states for which the Ints needs to be initialised
// @returns new map of string to two dimension array of int (Ints)
export method initialiseMapOfInts(array<string> types, int numberOfStates) =>
    mapToInts = map.new<string, Ints>()
    for t in types
        mapToInts.put(t, Ints.new(array.new<int>(numberOfStates, 0)))
    mapToInts.put('All', Ints.new(array.new<int>(numberOfStates, 0)))
    mapToInts

// @function Initialise map of two dimentional Ints based on types and number of states
// @param types types map for which a new Map to Ints to be created along with bool flag
// @param numberOfStates number of states for which the Ints needs to be initialised
// @returns new map of string to two dimension array of int (Ints)
export method initialiseMapOfInts(map<string, bool> types, int numberOfStates) =>
    mapToInts = map.new<string, Ints>()
    for [t, flag] in types
        if flag
            mapToInts.put(t, Ints.new(array.new<int>(numberOfStates, 0)))
    mapToInts.put('All', Ints.new(array.new<int>(numberOfStates, 0)))
    mapToInts

// @function get values of Ints based on key
// @param this map of string to Ints
// @param key string key
// @returns values inside Ints object associated in the map
export method get(map<string, Ints> this, string key) =>
    this.get(key).values

// @function intcrement the value of Ints based on key and n (secondary key)
// @param this map of string to Ints
// @param key string key
// @param n secondary int key
// @returns incremented nth object of Ints associated with key
export method increment(map<string, Ints> this, string key, int n) =>
    this.get(key).set(n, this.get(key).get(n) + 1)
