// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © Trendoscope Pty Ltd, Trendoscope®
//                                       ░▒
//                                  ▒▒▒   ▒▒
//                              ▒▒▒▒▒     ▒▒
//                      ▒▒▒▒▒▒▒░     ▒     ▒▒
//                  ▒▒▒▒▒▒           ▒     ▒▒
//             ▓▒▒▒       ▒        ▒▒▒▒▒▒▒▒▒▒▒
//   ▒▒▒▒▒▒▒▒▒▒▒ ▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
//   ▒  ▒       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
//   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒
//   ▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒
//    ▒▒▒▒▒         ▒▒▒▒▒▒▒
//                 ▒▒▒▒▒▒▒▒▒
//                ▒▒▒▒▒ ▒▒▒▒▒
//               ░▒▒▒▒   ▒▒▒▒▓      ████████╗██████╗ ███████╗███╗   ██╗██████╗  ██████╗ ███████╗ ██████╗ ██████╗ ██████╗ ███████╗
//              ▓▒▒▒▒     ▒▒▒▒      ╚══██╔══╝██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
//              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒        ██║   ██████╔╝█████╗  ██╔██╗ ██║██║  ██║██║   ██║███████╗██║     ██║   ██║██████╔╝█████╗
//             ▒▒▒▒▒       ▒▒▒▒▒       ██║   ██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██║   ██║╚════██║██║     ██║   ██║██╔═══╝ ██╔══╝
//            ▒▒▒▒▒         ▒▒▒▒▒      ██║   ██║  ██║███████╗██║ ╚████║██████╔╝╚██████╔╝███████║╚██████╗╚██████╔╝██║     ███████╗
//             ▒▒             ▒
//@version=6
// @description Library helps visualize matrix as array of arrays and enables users to use array methods such as push, pop, shift, unshift etc along with cleanup activities on drawing objects wherever required
library('_matrix', overlay = true)
import Trendoscope/arrays/2 as pa
remove_row_from_matrix(mtx, rowNumber) => matrix.remove_row(mtx, rowNumber)
delete_row_from_matrix(mtx, rowNumber) => remove_row_from_matrix(mtx, rowNumber).flush()

unshift_to_matrix(mtx, row, maxItems) =>
    matrix.add_row(mtx, 0, row)
    if matrix.rows(mtx) > maxItems
        delete_row_from_matrix(mtx, matrix.rows(mtx) - 1)
    mtx

push_to_matrix(mtx, row, maxItems) =>
    matrix.add_row(mtx, matrix.rows(mtx), row)
    if matrix.rows(mtx) > maxItems
        delete_row_from_matrix(mtx, 0)
    mtx

// @function deletes row from a matrix
// @param mtx matrix of objects
// @param rowNumber row index to be deleted
// @returns void
export method delete(simple matrix<line> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)
export method delete(simple matrix<label> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)
export method delete(simple matrix<box> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)
export method delete(simple matrix<linefill> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)
export method delete(simple matrix<table> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)
export method delete(simple matrix<int> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)
export method delete(simple matrix<float> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)
export method delete(simple matrix<bool> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)
export method delete(simple matrix<string> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)
export method delete(simple matrix<color> mtx, int rowNumber) =>
    delete_row_from_matrix(mtx, rowNumber)

// @function remove row from a matrix and returns them to caller
// @param mtx matrix of objects
// @param rowNumber row index to be deleted
// @returns type[]
export method remove(simple matrix<line> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)
export method remove(simple matrix<label> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)
export method remove(simple matrix<box> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)
export method remove(simple matrix<linefill> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)
export method remove(simple matrix<table> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)
export method remove(simple matrix<int> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)
export method remove(simple matrix<float> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)
export method remove(simple matrix<bool> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)
export method remove(simple matrix<string> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)
export method remove(simple matrix<color> mtx, int rowNumber) =>
    remove_row_from_matrix(mtx, rowNumber)

// @function unshift array of lines to first row of the matrix
// @param mtx matrix of lines
// @param row array of lines to be inserted in row 
// @returns resulting matrix of type
export method unshift(simple matrix<line> mtx, array<line> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)
export method unshift(simple matrix<label> mtx, array<label> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)
export method unshift(simple matrix<box> mtx, array<box> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)
export method unshift(simple matrix<linefill> mtx, array<linefill> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)
export method unshift(simple matrix<table> mtx, array<table> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)
export method unshift(simple matrix<int> mtx, array<int> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)
export method unshift(simple matrix<float> mtx, array<float> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)
export method unshift(simple matrix<bool> mtx, array<bool> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)
export method unshift(simple matrix<string> mtx, array<string> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)
export method unshift(simple matrix<color> mtx, array<color> row, simple int maxItems) =>
    unshift_to_matrix(mtx, row, maxItems)


// @function push array of lines to end of the matrix row
// @param mtx matrix of lines
// @param row array of lines to be inserted in row 
// @returns resulting matrix of lines
export method push(simple matrix<line> mtx, array<line> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)
export method push(simple matrix<label> mtx, array<label> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)
export method push(simple matrix<box> mtx, array<box> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)
export method push(simple matrix<linefill> mtx, array<linefill> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)
export method push(simple matrix<table> mtx, array<table> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)
export method push(simple matrix<int> mtx, array<int> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)
export method push(simple matrix<float> mtx, array<float> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)
export method push(simple matrix<bool> mtx, array<bool> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)
export method push(simple matrix<string> mtx, array<string> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)
export method push(simple matrix<color> mtx, array<color> row, simple int maxItems) =>
    push_to_matrix(mtx, row, maxItems)

// @function shift removes first row from matrix of lines
// @param mtx matrix of lines from which the shift operation need to be performed
// @returns void
export method shift(simple matrix<line> mtx) => mtx.delete(0)
export method shift(simple matrix<label> mtx) => mtx.delete(0)
export method shift(simple matrix<box> mtx) => mtx.delete(0)
export method shift(simple matrix<linefill> mtx) => mtx.delete(0)
export method shift(simple matrix<table> mtx) => mtx.delete(0)
export method shift(simple matrix<int> mtx) => mtx.delete(0)
export method shift(simple matrix<float> mtx) => mtx.delete(0)
export method shift(simple matrix<bool> mtx) => mtx.delete(0)
export method shift(simple matrix<string> mtx) => mtx.delete(0)
export method shift(simple matrix<color> mtx) => mtx.delete(0)

// @function rshift removes first row from matrix of lines and returns them as array
// @param mtx matrix of lines from which the rshift operation need to be performed
// @returns type[]
export method rshift(simple matrix<line> mtx) =>
    mtx.remove(0)
export method rshift(simple matrix<label> mtx) =>
    mtx.remove(0)
export method rshift(simple matrix<box> mtx) =>
    mtx.remove(0)
export method rshift(simple matrix<linefill> mtx) =>
    mtx.remove(0)
export method rshift(simple matrix<table> mtx) =>
    mtx.remove(0)
export method rshift(simple matrix<int> mtx) =>
    mtx.remove(0)
export method rshift(simple matrix<float> mtx) =>
    mtx.remove(0)
export method rshift(simple matrix<bool> mtx) =>
    mtx.remove(0)
export method rshift(simple matrix<string> mtx) =>
    mtx.remove(0)
export method rshift(simple matrix<color> mtx) =>
    mtx.remove(0)

// @function pop removes last row from matrix of lines
// @param mtx matrix of lines from which the pop operation need to be performed
// @returns void
export method pop(simple matrix<line> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)
export method pop(simple matrix<label> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)
export method pop(simple matrix<box> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)
export method pop(simple matrix<linefill> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)
export method pop(simple matrix<table> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)
export method pop(simple matrix<int> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)
export method pop(simple matrix<float> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)
export method pop(simple matrix<bool> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)
export method pop(simple matrix<string> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)
export method pop(simple matrix<color> mtx) =>
    mtx.delete(matrix.rows(mtx) - 1)


// @function rpop removes last row from matrix of lines and reutnrs the array to caller
// @param mtx matrix of lines from which the rpop operation need to be performed
// @returns void
export method rpop(simple matrix<line> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)
export method rpop(simple matrix<label> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)
export method rpop(simple matrix<box> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)
export method rpop(simple matrix<linefill> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)
export method rpop(simple matrix<table> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)
export method rpop(simple matrix<int> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)
export method rpop(simple matrix<float> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)
export method rpop(simple matrix<bool> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)
export method rpop(simple matrix<string> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)
export method rpop(simple matrix<color> mtx) =>
    mtx.remove(matrix.rows(mtx) - 1)

flush_matrix(mtx) =>
    while matrix.rows(mtx) > 0
        mtx.delete(0)

clear_matrix(mtx) =>
    while matrix.rows(mtx) > 0
        mtx.remove(0)

// @function clear clears the matrix
// @param mtx matrix of lines which needs to be cleared
// @returns void
export method clear(simple matrix<line> mtx) =>
    clear_matrix(mtx)
export method clear(simple matrix<label> mtx) =>
    clear_matrix(mtx)
export method clear(simple matrix<box> mtx) =>
    clear_matrix(mtx)
export method clear(simple matrix<linefill> mtx) =>
    clear_matrix(mtx)
export method clear(simple matrix<table> mtx) =>
    clear_matrix(mtx)
export method clear(simple matrix<int> mtx) =>
    clear_matrix(mtx)
export method clear(simple matrix<float> mtx) =>
    clear_matrix(mtx)
export method clear(simple matrix<bool> mtx) =>
    clear_matrix(mtx)
export method clear(simple matrix<string> mtx) =>
    clear_matrix(mtx)
export method clear(simple matrix<color> mtx) =>
    clear_matrix(mtx)

// @function clear clears the matrix but retains the drawing objects
// @param mtx matrix of lines which needs to be cleared
// @returns void
export method flush(simple matrix<line> mtx) =>
    flush_matrix(mtx)
export method flush(simple matrix<label> mtx) =>
    flush_matrix(mtx)
export method flush(simple matrix<box> mtx) =>
    flush_matrix(mtx)
export method flush(simple matrix<linefill> mtx) =>
    flush_matrix(mtx)
export method flush(simple matrix<table> mtx) =>
    flush_matrix(mtx)
export method flush(simple matrix<int> mtx) =>
    flush_matrix(mtx)
export method flush(simple matrix<float> mtx) =>
    flush_matrix(mtx)
export method flush(simple matrix<bool> mtx) =>
    flush_matrix(mtx)
export method flush(simple matrix<string> mtx) =>
    flush_matrix(mtx)
export method flush(simple matrix<color> mtx) =>
    flush_matrix(mtx)
