// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © newartjersey

//@version=6
indicator("HOLY KDJ Long Short Signal", overlay=false)

// === Inputs ===
n1 = input.int(9, "RSV Length")
n2 = input.int(3, "K Smoothing")
n3 = input.int(3, "D Smoothing")

ob = input.int(80, "OVER BUY")
os = input.int(20, "OVER SELL")

useOI = input.bool(true, "OPEN OI none")

// === KDJ ===
ll = ta.lowest(low, n1)
hh = ta.highest(high, n1)
rsv = hh == ll ? 50 : (close - ll) / (hh - ll) * 100

k = ta.rma(rsv, n2)
d = ta.rma(k, n3)
j = 3 * k - 2 * d

// === Open Interest ===
oiSymbol = syminfo.tickerid + "_OI"
oiClose = request.security(oiSymbol, timeframe.period, close, ignore_invalid_symbol=true)

oiAvailable = useOI and not na(oiClose)

// 🟢 OI
oiBull = oiAvailable and close > close[1] and oiClose > oiClose[1]

// 🔴 OI
oiBear = oiAvailable and close < close[1] and oiClose > oiClose[1]

// ⚪ OI
oiDown = oiAvailable and oiClose < oiClose[1]

//  OI 
oiLongOK = not useOI or not oiAvailable or oiBull
oiShortOK = not useOI or not oiAvailable or oiBear

// ===  KDJ  ===
baseLongSignal = ta.crossover(k, d) and j < 50
baseShortSignal = ta.crossunder(k, d) and j > 50

baseStrongLong = ta.crossover(k, d) and j < os
baseStrongShort = ta.crossunder(k, d) and j > ob

// ===  OI ===
longSignal = baseLongSignal and oiLongOK
shortSignal = baseShortSignal and oiShortOK

strongLong = baseStrongLong and oiLongOK
strongShort = baseStrongShort and oiShortOK

// ===  KDJ  ===
plotcandle(k, d, k, d, color = k >= d ? color.rgb(32, 153, 233) : color.rgb(223, 39, 94))

// === K D J  ===
plot(k, "K", color=color.rgb(29, 197, 219, 100))
plot(d, "D", color=color.rgb(226, 21, 147, 100))
plot(j, "J", color=color.rgb(255, 255, 255, 100))

// === light ===
obLine = plot(ob, "1", color=color.rgb(230, 21, 136, 67), linewidth=4)
obLine2 = plot(90, "", color=color.rgb(233, 23, 128, 64), linewidth=4)

osLine = plot(os, "2", color=color.rgb(45, 202, 202, 49), linewidth=4)
osLine2 = plot(10, "", color=color.rgb(41, 191, 202, 52), linewidth=4)

midLine = plot(50, "3", color=color.gray, linewidth=2)

fill(obLine, obLine2, color=color.new(#ec64b3, 85))
fill(osLine, osLine2, color=color.new(#64c4d4, 85))

// === SIGHT P ===
plotshape(longSignal, title="long", text="long", style=shape.labelup, location=location.bottom, color=color.rgb(75, 199, 151, 81), textcolor=color.rgb(245, 248, 248), size=size.small)

plotshape(shortSignal, title="short", text="short", style=shape.labeldown, location=location.top, color=color.rgb(190, 61, 132, 81), textcolor=color.white, size=size.small)

plotshape(strongLong, title="s long", text="s long", style=shape.triangleup, location=location.bottom, color=color.rgb(74, 10, 221), size=size.small)

plotshape(strongShort, title="s short", text="s short", style=shape.triangledown, location=location.top, color=color.rgb(243, 82, 8, 15), size=size.small)

// === SIGHT ===
alertcondition(longSignal, title="KDJ LONG ", message="KDJ LONG SIGHT + OI C｜{{ticker}}｜TIME {{interval}}｜PRICE {{close}}")

alertcondition(shortSignal, title="KDJ SHORT ", message="KDJ SHORT SIGHT + OI C｜{{ticker}}｜TIME {{interval}}｜PRICE {{close}}")

alertcondition(strongLong, title="KDJ STRONG LONG ", message="KDJ SIGHT + OI C｜{{ticker}}｜TIME {{interval}}｜PRICE {{close}}")

alertcondition(strongShort, title="KDJ STRONG SHORT ", message="KDJ SIGHT + OI C｜{{ticker}}｜TIME {{interval}}｜PRICE {{close}}")