// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Cinnamon_Bear

//@version=5

// @description This is a personal Library of the NON built-in PineScript Moving Average function used to code indicators
library("Cinnamon_BearIndicatorsMALibrary")

//@description ////////// ---------- MOVING AVERAGES ---------- //////////

// @function Double Exponential Moving Average (DEMA)
// @param Input parameter: Source, Lenght. 
// @returns A double level of smoothing helps to follow price movements more closely while still reducing noise compared to a single EMA.
export ma_dema(series float source, simple int length) =>
	 2 * ta.ema(source, length) - ta.ema(ta.ema(source, length), length)

// @function Double Smoothed Moving Average (DSMA)
// @param Input parameter: Source, Lenght. 
// @returns A double level of smoothing helps to follow price movements more closely while still reducing noise compared to a single SMA.
export ma_dsma(series float source, simple int length) =>
	2 * ta.sma(source, length) - ta.sma(ta.sma(source, length), length)

// @function Triple Exponential Moving Average (TEMA)
// @param Input parameter: Source, Lenght. 
// @returns A Triple level of smoothing helps to follow price movements even more closely compared to a DEMA.
export ma_tema(series float source, simple int length) =>
	3 * (ta.ema(source, length) - ta.ema(ta.ema(source, length), length)) + ta.ema(ta.ema(ta.ema(source, length), length), length)

// @function Volume-Weighted Exponential Moving Average (VWEMA)
// @param Input parameter: Source, Lenght. 
// @returns  The VWEMA weights based on volume and recent price, giving more weight to periods with higher trading volumes.
export ma_vwema(series float source, simple int length) =>
	// Calculate Volume-Weighted Price
	vw_price 	= math.sum(source * volume, length) / math.sum(volume, length)
	// Calculate VWEMA
	vwema 		= ta.ema(vw_price, length)

// @function Hull Moving Average (HMA)
// @param Input parameter: Source, Lenght. 
// @returns The HMA formula combines the properties of the weighted moving average (WMA) and the exponential moving average (EMA) to achieve a smoother and more responsive curve.
export ma_hma(series float source, simple int length) =>
	3 * (ta.wma(source, length)) - 2 * (ta.wma(source, length))
	
// @function Enhanced Moving Average (EHMA)
// @param Input parameter: Source, Lenght. 
// @returns The EHMA is calculated similarly to the Hull Moving Average (HMA) but uses a different weighting factor to further improve responsiveness.
export ma_ehma(series float source, simple int length) =>
	// Caluclate WMA
	wma_half 	 = ta.wma(source, length / 2)
	wma_full 	 = ta.wma(source, length)
	// Calcolo della EHMA
	hma 		 = 2 * wma_half - wma_full
	sqtrLength 	 = math.sqrt(length)
	ehma		 = ta.wma(hma, math.round(sqtrLength))

// @function Triple Exponential Moving Average (TRIX)
// @param Input parameter: Source, Lenght. 
// @returns The TRIX is an oscillator that shows the percentage change of a triple EMA. It is designed to filter out minor price movements and display only the most significant trends. The TRIX is a momentum indicator that can help identify trends and buy or sell signals.
export ma_trix(series float source, simple int length) =>
	// Calculate the first EMA
	ema1	 = ta.ema(source, length)
	// Calculate the second EMA on the first EMA
	ema2	 = ta.ema(ema1, length)
	// Calculate the third EMA on the second EMA
	ema3	 = ta.ema(ema2, length)
	// Calculate the TRIX as the percentage change of the third EMA
	trix	 = 100 * (ema3 - ema3[1]) / ema3[1]

// @function Linear Weighted Moving Average (LSMA)
// @param Input parameter: Source, Lenght. 
// @returns A moving average that gives more weight to recent prices. It is calculated using a formula that assigns linear weights to prices, with the highest weight given to the most recent price and the lowest weight given to the furthest price in the series.
export ma_lsma(series float source, simple int length) =>
	sum_weights 		= 0.0
	weighted_sum 		= 0.0
	for i 				= 0 to length - 1
    	weight 			= length - i
    	sum_weights    := sum_weights + weight
    	weighted_sum   := weighted_sum + source[i] * weight
	lsma 			    = weighted_sum / sum_weights

// @function Weighted Cumulative Moving Average (WCMA)
// @param Input parameter: Source, Lenght. 
// @returns A moving average that gives more weight to recent prices. Compared to a LSMA, the WCMA the weights of data increase linearly with time, so the most recent data has a greater weight compared to older data. This means that the contribution of the most recent data to the moving average is more significant.
export ma_wcma(series float source, simple int length) =>
    sum_w		 = 0.0
    sum_pw 		 = 0.0
    for i		 = 0 to length - 1
        weight	 = i + 1
        sum_w 	:= sum_w + weight
        sum_pw 	:= sum_pw + weight * source[length - i - 1]
    wcma 		 = sum_pw / sum_w

// @function Variable Index Dynamic Average (VIDYA)
// @param Input parameter: Source, Lenght. 
// @returns It is an adaptive moving average that adjusts its momentum based on market volatility using the formula of Chande Momentum Oscillator (CMO) .
export ma_vidya(series float source, simple int length) =>	
	cmo 		= ta.cmo(source, length)
	// Calculate scaling factor
	factor 		= math.abs(cmo) / length
	// Calculate EMA smoothing constant
	alpha		= 2 / (length + 1)
	// Calcolare la VIDYA
	var float vidya = na
	if na(vidya[1])
    	vidya      := close
	else
    	vidya      := alpha * close + (1 - alpha) * vidya[1] * factor

// @function Zero-Lag Moving Average (ZLMA)
// @param Input parameter: Source, Lenght.
// @returns Its aims to minimize the lag typically associated with MA, designed to react more quickly to price changes.
export ma_zlma(series float source, simple int length) =>
	ema1 = ta.ema(source, length)
	ema2 = ta.ema(ema1, length)
	// Calculate the ZLMA
	zlma = 2 * ema1 - ema2

// @function Generalized Moving Average (GMA)
// @param Input parameter: Source, Lenght, Power.
// @returns It is a moving average that uses a power parameter to adjust the weight of historical data. This allows the GMA to adapt to various styles of MA.
export ma_gma(series float source, simple int length, simple int power) =>
// Function to calculate GMA
    alpha 		= 2 / (length + 1)
    weight 		= math.pow(alpha, power)
    sum_weights = 0.0
    sum_values 	= 0.0
    for i = 0 to length - 1
        current_weight = math.pow(1 - weight, i)
        sum_weights := sum_weights + current_weight
        sum_values := sum_values + current_weight * source[i]
    sum_values / sum_weights

// @function Triangular Moving Average (TMA)
// @param Input parameter: Source, Lenght. 
// @returns MA more sensitive to changes in recent data compared to the SMA, providing a moving average that better adapts to short-term price changes.
export ma_tma(series float source, simple int length) =>
	sum			= 0.0
	weight_sum 	= 0.0
	for i = 0 to length - 1
	    weight 		= i + 1
	    sum 	   := sum + source[length - i - 1] * weight
    	weight_sum := weight_sum + weight
	tma   = sum / weight_sum

////////// ---------- GET A SUMARIZED TABLE OF THE MOVING AVERAGES TYPE---------- //////////

var table myTable = table.new(position = position.middle_center, columns =  4, rows =  14, bgcolor = color.new(color.white, 30),frame_width = 2,
							  frame_color = color.aqua, border_width = 1, border_color = color.aqua)
// Get "TITLE" column
table.cell(myTable, 0, 0, "Titles")
table.cell(myTable, 0, 1, "DEMA")
table.cell(myTable, 0, 2, "DSMA")
table.cell(myTable, 0, 3, "TEMA")
table.cell(myTable, 0, 4, "VWEMA")
table.cell(myTable, 0, 5, "HMA")
table.cell(myTable, 0, 6, "EHMA")
table.cell(myTable, 0, 7, "TRIX")
table.cell(myTable, 0, 8, "LSMA")
table.cell(myTable, 0, 9, "WCMA")
table.cell(myTable, 0, 10, "VIDYA")
table.cell(myTable, 0, 11, "ZLMA")
table.cell(myTable, 0, 12, "GMA")
table.cell(myTable, 0, 13, "TMA")
//Get "DESCRIPTION" column
table.cell(myTable, 1, 0, "Descriptions")
table.cell(myTable, 1, 1, "A double level of smoothing EMA.")
table.cell(myTable, 1, 2, "A double level of smoothing SMA.")
table.cell(myTable, 1, 3, "A triple level of smoothing EMA.")
table.cell(myTable, 1, 4, "Give weights based on volume and recent price.")
table.cell(myTable, 1, 5, "Achieve a smoother and more responsive curve.")
table.cell(myTable, 1, 6, "Uses a different weighting factor compared to HMA")
table.cell(myTable, 1, 7, "Oscillator that shows the percentage change of a triple EMA.")
table.cell(myTable, 1, 8, "Formula that assigns linear weights to prices.")
table.cell(myTable, 1, 9, "Formula where the weights of data increase linearly with time.")
table.cell(myTable, 1, 10, "MA that adjusts its momentum based on market volatility.")
table.cell(myTable, 1, 11, "Aims to minimize the lag typically associated with MA.")
table.cell(myTable, 1, 12, "Uses a power parameter to adjust the weight of historical data.")
table.cell(myTable, 1, 13, "Similar to SMA but more sensitive")
//Get "INPUTS" column
table.cell(myTable, 2, 0, "Inputs")
table.cell(myTable, 2, 1, "Source, Lenght")
table.cell(myTable, 2, 2, "Source, Lenght")
table.cell(myTable, 2, 3, "Source, Lenght")
table.cell(myTable, 2, 4, "Source, Lenght")
table.cell(myTable, 2, 5, "Source, Lenght")
table.cell(myTable, 2, 6, "Source, Lenght")
table.cell(myTable, 2, 7, "Source, Lenght")
table.cell(myTable, 2, 8, "Source, Lenght")
table.cell(myTable, 2, 9, "Source, Lenght")
table.cell(myTable, 2, 10, "Source, Lenght")
table.cell(myTable, 2, 11, "Source, Lenght")
table.cell(myTable, 2, 12, "Source, Lenght, Power")
table.cell(myTable, 2, 13, "Source, Lenght")
//Get "FUNCTIONS" column
table.cell(myTable, 3, 0, "Functions")
table.cell(myTable, 3, 1, "ma_dema")
table.cell(myTable, 3, 2, "ma_dsma")
table.cell(myTable, 3, 3, "ma_tema")
table.cell(myTable, 3, 4, "ma_vwema")
table.cell(myTable, 3, 5, "ma_hma")
table.cell(myTable, 3, 6, "ma_ehma")
table.cell(myTable, 3, 7, "ma_trix")
table.cell(myTable, 3, 8, "ma_lsma")
table.cell(myTable, 3, 9, "ma_wcma")
table.cell(myTable, 3, 10, "ma_vidya")
table.cell(myTable, 3, 11, "ma_zlma")
table.cell(myTable, 3, 12, "ma_gma")
table.cell(myTable, 3, 13, "ma_tma")