// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © moebius1977
 
//@version=5

// @description Contains methods for conversion of matrices to string. 
// Supports matrices of int/float/bool/string/line/label/box/color types. 
// - toStringMx(matrix) - converts matrix to a string matrix by applying toS to each of its elements
// - toS(matrix) - converts the matrix to a string matrix (using toStringMx()) and outputs as string using str.tostring(matrix)
library("ToStringMx", overlay = false)
import moebius1977/ToS/1

// ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
// ┃                          toStringMx()  FUNCTIONS                             ┃ {

// ━━━━━━ _toStringMatrix(<this, index_from, index_to, separator, format, _truncate) ━━━━━━ {
//{
//{
// @function Returns a string matrix made of original matrix items converted to string with toS().
// @param format (string) Like in str.format() with some shorthand options:
// ```
// --- number ---
// - "" 						 => "{0}"
// - "number"                    => "{0}"
// - "0"                         => "{0, number, 0       }"
// - "0.0"                       => "{0, number, 0.0      }"
// - "0.00"                      => "{0, number, 0.00     }"
// - "0.000"                     => "{0, number, 0.000    }"
// - "0.0000"                    => "{0, number, 0.0000   }"
// - "0.00000"                   => "{0, number, 0.00000  }"
// - "0.000000"                  => "{0, number, 0.000000 }"
// - "0.0000000"                 => "{0, number, 0.0000000}"
// --- date ---           	                       
// - "date"                      => "{0, date, dd.MM.YY}"
// - "date : time"               => "{0, date, dd.MM.YY} : {0, time, HH.mm.ss}"
// - "dd.MM"                     => "{0, date, dd:MM}"
// - "dd"                        => "{0, date, dd}"
// - "... <date> ... " in any place is substituted with "{0, date, dd.MM.YY}" 
// --- time ---           	                       
// - "time"                      => "{0, time, HH:mm:ss}"
// - "HH:mm"                     => "{0, time, HH:mm}"
// - "mm:ss"                     => "{0, time, mm:ss}"
// - "date time"                 => "{0, date, dd.MM.YY\} {0, time, HH.mm.ss}"
// - "date, time"                => "{0, date, dd.MM.YY\}, {0, time, HH.mm.ss}"
// - "date,time"                 => "{0, date, dd.MM.YY\},{0, time, HH.mm.ss}"
// - "date\ntime"                => "{0, date, dd.MM.YY\}\n{0, time, HH.mm.ss}"
// - "... <time> ... " in any place is substituted with "{0, time, HH.mm.ss}" 
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.
_toStringMx(mx, string format = "", string nz = na) =>
    if na(mx)
        runtime.error("toStringMx: matrix is na")
    rs = mx.rows()
    cs = mx.columns()
	mxS = matrix.new<string>(rs, cs ,na)
    if rs > 0     
        while rs > 0  
            rs-=1 
            cs1 = cs
            while cs1 >0 
                cs1-=1    
                mxS.set( rs, cs1, ToS.toS(mx.get(rs, cs1), format, nz)    )
	mxS
// END OF _toStringMx() }

// ━━━━━━ toStringMx(matrix<bool> , format, nz) ━━━━━━ {
// @function Returns a string matrix made of original matrix items converted to string with toS().
// @param format (string) Like in str.format() 
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.
export method toStringMx(matrix<bool>     mx, string format = "", string nz = na) => _toStringMx(mx, format, nz)
//}

// ━━━━━━ toStringMx(matrix<int> , format, nz) ━━━━━━ {
//{
//{
// @function Returns a string matrix made of original matrix items converted to string with toS().
// @param format (string) Like in str.format() with some shorthand options:
// ```
// --- number ---
// - "" 						 => "{0}"
// - "number"                    => "{0}"
// - "0"                         => "{0, number, 0       }"
// - "0.0"                       => "{0, number, 0.0      }"
// - "0.00"                      => "{0, number, 0.00     }"
// - "0.000"                     => "{0, number, 0.000    }"
// - "0.0000"                    => "{0, number, 0.0000   }"
// - "0.00000"                   => "{0, number, 0.00000  }"
// - "0.000000"                  => "{0, number, 0.000000 }"
// - "0.0000000"                 => "{0, number, 0.0000000}"
// --- date ---           	                       
// - "date"                      => "{0, date, dd.MM.YY}"
// - "date : time"               => "{0, date, dd.MM.YY} : {0, time, HH.mm.ss}"
// - "dd.MM"                     => "{0, date, dd:MM}"
// - "dd"                        => "{0, date, dd}"
// - "... <date> ... " in any place is substituted with "{0, date, dd.MM.YY}" 
// --- time ---           	                       
// - "time"                      => "{0, time, HH:mm:ss}"
// - "HH:mm"                     => "{0, time, HH:mm}"
// - "mm:ss"                     => "{0, time, mm:ss}"
// - "date time"                 => "{0, date, dd.MM.YY\} {0, time, HH.mm.ss}"
// - "date, time"                => "{0, date, dd.MM.YY\}, {0, time, HH.mm.ss}"
// - "date,time"                 => "{0, date, dd.MM.YY\},{0, time, HH.mm.ss}"
// - "date\ntime"                => "{0, date, dd.MM.YY\}\n{0, time, HH.mm.ss}"
// - "... <time> ... " in any place is substituted with "{0, time, HH.mm.ss}" 
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.
export method toStringMx(matrix<int>      mx, string format = "", string nz = na) => _toStringMx(mx, format, nz)
//}

// ━━━━━━ toStringMx(matrix<float> , format, nz) ━━━━━━ {
//{
//{
// @function Returns a string matrix made of original matrix items converted to string with toS().
// @param format (string) Like in str.format() with some shorthand options:
// ```
// --- number ---
// - "" 						 => "{0}"
// - "number"                    => "{0}"
// - "0"                         => "{0, number, 0       }"
// - "0.0"                       => "{0, number, 0.0      }"
// - "0.00"                      => "{0, number, 0.00     }"
// - "0.000"                     => "{0, number, 0.000    }"
// - "0.0000"                    => "{0, number, 0.0000   }"
// - "0.00000"                   => "{0, number, 0.00000  }"
// - "0.000000"                  => "{0, number, 0.000000 }"
// - "0.0000000"                 => "{0, number, 0.0000000}"
// --- date ---           	                       
// - "date"                      => "{0, date, dd.MM.YY}"
// - "date : time"               => "{0, date, dd.MM.YY} : {0, time, HH.mm.ss}"
// - "dd.MM"                     => "{0, date, dd:MM}"
// - "dd"                        => "{0, date, dd}"
// - "... <date> ... " in any place is substituted with "{0, date, dd.MM.YY}" 
// --- time ---           	                       
// - "time"                      => "{0, time, HH:mm:ss}"
// - "HH:mm"                     => "{0, time, HH:mm}"
// - "mm:ss"                     => "{0, time, mm:ss}"
// - "date time"                 => "{0, date, dd.MM.YY\} {0, time, HH.mm.ss}"
// - "date, time"                => "{0, date, dd.MM.YY\}, {0, time, HH.mm.ss}"
// - "date,time"                 => "{0, date, dd.MM.YY\},{0, time, HH.mm.ss}"
// - "date\ntime"                => "{0, date, dd.MM.YY\}\n{0, time, HH.mm.ss}"
// - "... <time> ... " in any place is substituted with "{0, time, HH.mm.ss}" 
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.
export method toStringMx(matrix<float>    mx, string format = "", string nz = na) => _toStringMx(mx, format, nz)
//}

// ━━━━━━ toStringMx(matrix<string> , format, nz) ━━━━━━ {
// @function Returns a string matrix made of original matrix items converted to string with toS().
// @param format (string) Like in str.format() 
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.
export method toStringMx(matrix<string>   mx, string format = "", string nz = na) => _toStringMx(mx, format, nz)
//}

// ━━━━━━ toStringMx(matrix<color> , format, nz) ━━━━━━ {
// @function Returns a string matrix made of original matrix items converted to string with toS().
// @param format (string) "HEX" (default) or "RGB"
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.
export method toStringMx(matrix<color >   mx, string format = "HEX", string nz = na) => _toStringMx(mx, format, nz)
//}

// ━━━━━━ toStringMx(matrix<line> , format, nz) ━━━━━━ {
// @function Returns a string matrix made of original matrix items converted to string with toS().
// @param format (string) (Optional) Format string. By default "{0}: {1}" if showIDs = true or "{1}" otherwise. (use "{0}" as a placeholder for id and "{1}" for item value)
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.
export method toStringMx(matrix<line>     mx, string format = "", string nz = na) => _toStringMx(mx, format, nz)
//}

// ━━━━━━ toStringMx(matrix<label> , format, nz) ━━━━━━ {
// @function Returns a string matrix made of original matrix items converted to string with toS().
// @param format (string) (Optional) Format string. By default "{0}: {1}" if showIDs = true or "{1}" otherwise. (use "{0}" as a placeholder for id and "{1}" for item value)
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.
export method toStringMx(matrix<label>    mx, string format = "", string nz = na) => _toStringMx(mx, format, nz)
//}

// ━━━━━━ toStringMx(matrix<box> , format, nz) ━━━━━━ {
// @function Returns a string matrix made of original matrix items converted to string with toS().
// @param format (string) (Optional) Format string. By default "{0}: {1}" if showIDs = true or "{1}" otherwise. (use "{0}" as a placeholder for id and "{1}" for item value)
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.
export method toStringMx(matrix<box>      mx, string format = "", string nz = na) => _toStringMx(mx, format, nz)
//}


// ^^^ END OF toStringMx() FUNCTIONS }
// ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ 

// ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
// ┃                          toS(matrix)  FUNCTIONS                              ┃ {

// ━━━━━━ toS(matrix<bool> , format, nz) ━━━━━━ {
// @function Converts each element of the matrix to string outputs using str.tostring(matrix)  
// @param this (matrix) Matrix to be converted to string
// @param format (string) Format string as in str.format() 
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.export method toS(matrix<float> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
export method toS(matrix<bool> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
//}

// // ━━━━━━ toS(matrix<int> , format, nz) ━━━━━━ {
// //{
// //{
// // @function Converts each element of the matrix to string outputs using str.tostring(matrix)  
// // @param this (matrix) Matrix to be converted to string
// // @param format (string) Like in str.format() with some shorthand options:
// // ```
// // --- number ---
// // - "" 						 => "{0}"
// // - "number"                    => "{0}"
// // - "0"                         => "{0, number, 0       }"
// // - "0.0"                       => "{0, number, 0.0      }"
// // - "0.00"                      => "{0, number, 0.00     }"
// // - "0.000"                     => "{0, number, 0.000    }"
// // - "0.0000"                    => "{0, number, 0.0000   }"
// // - "0.00000"                   => "{0, number, 0.00000  }"
// // - "0.000000"                  => "{0, number, 0.000000 }"
// // - "0.0000000"                 => "{0, number, 0.0000000}"
// // --- date ---           	                       
// // - "date"                      => "{0, date, dd.MM.YY}"
// // - "date : time"               => "{0, date, dd.MM.YY} : {0, time, HH.mm.ss}"
// // - "dd.MM"                     => "{0, date, dd:MM}"
// // - "dd"                        => "{0, date, dd}"
// // - "... <date> ... " in any place is substituted with "{0, date, dd.MM.YY}" 
// // --- time ---           	                       
// // - "time"                      => "{0, time, HH:mm:ss}"
// // - "HH:mm"                     => "{0, time, HH:mm}"
// // - "mm:ss"                     => "{0, time, mm:ss}"
// // - "date time"                 => "{0, date, dd.MM.YY\} {0, time, HH.mm.ss}"
// // - "date, time"                => "{0, date, dd.MM.YY\}, {0, time, HH.mm.ss}"
// // - "date,time"                 => "{0, date, dd.MM.YY\},{0, time, HH.mm.ss}"
// // - "date\ntime"                => "{0, date, dd.MM.YY\}\n{0, time, HH.mm.ss}"
// // - "... <time> ... " in any place is substituted with "{0, time, HH.mm.ss}" 
// // @param nz (string) If val is na and nz is not na the value of nz param is returned instead.export method toS(matrix<float> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
// export method toS(matrix<int> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
// //}

// ━━━━━━ toS(matrix<float> , format, nz) ━━━━━━ {
//{
//{
// @function Converts each element of the matrix to string outputs using str.tostring(matrix)  
// @param this (matrix) Matrix to be converted to string
// @param format (string) Like in str.format() with some shorthand options:
// ```
// --- number ---
// - "" 						 => "{0}"
// - "number"                    => "{0}"
// - "0"                         => "{0, number, 0       }"
// - "0.0"                       => "{0, number, 0.0      }"
// - "0.00"                      => "{0, number, 0.00     }"
// - "0.000"                     => "{0, number, 0.000    }"
// - "0.0000"                    => "{0, number, 0.0000   }"
// - "0.00000"                   => "{0, number, 0.00000  }"
// - "0.000000"                  => "{0, number, 0.000000 }"
// - "0.0000000"                 => "{0, number, 0.0000000}"
// --- date ---           	                       
// - "date"                      => "{0, date, dd.MM.YY}"
// - "date : time"               => "{0, date, dd.MM.YY} : {0, time, HH.mm.ss}"
// - "dd.MM"                     => "{0, date, dd:MM}"
// - "dd"                        => "{0, date, dd}"
// - "... <date> ... " in any place is substituted with "{0, date, dd.MM.YY}" 
// --- time ---           	                       
// - "time"                      => "{0, time, HH:mm:ss}"
// - "HH:mm"                     => "{0, time, HH:mm}"
// - "mm:ss"                     => "{0, time, mm:ss}"
// - "date time"                 => "{0, date, dd.MM.YY\} {0, time, HH.mm.ss}"
// - "date, time"                => "{0, date, dd.MM.YY\}, {0, time, HH.mm.ss}"
// - "date,time"                 => "{0, date, dd.MM.YY\},{0, time, HH.mm.ss}"
// - "date\ntime"                => "{0, date, dd.MM.YY\}\n{0, time, HH.mm.ss}"
// - "... <time> ... " in any place is substituted with "{0, time, HH.mm.ss}" 
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.export method toS(matrix<float> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
export method toS(matrix<float> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
//}

// ━━━━━━ toS(matrix<string> , format, nz) ━━━━━━ {
// @function Converts each element of the matrix to string outputs using str.tostring(matrix)  
// @param this (matrix) Matrix to be converted to string
// @param format (string) Format string as in str.format() 
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.export method toS(matrix<float> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
export method toS(matrix<string> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
//}

// ━━━━━━ toS(matrix<color> , format, nz) ━━━━━━ {
// @function Converts each element of the matrix to string outputs using str.tostring(matrix)  
// @param this (matrix) Matrix to be converted to string
// @param format (string) "HEX" (default) or "RGB"
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.export method toS(matrix<float> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
export method toS(matrix<color> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
//}

// ━━━━━━ toS(matrix<line> , format, nz) ━━━━━━ {
// @function Converts each element of the matrix to string outputs using str.tostring(matrix)  
// @param this (matrix) Matrix to be converted to string
// @param format (string) (Optional) Format string. By default "{0}: {1}" if showIDs = true or "{1}" otherwise. (use "{0}" as a placeholder for id and "{1}" for item value)
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.export method toS(matrix<float> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
export method toS(matrix<line> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
//}

// ━━━━━━ toS(matrix<label> , format, nz) ━━━━━━ {
// @function Converts each element of the matrix to string outputs using str.tostring(matrix)  
// @param this (matrix) Matrix to be converted to string
// @param format (string) (Optional) Format string. By default "{0}: {1}" if showIDs = true or "{1}" otherwise. (use "{0}" as a placeholder for id and "{1}" for item value)
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.export method toS(matrix<float> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
export method toS(matrix<label> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
//}

// ━━━━━━ toS(matrix<box> , format, nz) ━━━━━━ {
// @function Converts each element of the matrix to string outputs using str.tostring(matrix)  
// @param this (matrix) Matrix to be converted to string
// @param format (string) (Optional) Format string. By default "{0}: {1}" if showIDs = true or "{1}" otherwise. (use "{0}" as a placeholder for id and "{1}" for item value)
// @param nz (string) If val is na and nz is not na the value of nz param is returned instead.export method toS(matrix<float> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
export method toS(matrix<box> this,  string format = "", string nz = na) => str.tostring(this.toStringMx(format, nz))
//}

// ^^^ END OF toS() FUNCTIONS }
// ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ 


// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║                                DEMO                                          ║ { 
//{
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ INPUT ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ {

i_dbgN = input.int(1, "dbgN", inline = "")

i_clr = input.color(color.red, "Sample color", inline = "")
i_cell1W = input.int(80, "Width: cell 1", inline = "0")
i_cell2W = input.int(20, "cell 2", inline = "0")

i_From = input.int(0, "From", inline = "1")
i_To = input.int(1000, "To", inline = "1")
i_WrapTo = input.int(80, "Wrap to", inline = "1")
i_WrapPrefix=			input.string("", "Wrap: prefix"		, inline = "wrap")
i_WrapPostfix=			input.string("", "postfix"			, inline = "wrap")
i_MaxL = input.int(1000, "MaxLength", inline = "2")
i_Trunc = input.string("Left", "Truncate", options=["Left", "Right"], inline = "2")
ishowIDs = input.bool(false, "ShowIDs", tooltip = "Only has effect if iformatMap is empty")
iseparator=input.string(",", "Separator")
i_NaS=input.string("--", "NA placeholder", tooltip = "Text which is shown instead of na values.")
iformatMap=input.string("{0}: <{1}, {2}>", "Format string (maps)", tooltip = "args: id, key, val")

iFormatMap = iformatMap == "" ? string(na) : iformatMap

// ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ END OF INPUT  ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ }


// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ DEMO MAIN ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ {


if bar_index == last_bar_index - 1
	// ---  test values --- {
	b = true 	// bool
	i = 1 		// int
	f = 1. 		// float
	s = "aaa"	// string
	lnB = line.new(bar_index - 3, low[3], bar_index, low, color = color.yellow)
	lnT = line.new(time[6], low[6], time[3], low[3], color = color.rgb(255, 148, 134), xloc = xloc.bar_time)
	lblB = label.new(bar_index,high, "test", color = color.yellow)
	lblT = label.new(time[6],high[6], "test", color = color.yellow, xloc = xloc.bar_time)
	bxB =  box.new(bar_index - 3, low[3], bar_index,low, text = "box", bgcolor = color.rgb(170, 237, 246, 57))
	bxT =  box.new(time[6], low[6], time[3], low[3], text = "box", bgcolor = color.rgb(243, 213, 169, 59), xloc = xloc.bar_time)


	arB = array.from(true,false)
	arI = array.from(10,20)
	arF = array.from(30,40.)
	arS = array.from("AAA","BBB")
	arC = array.from(color.red, #00bcd4)
	arLn = array.from(lnB,lnT)
	arLbl = array.from(lblB,lblT)
	arBx = array.from(bxB,bxT)
	arT = array.from(time,time[1])

		// --- float matrix --- 
	mxF = matrix.new<float>()
	mxF.add_row(0, arI)
	mxF.add_row(0, arF)
	mxF.add_row(0, array.from(float(na), -3.14))
	
	// --- color matrix --- 
	mxC = matrix.new<color>()
	mxC.add_row(0, arC)
	mxC.add_row(0, arC)
	//}

	// --- box matrix --- 
	mxBx = matrix.new<box>()
	mxBx.add_row(0, arBx)
	mxBx.add_row(0, arBx)
	//}

	txt = ""


 	// ━━━━━ test matrix.toStringMx() ━━━━━ {
	txt += "\n -------------- matrix.toStringMx () ------------------- \n"
	
	txt += "\n" + "matrix<int>	toStringMx():\n" + str.tostring(mxF.toStringMx(nz = "--"))

	txt += "\n --------------------------------- "
	txt += "\n" + "matrix<color>	toStringMx(HEX):\n" + str.tostring(mxC.toStringMx(format = "HEX"))
	
	txt += "\n --------------------------------- "
	txt += "\n" + "matrix<box>	toStringMx().toS():\n" + mxBx.toStringMx().toS()

	txt += "\n --------------------------------- "
	//}
	
	// ━━━━━ test matrix.toS() ━━━━━ {
	//}



	// --- draw table --- {
	// TEST ALL 
	t = table.new(position.bottom_center, 2, 1, bgcolor = color.rgb(245, 243, 149), border_color = color.black, border_width = 1, frame_color = color.black, frame_width = 1)
	table.cell(t,0,0, text_halign = text.align_left,width = i_cell1W, height = 100 , text_font_family = font.family_monospace)
	table.cell(t,1,0, text_halign = text.align_left,width = i_cell2W, height = 100 , text_font_family = font.family_monospace)

	table.cell_set_text(t, 0, 0, txt)
	// table.cell_set_text(t, 0, 0, txt)
	table.cell_set_text_size(t, 0, 0, size.tiny)

	table.cell_set_text(t, 1, 0, "")
	table.cell_set_text_size(t, 1, 0, size.tiny)

	//}
// ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ END OF DEMO MAIN  ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ }

// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ DEBUG PRINTS ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ {

plotchar(bar_index, "bar_index",  "", location = location.bottom)
plotchar(array.size(table.all), "table.all size",  "", location = location.bottom)
plotchar(array.size(line.all), "line.all size",  "", location = location.bottom)
plotchar(array.size(label.all), "label.all size",  "", location = location.bottom)

// ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ END OF DEBUG PRINTS  ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ }


// ║                 END OF MAIN                                                  ║ }
// ╚══════════════════════════════════════════════════════════════════════════════╝



