//@version=5
library("Autofibo", overlay=true)

import TradingView/ta/7

//@description This library aims to provide functions to calculate fibonacci values based on min/max values or tracking min/max according with trend changes.
//@description ALGOA+ inteligent solutions by metacamaleo - June, 2024.

//@function Creates an array with fibbonaci levels and plots lines.
//@param float up, float down, bool plotLines = true, color color_fibo = color.purple
//@returns [fibo0382, fibo0500, fibo0618, up_fibo1618, up_fibo2618, down_fibo1618, down_fibo2618] --> var float tupple.
export fibonacci(float up, float down, bool calculate, bool log = false, color color1 = color.navy, color color2 = color.maroon, bool plot) =>
    var float fibo0382 = na
    var float fibo0500 = na
    var float fibo0618 = na
    var float up_fibo1618 = na
    var float up_fibo2618 = na
    var float down_fibo1618 = na
    var float down_fibo2618 = na
    if calculate
        _up = log ? math.log(up) : up
        _down = log ? math.log(down) : down
        diff = _up - _down
        fibo0382 := log ? math.exp(_down + (diff * 0.382)) : down + (diff * 0.382)
        fibo0500 := log ? math.exp(_down + (diff * 0.500)) : down + (diff * 0.500)
        fibo0618 := log ? math.exp(_down + (diff * 0.618)) : down + (diff * 0.618)
        up_fibo1618 := log ? math.exp(_down + (diff * 1.618)) : down + (diff * 1.618)
        up_fibo2618 := log ? math.exp(_down + (diff * 2.618)) : down + (diff * 2.618)
        down_fibo1618 := log ? math.exp(_down - (diff * 1.618)) : down - (diff * 1.618)
        down_fibo2618 := log ? math.exp(_down - (diff * 2.618)) : down - (diff * 2.618)

        if plot
            var line[] fibo_lines = array.new<line>(9)
            for i = 0 to 8
                fibo_value = switch i
                    0 => up
                    1 => down
                    2 => fibo0382
                    3 => fibo0500
                    4 => fibo0618
                    5 => up_fibo1618
                    6 => up_fibo2618
                    7 => down_fibo1618
                    8 => down_fibo2618
                line_style = i < 2 ? line.style_solid : line.style_dashed
                line_width = i < 2 ? 2 : 1
                color_fibo = i > 1 and i < 5 ? color2 : color1
                line.delete(fibo_lines.shift())
                fibo_lines.push(line.new(bar_index - 1, fibo_value, bar_index, fibo_value, extend=extend.both, color= color_fibo, style= line_style, width = line_width, force_overlay = true))
    [fibo0382, fibo0500, fibo0618, up_fibo1618, up_fibo2618, down_fibo1618, down_fibo2618]

//@function Fibonacci extension.
//@description up (float) Up level.
//@description down (float) Down level.
//@description direction (string) Options "up" or "down".
//@returns [level1618, level2618] -> var float, var float
export fibonacciExtension(float up, float down, string direction = "up", bool log = false, bool calculate = true, color color1 = color.teal, bool plot = true) =>
    _up = log ? math.log(up) : up
    _down = log ? math.log(down) : down
    diff = _up - _down
    m = direction == "up" ? 1 : -1
    var float level1618 = na, var float level2618 = na
    level1618 := calculate ? log ? math.exp(_down + (diff * 1.618 * m)) : down + (diff * 1.618 * m) : level1618
    level2618 := calculate ? log ? math.exp(_down + (diff * 2.618 * m)) : down + (diff * 2.618 * m) : level2618
    if plot
        var line[] fibo_ext_line_array = array.new<line>(2)
        line.delete(fibo_ext_line_array.shift())
        line.delete(fibo_ext_line_array.shift())
        fibo_ext_line_array.push(line.new(bar_index, level1618, bar_index + 1, level1618, extend = extend.both, color = color1, style = line.style_dotted, width = 2, force_overlay = true))
        fibo_ext_line_array.push(line.new(bar_index, level2618, bar_index + 1, level2618, extend = extend.both, color = color1, style = line.style_dotted, width = 2, force_overlay = true))
    [level1618, level2618]

//@function maxPrice function.
maxPrice(bool condition) =>
    var float maxPrice = na
    maxPrice := condition ? math.max(nz(maxPrice, high), high) : na

//@function minPrice function.
minPrice(bool condition) =>
    var float minPrice = na
    minPrice := condition ? math.min(nz(minPrice, low), low) : na

//@function Calculates automatic fibo values based on trends, returning a tupple with most important values.
//@param bool uptrend
//@param bool downtrend
//@param bool log_option = true
//@param color color1 = color.navy
//@param color color2 = color.maroon
//@param bool plot = true
//@returns [down_fibo2618, down_fibo1618, fibo0000, fibo0382, fibo0500, fibo0618, fibo1000, up_fibo1618, up_fibo2618]
export trendFibo(bool uptrend, bool downtrend, bool log_option = true, color color1 = color.navy, color color2 = color.maroon, bool plot = true)=>
    var float uptrend_max = na, var float uptrend_min = na
    var float downtrend_max = na, var float downtrend_min = na
    change_to_downtrend = downtrend and not downtrend[1]
    change_to_uptrend = uptrend and not uptrend[1]
    change = change_to_downtrend or change_to_uptrend
    max = nz(maxPrice(not change), high)
    min = nz(minPrice(not change), low)
    calculate_upfibo = max > uptrend_max or change_to_uptrend
    calculate_dnfibo = min < downtrend_min or change_to_downtrend 

    var float min_retrace = na
    min_retrace := nz(minPrice(high < uptrend_max), min_retrace)
    uptrend_max := na(uptrend_max) and uptrend ? high : calculate_upfibo ? max : uptrend_max
    uptrend_min := na(uptrend_min) and uptrend ? low : change_to_uptrend ? nz(min_retrace[1], uptrend_min) : uptrend_min 
    downtrend_max := na(downtrend_max) and downtrend ? high : change_to_downtrend ? nz(max[1], downtrend_max) : downtrend_max
    downtrend_min := na(downtrend_min) and downtrend ? low : calculate_dnfibo ? min[1] : downtrend_min
    fibo0000 = uptrend ? uptrend_min : downtrend_min
    fibo1000 = uptrend ? uptrend_max : downtrend_max
    [fibo0382, fibo0500, fibo0618, up_fibo1618, up_fibo2618, down_fibo1618, down_fibo2618] = fibonacci(fibo1000, fibo0000, calculate_upfibo or calculate_dnfibo, log_option, color1, color2, plot = plot)
    [down_fibo2618, down_fibo1618, fibo0000, fibo0382, fibo0500, fibo0618, fibo1000, up_fibo1618, up_fibo2618]

//|[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[  EXAMPLE  ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
// MOVING AVERAGES
fibo_log_ret_option = input.bool(false, "Log-based fibonacci") 
fibo_calc_on_ltf = input.bool(false, "Calculate on LTF trend")

bb_ma = ta.ema(close, 20)
fast_MA = ta.ema(close, 50)
slow_MA = ta.ema(close, 200)
uptrend = fast_MA[1] > slow_MA[1]
downtrend = fast_MA[1] < slow_MA[1]
ltf_uptrend = bb_ma[1] > fast_MA[1]
ltf_downtrend = bb_ma[1] < fast_MA[1]
downtrend := fibo_calc_on_ltf ? ltf_downtrend : downtrend
uptrend := fibo_calc_on_ltf ? ltf_uptrend : uptrend
trendFibo(uptrend, downtrend, fibo_log_ret_option)

// PLOTS
plot(bb_ma, title = "Fastest ma", color = color.yellow)
plot(fast_MA, title = "Fast MA", color = color.orange, style = plot.style_linebr)
plot(slow_MA, title = "Slow MA", color = color.maroon, style = plot.style_linebr)
