// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © addamsson
//@version=6

// @description Shared global utilities that can be used for
// - creating bounded queues from primitives
// - checking visibility of objects having Bounds on both (x, y) axes
// - checking if a line is too long
library("HexworksSharedUtilities", overlay = true)

//#region constants
const int MAX_LINE_LENGTH = 1000
const int MAX_DRAW_DISTANCE = 500
//#endregion

//#region History implementations
// 📘 Note that Pinescript doesn't support generics so we need these ...

export type FloatHistory
	array<float> history
	int maxLength = 200

// @description inserts the given value into the history array at idx `0`
// and removes all elements at the end to trim the array size to `maxLength`
export method offer(FloatHistory history, simple float value) =>
	arr = history.history
	maxLength = history.maxLength
    while(arr.size() >= maxLength - 1)
        arr.pop()
    arr.insert(0, value)
    arr

export type IntHistory
	array<int> history
	int maxLength = 200

// @description inserts the given value into the history array at idx `0`
// and removes all elements at the end to trim the array size to `maxLength`
export method offer(IntHistory history, simple int value) =>
	arr = history.history
	maxLength = history.maxLength
    while(arr.size() >= maxLength - 1)
        arr.pop()
    arr.insert(0, value)
    arr

export type StringHistory
	array<string> history
	int maxLength = 200

// @description inserts the given value into the history array at idx `0`
// and removes all elements at the end to trim the array size to `maxLength`
export method offer(StringHistory history, simple string value) =>
	arr = history.history
	maxLength = history.maxLength
    while(arr.size() >= maxLength - 1)
        arr.pop()
    arr.insert(0, value)
    arr

export type BoolHistory
	array<bool> history
	int maxLength = 200

// @description inserts the given value into the history array at idx `0`
// and removes all elements at the end to trim the array size to `maxLength`
export method offer(BoolHistory history, simple bool value) =>
	arr = history.history
	maxLength = history.maxLength
    while(arr.size() >= maxLength - 1)
        arr.pop()
    arr.insert(0, value)
    arr

//#endregion

//#region Utilities: toString implementations for commonly used primitives and structures

export method toString(simple chart.point point) => "index=" + str.tostring(point.index) + ", price=" + str.tostring(point.price)

export method toString(simple float num) => str.tostring(num)

export method toString(simple int num) => str.tostring(num)

export method toString(simple bool value) => str.tostring(value)

export method toString(simple line l) => str.format("x1={0}, x2={1}, y1={2}, y2={3}", l.get_x1(), l.get_x2(), l.get_y1(), l.get_y2())

//#endregion

//#region Utilities: line length check
// @description checks whether the given line is too long (eg: would crash the script if drawn)
export method isLineTooLong(chart.point fromPoint, chart.point toPoint) =>
    result = false
    if(fromPoint.index > toPoint.index and fromPoint.index - toPoint.index >= MAX_LINE_LENGTH) 
        result := true
    if(toPoint.index > fromPoint.index and toPoint.index - fromPoint.index >= MAX_LINE_LENGTH)
        result := true
    result

// @description checks whether the given line is too long (eg: would crash the script if drawn)
export method isTooLong(line l) =>
    result = false
    if(l.get_x1() > l.get_x2() and l.get_x1() - l.get_x2() >= MAX_LINE_LENGTH) 
        result := true
    if(l.get_x1() < l.get_x2() and l.get_x2() - l.get_x1() >= MAX_LINE_LENGTH) 
        result := true
    result

//#endregion

//#region Utilities: visibility check

// @description checks whether the given line is too long (eg: would crash the script if drawn)
export type Bounds
	int startIdx
	int endIdx
	float highValue
	float lowValue

// @description can be used to check the visibility of objects
// on the chart. as opposed to the visiblity check outlined in the documentation
// this one also takes into account if an object is visible on the `y` axis 
// __note that__ You __need__ to call `update` on every tick in order
// for this to work
export type VisibilityChecker
	int leftVisibleBarIdx = -1
	int rightVisibleBarIdx = -1
	int maxDrawDistance = -1
	int updatedAt = -1
	float visibleHighest = 0
	float visibleLowest = 999999

// @description creates a new visibility checker
export createVisibilityChecker() =>
	VisibilityChecker.new(maxDrawDistance = MAX_DRAW_DISTANCE)


// @description Updates the internal state of the visiblity checker based on current price action
export method update(VisibilityChecker v) =>
	if(bar_index != v.updatedAt)
		if(time == chart.left_visible_bar_time)
			v.leftVisibleBarIdx := bar_index
		if(time == chart.right_visible_bar_time)
			v.rightVisibleBarIdx := bar_index
			fromIdx = v.rightVisibleBarIdx - v.leftVisibleBarIdx
			for i = fromIdx to 0 by 1
				v.visibleHighest := math.max(v.visibleHighest, high[i])
				v.visibleLowest := math.min(v.visibleLowest, low[i])
		v.updatedAt := bar_index

// @description Tells whether we can draw on the chart
// We can only draw when we're at the last visible bar. After that whatever drawings we have 
// they are no longer visible. Before the last bar we can't yet determine the min/max price
export method canDraw(VisibilityChecker v) => 
	// 📘 We make sure that we're at the latest state
	v.update()
	time == chart.right_visible_bar_time

// @description tells whether the object with the given bounds is visible on the screen right now
export method isVisible(VisibilityChecker v, Bounds b) =>
	v.update()
	// 📘 it doesn't start too far in the past
    visibleLeft = bar_index - b.startIdx < v.maxDrawDistance
    // 📘 it extends into the viewport from the left
    visibleRight = b.endIdx > v.leftVisibleBarIdx
    visibleUp = b.lowValue < v.visibleHighest
    visibleDown = b.highValue > v.visibleLowest
    visibleLeft and visibleRight and visibleUp and visibleDown

//#endregion