//@version=6
library("NodialTreesLows1")

// --- TREE 0 ---
export method tree_0(array<float> f) =>
    if f.get(9) <= 0.29365
        if f.get(9) <= 0.12735
            if f.get(14) <= 0.50000
                if f.get(15) <= 0.50000
                    if f.get(8) <= 0.10295
                        if f.get(2) <= -5.27140
                            if f.get(5) <= -2.79600
                                0.00000
                            else
                                if f.get(26) <= 29.69245
                                    0.34759
                                else
                                    0.70717
                        else
                            if f.get(1) <= 37.12500
                                if f.get(18) <= -0.12165
                                    0.15594
                                else
                                    0.09975
                            else
                                if f.get(3) <= 1.56415
                                    0.16781
                                else
                                    0.36578
                    else
                        if f.get(4) <= -6.13485
                            if f.get(5) <= -0.30170
                                if f.get(18) <= -1.34690
                                    0.83806
                                else
                                    0.30806
                            else
                                if f.get(24) <= 0.15055
                                    0.00000
                                else
                                    0.50235
                        else
                            if f.get(1) <= 35.84000
                                if f.get(18) <= -0.27485
                                    0.78892
                                else
                                    0.31894
                            else
                                if f.get(3) <= 1.57875
                                    0.66105
                                else
                                    0.84696
                else
                    if f.get(5) <= 0.08050
                        if f.get(1) <= 41.88000
                            if f.get(6) <= 1.21735
                                if f.get(2) <= 0.29545
                                    0.36392
                                else
                                    0.97183
                            else
                                if f.get(7) <= 30.89550
                                    0.49318
                                else
                                    0.87121
                        else
                            if f.get(18) <= 0.11350
                                if f.get(26) <= 7.11425
                                    0.70988
                                else
                                    0.92238
                            else
                                1.00000
                    else
                        if f.get(9) <= 0.10060
                            if f.get(24) <= 0.38755
                                if f.get(24) <= 0.32085
                                    0.87342
                                else
                                    1.00000
                            else
                                if f.get(19) <= 0.01005
                                    0.71429
                                else
                                    0.97576
                        else
                            if f.get(13) <= 0.50000
                                0.86348
                            else
                                0.51111
            else
                if f.get(19) <= -0.29160
                    if f.get(3) <= 1.26915
                        0.11917
                    else
                        0.38547
                else
                    if f.get(7) <= 39.00720
                        if f.get(24) <= 2.76620
                            if f.get(4) <= -17.19195
                                0.54762
                            else
                                if f.get(8) <= 0.25150
                                    0.00000
                                else
                                    0.87967
                        else
                            0.97183
                    else
                        0.15033
        else
            if f.get(13) <= 2.50000
                if f.get(18) <= -0.31745
                    if f.get(8) <= 0.22630
                        if f.get(8) <= 0.11855
                            if f.get(26) <= 1.91880
                                0.45545
                            else
                                if f.get(3) <= 1.61705
                                    0.00000
                                else
                                    0.22330
                        else
                            if f.get(23) <= 0.36575
                                if f.get(24) <= 1.97415
                                    0.34282
                                else
                                    0.08425
                            else
                                0.64789
                    else
                        if f.get(23) <= 0.89265
                            if f.get(6) <= 1.02110
                                if f.get(3) <= 0.75940
                                    0.53488
                                else
                                    0.10798
                            else
                                if f.get(26) <= 15.88335
                                    0.81030
                                else
                                    0.24731
                        else
                            if f.get(24) <= 1.07750
                                if f.get(13) <= 0.50000
                                    0.76303
                                else
                                    1.00000
                            else
                                0.38547
                else
                    if f.get(1) <= 53.48000
                        if f.get(1) <= 38.57500
                            if f.get(7) <= 18.06440
                                if f.get(6) <= 0.85685
                                    0.10550
                                else
                                    0.64912
                            else
                                if f.get(2) <= -1.55760
                                    0.39173
                                else
                                    0.11251
                        else
                            if f.get(11) <= 0.50000
                                if f.get(4) <= -11.98725
                                    0.69697
                                else
                                    0.53354
                            else
                                if f.get(6) <= 0.93395
                                    0.50298
                                else
                                    0.27826
                    else
                        if f.get(18) <= -0.17740
                            if f.get(8) <= 0.86310
                                0.79310
                            else
                                1.00000
                        else
                            if f.get(3) <= 1.42340
                                0.47917
                            else
                                0.85790
            else
                if f.get(1) <= 40.09000
                    if f.get(14) <= 0.50000
                        if f.get(7) <= 31.85900
                            if f.get(0) <= 345600.00000
                                if f.get(8) <= 0.52155
                                    0.18463
                                else
                                    0.35440
                            else
                                if f.get(3) <= 1.02285
                                    0.30012
                                else
                                    0.45789
                        else
                            if f.get(15) <= 0.50000
                                if f.get(23) <= 0.45400
                                    0.22070
                                else
                                    0.52177
                            else
                                if f.get(0) <= 50400.00000
                                    0.57983
                                else
                                    0.79496
                    else
                        if f.get(23) <= 0.75830
                            if f.get(6) <= 0.97750
                                if f.get(7) <= 27.19635
                                    0.27711
                                else
                                    0.00000
                            else
                                0.00000
                        else
                            if f.get(1) <= 35.38500
                                if f.get(4) <= -14.44665
                                    0.84018
                                else
                                    0.11917
                            else
                                if f.get(8) <= 0.92505
                                    0.77528
                                else
                                    0.95041
                else
                    if f.get(1) <= 42.10500
                        if f.get(7) <= 20.74350
                            if f.get(23) <= 0.28045
                                0.05192
                            else
                                if f.get(1) <= 40.53500
                                    0.80831
                                else
                                    0.34328
                        else
                            if f.get(3) <= 1.09315
                                if f.get(1) <= 40.74500
                                    0.74446
                                else
                                    0.09465
                            else
                                if f.get(5) <= -0.70415
                                    0.95392
                                else
                                    0.75410
                    else
                        if f.get(8) <= 0.18455
                            0.24731
                        else
                            if f.get(18) <= -0.11710
                                if f.get(18) <= -0.54980
                                    0.88314
                                else
                                    0.97394
                            else
                                if f.get(4) <= 9.01930
                                    0.71963
                                else
                                    1.00000
    else
        if f.get(4) <= -1.64830
            if f.get(8) <= 0.47065
                if f.get(24) <= 1.63375
                    if f.get(0) <= 345600.00000
                        if f.get(2) <= -2.97085
                            0.74937
                        else
                            if f.get(18) <= -0.17730
                                if f.get(9) <= 1.16195
                                    0.35704
                                else
                                    0.18239
                            else
                                if f.get(23) <= 0.43115
                                    0.21803
                                else
                                    0.30762
                    else
                        if f.get(18) <= -0.01885
                            if f.get(18) <= -0.22410
                                if f.get(9) <= 0.42135
                                    0.36508
                                else
                                    0.56098
                            else
                                if f.get(2) <= 0.38115
                                    0.30464
                                else
                                    0.74612
                        else
                            if f.get(6) <= 1.12945
                                if f.get(7) <= 41.53935
                                    0.58211
                                else
                                    0.93243
                            else
                                0.09465
                else
                    if f.get(26) <= 6.36925
                        if f.get(24) <= 1.69065
                            0.00000
                        else
                            if f.get(3) <= 1.94285
                                if f.get(11) <= 0.50000
                                    0.49176
                                else
                                    0.65142
                            else
                                if f.get(6) <= 1.32180
                                    0.82143
                                else
                                    0.62162
                    else
                        if f.get(26) <= 31.18660
                            if f.get(3) <= 1.04200
                                if f.get(19) <= 0.07840
                                    0.33441
                                else
                                    0.03469
                            else
                                if f.get(23) <= 0.41375
                                    0.32324
                                else
                                    0.50257
                        else
                            if f.get(8) <= 0.29030
                                if f.get(1) <= 26.80500
                                    0.63122
                                else
                                    0.17481
                            else
                                if f.get(5) <= -2.81970
                                    0.46593
                                else
                                    0.83333
            else
                if f.get(18) <= -0.31875
                    if f.get(6) <= 1.44455
                        if f.get(26) <= 29.62800
                            if f.get(10) <= 0.50000
                                if f.get(23) <= 0.62665
                                    0.51433
                                else
                                    0.71082
                            else
                                if f.get(8) <= 0.67910
                                    0.47128
                                else
                                    0.65278
                        else
                            if f.get(9) <= 6.92900
                                if f.get(0) <= 50400.00000
                                    0.55326
                                else
                                    0.85860
                            else
                                if f.get(13) <= 2.50000
                                    0.72125
                                else
                                    0.08127
                    else
                        if f.get(1) <= 13.25500
                            0.36508
                        else
                            if f.get(17) <= -0.21300
                                if f.get(3) <= 1.78100
                                    0.65058
                                else
                                    0.86075
                            else
                                if f.get(3) <= 2.18680
                                    0.07348
                                else
                                    0.78892
                else
                    if f.get(14) <= 0.50000
                        if f.get(0) <= 345600.00000
                            if f.get(6) <= 1.16020
                                if f.get(8) <= 0.76650
                                    0.35473
                                else
                                    0.47164
                            else
                                if f.get(8) <= 0.69890
                                    0.44931
                                else
                                    0.64472
                        else
                            if f.get(6) <= 0.67955
                                if f.get(9) <= 3.25360
                                    0.69697
                                else
                                    0.32857
                            else
                                if f.get(23) <= 1.18185
                                    0.71356
                                else
                                    0.84579
                    else
                        if f.get(0) <= 345600.00000
                            if f.get(5) <= -0.12480
                                if f.get(8) <= 0.94390
                                    0.47368
                                else
                                    0.75266
                            else
                                if f.get(2) <= -1.13865
                                    0.61686
                                else
                                    0.90719
                        else
                            if f.get(8) <= 0.69910
                                if f.get(7) <= 14.13870
                                    0.24731
                                else
                                    0.70988
                            else
                                if f.get(23) <= 0.58835
                                    0.59410
                                else
                                    0.87420
        else
            if f.get(23) <= 0.55635
                if f.get(23) <= 0.03305
                    if f.get(9) <= 0.60660
                        if f.get(9) <= 0.49915
                            if f.get(1) <= 43.07000
                                0.00000
                            else
                                0.84018
                        else
                            0.10798
                    else
                        if f.get(7) <= 16.01430
                            if f.get(6) <= 0.86690
                                0.42073
                            else
                                0.71671
                        else
                            if f.get(9) <= 4.47190
                                if f.get(7) <= 22.39645
                                    0.95095
                                else
                                    0.84018
                            else
                                if f.get(17) <= 0.05910
                                    0.41441
                                else
                                    0.91477
                else
                    if f.get(0) <= 345600.00000
                        if f.get(18) <= -0.03385
                            if f.get(4) <= -1.45790
                                if f.get(17) <= 0.03130
                                    0.82143
                                else
                                    0.89610
                            else
                                if f.get(4) <= -1.15080
                                    0.00000
                                else
                                    0.43994
                        else
                            if f.get(2) <= 0.01365
                                if f.get(26) <= 3.43100
                                    0.18449
                                else
                                    0.53488
                            else
                                0.60526
                    else
                        if f.get(23) <= 0.26930
                            if f.get(18) <= -0.18590
                                if f.get(24) <= 0.41550
                                    0.15541
                                else
                                    0.48357
                            else
                                if f.get(1) <= 42.50000
                                    0.40716
                                else
                                    0.21925
                        else
                            if f.get(11) <= 0.50000
                                if f.get(23) <= 0.55035
                                    0.62716
                                else
                                    0.08425
                            else
                                if f.get(24) <= 1.00560
                                    0.41084
                                else
                                    0.56029
            else
                if f.get(0) <= 345600.00000
                    if f.get(5) <= 0.55450
                        if f.get(1) <= 39.08000
                            if f.get(8) <= 0.56490
                                if f.get(4) <= -0.32820
                                    0.18254
                                else
                                    0.39438
                            else
                                if f.get(6) <= 1.59160
                                    0.51876
                                else
                                    0.85352
                        else
                            if f.get(18) <= 0.02205
                                if f.get(2) <= 0.03270
                                    0.64124
                                else
                                    0.00000
                            else
                                if f.get(3) <= 1.17950
                                    0.47917
                                else
                                    0.86559
                    else
                        if f.get(23) <= 1.07840
                            if f.get(5) <= 0.63480
                                0.84018
                            else
                                if f.get(24) <= 0.84485
                                    0.38547
                                else
                                    0.00000
                        else
                            if f.get(2) <= -0.49590
                                if f.get(1) <= 30.21500
                                    1.00000
                                else
                                    0.64377
                            else
                                1.00000
                else
                    if f.get(18) <= -1.24965
                        if f.get(4) <= 37.52820
                            if f.get(7) <= 32.21935
                                0.14110
                            else
                                0.48936
                        else
                            if f.get(8) <= 0.71990
                                0.72125
                            else
                                0.77528
                    else
                        if f.get(23) <= 0.98495
                            if f.get(8) <= 0.70770
                                if f.get(9) <= 0.43615
                                    0.22967
                                else
                                    0.68009
                            else
                                if f.get(7) <= 11.05995
                                    0.47368
                                else
                                    0.79914
                        else
                            if f.get(5) <= 2.91470
                                if f.get(8) <= 0.34550
                                    0.00000
                                else
                                    0.82024
                            else
                                if f.get(7) <= 23.54495
                                    0.38983
                                else
                                    0.75976

// --- TREE 1 ---
export method tree_1(array<float> f) =>
    if f.get(23) <= 0.44065
        if f.get(4) <= -0.71630
            if f.get(9) <= 0.33345
                if f.get(0) <= 345600.00000
                    if f.get(6) <= 2.21065
                        if f.get(3) <= 0.49945
                            if f.get(24) <= 0.06810
                                if f.get(1) <= 25.76500
                                    0.30131
                                else
                                    0.01561
                            else
                                if f.get(9) <= 0.28475
                                    0.24138
                                else
                                    0.40268
                        else
                            if f.get(23) <= 0.10135
                                if f.get(13) <= 3.50000
                                    0.06235
                                else
                                    0.12553
                            else
                                if f.get(2) <= -0.52925
                                    0.19784
                                else
                                    0.13134
                    else
                        if f.get(17) <= -0.36815
                            if f.get(19) <= 0.21365
                                0.00000
                            else
                                0.36508
                        else
                            if f.get(23) <= 0.05570
                                0.82143
                            else
                                if f.get(4) <= -20.10040
                                    0.75410
                                else
                                    0.12568
                else
                    if f.get(2) <= 1.77870
                        if f.get(23) <= 0.11085
                            if f.get(8) <= 0.14410
                                if f.get(3) <= 2.99980
                                    0.17786
                                else
                                    0.66057
                            else
                                if f.get(26) <= 1.40920
                                    0.91477
                                else
                                    0.33891
                        else
                            if f.get(8) <= 0.12685
                                if f.get(2) <= -0.21405
                                    0.24211
                                else
                                    0.67742
                            else
                                if f.get(5) <= -2.42770
                                    0.83716
                                else
                                    0.43043
                    else
                        if f.get(8) <= 0.18855
                            0.00000
                        else
                            0.24731
            else
                if f.get(23) <= 0.04215
                    if f.get(8) <= 0.51490
                        if f.get(7) <= 24.63445
                            if f.get(17) <= 0.10905
                                if f.get(13) <= 3.50000
                                    0.10470
                                else
                                    0.53488
                            else
                                if f.get(9) <= 0.54695
                                    0.13295
                                else
                                    0.00000
                        else
                            if f.get(5) <= -0.15500
                                if f.get(9) <= 0.93725
                                    0.36508
                                else
                                    0.78508
                            else
                                0.92000
                    else
                        if f.get(6) <= 1.10865
                            if f.get(26) <= 10.06310
                                if f.get(6) <= 1.05060
                                    0.62112
                                else
                                    0.16667
                            else
                                if f.get(5) <= -1.03885
                                    0.72441
                                else
                                    0.96988
                        else
                            if f.get(2) <= -1.24860
                                0.74194
                            else
                                if f.get(17) <= 0.07295
                                    0.97089
                                else
                                    0.78892
                else
                    if f.get(24) <= 1.73510
                        if f.get(19) <= -1.13715
                            if f.get(1) <= 36.68500
                                if f.get(2) <= -1.24265
                                    0.17293
                                else
                                    0.00919
                            else
                                0.34673
                        else
                            if f.get(23) <= 0.22460
                                if f.get(25) <= 0.00000
                                    0.18930
                                else
                                    0.27238
                            else
                                if f.get(18) <= -0.09360
                                    0.37645
                                else
                                    0.28437
                    else
                        if f.get(9) <= 3.91380
                            if f.get(0) <= 345600.00000
                                if f.get(6) <= 1.47885
                                    0.22712
                                else
                                    0.63303
                            else
                                if f.get(26) <= 7.90050
                                    0.68018
                                else
                                    0.44011
                        else
                            if f.get(19) <= -0.22360
                                0.00000
                            else
                                if f.get(18) <= -0.59140
                                    0.53488
                                else
                                    0.15646
        else
            if f.get(3) <= 0.23210
                if f.get(4) <= 64.19040
                    if f.get(6) <= 0.77820
                        if f.get(18) <= -0.01655
                            if f.get(2) <= -0.61645
                                if f.get(5) <= 1.04680
                                    0.31507
                                else
                                    0.00000
                            else
                                0.00000
                        else
                            0.43396
                    else
                        if f.get(18) <= -0.49650
                            if f.get(26) <= 7.67265
                                0.36508
                            else
                                0.00000
                        else
                            if f.get(6) <= 1.06570
                                if f.get(25) <= 0.00000
                                    0.67047
                                else
                                    0.51977
                            else
                                if f.get(3) <= 0.07150
                                    0.80407
                                else
                                    0.55645
                else
                    if f.get(8) <= 0.96375
                        0.68109
                    else
                        1.00000
            else
                if f.get(9) <= 0.39285
                    if f.get(23) <= 0.11455
                        if f.get(24) <= 5.49510
                            if f.get(2) <= -1.90525
                                if f.get(1) <= 29.21000
                                    0.31507
                                else
                                    0.04106
                            else
                                if f.get(9) <= 0.07825
                                    0.16014
                                else
                                    0.27124
                        else
                            0.50549
                    else
                        if f.get(13) <= 2.50000
                            if f.get(23) <= 0.11775
                                if f.get(19) <= -0.09065
                                    0.87928
                                else
                                    0.43396
                            else
                                if f.get(24) <= 1.92455
                                    0.42370
                                else
                                    0.09942
                        else
                            if f.get(2) <= -0.25855
                                if f.get(18) <= -0.09775
                                    0.25234
                                else
                                    0.45098
                            else
                                if f.get(19) <= 0.10960
                                    0.00000
                                else
                                    0.13295
                else
                    if f.get(6) <= 1.26360
                        if f.get(7) <= 12.64680
                            if f.get(1) <= 39.65000
                                0.00000
                            else
                                if f.get(7) <= 11.41520
                                    0.50860
                                else
                                    0.12568
                        else
                            if f.get(0) <= 345600.00000
                                if f.get(24) <= 0.07605
                                    0.79310
                                else
                                    0.24910
                            else
                                if f.get(5) <= 1.56320
                                    0.56399
                                else
                                    0.34022
                    else
                        if f.get(23) <= 0.17270
                            if f.get(1) <= 44.67000
                                0.45545
                            else
                                0.09871
                        else
                            if f.get(10) <= 0.50000
                                if f.get(5) <= 5.90865
                                    0.77257
                                else
                                    0.32624
                            else
                                if f.get(9) <= 1.00035
                                    0.36508
                                else
                                    0.13295
    else
        if f.get(0) <= 345600.00000
            if f.get(0) <= 50400.00000
                if f.get(8) <= 0.63895
                    if f.get(6) <= 1.18120
                        if f.get(4) <= -5.94240
                            if f.get(18) <= 0.25515
                                if f.get(18) <= -0.03645
                                    0.18786
                                else
                                    0.30393
                            else
                                0.90196
                        else
                            if f.get(9) <= 1.72080
                                if f.get(24) <= 0.30595
                                    0.11058
                                else
                                    0.31507
                            else
                                if f.get(23) <= 0.48930
                                    0.14110
                                else
                                    0.00000
                    else
                        if f.get(24) <= 0.82710
                            if f.get(17) <= 0.59055
                                if f.get(19) <= 2.05530
                                    0.28623
                                else
                                    0.68109
                            else
                                if f.get(6) <= 1.29650
                                    0.43396
                                else
                                    0.90881
                        else
                            if f.get(3) <= 3.86440
                                if f.get(23) <= 0.96135
                                    0.34251
                                else
                                    0.52003
                            else
                                if f.get(7) <= 25.23270
                                    0.17969
                                else
                                    0.64972
                else
                    if f.get(3) <= 2.87120
                        if f.get(8) <= 0.86980
                            if f.get(6) <= 1.04780
                                if f.get(1) <= 24.31500
                                    0.03343
                                else
                                    0.30139
                            else
                                if f.get(5) <= -1.31130
                                    0.70446
                                else
                                    0.44028
                        else
                            if f.get(1) <= 23.26000
                                if f.get(9) <= 0.83720
                                    0.40529
                                else
                                    0.74631
                            else
                                if f.get(9) <= 0.50930
                                    0.57983
                                else
                                    0.44749
                    else
                        if f.get(6) <= 1.13755
                            if f.get(1) <= 29.80500
                                if f.get(24) <= 0.41580
                                    0.24731
                                else
                                    0.00000
                            else
                                if f.get(7) <= 38.18825
                                    0.41235
                                else
                                    0.00000
                        else
                            if f.get(6) <= 1.69790
                                if f.get(8) <= 0.90700
                                    0.58289
                                else
                                    0.83550
                            else
                                if f.get(19) <= 0.47345
                                    0.76551
                                else
                                    0.89981
            else
                if f.get(8) <= 0.72490
                    if f.get(18) <= -0.32035
                        if f.get(5) <= -1.42625
                            if f.get(2) <= -4.13025
                                if f.get(3) <= 1.54480
                                    0.35115
                                else
                                    0.64199
                            else
                                if f.get(3) <= 1.78545
                                    0.14110
                                else
                                    0.39394
                        else
                            if f.get(17) <= -2.56345
                                0.87342
                            else
                                if f.get(6) <= 1.20205
                                    0.44499
                                else
                                    0.68247
                    else
                        if f.get(8) <= 0.54465
                            if f.get(6) <= 1.01670
                                if f.get(17) <= 0.84585
                                    0.32326
                                else
                                    0.05192
                            else
                                if f.get(17) <= -0.01775
                                    0.38181
                                else
                                    0.50237
                        else
                            if f.get(19) <= 0.23700
                                if f.get(5) <= -0.45030
                                    0.36841
                                else
                                    0.47954
                            else
                                if f.get(18) <= -0.09480
                                    0.74405
                                else
                                    0.51977
                else
                    if f.get(4) <= -35.62645
                        if f.get(19) <= -0.66450
                            if f.get(1) <= 33.94000
                                if f.get(2) <= -1.52740
                                    0.38547
                                else
                                    0.00000
                            else
                                0.64789
                        else
                            if f.get(8) <= 0.79440
                                if f.get(8) <= 0.76255
                                    0.80472
                                else
                                    0.95079
                            else
                                if f.get(9) <= 0.03650
                                    0.13295
                                else
                                    0.73851
                    else
                        if f.get(5) <= -0.19595
                            if f.get(23) <= 2.05925
                                if f.get(24) <= 2.07935
                                    0.51422
                                else
                                    0.23789
                            else
                                if f.get(22) <= 0.50000
                                    0.79057
                                else
                                    0.54949
                        else
                            if f.get(3) <= 1.17765
                                if f.get(3) <= 0.85975
                                    0.32070
                                else
                                    0.51925
                            else
                                if f.get(26) <= 2.19160
                                    0.57859
                                else
                                    0.69914
        else
            if f.get(8) <= 0.75110
                if f.get(7) <= 24.56310
                    if f.get(8) <= 0.28805
                        if f.get(6) <= 1.07500
                            if f.get(4) <= 7.92710
                                0.00000
                            else
                                0.37705
                        else
                            if f.get(3) <= 2.41925
                                if f.get(13) <= 3.50000
                                    0.38547
                                else
                                    0.00000
                            else
                                if f.get(4) <= 11.92210
                                    0.75197
                                else
                                    0.41441
                    else
                        if f.get(23) <= 0.63870
                            if f.get(1) <= 42.08500
                                if f.get(24) <= 1.04095
                                    0.39292
                                else
                                    0.62276
                            else
                                if f.get(19) <= -0.03765
                                    0.55250
                                else
                                    0.73502
                        else
                            if f.get(24) <= 0.69020
                                if f.get(5) <= 1.68835
                                    0.56748
                                else
                                    0.79183
                            else
                                if f.get(4) <= 26.71975
                                    0.72971
                                else
                                    0.55790
                else
                    if f.get(17) <= -1.02065
                        if f.get(10) <= 0.50000
                            if f.get(23) <= 1.05495
                                if f.get(6) <= 1.19185
                                    0.08127
                                else
                                    0.70890
                            else
                                0.08425
                        else
                            if f.get(19) <= 0.32690
                                if f.get(26) <= 22.11465
                                    0.34328
                                else
                                    0.67153
                            else
                                0.95392
                    else
                        if f.get(26) <= 5.17790
                            if f.get(23) <= 0.76145
                                if f.get(7) <= 24.88390
                                    0.85673
                                else
                                    0.40378
                            else
                                if f.get(22) <= 0.50000
                                    0.80717
                                else
                                    0.46939
                        else
                            if f.get(15) <= 0.50000
                                if f.get(13) <= 4.50000
                                    0.71567
                                else
                                    0.91130
                            else
                                if f.get(22) <= 0.50000
                                    0.88462
                                else
                                    1.00000
            else
                if f.get(23) <= 1.06360
                    if f.get(24) <= 2.39240
                        if f.get(2) <= 0.28890
                            if f.get(24) <= 0.32325
                                if f.get(24) <= 0.03865
                                    0.47917
                                else
                                    0.86966
                            else
                                if f.get(6) <= 0.85055
                                    0.65609
                                else
                                    0.79655
                        else
                            if f.get(16) <= 0.50000
                                if f.get(17) <= 0.14145
                                    0.92000
                                else
                                    0.61424
                            else
                                0.00000
                    else
                        if f.get(2) <= -3.48600
                            if f.get(1) <= 37.66000
                                if f.get(18) <= -0.50355
                                    0.19492
                                else
                                    0.77072
                            else
                                if f.get(7) <= 23.22965
                                    0.61686
                                else
                                    0.90551
                        else
                            if f.get(3) <= 0.87055
                                if f.get(10) <= 0.50000
                                    0.52767
                                else
                                    0.83587
                            else
                                if f.get(8) <= 0.80610
                                    0.59410
                                else
                                    0.17829
                else
                    if f.get(20) <= 0.50000
                        if f.get(7) <= 11.82390
                            0.55645
                        else
                            if f.get(3) <= 4.76460
                                if f.get(9) <= 0.66290
                                    0.88775
                                else
                                    0.79526
                            else
                                0.30131
                    else
                        if f.get(17) <= 0.49345
                            if f.get(7) <= 27.13270
                                if f.get(2) <= -1.23470
                                    0.96305
                                else
                                    0.86520
                            else
                                if f.get(19) <= -0.15225
                                    0.48936
                                else
                                    0.81911
                        else
                            if f.get(7) <= 21.29100
                                if f.get(25) <= 0.00000
                                    0.94845
                                else
                                    0.85673
                            else
                                if f.get(26) <= 25.94585
                                    1.00000
                                else
                                    0.93730

// --- TREE 2 ---
export method tree_2(array<float> f) =>
    if f.get(0) <= 345600.00000
        if f.get(6) <= 1.17765
            if f.get(23) <= 0.54865
                if f.get(8) <= 0.20055
                    if f.get(1) <= 40.18000
                        if f.get(25) <= 0.00000
                            if f.get(23) <= 0.08905
                                if f.get(6) <= 0.56795
                                    0.43396
                                else
                                    0.07702
                            else
                                if f.get(13) <= 4.50000
                                    0.13172
                                else
                                    0.41566
                        else
                            if f.get(4) <= -0.08235
                                if f.get(1) <= 35.89000
                                    0.15653
                                else
                                    0.00000
                            else
                                if f.get(26) <= 1.00765
                                    0.62422
                                else
                                    0.19114
                    else
                        if f.get(3) <= 1.26385
                            0.00000
                        else
                            0.85673
                else
                    if f.get(1) <= 40.28000
                        if f.get(19) <= -0.06280
                            if f.get(18) <= -0.08610
                                if f.get(23) <= 0.16405
                                    0.07737
                                else
                                    0.30055
                            else
                                if f.get(19) <= -1.53375
                                    0.01269
                                else
                                    0.21458
                        else
                            if f.get(0) <= 50400.00000
                                if f.get(3) <= 1.29655
                                    0.26944
                                else
                                    0.11492
                            else
                                if f.get(26) <= 20.19540
                                    0.38066
                                else
                                    0.16572
                    else
                        if f.get(18) <= 0.02465
                            if f.get(7) <= 13.51290
                                if f.get(24) <= 0.21535
                                    0.00000
                                else
                                    0.43396
                            else
                                if f.get(5) <= -0.52600
                                    0.08425
                                else
                                    0.67228
                        else
                            if f.get(19) <= -0.23110
                                0.88746
                            else
                                0.55850
            else
                if f.get(1) <= 35.80500
                    if f.get(7) <= 17.97525
                        if f.get(2) <= -1.22845
                            if f.get(17) <= -0.38260
                                if f.get(23) <= 0.77105
                                    0.12568
                                else
                                    0.00000
                            else
                                if f.get(8) <= 0.51995
                                    0.34673
                                else
                                    0.72441
                        else
                            if f.get(1) <= 35.30500
                                if f.get(6) <= 0.97990
                                    0.33633
                                else
                                    0.20100
                            else
                                0.00000
                    else
                        if f.get(18) <= -0.19595
                            if f.get(8) <= 0.38880
                                if f.get(7) <= 24.46405
                                    0.02975
                                else
                                    0.34137
                            else
                                if f.get(23) <= 0.59155
                                    0.20814
                                else
                                    0.54412
                        else
                            if f.get(4) <= -48.90980
                                if f.get(9) <= 1.43745
                                    0.75761
                                else
                                    0.41441
                            else
                                if f.get(9) <= 1.26340
                                    0.35134
                                else
                                    0.44414
                else
                    if f.get(23) <= 0.81725
                        if f.get(17) <= 0.29210
                            if f.get(3) <= 0.92955
                                if f.get(4) <= 1.46980
                                    0.53398
                                else
                                    0.84579
                            else
                                if f.get(26) <= 11.73910
                                    0.27816
                                else
                                    0.58430
                        else
                            if f.get(6) <= 1.06575
                                if f.get(17) <= 1.32605
                                    0.09040
                                else
                                    0.48936
                            else
                                0.59811
                    else
                        if f.get(17) <= 0.43675
                            if f.get(4) <= -30.85965
                                if f.get(19) <= -0.29370
                                    0.45098
                                else
                                    0.81672
                            else
                                if f.get(4) <= -5.90895
                                    0.46017
                                else
                                    0.57335
                        else
                            if f.get(18) <= -0.15405
                                if f.get(24) <= 1.05240
                                    0.92160
                                else
                                    0.72125
                            else
                                if f.get(4) <= -12.32020
                                    0.80063
                                else
                                    0.59027
        else
            if f.get(8) <= 0.43245
                if f.get(9) <= 0.19775
                    if f.get(3) <= 1.32795
                        if f.get(26) <= 2.58905
                            if f.get(9) <= 0.14705
                                0.00000
                            else
                                0.64789
                        else
                            if f.get(9) <= 0.03815
                                if f.get(19) <= -0.22685
                                    0.21905
                                else
                                    0.06977
                            else
                                if f.get(20) <= 0.50000
                                    0.01515
                                else
                                    0.09871
                    else
                        if f.get(6) <= 1.70340
                            if f.get(23) <= 0.44225
                                if f.get(17) <= 0.43550
                                    0.15345
                                else
                                    0.53991
                            else
                                if f.get(8) <= 0.20710
                                    0.33435
                                else
                                    0.82143
                        else
                            if f.get(7) <= 26.57780
                                if f.get(8) <= 0.03180
                                    0.13295
                                else
                                    0.80100
                            else
                                if f.get(24) <= 2.85360
                                    0.21231
                                else
                                    0.68220
                else
                    if f.get(2) <= -2.02045
                        if f.get(10) <= 0.50000
                            if f.get(24) <= 1.86225
                                if f.get(8) <= 0.23805
                                    0.78113
                                else
                                    0.49917
                            else
                                if f.get(6) <= 1.85470
                                    0.44444
                                else
                                    0.06907
                        else
                            if f.get(6) <= 1.82355
                                if f.get(9) <= 0.66470
                                    0.19008
                                else
                                    0.00000
                            else
                                if f.get(3) <= 1.41665
                                    0.83287
                                else
                                    0.49198
                    else
                        if f.get(24) <= 0.08430
                            if f.get(5) <= -1.13450
                                0.34673
                            else
                                if f.get(6) <= 1.19745
                                    0.43396
                                else
                                    0.00000
                        else
                            if f.get(26) <= 3.78115
                                if f.get(26) <= 3.66630
                                    0.46780
                                else
                                    0.74729
                            else
                                if f.get(1) <= 32.83000
                                    0.24498
                                else
                                    0.43942
            else
                if f.get(8) <= 0.69890
                    if f.get(6) <= 2.25255
                        if f.get(9) <= 5.69270
                            if f.get(18) <= -0.24110
                                if f.get(26) <= 19.06860
                                    0.70735
                                else
                                    0.46532
                            else
                                if f.get(1) <= 35.28500
                                    0.40620
                                else
                                    0.57848
                        else
                            if f.get(12) <= 0.50000
                                if f.get(26) <= 17.63840
                                    0.33508
                                else
                                    0.00000
                            else
                                0.71875
                    else
                        if f.get(19) <= 0.17345
                            if f.get(24) <= 0.69375
                                0.72441
                            else
                                0.00000
                        else
                            if f.get(1) <= 10.25000
                                1.00000
                            else
                                0.87342
                else
                    if f.get(6) <= 1.63430
                        if f.get(1) <= 30.45500
                            if f.get(17) <= 0.23315
                                if f.get(8) <= 0.96125
                                    0.43213
                                else
                                    0.66502
                            else
                                if f.get(6) <= 1.23740
                                    0.96084
                                else
                                    0.56684
                        else
                            if f.get(23) <= 2.02385
                                if f.get(0) <= 50400.00000
                                    0.49289
                                else
                                    0.67446
                            else
                                if f.get(8) <= 0.75250
                                    0.32624
                                else
                                    0.82022
                    else
                        if f.get(1) <= 28.33000
                            if f.get(17) <= -0.73810
                                if f.get(2) <= -6.26595
                                    0.80831
                                else
                                    0.40351
                            else
                                if f.get(9) <= 0.35020
                                    0.53488
                                else
                                    0.90591
                        else
                            if f.get(3) <= 4.84615
                                if f.get(6) <= 1.68555
                                    0.48252
                                else
                                    0.76061
                            else
                                0.19492
    else
        if f.get(23) <= 0.40110
            if f.get(3) <= 0.03830
                if f.get(17) <= -0.04925
                    if f.get(4) <= 8.15825
                        if f.get(24) <= 1.24320
                            if f.get(9) <= 0.14350
                                if f.get(24) <= 0.87720
                                    0.12921
                                else
                                    0.59410
                            else
                                if f.get(4) <= -13.38090
                                    0.97642
                                else
                                    0.82922
                        else
                            if f.get(9) <= 0.70000
                                if f.get(24) <= 2.12180
                                    0.15033
                                else
                                    0.57295
                            else
                                0.89610
                    else
                        if f.get(7) <= 46.36245
                            if f.get(8) <= 0.50700
                                if f.get(17) <= -1.06955
                                    0.79769
                                else
                                    0.53488
                            else
                                if f.get(17) <= -0.60005
                                    1.00000
                                else
                                    0.96595
                        else
                            0.53488
                else
                    if f.get(6) <= 0.72950
                        if f.get(1) <= 43.02500
                            if f.get(2) <= 0.39275
                                if f.get(6) <= 0.63540
                                    0.29487
                                else
                                    0.00000
                            else
                                0.47917
                        else
                            0.63303
                    else
                        if f.get(17) <= -0.02355
                            0.13690
                        else
                            if f.get(9) <= 0.57120
                                if f.get(12) <= 0.50000
                                    0.34900
                                else
                                    0.56491
                            else
                                if f.get(7) <= 16.23195
                                    0.61583
                                else
                                    0.86075
            else
                if f.get(3) <= 1.20825
                    if f.get(26) <= 21.48005
                        if f.get(23) <= 0.12285
                            if f.get(26) <= 12.77940
                                if f.get(8) <= 0.05725
                                    0.15048
                                else
                                    0.30300
                            else
                                if f.get(23) <= 0.07765
                                    0.07612
                                else
                                    0.19547
                        else
                            if f.get(8) <= 0.21665
                                if f.get(1) <= 33.94500
                                    0.60182
                                else
                                    0.36121
                            else
                                if f.get(3) <= 1.19525
                                    0.52722
                                else
                                    0.83287
                    else
                        if f.get(19) <= -0.52285
                            if f.get(1) <= 42.26000
                                if f.get(3) <= 0.26165
                                    0.21296
                                else
                                    0.00000
                            else
                                0.53488
                        else
                            if f.get(6) <= 1.17415
                                if f.get(8) <= 0.09065
                                    0.12234
                                else
                                    0.54713
                            else
                                if f.get(24) <= 0.96850
                                    0.81083
                                else
                                    0.48102
                else
                    if f.get(8) <= 0.09555
                        if f.get(3) <= 2.74490
                            if f.get(3) <= 1.42840
                                if f.get(9) <= 0.00020
                                    0.29487
                                else
                                    0.09352
                            else
                                if f.get(19) <= -0.15850
                                    0.50429
                                else
                                    0.19680
                        else
                            if f.get(9) <= 0.00510
                                0.24731
                            else
                                if f.get(19) <= 0.32805
                                    0.18699
                                else
                                    0.63812
                    else
                        if f.get(18) <= -0.19700
                            if f.get(17) <= -0.12790
                                if f.get(26) <= 4.96955
                                    0.00000
                                else
                                    0.31684
                            else
                                if f.get(17) <= -0.10060
                                    0.69697
                                else
                                    0.36103
                        else
                            if f.get(6) <= 0.87815
                                if f.get(4) <= -17.74920
                                    0.49052
                                else
                                    0.12299
                            else
                                if f.get(4) <= 28.12965
                                    0.58422
                                else
                                    0.31507
        else
            if f.get(7) <= 24.43615
                if f.get(9) <= 0.62395
                    if f.get(23) <= 0.52565
                        if f.get(3) <= 1.62170
                            if f.get(23) <= 0.44640
                                if f.get(5) <= 0.55955
                                    0.62963
                                else
                                    0.45098
                            else
                                if f.get(24) <= 0.11180
                                    0.97354
                                else
                                    0.72274
                        else
                            if f.get(8) <= 0.20740
                                if f.get(3) <= 2.61425
                                    0.75824
                                else
                                    0.31507
                            else
                                if f.get(1) <= 40.77500
                                    0.14110
                                else
                                    0.50549
                    else
                        if f.get(18) <= -0.42945
                            if f.get(23) <= 0.69885
                                if f.get(26) <= 10.54650
                                    0.00000
                                else
                                    0.69697
                            else
                                if f.get(19) <= -0.08220
                                    0.87815
                                else
                                    0.70014
                        else
                            if f.get(6) <= 1.20230
                                if f.get(8) <= 0.22340
                                    0.00000
                                else
                                    0.83184
                            else
                                if f.get(10) <= 0.50000
                                    0.88127
                                else
                                    0.95440
                else
                    if f.get(19) <= 0.26620
                        if f.get(23) <= 0.66300
                            if f.get(9) <= 1.48535
                                if f.get(26) <= 1.91685
                                    0.82922
                                else
                                    0.61328
                            else
                                if f.get(13) <= 2.50000
                                    0.51356
                                else
                                    0.65300
                        else
                            if f.get(1) <= 38.58000
                                if f.get(26) <= 23.20590
                                    0.65779
                                else
                                    0.31507
                            else
                                if f.get(8) <= 0.49150
                                    0.51707
                                else
                                    0.76043
                    else
                        if f.get(7) <= 13.84080
                            if f.get(17) <= 0.15665
                                0.53488
                            else
                                0.23469
                        else
                            if f.get(9) <= 1.55515
                                if f.get(9) <= 1.25355
                                    0.78985
                                else
                                    0.34673
                            else
                                if f.get(17) <= 0.21105
                                    0.90563
                                else
                                    0.63014
            else
                if f.get(2) <= -9.33295
                    if f.get(26) <= 23.68450
                        if f.get(3) <= 1.83820
                            if f.get(7) <= 31.43520
                                0.78632
                            else
                                0.24731
                        else
                            0.23077
                    else
                        if f.get(19) <= 0.28660
                            if f.get(18) <= -0.36615
                                0.64377
                            else
                                0.95134
                        else
                            0.46939
                else
                    if f.get(1) <= 60.64000
                        if f.get(3) <= 0.92440
                            if f.get(8) <= 0.75115
                                if f.get(24) <= 0.28720
                                    0.00000
                                else
                                    0.61018
                            else
                                if f.get(7) <= 25.17235
                                    0.46309
                                else
                                    0.78463
                        else
                            if f.get(18) <= 0.13270
                                if f.get(15) <= 0.50000
                                    0.75155
                                else
                                    0.85270
                            else
                                if f.get(14) <= 0.50000
                                    0.84061
                                else
                                    1.00000
                    else
                        if f.get(23) <= 1.13610
                            if f.get(3) <= 1.08855
                                if f.get(3) <= 0.92350
                                    0.90196
                                else
                                    1.00000
                            else
                                0.62779
                        else
                            if f.get(24) <= 0.47070
                                if f.get(19) <= 0.07560
                                    1.00000
                                else
                                    0.98660
                            else
                                0.87342

// --- TREE 3 ---
export method tree_3(array<float> f) =>
    if f.get(23) <= 0.42845
        if f.get(0) <= 345600.00000
            if f.get(23) <= 0.23615
                if f.get(4) <= -0.56625
                    if f.get(3) <= 0.22570
                        if f.get(6) <= 1.03850
                            if f.get(17) <= 0.65670
                                if f.get(2) <= 0.06740
                                    0.24121
                                else
                                    0.51111
                            else
                                if f.get(24) <= 2.33685
                                    0.00000
                                else
                                    0.13295
                        else
                            if f.get(9) <= 9.75000
                                if f.get(7) <= 38.68000
                                    0.34125
                                else
                                    0.59547
                            else
                                0.83133
                    else
                        if f.get(6) <= 2.04585
                            if f.get(23) <= 0.10045
                                if f.get(24) <= 1.09380
                                    0.09934
                                else
                                    0.17262
                            else
                                if f.get(6) <= 0.70085
                                    0.04618
                                else
                                    0.18486
                        else
                            if f.get(19) <= -0.10535
                                0.00000
                            else
                                if f.get(6) <= 2.27005
                                    0.77528
                                else
                                    0.37705
                else
                    if f.get(8) <= 0.47125
                        if f.get(26) <= 0.89050
                            if f.get(19) <= -0.11890
                                if f.get(24) <= 0.37935
                                    0.15033
                                else
                                    0.00000
                            else
                                0.00000
                        else
                            if f.get(18) <= 0.00350
                                if f.get(6) <= 1.24955
                                    0.34776
                                else
                                    0.60526
                            else
                                if f.get(26) <= 3.50430
                                    0.00000
                                else
                                    0.16084
                    else
                        if f.get(4) <= 1.88085
                            if f.get(17) <= 0.00855
                                0.92284
                            else
                                0.28870
                        else
                            0.10314
            else
                if f.get(3) <= 2.09155
                    if f.get(23) <= 0.24055
                        if f.get(6) <= 0.98610
                            if f.get(10) <= 0.50000
                                if f.get(18) <= -0.06475
                                    0.71875
                                else
                                    0.15033
                            else
                                0.00000
                        else
                            if f.get(5) <= -0.37820
                                if f.get(7) <= 31.32970
                                    0.95392
                                else
                                    0.63303
                            else
                                if f.get(18) <= -0.06540
                                    0.75976
                                else
                                    0.38017
                    else
                        if f.get(24) <= 0.00285
                            0.69697
                        else
                            if f.get(1) <= 40.30500
                                if f.get(17) <= 1.12950
                                    0.26455
                                else
                                    0.02864
                            else
                                if f.get(8) <= 0.35520
                                    0.00000
                                else
                                    0.76420
                else
                    if f.get(4) <= -1.84735
                        if f.get(7) <= 24.80310
                            if f.get(13) <= 4.50000
                                if f.get(5) <= -0.24775
                                    0.20205
                                else
                                    0.02030
                            else
                                if f.get(18) <= -0.37225
                                    0.23469
                                else
                                    0.57295
                        else
                            if f.get(19) <= 0.27970
                                if f.get(6) <= 0.92670
                                    0.33333
                                else
                                    0.06830
                            else
                                0.00000
                    else
                        if f.get(4) <= -1.09215
                            0.78328
                        else
                            0.09091
        else
            if f.get(9) <= 0.36200
                if f.get(18) <= -0.12150
                    if f.get(9) <= 0.12095
                        if f.get(8) <= 0.14645
                            if f.get(13) <= 2.50000
                                if f.get(7) <= 45.57705
                                    0.15454
                                else
                                    0.34457
                            else
                                if f.get(5) <= 0.20635
                                    0.18304
                                else
                                    0.34348
                        else
                            if f.get(18) <= -0.30995
                                if f.get(1) <= 50.06500
                                    0.38017
                                else
                                    0.79633
                            else
                                if f.get(17) <= -0.00810
                                    0.86096
                                else
                                    0.50156
                    else
                        if f.get(9) <= 0.12205
                            0.90619
                        else
                            if f.get(24) <= 10.87425
                                if f.get(24) <= 5.46030
                                    0.33878
                                else
                                    0.09163
                            else
                                if f.get(1) <= 30.85000
                                    0.89399
                                else
                                    0.00000
                else
                    if f.get(7) <= 18.86200
                        if f.get(24) <= 1.11970
                            if f.get(4) <= -1.53780
                                if f.get(1) <= 33.80500
                                    0.57983
                                else
                                    0.35621
                            else
                                if f.get(8) <= 0.01650
                                    0.00000
                                else
                                    0.64080
                        else
                            if f.get(23) <= 0.11145
                                if f.get(26) <= 4.98300
                                    0.07468
                                else
                                    0.00000
                            else
                                if f.get(3) <= 1.56530
                                    0.53014
                                else
                                    0.00000
                    else
                        if f.get(19) <= -0.19135
                            if f.get(19) <= -0.20405
                                if f.get(17) <= 0.17775
                                    0.53488
                                else
                                    0.07508
                            else
                                0.84526
                        else
                            if f.get(8) <= 0.11725
                                if f.get(23) <= 0.01970
                                    0.16953
                                else
                                    0.04665
                            else
                                if f.get(5) <= 0.92400
                                    0.50893
                                else
                                    0.26251
            else
                if f.get(19) <= -0.81445
                    if f.get(2) <= -0.04105
                        if f.get(6) <= 0.97305
                            0.12921
                        else
                            0.00000
                    else
                        0.49640
                else
                    if f.get(8) <= 0.37885
                        if f.get(25) <= 0.00000
                            if f.get(23) <= 0.38720
                                if f.get(26) <= 29.21380
                                    0.47693
                                else
                                    0.69043
                            else
                                if f.get(9) <= 0.81550
                                    0.82670
                                else
                                    0.41650
                        else
                            if f.get(23) <= 0.27460
                                if f.get(24) <= 0.97755
                                    0.19874
                                else
                                    0.41272
                            else
                                if f.get(19) <= -0.02255
                                    0.61709
                                else
                                    0.41998
                    else
                        if f.get(11) <= 0.50000
                            if f.get(6) <= 1.06275
                                if f.get(2) <= -0.30765
                                    0.63619
                                else
                                    0.53940
                            else
                                if f.get(3) <= 0.63105
                                    0.88111
                                else
                                    0.65827
                        else
                            if f.get(8) <= 0.73865
                                if f.get(22) <= 0.50000
                                    0.44736
                                else
                                    0.66346
                            else
                                if f.get(21) <= 0.50000
                                    0.93949
                                else
                                    0.35115
    else
        if f.get(16) <= 0.50000
            if f.get(0) <= 345600.00000
                if f.get(0) <= 50400.00000
                    if f.get(23) <= 1.80485
                        if f.get(13) <= 4.50000
                            if f.get(6) <= 1.14355
                                if f.get(1) <= 44.94000
                                    0.26720
                                else
                                    0.71671
                            else
                                if f.get(7) <= 46.07600
                                    0.43882
                                else
                                    0.26188
                        else
                            if f.get(9) <= 5.77820
                                if f.get(5) <= -1.04020
                                    0.47099
                                else
                                    0.33860
                            else
                                if f.get(2) <= -3.46720
                                    0.74194
                                else
                                    0.11173
                    else
                        if f.get(6) <= 1.21235
                            if f.get(3) <= 2.01405
                                if f.get(15) <= 0.50000
                                    0.48936
                                else
                                    0.92400
                            else
                                if f.get(2) <= -0.00775
                                    0.41257
                                else
                                    0.15862
                        else
                            if f.get(19) <= -1.38630
                                if f.get(19) <= -2.07230
                                    0.50156
                                else
                                    0.13295
                            else
                                if f.get(6) <= 1.69790
                                    0.62385
                                else
                                    0.80072
                else
                    if f.get(1) <= 40.13500
                        if f.get(3) <= 1.56505
                            if f.get(15) <= 0.50000
                                if f.get(1) <= 32.14500
                                    0.39594
                                else
                                    0.45654
                            else
                                if f.get(24) <= 0.26805
                                    0.41774
                                else
                                    0.65638
                        else
                            if f.get(3) <= 7.47715
                                if f.get(23) <= 0.80335
                                    0.35811
                                else
                                    0.56975
                            else
                                if f.get(8) <= 0.38900
                                    0.32136
                                else
                                    0.83167
                    else
                        if f.get(7) <= 12.94465
                            if f.get(17) <= 0.42645
                                0.00000
                            else
                                0.33824
                        else
                            if f.get(6) <= 1.12775
                                if f.get(17) <= -0.08275
                                    0.79167
                                else
                                    0.56278
                            else
                                if f.get(8) <= 0.66630
                                    0.38547
                                else
                                    0.80405
            else
                if f.get(8) <= 0.43820
                    if f.get(7) <= 16.13655
                        if f.get(8) <= 0.35970
                            if f.get(9) <= 0.48230
                                0.10314
                            else
                                0.63753
                        else
                            if f.get(26) <= 4.71235
                                0.12568
                            else
                                0.00000
                    else
                        if f.get(8) <= 0.24020
                            if f.get(18) <= -0.74535
                                0.56403
                            else
                                if f.get(5) <= -1.13325
                                    0.14110
                                else
                                    0.00000
                        else
                            if f.get(21) <= 0.50000
                                if f.get(17) <= -0.27260
                                    0.75922
                                else
                                    0.48392
                            else
                                if f.get(26) <= 21.90840
                                    0.20131
                                else
                                    0.60526
                else
                    if f.get(9) <= 2.38750
                        if f.get(3) <= 1.35050
                            if f.get(23) <= 0.66120
                                if f.get(23) <= 0.63925
                                    0.71875
                                else
                                    0.37355
                            else
                                if f.get(2) <= 0.92090
                                    0.78592
                                else
                                    0.95309
                        else
                            if f.get(24) <= 0.87030
                                if f.get(1) <= 36.49500
                                    0.88085
                                else
                                    0.72098
                            else
                                if f.get(3) <= 2.49890
                                    0.86962
                                else
                                    0.95022
                    else
                        if f.get(8) <= 0.56250
                            if f.get(24) <= 2.62530
                                if f.get(9) <= 6.17835
                                    0.51111
                                else
                                    0.15367
                            else
                                if f.get(18) <= -0.45855
                                    0.43396
                                else
                                    0.84293
                        else
                            if f.get(18) <= -1.20470
                                0.22330
                            else
                                if f.get(2) <= 1.06175
                                    0.70517
                                else
                                    0.93730
        else
            if f.get(6) <= 1.67670
                if f.get(1) <= 37.41500
                    if f.get(8) <= 0.43820
                        if f.get(24) <= 1.97795
                            if f.get(24) <= 0.73620
                                if f.get(1) <= 35.72000
                                    0.51738
                                else
                                    0.00000
                            else
                                if f.get(5) <= 0.52970
                                    0.14213
                                else
                                    0.50764
                        else
                            if f.get(2) <= -7.72390
                                if f.get(8) <= 0.34130
                                    0.00000
                                else
                                    0.62162
                            else
                                if f.get(24) <= 3.11955
                                    0.52975
                                else
                                    0.68771
                    else
                        if f.get(0) <= 345600.00000
                            if f.get(6) <= 1.43825
                                if f.get(24) <= 1.61670
                                    0.44577
                                else
                                    0.64486
                            else
                                if f.get(24) <= 0.84595
                                    0.54151
                                else
                                    0.74194
                        else
                            if f.get(3) <= 0.95125
                                if f.get(24) <= 2.00570
                                    0.14110
                                else
                                    0.63303
                            else
                                if f.get(17) <= -1.22610
                                    0.40351
                                else
                                    0.77336
                else
                    if f.get(15) <= 0.50000
                        if f.get(8) <= 0.67035
                            if f.get(13) <= 1.50000
                                if f.get(6) <= 0.85155
                                    0.28571
                                else
                                    0.59340
                            else
                                if f.get(24) <= 0.69000
                                    0.56790
                                else
                                    0.72470
                        else
                            if f.get(3) <= 0.71255
                                if f.get(3) <= 0.70105
                                    0.70066
                                else
                                    0.09091
                            else
                                if f.get(3) <= 2.69410
                                    0.78749
                                else
                                    0.58530
                    else
                        if f.get(23) <= 0.49390
                            0.36508
                        else
                            if f.get(7) <= 31.04270
                                if f.get(1) <= 38.98000
                                    0.53488
                                else
                                    0.86336
                            else
                                if f.get(7) <= 32.03175
                                    0.23469
                                else
                                    0.75410
            else
                if f.get(17) <= -1.40480
                    if f.get(2) <= -10.34170
                        0.80349
                    else
                        0.30131
                else
                    if f.get(5) <= -0.13175
                        if f.get(24) <= 3.03595
                            if f.get(18) <= -0.43165
                                0.40828
                            else
                                0.29487
                        else
                            0.84663
                    else
                        if f.get(23) <= 4.71190
                            if f.get(8) <= 0.24805
                                0.11330
                            else
                                if f.get(8) <= 0.68275
                                    0.78684
                                else
                                    0.91753
                        else
                            0.44805

// --- TREE 4 ---
export method tree_4(array<float> f) =>
    if f.get(8) <= 0.43455
        if f.get(0) <= 345600.00000
            if f.get(8) <= 0.19995
                if f.get(8) <= 0.10255
                    if f.get(0) <= 50400.00000
                        if f.get(6) <= 1.96435
                            if f.get(4) <= -10.24035
                                if f.get(1) <= 38.22500
                                    0.09753
                                else
                                    0.65714
                            else
                                if f.get(3) <= 0.15175
                                    0.21296
                                else
                                    0.03184
                        else
                            if f.get(17) <= -0.07505
                                if f.get(24) <= 1.39975
                                    0.19771
                                else
                                    0.53488
                            else
                                0.64143
                    else
                        if f.get(18) <= 0.00540
                            if f.get(3) <= 1.35520
                                if f.get(17) <= 0.03900
                                    0.16745
                                else
                                    0.08283
                            else
                                if f.get(23) <= 0.01165
                                    0.27527
                                else
                                    0.19209
                        else
                            if f.get(9) <= 0.12220
                                if f.get(3) <= 1.38700
                                    0.01859
                                else
                                    0.15327
                            else
                                if f.get(2) <= -0.50750
                                    0.00000
                                else
                                    0.36099
                else
                    if f.get(18) <= -0.76475
                        if f.get(2) <= -4.18710
                            if f.get(17) <= -1.38805
                                0.00000
                            else
                                0.10798
                        else
                            if f.get(8) <= 0.15590
                                0.90196
                            else
                                0.37705
                    else
                        if f.get(18) <= 0.10585
                            if f.get(26) <= 3.04645
                                if f.get(8) <= 0.12300
                                    0.43207
                                else
                                    0.18194
                            else
                                if f.get(9) <= 0.11535
                                    0.74937
                                else
                                    0.17342
                        else
                            if f.get(7) <= 23.92660
                                0.70827
                            else
                                if f.get(23) <= 0.16545
                                    0.36800
                                else
                                    0.02270
            else
                if f.get(3) <= 1.76920
                    if f.get(24) <= 0.37980
                        if f.get(21) <= 0.50000
                            if f.get(23) <= 0.41655
                                if f.get(5) <= -0.12105
                                    0.15562
                                else
                                    0.33706
                            else
                                if f.get(26) <= 4.75005
                                    0.19567
                                else
                                    0.49455
                        else
                            if f.get(1) <= 26.56000
                                if f.get(17) <= 0.18280
                                    0.18909
                                else
                                    0.45476
                            else
                                if f.get(7) <= 47.16805
                                    0.15427
                                else
                                    0.46000
                    else
                        if f.get(17) <= -0.46930
                            if f.get(23) <= 0.43585
                                if f.get(3) <= 1.46250
                                    0.06848
                                else
                                    0.27711
                            else
                                if f.get(4) <= -11.12550
                                    0.17293
                                else
                                    0.57295
                        else
                            if f.get(24) <= 0.52855
                                if f.get(3) <= 1.41040
                                    0.41176
                                else
                                    0.20131
                            else
                                if f.get(6) <= 1.88780
                                    0.26251
                                else
                                    0.82734
                else
                    if f.get(18) <= -0.31800
                        if f.get(18) <= -0.58355
                            if f.get(24) <= 2.37420
                                if f.get(24) <= 1.85580
                                    0.14712
                                else
                                    0.00000
                            else
                                if f.get(24) <= 2.52385
                                    0.72125
                                else
                                    0.24528
                        else
                            if f.get(7) <= 30.34125
                                if f.get(0) <= 50400.00000
                                    0.12127
                                else
                                    0.52530
                            else
                                if f.get(6) <= 1.16425
                                    0.39968
                                else
                                    0.77261
                    else
                        if f.get(26) <= 1.23205
                            0.70306
                        else
                            if f.get(23) <= 0.37005
                                0.81176
                            else
                                if f.get(8) <= 0.37885
                                    0.26795
                                else
                                    0.39311
        else
            if f.get(9) <= 0.12830
                if f.get(23) <= 0.05160
                    if f.get(26) <= 1.52070
                        if f.get(8) <= 0.08305
                            if f.get(24) <= 2.70130
                                if f.get(24) <= 1.35895
                                    0.28795
                                else
                                    0.00000
                            else
                                0.53488
                        else
                            0.92000
                    else
                        if f.get(2) <= -5.32315
                            if f.get(17) <= -1.09125
                                if f.get(8) <= 0.01530
                                    0.00000
                                else
                                    0.24731
                            else
                                if f.get(1) <= 30.31500
                                    0.00000
                                else
                                    0.71239
                        else
                            if f.get(1) <= 30.11000
                                if f.get(18) <= -0.56705
                                    0.18699
                                else
                                    0.00000
                            else
                                if f.get(18) <= -0.49800
                                    0.05569
                                else
                                    0.18833
                else
                    if f.get(24) <= 0.04865
                        0.81176
                    else
                        if f.get(3) <= 0.68725
                            0.63753
                        else
                            if f.get(19) <= -0.22285
                                if f.get(23) <= 0.08450
                                    0.62664
                                else
                                    0.25414
                            else
                                if f.get(26) <= 0.61810
                                    0.74194
                                else
                                    0.21883
            else
                if f.get(7) <= 27.59325
                    if f.get(14) <= 0.50000
                        if f.get(26) <= 11.54200
                            if f.get(3) <= 0.99690
                                if f.get(7) <= 12.62355
                                    0.22981
                                else
                                    0.42453
                            else
                                if f.get(4) <= 20.32820
                                    0.52184
                                else
                                    0.22330
                        else
                            if f.get(9) <= 0.19685
                                if f.get(1) <= 44.80000
                                    0.19362
                                else
                                    0.54644
                            else
                                if f.get(24) <= 13.99890
                                    0.40499
                                else
                                    0.75117
                    else
                        if f.get(4) <= -3.18060
                            if f.get(4) <= -44.80985
                                if f.get(23) <= 0.20765
                                    0.95134
                                else
                                    0.56098
                            else
                                if f.get(17) <= 0.16145
                                    0.09091
                                else
                                    0.67828
                        else
                            if f.get(22) <= 0.50000
                                if f.get(5) <= 1.83195
                                    0.59453
                                else
                                    0.84018
                            else
                                if f.get(9) <= 0.49945
                                    0.80831
                                else
                                    0.96764
                else
                    if f.get(3) <= 0.94630
                        if f.get(1) <= 28.25000
                            if f.get(6) <= 0.97495
                                if f.get(19) <= -0.03475
                                    0.44598
                                else
                                    0.13295
                            else
                                if f.get(4) <= -49.55850
                                    1.00000
                                else
                                    0.73896
                        else
                            if f.get(21) <= 0.50000
                                if f.get(1) <= 52.09000
                                    0.52767
                                else
                                    0.75824
                            else
                                if f.get(24) <= 3.28645
                                    0.38202
                                else
                                    0.11147
                    else
                        if f.get(5) <= 6.14250
                            if f.get(26) <= 28.02000
                                if f.get(3) <= 2.16390
                                    0.52044
                                else
                                    0.69198
                            else
                                if f.get(19) <= -0.17675
                                    0.22330
                                else
                                    0.70356
                        else
                            if f.get(18) <= -1.22535
                                0.61259
                            else
                                0.00000
    else
        if f.get(16) <= 0.50000
            if f.get(0) <= 345600.00000
                if f.get(6) <= 1.20125
                    if f.get(23) <= 0.79045
                        if f.get(6) <= 0.77705
                            if f.get(8) <= 0.60545
                                if f.get(26) <= 9.23145
                                    0.21754
                                else
                                    0.06516
                            else
                                if f.get(6) <= 0.67910
                                    0.46649
                                else
                                    0.23300
                        else
                            if f.get(17) <= -4.42920
                                0.94845
                            else
                                if f.get(1) <= 40.58500
                                    0.35087
                                else
                                    0.56479
                    else
                        if f.get(8) <= 0.72550
                            if f.get(17) <= -0.00005
                                if f.get(18) <= -0.05705
                                    0.51068
                                else
                                    0.34988
                            else
                                if f.get(17) <= 0.39140
                                    0.32624
                                else
                                    0.46460
                        else
                            if f.get(0) <= 50400.00000
                                if f.get(24) <= 1.53815
                                    0.43778
                                else
                                    0.13105
                            else
                                if f.get(1) <= 47.34500
                                    0.56426
                                else
                                    0.90881
                else
                    if f.get(3) <= 2.27300
                        if f.get(8) <= 0.69975
                            if f.get(1) <= 23.58000
                                if f.get(8) <= 0.49620
                                    0.28196
                                else
                                    0.62371
                            else
                                if f.get(9) <= 2.52940
                                    0.48926
                                else
                                    0.26674
                        else
                            if f.get(2) <= 0.00475
                                if f.get(15) <= 0.50000
                                    0.58761
                                else
                                    0.74694
                            else
                                if f.get(19) <= -0.02965
                                    0.63303
                                else
                                    0.89658
                    else
                        if f.get(18) <= -0.10915
                            if f.get(13) <= 4.50000
                                if f.get(8) <= 0.45475
                                    0.09871
                                else
                                    0.67993
                            else
                                if f.get(23) <= 5.25810
                                    0.74970
                                else
                                    0.88230
                        else
                            if f.get(2) <= 0.26290
                                if f.get(8) <= 0.78580
                                    0.40883
                                else
                                    0.68945
                            else
                                if f.get(5) <= -0.52585
                                    0.72441
                                else
                                    0.96503
            else
                if f.get(3) <= 1.09660
                    if f.get(7) <= 8.80985
                        0.00000
                    else
                        if f.get(17) <= 0.06615
                            if f.get(15) <= 0.50000
                                if f.get(4) <= -3.44215
                                    0.65293
                                else
                                    0.89763
                            else
                                if f.get(17) <= -0.38925
                                    0.68401
                                else
                                    0.87164
                        else
                            if f.get(7) <= 28.87200
                                if f.get(4) <= -59.97955
                                    0.84293
                                else
                                    0.55751
                            else
                                if f.get(3) <= 0.63410
                                    0.86864
                                else
                                    0.68381
                else
                    if f.get(20) <= 0.50000
                        if f.get(3) <= 4.61785
                            if f.get(19) <= 0.00005
                                if f.get(26) <= 22.65080
                                    0.67589
                                else
                                    0.97121
                            else
                                if f.get(17) <= -1.05325
                                    0.68109
                                else
                                    0.86158
                        else
                            0.36508
                    else
                        if f.get(1) <= 37.70500
                            if f.get(23) <= 0.60135
                                0.43396
                            else
                                if f.get(9) <= 1.44840
                                    0.92913
                                else
                                    0.74275
                        else
                            if f.get(2) <= -0.13730
                                if f.get(19) <= 0.05035
                                    0.72851
                                else
                                    0.41317
                            else
                                if f.get(1) <= 40.12000
                                    0.49198
                                else
                                    0.91477
        else
            if f.get(8) <= 0.78625
                if f.get(26) <= 4.16600
                    if f.get(5) <= 0.65720
                        if f.get(3) <= 0.05575
                            if f.get(8) <= 0.60665
                                if f.get(4) <= -0.87490
                                    0.12568
                                else
                                    0.76744
                            else
                                if f.get(9) <= 2.11140
                                    1.00000
                                else
                                    0.75410
                        else
                            if f.get(0) <= 345600.00000
                                if f.get(1) <= 40.34500
                                    0.47622
                                else
                                    0.82966
                            else
                                if f.get(18) <= -0.29200
                                    0.50691
                                else
                                    0.64051
                    else
                        if f.get(5) <= 0.92985
                            if f.get(23) <= 0.82400
                                0.55645
                            else
                                if f.get(18) <= -0.55730
                                    0.87342
                                else
                                    1.00000
                        else
                            0.45098
                else
                    if f.get(23) <= 0.64770
                        if f.get(13) <= 4.50000
                            if f.get(17) <= -0.19650
                                if f.get(2) <= -5.77145
                                    0.49198
                                else
                                    0.73069
                            else
                                if f.get(26) <= 12.25875
                                    0.52877
                                else
                                    0.67280
                        else
                            if f.get(1) <= 28.51500
                                0.46939
                            else
                                0.00000
                    else
                        if f.get(13) <= 1.50000
                            if f.get(26) <= 9.16335
                                if f.get(24) <= 1.07710
                                    0.82401
                                else
                                    0.44694
                            else
                                if f.get(17) <= -0.03450
                                    0.51039
                                else
                                    0.67015
                        else
                            if f.get(0) <= 345600.00000
                                if f.get(2) <= -3.95675
                                    0.20354
                                else
                                    0.66432
                            else
                                if f.get(5) <= 2.63115
                                    0.83959
                                else
                                    0.70192
            else
                if f.get(15) <= 0.50000
                    if f.get(19) <= -0.95955
                        0.10798
                    else
                        if f.get(4) <= 6.96825
                            if f.get(20) <= 0.50000
                                if f.get(6) <= 1.14685
                                    0.63831
                                else
                                    0.76016
                            else
                                if f.get(17) <= 0.15525
                                    0.96305
                                else
                                    0.80304
                        else
                            if f.get(6) <= 0.77340
                                0.19220
                            else
                                if f.get(9) <= 3.57240
                                    0.83532
                                else
                                    0.74278
                else
                    if f.get(1) <= 38.65000
                        if f.get(23) <= 1.03895
                            0.07850
                        else
                            if f.get(23) <= 1.46435
                                0.87342
                            else
                                0.48936
                    else
                        if f.get(8) <= 0.79255
                            1.00000
                        else
                            if f.get(18) <= -0.12750
                                if f.get(19) <= -0.04940
                                    0.79908
                                else
                                    0.93058
                            else
                                if f.get(19) <= 0.08205
                                    0.73343
                                else
                                    0.94589

// --- TREE 5 ---
export method tree_5(array<float> f) =>
    if f.get(23) <= 0.55595
        if f.get(0) <= 345600.00000
            if f.get(19) <= 0.84650
                if f.get(1) <= 40.19500
                    if f.get(9) <= 0.28060
                        if f.get(5) <= 0.38455
                            if f.get(13) <= 4.50000
                                if f.get(17) <= 0.49820
                                    0.15994
                                else
                                    0.07483
                            else
                                if f.get(9) <= 0.08345
                                    0.24023
                                else
                                    0.15693
                        else
                            if f.get(24) <= 0.44660
                                if f.get(19) <= -0.02330
                                    0.87342
                                else
                                    0.24731
                            else
                                if f.get(1) <= 24.21500
                                    0.69697
                                else
                                    0.14712
                    else
                        if f.get(4) <= -2.34910
                            if f.get(2) <= -3.85860
                                if f.get(9) <= 1.14330
                                    0.46532
                                else
                                    0.70588
                            else
                                if f.get(17) <= -0.51840
                                    0.11100
                                else
                                    0.27329
                        else
                            if f.get(17) <= 0.19700
                                if f.get(18) <= -0.00950
                                    0.49198
                                else
                                    0.30942
                            else
                                if f.get(23) <= 0.31625
                                    0.35839
                                else
                                    0.08915
                else
                    if f.get(8) <= 0.66215
                        if f.get(19) <= 0.06350
                            if f.get(17) <= 0.04380
                                if f.get(4) <= -1.62060
                                    0.13556
                                else
                                    0.89399
                            else
                                if f.get(18) <= -0.06655
                                    0.12568
                                else
                                    0.00000
                        else
                            if f.get(7) <= 12.57660
                                0.88950
                            else
                                0.25651
                    else
                        if f.get(3) <= 0.55205
                            if f.get(23) <= 0.07825
                                0.82922
                            else
                                if f.get(24) <= 0.20020
                                    0.12568
                                else
                                    0.53488
                        else
                            if f.get(9) <= 0.58400
                                if f.get(9) <= 0.14910
                                    1.00000
                                else
                                    0.94152
                            else
                                0.69697
            else
                if f.get(26) <= 9.76065
                    if f.get(1) <= 18.43500
                        0.17293
                    else
                        0.00000
                else
                    if f.get(4) <= -17.94205
                        if f.get(19) <= 3.44375
                            if f.get(23) <= 0.48085
                                0.00000
                            else
                                0.17293
                        else
                            0.27711
                    else
                        0.50549
        else
            if f.get(1) <= 46.89500
                if f.get(26) <= 2.77725
                    if f.get(23) <= 0.33460
                        if f.get(9) <= 0.62230
                            if f.get(8) <= 0.01720
                                if f.get(5) <= 0.04055
                                    0.45545
                                else
                                    0.03272
                            else
                                if f.get(25) <= 0.00000
                                    0.47883
                                else
                                    0.30131
                        else
                            if f.get(3) <= 0.65780
                                if f.get(2) <= -0.56460
                                    0.86411
                                else
                                    0.56098
                            else
                                if f.get(5) <= 0.22155
                                    0.65058
                                else
                                    0.23469
                    else
                        if f.get(2) <= -0.19295
                            if f.get(10) <= 0.50000
                                if f.get(6) <= 1.13075
                                    0.48842
                                else
                                    0.73299
                            else
                                if f.get(26) <= 2.13715
                                    0.89870
                                else
                                    0.65058
                        else
                            if f.get(7) <= 20.12390
                                if f.get(18) <= -0.15765
                                    0.84102
                                else
                                    1.00000
                            else
                                0.64143
                else
                    if f.get(14) <= 0.50000
                        if f.get(23) <= 0.16985
                            if f.get(3) <= 0.03800
                                if f.get(8) <= 0.55190
                                    0.38521
                                else
                                    0.77218
                            else
                                if f.get(9) <= 0.06655
                                    0.15245
                                else
                                    0.29628
                        else
                            if f.get(18) <= -0.17805
                                if f.get(26) <= 22.14035
                                    0.42224
                                else
                                    0.53936
                            else
                                if f.get(4) <= 35.19775
                                    0.55004
                                else
                                    0.10088
                    else
                        if f.get(8) <= 0.19760
                            if f.get(9) <= 0.18885
                                if f.get(3) <= 1.24605
                                    0.00000
                                else
                                    0.00000
                            else
                                0.36508
                        else
                            if f.get(9) <= 1.67440
                                if f.get(24) <= 1.53600
                                    0.60262
                                else
                                    0.81958
                            else
                                if f.get(23) <= 0.45065
                                    0.50549
                                else
                                    0.06166
            else
                if f.get(8) <= 0.19815
                    if f.get(9) <= 0.03910
                        if f.get(19) <= -0.19330
                            0.23077
                        else
                            0.00000
                    else
                        if f.get(1) <= 47.95000
                            if f.get(16) <= 0.50000
                                0.47917
                            else
                                if f.get(8) <= 0.10070
                                    0.00000
                                else
                                    0.61307
                        else
                            if f.get(4) <= 69.13305
                                if f.get(6) <= 1.12860
                                    0.10841
                                else
                                    0.33369
                            else
                                if f.get(8) <= 0.13125
                                    0.71360
                                else
                                    0.12568
                else
                    if f.get(11) <= 0.50000
                        if f.get(6) <= 0.84970
                            if f.get(26) <= 2.74945
                                if f.get(26) <= 2.18610
                                    0.51768
                                else
                                    0.89610
                            else
                                if f.get(6) <= 0.71110
                                    0.57295
                                else
                                    0.31507
                        else
                            if f.get(3) <= 0.85905
                                if f.get(2) <= -2.02770
                                    0.92314
                                else
                                    0.73591
                            else
                                if f.get(18) <= -0.52430
                                    0.82982
                                else
                                    0.48568
                    else
                        if f.get(8) <= 0.30365
                            if f.get(26) <= 8.94890
                                0.41441
                            else
                                if f.get(25) <= 0.00000
                                    0.24731
                                else
                                    0.00000
                        else
                            if f.get(26) <= 5.76645
                                if f.get(5) <= 0.33570
                                    0.73404
                                else
                                    0.00000
                            else
                                if f.get(26) <= 13.07120
                                    0.77528
                                else
                                    0.56098
    else
        if f.get(4) <= 1.06250
            if f.get(23) <= 1.01585
                if f.get(8) <= 0.47405
                    if f.get(18) <= -0.19315
                        if f.get(8) <= 0.16335
                            if f.get(24) <= 0.84620
                                0.38547
                            else
                                if f.get(7) <= 23.62650
                                    0.00000
                                else
                                    0.00000
                        else
                            if f.get(20) <= 0.50000
                                if f.get(18) <= -0.20000
                                    0.39321
                                else
                                    0.73966
                            else
                                if f.get(8) <= 0.40550
                                    0.46939
                                else
                                    0.71239
                    else
                        if f.get(13) <= 1.50000
                            0.76303
                        else
                            if f.get(26) <= 2.50870
                                if f.get(9) <= 0.89985
                                    0.18891
                                else
                                    0.69000
                            else
                                if f.get(0) <= 345600.00000
                                    0.26114
                                else
                                    0.49169
                else
                    if f.get(4) <= -48.01150
                        if f.get(13) <= 4.50000
                            if f.get(26) <= 30.27925
                                if f.get(26) <= 30.05370
                                    0.76572
                                else
                                    1.00000
                            else
                                if f.get(0) <= 345600.00000
                                    0.43396
                                else
                                    0.87928
                        else
                            if f.get(0) <= 50400.00000
                                0.59410
                            else
                                0.30464
                    else
                        if f.get(0) <= 345600.00000
                            if f.get(0) <= 50400.00000
                                if f.get(7) <= 41.13565
                                    0.29920
                                else
                                    0.48653
                            else
                                if f.get(14) <= 0.50000
                                    0.46562
                                else
                                    0.62999
                        else
                            if f.get(9) <= 1.56800
                                if f.get(12) <= 0.50000
                                    0.74257
                                else
                                    0.93949
                            else
                                if f.get(7) <= 35.02945
                                    0.61986
                                else
                                    0.87515
            else
                if f.get(8) <= 0.54590
                    if f.get(0) <= 345600.00000
                        if f.get(6) <= 2.57590
                            if f.get(18) <= -0.28160
                                if f.get(26) <= 6.17930
                                    0.25117
                                else
                                    0.57429
                            else
                                if f.get(3) <= 2.58045
                                    0.46444
                                else
                                    0.28399
                        else
                            0.90619
                    else
                        if f.get(2) <= -1.64885
                            if f.get(1) <= 24.11500
                                0.59410
                            else
                                if f.get(3) <= 2.49550
                                    0.53488
                                else
                                    0.94063
                        else
                            if f.get(4) <= -9.90540
                                if f.get(2) <= 0.20260
                                    0.50156
                                else
                                    0.92000
                            else
                                0.23077
                else
                    if f.get(1) <= 41.09500
                        if f.get(18) <= -0.28335
                            if f.get(2) <= -13.09755
                                0.27711
                            else
                                if f.get(0) <= 345600.00000
                                    0.69736
                                else
                                    0.82208
                        else
                            if f.get(0) <= 345600.00000
                                if f.get(23) <= 2.22525
                                    0.51291
                                else
                                    0.65895
                            else
                                if f.get(5) <= -1.84135
                                    0.92839
                                else
                                    0.81319
                    else
                        if f.get(18) <= -0.17570
                            if f.get(1) <= 44.14500
                                if f.get(26) <= 8.51255
                                    0.82883
                                else
                                    0.60802
                            else
                                if f.get(6) <= 1.09775
                                    0.94804
                                else
                                    0.75610
                        else
                            if f.get(2) <= 0.83520
                                if f.get(9) <= 0.23665
                                    0.77893
                                else
                                    0.61266
                            else
                                if f.get(7) <= 23.89830
                                    1.00000
                                else
                                    0.83498
        else
            if f.get(15) <= 0.50000
                if f.get(1) <= 39.08500
                    if f.get(8) <= 0.33080
                        if f.get(2) <= -2.13885
                            0.00000
                        else
                            if f.get(13) <= 3.50000
                                0.57295
                            else
                                0.00000
                    else
                        if f.get(18) <= -0.50775
                            if f.get(13) <= 4.50000
                                if f.get(2) <= -4.33265
                                    0.08745
                                else
                                    0.56522
                            else
                                if f.get(1) <= 32.82000
                                    0.74729
                                else
                                    0.91477
                        else
                            if f.get(4) <= 7.97420
                                if f.get(24) <= 0.20735
                                    0.19492
                                else
                                    0.67034
                            else
                                if f.get(9) <= 8.47540
                                    0.81205
                                else
                                    0.57500
                else
                    if f.get(3) <= 2.69025
                        if f.get(8) <= 0.71545
                            if f.get(9) <= 8.21605
                                if f.get(18) <= -0.00385
                                    0.72390
                                else
                                    0.55758
                            else
                                if f.get(5) <= 2.62125
                                    0.50029
                                else
                                    0.78044
                        else
                            if f.get(14) <= 0.50000
                                if f.get(9) <= 0.82475
                                    0.75044
                                else
                                    0.81690
                            else
                                if f.get(2) <= -0.26080
                                    0.85185
                                else
                                    0.98951
                    else
                        if f.get(13) <= 1.50000
                            if f.get(25) <= 0.00000
                                0.00000
                            else
                                0.34328
                        else
                            if f.get(19) <= 0.26395
                                0.53488
                            else
                                if f.get(23) <= 1.65660
                                    0.62162
                                else
                                    0.92000
            else
                if f.get(6) <= 1.41440
                    if f.get(7) <= 29.34915
                        if f.get(26) <= 2.45100
                            if f.get(26) <= 1.54090
                                0.90619
                            else
                                if f.get(7) <= 17.91870
                                    0.67153
                                else
                                    0.30464
                        else
                            if f.get(3) <= 1.13270
                                if f.get(26) <= 10.03770
                                    0.85923
                                else
                                    0.56557
                            else
                                if f.get(1) <= 38.71500
                                    0.56403
                                else
                                    0.89881
                    else
                        if f.get(9) <= 0.13205
                            if f.get(24) <= 1.00530
                                0.97506
                            else
                                0.73761
                        else
                            if f.get(23) <= 0.94915
                                0.00000
                            else
                                if f.get(4) <= 30.98375
                                    0.49640
                                else
                                    0.97354
                else
                    if f.get(4) <= 16.87170
                        0.81176
                    else
                        if f.get(1) <= 42.40000
                            0.83806
                        else
                            if f.get(25) <= 0.00000
                                1.00000
                            else
                                if f.get(1) <= 59.06000
                                    0.89399
                                else
                                    1.00000
