// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © duzhengjie100

//@version=6
library("chanBasicPub")

// 缠论基本k线数据，只有最高价和最低价
export type data_item 
    float high_
    float low_
    int   index_
    int  time_
    bool is_special
//

// 分型顶点数据类型
export type shape
    data_item data_left
    data_item data_mid
    data_item data_right
    int type_ // 1表示顶分型顶点，2表示底分型顶点
    int merge_index_ // 标识中间k线在data merge数组中的偏移
    bool is_standrad_ // 标识分型是否是标准的
    label draw_label_
//

export type pen
    shape start_
    shape end_
    int type_ // 标识笔的类型，1表示向上笔，2表示向下笔，0表示未成型笔(即只有start)
    line draw_line_

export type line_seq
    shape start_
    shape end_
    int pen_index_ // 组成线段的最后一笔在笔数组中的偏移
    int type_ // 标识线段的类型，1表示向上线段，2表示向下线段
    line draw_line_seq_
    int special_type_ // 表示该段的特殊类型，0表示正常走势

export type process_pen_paras
    shape la_record_shape
    shape sp_tail_shape_record
    bool sp_tail_flag
    shape sp_tail_shape_record_2
    bool sp_tail_flag_2
    shape sp_sub_shape_record
    bool sp_sub_flag
    bool special_cond_flag_1
    shape special_shape_1
    bool fix_cond_flag_1
    pen fix_cond_1_pen_1
    pen fix_cond_1_pen_2
    shape fix_cond_record_shape
    pen fix_cond_1_pre_pen_1
    pen fix_cond_1_pre_pen_2

// === 主逻辑1: 判断本k线是否要合并，并执行合并 ===
// 判断是否为局部极值
export is_extre_from_specific_item(data_item specific_data, int direction, data_item local_data, array<data_item> chan_data_array, int chan_data_array_offset)=>
    float tmp_extre = na

    if (direction == 1) // 是否局部高值
        tmp_extre := chan_data_array.get(specific_data.index_ - chan_data_array_offset).high_
        for i = specific_data.index_ to local_data.index_
            if (tmp_extre < chan_data_array.get(i - chan_data_array_offset).high_)
                tmp_extre := chan_data_array.get(i - chan_data_array_offset).high_
        if (local_data.high_ >= tmp_extre)
            true
        else
            false
    else if (direction == 2) // 是否局部低值
        tmp_extre := chan_data_array.get(specific_data.index_ - chan_data_array_offset).low_
        for i = specific_data.index_ to local_data.index_
            if (tmp_extre > chan_data_array.get(i - chan_data_array_offset).low_)
                tmp_extre := chan_data_array.get(i - chan_data_array_offset).low_
        if (local_data.low_ <= tmp_extre)
            true
        else
            false

//执行k线恢复函数（调用条件：需要至少一个确认分型）
export recover_k_data(data_item cur_data_item, array<data_item> chan_data_array, int chan_data_array_offset, array<data_item> data_merge_array, int data_merge_array_offset, array<pen> pen_array, shape la_record_shape, array<bool> merge_flag, int merge_flag_offset, array<int> merge_dir, int merge_dir_offset)=>
    if (pen_array.size() > 0)
        // 记录当前的局部极值
        //shape la_shape = pen_array.last().end_ // 取出最近的历史分型

        //shape la_shape = shape_array.last() // 取出最近的局部
        shape la_shape = la_record_shape      // 取出最近的记录分型
        //shape la_pre_shape = pen_array.last().start_
        shape la_pre_shape = na
        if (la_shape.merge_index_ > pen_array.last().end_.merge_index_)
            la_pre_shape := pen_array.last().end_
        else
            la_pre_shape := pen_array.last().start_
        pre_data_item = data_merge_array.last()
        retire_merge_flag = true
        if ((la_shape.type_ == 1) and ((((pre_data_item.high_ >= la_shape.data_mid.high_)) and (pre_data_item.high_ > cur_data_item.high_)) or ((pre_data_item.low_ <= la_pre_shape.data_mid.low_) and (pre_data_item.low_ < cur_data_item.low_))))
            retire_merge_flag := false
        else if ((la_shape.type_ == 2) and (((pre_data_item.low_ <= la_shape.data_mid.low_) and (pre_data_item.low_ < cur_data_item.low_)) or ((pre_data_item.high_ >= la_pre_shape.data_mid.high_) and (pre_data_item.high_ > cur_data_item.high_))))
            retire_merge_flag := false
        else if (data_merge_array.size() > 1)
            if ((cur_data_item.high_ < pre_data_item.high_) and is_extre_from_specific_item(la_shape.data_mid, 1, pre_data_item, chan_data_array, chan_data_array_offset)) // 处理k线刚好为顶分型右k线触发合并恢复的情况
                retire_merge_flag := false
            else if ((cur_data_item.low_ > pre_data_item.low_) and is_extre_from_specific_item(la_shape.data_mid, 2, pre_data_item, chan_data_array, chan_data_array_offset)) // 处理k线刚好为底分型右k线触发合并恢复的情况
                retire_merge_flag := false

        if (data_merge_array.last().is_special == true) //解决情况如问题 4.115
            retire_merge_flag := false

        if ((la_shape.merge_index_ < (data_merge_array.size() + data_merge_array_offset - 1)) and (retire_merge_flag == true) and (is_extre_from_specific_item(la_shape.data_mid, 1, cur_data_item, chan_data_array, chan_data_array_offset) or is_extre_from_specific_item(la_shape.data_mid, 2, cur_data_item, chan_data_array, chan_data_array_offset))) // 当前出现新的局部极值，执行取消前序合并的操作
            if (pen_array.size() > 1)
            //if (shape_array.size() > 1)
                //tmp_merge_index = pen_array.last().end_.merge_index_ + 1
                //tmp_merge_index = shape_array.last().merge_index_ + 1
                tmp_merge_index = la_shape.merge_index_ + 1
                if ((data_merge_array.size() + data_merge_array_offset - pen_array.last().end_.merge_index_) <= 3)
                    if ((pen_array.last().end_.type_ == 1) and (is_extre_from_specific_item(la_shape.data_mid, 2, cur_data_item, chan_data_array, chan_data_array_offset)))
                        tmp_merge_index := pen_array.last().end_.merge_index_ + 1
                    else if ((pen_array.last().end_.type_ == 2) and (is_extre_from_specific_item(la_shape.data_mid, 1, cur_data_item, chan_data_array, chan_data_array_offset)))
                        tmp_merge_index := pen_array.last().end_.merge_index_ + 1
        
                merge_count = data_merge_array.size() + data_merge_array_offset - tmp_merge_index
                chan_data_count = chan_data_array.size() + chan_data_array_offset - 1 // 用于处理判断合并k线恢复
                if (merge_count > 0)
                    tmp_original_index = data_merge_array.get(tmp_merge_index - data_merge_array_offset).index_
                    if ((data_merge_array.size() + data_merge_array_offset -tmp_merge_index) != (chan_data_count-tmp_original_index)) //存在被包含的k线，执行恢复
                        // 执行恢复合并的k线
                        tmp_merge_index += 1
                        count = 1
                        for i = (tmp_original_index+1) to (chan_data_count-1) by 1
                            recover_data = chan_data_array.get(i - chan_data_array_offset)
                            if (tmp_merge_index < (data_merge_array.size() + data_merge_array_offset))
                                data_merge_array.set(tmp_merge_index - data_merge_array_offset, recover_data)
                                merge_flag.set(tmp_merge_index - merge_flag_offset, false)
                                merge_dir.set(tmp_merge_index - merge_dir_offset, 0)
                            else
                                data_merge_array.push(recover_data)
                                merge_flag.push(false)
                                merge_dir.push(0)
                            tmp_merge_index += 1
                            count += 1


export merge_k_data(data_item cur_data_item, shape la_record_shape, array<data_item> chan_data_array, int chan_data_array_offset, array<data_item> data_merge_array, int data_merge_array_offset, array<pen> pen_array, array<bool> merge_flag, array<int> merge_dir)=>
    array<data_item> res = array.new<data_item>()
    res.push(cur_data_item)
    while (res.size() > 0) // 以递归的方式往前合并
        data_item cur_data = res.get(0)

        if ((pen_array.size()==0) and (data_merge_array.size()<4)) //无历史分型并且前序少于4根k线
        //if ((shape_array.size()==0) and (data_merge_array.size()<4)) //无历史分型并且前序少于4根k线
            data_merge_array.push(cur_data)
            merge_flag.push(false)
            merge_dir.push(0)
            res.clear()
            true
        else
            // 计算当前k线的合并状态
            if (pen_array.size()==0) // 无历史分型
                size_count = data_merge_array.size() + data_merge_array_offset
                values_top = math.max(data_merge_array.get(size_count - data_merge_array_offset -3).high_,data_merge_array.get(size_count - data_merge_array_offset -2).high_, data_merge_array.get(size_count - data_merge_array_offset -1).high_)
                values_below = math.min(data_merge_array.get(size_count - data_merge_array_offset -3).low_,data_merge_array.get(size_count - data_merge_array_offset -2).low_, data_merge_array.get(size_count - data_merge_array_offset -1).low_)
                if (cur_data.high_ > values_top)
                    merge_flag.push(true)
                    merge_dir.push(1)
                else if (cur_data.low_ < values_below)
                    merge_flag.push(true)
                    merge_dir.push(2)
                else
                    merge_flag.push(false)
                    merge_dir.push(0)
            else // 有历史分型
                shape la_shape = pen_array.last().end_ // 取出最近的历史分型
                //shape la_shape = shape_array.last() // 取出最近的历史分型
                //shape la_shape = la_record_shape
                shape la_pre_shape = pen_array.last().start_
                tmp_index = la_shape.merge_index_
                cur_data_index = data_merge_array.size() + data_merge_array_offset

                if ((cur_data_index - la_shape.merge_index_) < 3) //改为3兼容当前4k也可成笔的情况
                //if ((cur_data.index_ - la_shape.data_mid.index_) < 4) // 和分型顶点间少于4根k线
                    merge_flag.push(false)
                    merge_dir.push(0)
                    if ((la_shape.type_ == 1) and (cur_data.high_ >= la_shape.data_mid.high_) and (is_extre_from_specific_item(la_shape.data_mid,1,cur_data, chan_data_array, chan_data_array_offset) == true))
                        merge_flag.set(-1, true)
                        merge_dir.set(-1, 1)
                    else if ((la_shape.type_ == 2) and (cur_data.low_ <= la_shape.data_mid.low_) and (is_extre_from_specific_item(la_shape.data_mid,2,cur_data, chan_data_array, chan_data_array_offset) == true)) 
                        merge_flag.set(-1, true)
                        merge_dir.set(-1, 2)
                    //注释掉：解决问题4.1
                    // else if ((la_shape.merge_index_ < la_record_shape.merge_index_))
                    //     if ((la_record_shape.type_ == 1) and (cur_data.high_ >= la_record_shape.data_mid.high_) and (is_extre_from_specific_item(la_record_shape.data_mid,1,cur_data, chan_data_array, chan_data_array_offset) == true))
                    //         merge_flag.set(-1, true)
                    //         merge_dir.set(-1, 1)
                    //     else if ((la_record_shape.type_ == 2) and (cur_data.low_ <= la_record_shape.data_mid.low_) and (is_extre_from_specific_item(la_record_shape.data_mid,2,cur_data, chan_data_array, chan_data_array_offset) == true))
                    //         merge_flag.set(-1, true)
                    //         merge_dir.set(-1, 2)
                    //else
                    if (pen_array.size() > 1)
                        pre_pre_shape = pen_array.last().start_
                        pre_pre_pre_shape = pen_array.get(-2).start_
                        //pre_pre_shape = shape_array.get(-2)
                        //pre_pre_shape = la_pre_record_shape
                        // if (pre_pre_shape.type_ == 2)
                        //     label.new(la_shape.data_mid.index_,high, str.tostring(pre_pre_shape.type_), style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price
                        if ((pre_pre_shape.type_ == 1) and (cur_data.high_ > pre_pre_shape.data_mid.high_) and (is_extre_from_specific_item(pre_pre_shape.data_mid,1,cur_data, chan_data_array, chan_data_array_offset) == true))
                            merge_flag.set(-1, true)
                            merge_dir.set(-1, 1)
                            if (is_extre_from_specific_item(pre_pre_pre_shape.data_mid, 2, cur_data, chan_data_array, chan_data_array_offset))
                                cur_data.is_special := true
                        else if ((pre_pre_shape.type_ == 2) and (cur_data.low_ < pre_pre_shape.data_mid.low_) and (is_extre_from_specific_item(pre_pre_shape.data_mid,2,cur_data, chan_data_array, chan_data_array_offset) == true))
                            merge_flag.set(-1, true)
                            merge_dir.set(-1, 2)
                            if (is_extre_from_specific_item(pre_pre_pre_shape.data_mid, 1, cur_data, chan_data_array, chan_data_array_offset))
                                cur_data.is_special := true
                else // 比较顶点及向右3根k线
                    // if ((cur_data_index - la_shape.merge_index_) == 4)
                    //label.new(bar_index,high, "??", style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)
                    merge_flag.push(false)
                    merge_dir.push(0)
                    if (la_shape.type_ == 1) // 顶分型, 比较最低值
                        //values_below = math.min(data_merge_array.get(tmp_index).low_, data_merge_array.get(tmp_index+1).low_, data_merge_array.get(tmp_index+2).low_)                    
                        if ((is_extre_from_specific_item(la_shape.data_mid, 1, cur_data, chan_data_array, chan_data_array_offset))) //最高值高于顶分型顶点最高值
                            merge_flag.set(-1, true)
                            merge_dir.set(-1, 1)
                            if (is_extre_from_specific_item(la_pre_shape.data_mid, 2, cur_data, chan_data_array, chan_data_array_offset))
                                merge_dir.set(-1, 2)
                                cur_data.is_special := true
                        //else if (cur_data.low_ <= math.min(values_below, data_merge_array.get(data_merge_array.size()-1).low_))
                        else if (is_extre_from_specific_item(la_shape.data_right, 2, cur_data, chan_data_array, chan_data_array_offset) == true)
                            merge_flag.set(-1, true)
                            merge_dir.set(-1, 2)
                            //label.new(bar_index,high, "??", style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)
                        else if ((la_shape.merge_index_ < la_record_shape.merge_index_))
                            if ((cur_data.index_ - la_shape.data_mid.index_) > 9) // 10根k线后
                                pre_local_val_below = math.min(data_merge_array.get(cur_data_index - data_merge_array_offset - 1).low_, data_merge_array.get(cur_data_index - data_merge_array_offset - 2).low_, data_merge_array.get(cur_data_index - data_merge_array_offset - 3).low_)
                                if (cur_data.low_ <= pre_local_val_below)
                                    merge_flag.set(-1,true)
                                    merge_dir.set(-1,2)
                        
                            //if (cur_data.low_ <= la_record_shape.data_mid.low_)
                            if (is_extre_from_specific_item(la_record_shape.data_mid, 2, cur_data, chan_data_array, chan_data_array_offset))
                                merge_flag.set(-1, true)
                                merge_dir.set(-1, 2)
                            else if ((cur_data_index - la_record_shape.merge_index_)>=4)
                                tmp_index_2 = la_record_shape.merge_index_
                                //values_top = math.max(data_merge_array.get(tmp_index_2).high_, data_merge_array.get(tmp_index_2+1).high_, data_merge_array.get(tmp_index_2+2).high_)
                                //if (cur_data.high_ >= math.max(values_top, data_merge_array.get(-1).high_))
                                if (is_extre_from_specific_item(la_record_shape.data_right, 1, cur_data, chan_data_array, chan_data_array_offset))
                                    merge_flag.set(-1, true)
                                    merge_dir.set(-1, 1)
                    else if (la_shape.type_ == 2) //底分型, 比较最高值
                        //values_top = math.max(data_merge_array.get(tmp_index).high_, data_merge_array.get(tmp_index+1).high_, data_merge_array.get(tmp_index+2).high_)
                        if ((is_extre_from_specific_item(la_shape.data_mid, 2, cur_data, chan_data_array, chan_data_array_offset) == true)) //最低值低于底分型顶点最低值
                            merge_flag.set(-1, true)
                            merge_dir.set(-1, 2)
                            if (is_extre_from_specific_item(la_pre_shape.data_mid, 1, cur_data, chan_data_array, chan_data_array_offset))
                                merge_dir.set(-1, 1)
                                cur_data.is_special := true
                        //else if (cur_data.high_ >= math.max(values_top, data_merge_array.get(data_merge_array.size()-1).high_))
                        else if ((is_extre_from_specific_item(la_shape.data_right, 1, cur_data, chan_data_array, chan_data_array_offset) == true))
                            merge_flag.set(-1, true)
                            merge_dir.set(-1, 1)
                        else if ((la_shape.merge_index_ < la_record_shape.merge_index_))

                            if ((cur_data.index_ - la_shape.data_mid.index_) > 9) // 10根k线后
                                pre_local_val_top = math.max(data_merge_array.get(cur_data_index - data_merge_array_offset - 1).high_, data_merge_array.get(cur_data_index - data_merge_array_offset - 2).high_, data_merge_array.get(cur_data_index - data_merge_array_offset - 3).high_)
                                if (cur_data.high_ >= pre_local_val_top)
                                    merge_flag.set(-1, true)
                                    merge_dir.set(-1, 1)
                            
                            //if (cur_data.high_ >= la_record_shape.data_mid.high_)
                            if (is_extre_from_specific_item(la_record_shape.data_mid, 1, cur_data, chan_data_array, chan_data_array_offset) == true)
                                merge_flag.set(-1, true)
                                merge_dir.set(-1, 1)
                            else if ((cur_data_index - la_record_shape.merge_index_)>=4)
                                tmp_index_2 = la_record_shape.merge_index_
                                //values_below = math.min(data_merge_array.get(tmp_index_2).low_, data_merge_array.get(tmp_index_2+1).low_, data_merge_array.get(tmp_index_2+2).low_)
                                //if (cur_data.low_ <= math.min(values_below, data_merge_array.get(-1).low_))
                                if (is_extre_from_specific_item(la_record_shape.data_right, 2, cur_data, chan_data_array, chan_data_array_offset) == true)
                                    merge_flag.set(-1, true)
                                    merge_dir.set(-1, 2)                    

            data_item prev_data_item = data_merge_array.last()
            bool is_right_merge = ((cur_data.high_ <= prev_data_item.high_) and (cur_data.low_ >= prev_data_item.low_)) // 是否右包含
            bool is_left_merge = ((cur_data.high_ >= prev_data_item.high_) and (cur_data.low_ <= prev_data_item.low_)) // 是否左包含
            if  (is_left_merge or is_right_merge) // 包含，直接进行合并
                bool is_merge = false
                int tmp_merge_dir = 0
                if (is_right_merge)
                    is_merge := merge_flag.get(-2)
                    tmp_merge_dir := merge_dir.get(-2)
                else                        
                    is_merge := merge_flag.get(-1) and (data_merge_array.size() > 4)
                    tmp_merge_dir := merge_dir.get(-1)    

                if (is_merge)
                    int tmp_index = na
                    int tmp_time = na
                    bool tmp_special = false
                    if (is_right_merge) // 如果右包含，选前一个k线
                        if ((tmp_merge_dir == 1) and (cur_data_item.high_ == prev_data_item.high_))
                            tmp_index := cur_data_item.index_
                            tmp_time := cur_data_item.time_
                            tmp_special := cur_data.is_special
                        else if ((tmp_merge_dir == 2) and (cur_data_item.low_ == prev_data_item.low_))
                            tmp_index := cur_data_item.index_
                            tmp_time := cur_data_item.time_
                            tmp_special := cur_data.is_special
                        else
                            tmp_index := prev_data_item.index_
                            tmp_time := prev_data_item.time_
                            tmp_special := prev_data_item.is_special
                        // if(show_merge)
                        //     label.new(cur_data.time_,cur_data.low_, "合: 左 " + str.tostring(tmp_merge_dir), style=label.style_label_up, size=size.tiny, textcolor=color.white, color=color.gray, yloc=yloc.price, xloc = xloc.bar_time)
                        // //label.new(cur_data.index_,cur_data.high_, str.tostring(math.max(prev_data_item.high_, cur_data.high_)), style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.orange, yloc=yloc.price)
                    else if (is_left_merge)
                        tmp_index := cur_data.index_
                        tmp_time := cur_data.time_
                        tmp_special := cur_data.is_special
                        // if(show_merge)
                        //     label.new(prev_data_item.time_,prev_data_item.low_, "合: 右" + str.tostring(tmp_merge_dir), style=label.style_label_up, size=size.tiny, textcolor=color.white, color=color.gray, yloc=yloc.price, xloc = xloc.bar_time)
                        //label.new(prev_data_item.index_,prev_data_item.high_, str.tostring(math.max(prev_data_item.high_, cur_data.high_)), style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.orange, yloc=yloc.price)

                    data_item tmp_data_item = na
                    if (tmp_merge_dir == 1) // 向上合并，取高高
                        tmp_data_item := data_item.new(math.max(prev_data_item.high_, cur_data.high_), math.max(prev_data_item.low_, cur_data.low_), tmp_index, tmp_time, tmp_special)
                        //label.new(bar_index,high, str.tostring(math.max(prev_data_item.low_, cur_data.low_)), style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.orange, yloc=yloc.price)
                    else if (tmp_merge_dir == 2) // 向下合并，取低低
                        tmp_data_item := data_item.new(math.min(prev_data_item.high_, cur_data.high_), math.min(prev_data_item.low_, cur_data.low_), tmp_index, tmp_time, tmp_special)

                    res.clear()
                    res.push(tmp_data_item)
                    data_merge_array.pop()

                    merge_flag.pop()
                    merge_flag.pop()
                    merge_dir.pop()
                    merge_dir.pop()
                    true
                else
                    data_merge_array.push(cur_data)
                    res.clear()
                    true
                true
            else // 不被包含，判断当前可合并状态并保存当前k线
                data_merge_array.push(cur_data)
                res.clear()
                true
// === 主逻辑1: 结束===


// === 主逻辑2: 检测分型并保存 ==
export process_shape(array<data_item> chan_data_array, int chan_data_array_offset, array<data_item> data_merge_array, int data_merge_array_offset, array<shape> shape_array, array<pen> pen_array)=>
    bool is_store_shape = false

    if (data_merge_array.size() >= 3)
        tmp_size = data_merge_array.size() + data_merge_array_offset
        tmp_left_data = data_merge_array.get(tmp_size - data_merge_array_offset - 3)
        tmp_right_data = data_merge_array.get(tmp_size - data_merge_array_offset - 1)
        tmp_mid_data = data_merge_array.get(tmp_size - data_merge_array_offset - 2)

        tmp_chan_mid_data = chan_data_array.get(tmp_mid_data.index_ - chan_data_array_offset)
        tmp_chan_right_data = chan_data_array.get(tmp_right_data.index_ - chan_data_array_offset)
        tmp_chan_left_data = chan_data_array.get(tmp_left_data.index_ - chan_data_array_offset)
        //label.new(bar_index,high, str.tostring(tmp_left_data.high_), style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)

        if ((tmp_mid_data.high_ >= math.max(tmp_left_data.high_, tmp_right_data.high_)) and (tmp_mid_data.low_ >= math.max(tmp_left_data.low_, tmp_right_data.low_))) // 顶分型
            
            //label.new(bar_index,high, "??", style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)
            is_store_shape := true
            tmp_shape = shape.new(tmp_left_data, tmp_mid_data, tmp_right_data, 1, tmp_size-2, true) // 存储顶分型
            if ((shape_array.size()>0) and (tmp_shape.merge_index_ <= shape_array.last().merge_index_)) //解决因合并导致重复加入分型数组
                //label.new(bar_index,high, str.tostring(data_merge_array.get(tmp_shape.merge_index_).high_), style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)

                if (tmp_shape.data_mid.high_ == shape_array.last().data_mid.high_)
                    is_store_shape := false
                else
                    is_store_shape := true
                shape_array.pop()
            shape_array.push(tmp_shape)

        else if ((tmp_mid_data.high_ <= math.min(tmp_left_data.high_, tmp_right_data.high_)) and (tmp_mid_data.low_ <= math.min(tmp_left_data.low_, tmp_right_data.low_))) // 底分型
            //label.new(bar_index,high, "??", style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)

            tmp_shape = shape.new(tmp_left_data, tmp_mid_data, tmp_right_data, 2, tmp_size-2, true) // 存储底分型
            is_store_shape := true
            if ((shape_array.size()>0) and (tmp_shape.merge_index_ <= shape_array.last().merge_index_))
                //label.new(bar_index,high, str.tostring(tmp_shape.data_mid.high_), style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)
                if (tmp_shape.data_mid.low_ == shape_array.last().data_mid.low_)
                    is_store_shape := false
                else
                    is_store_shape := true
                shape_array.pop()
            shape_array.push(tmp_shape)
        else if ((tmp_mid_data.is_special == true) and (tmp_chan_mid_data.high_ > math.max(tmp_chan_left_data.high_, tmp_chan_right_data.high_)))
            tmp_mid_data.high_ := tmp_chan_mid_data.high_
            tmp_shape = shape.new(tmp_left_data, tmp_mid_data, tmp_right_data, 1, tmp_size-2, false)
            is_store_shape := true
            shape_array.push(tmp_shape)
        else if ((tmp_mid_data.is_special == true) and (tmp_chan_mid_data.low_ < math.min(tmp_chan_left_data.low_, tmp_chan_right_data.low_)))
            tmp_mid_data.low_ := tmp_chan_mid_data.low_
            tmp_shape = shape.new(tmp_left_data, tmp_mid_data, tmp_right_data, 2, tmp_size-2, false)
            is_store_shape := true
            shape_array.push(tmp_shape)
        else if (pen_array.size() > 0) // 将5k以内的高(低)点处理成分型，以便后续进行特殊笔的判断
            new_item = data_merge_array.last()
            pre_shape = pen_array.last().end_
            if (((tmp_size-2) - pre_shape.merge_index_) < 4)
                if ((pre_shape.type_ == 1) and (tmp_mid_data.low_ <= math.min(tmp_left_data.low_, tmp_right_data.low_)))
                    tmp_shape = shape.new(tmp_left_data, tmp_mid_data, tmp_right_data, 2, tmp_size-2, false) // 存储底分型
                    is_store_shape := true
                    if ((shape_array.size()>0) and (tmp_shape.merge_index_ == shape_array.last().merge_index_))
                        if (tmp_shape.data_mid.low_ == shape_array.last().data_mid.low_)
                            is_store_shape := false
                        else
                            is_store_shape := true
                        shape_array.pop()
                    shape_array.push(tmp_shape)
                else if ((pre_shape.type_ == 2) and (tmp_mid_data.high_ >= math.max(tmp_left_data.high_, tmp_right_data.high_)))
                    tmp_shape = shape.new(tmp_left_data, tmp_mid_data, tmp_right_data, 1, tmp_size-2, false) // 存储顶分型
                    is_store_shape := true
                    if ((shape_array.size()>0) and (tmp_shape.merge_index_ == shape_array.last().merge_index_))
                        if (tmp_shape.data_mid.high_ == shape_array.last().data_mid.high_)
                            is_store_shape := false
                        else
                            is_store_shape := true
                        shape_array.pop()
                    shape_array.push(tmp_shape)
    is_store_shape
        
// // === 主逻辑2：结束 ===

// //函数判断给定的k线是否为局部极值
export is_local_extre(shape pre_local_shape, int end_index, data_item local_item, array<data_item> chan_data_array, int chan_data_array_offset,array<data_item> data_merge_array, int data_merge_array_offset, int type_) =>
    //将比较修改为更为严格的比较原始k线
    if ((pre_local_shape.merge_index_ > (end_index - 1)))
        false
    else
        float local_extre = -1
        float local_extre_2 = -1
        int end_index_original = data_merge_array.get(end_index - data_merge_array_offset).index_ - 1
        int tmp_b_index = 0

        if (pre_local_shape.type_ == 1)
            //local_extre := chan_data_array.get(pre_local_shape.data_mid.index_ - chan_data_array_offset).low_ // 解决4.12 笔错误成立的情况
            if (type_ == 0)
                local_extre := chan_data_array.get(pre_local_shape.data_right.index_ - chan_data_array_offset).low_ // 解决4.19 笔未成立的情况
                local_extre_2 := pre_local_shape.data_right.high_
                tmp_b_index := pre_local_shape.data_right.index_
            else if (type_ == 1)
                local_extre := chan_data_array.get(pre_local_shape.data_left.index_ - chan_data_array_offset).low_ // 解决4.19 笔未成立的情况
                local_extre_2 := pre_local_shape.data_left.high_
                tmp_b_index := pre_local_shape.data_left.index_
            for i = tmp_b_index to end_index_original
                tmp_item = chan_data_array.get(i - chan_data_array_offset)
                if (local_extre >= tmp_item.low_)
                    local_extre := tmp_item.low_
                if (local_extre_2 <= tmp_item.high_)
                    local_extre_2 := tmp_item.high_
                
            if ((local_item.low_ <= local_extre) and (pre_local_shape.data_mid.high_ >= local_extre_2))
                true
            else
                false
        else if (pre_local_shape.type_ == 2)
            //local_extre := chan_data_array.get(pre_local_shape.data_mid.index_ - chan_data_array_offset).high_ // 解决4.12 笔错误成立的情况
            if (type_ == 0)
                local_extre := chan_data_array.get(pre_local_shape.data_right.index_ - chan_data_array_offset).high_ // 解决4.19 笔未成立的情况
                local_extre_2 := pre_local_shape.data_right.low_
                tmp_b_index := pre_local_shape.data_right.index_
            else if (type_ == 1)
                local_extre := chan_data_array.get(pre_local_shape.data_left.index_ - chan_data_array_offset).high_ // 解决4.19 笔未成立的情况
                local_extre_2 := pre_local_shape.data_left.low_
                tmp_b_index := pre_local_shape.data_left.index_
            for i = tmp_b_index to end_index_original
                tmp_item = chan_data_array.get(i - chan_data_array_offset)
                if (local_extre <= tmp_item.high_)
                    local_extre := tmp_item.high_
                if (local_extre_2 >= tmp_item.low_)
                    local_extre_2 := tmp_item.low_
                
            if ((local_item.high_ >= local_extre) and (pre_local_shape.data_mid.low_ <= local_extre_2))
                true
            else
                false

//该函数返回分型在局部的次序序列，比如如果是次高（低）点，则返回1
export get_level_seq(shape pre_shape, shape local_shape, array<data_item> data_merge_array, int data_merge_array_offset, array<data_item> chan_data_array, int chan_data_array_offset)=>
    int count = 0
    record_flag = false
    if (pre_shape.type_ == 1)
        data_item tmp_pre_item = na
        for i = (pre_shape.merge_index_+1) to (local_shape.merge_index_)
            //tmp_item = data_merge_array.get(i - data_merge_array_offset)
            tmp_item = chan_data_array.get(data_merge_array.get(i - data_merge_array_offset).index_ - chan_data_array_offset)
            if ((tmp_item.low_ <= local_shape.data_mid.low_) and ((na(tmp_pre_item) == true) or (tmp_item.low_ < tmp_pre_item.low_)) and (record_flag == false))
                count += 1
                record_flag := true
            else if ((na(tmp_pre_item) == false) and (tmp_pre_item.low_ < tmp_item.low_))
                record_flag := false 
            tmp_pre_item := tmp_item
    else if (pre_shape.type_ == 2)
        data_item tmp_pre_item = na
        for i = (pre_shape.merge_index_+1) to (local_shape.merge_index_)
            //tmp_item = data_merge_array.get(i - data_merge_array_offset)
            tmp_item = chan_data_array.get(data_merge_array.get(i - data_merge_array_offset).index_ - chan_data_array_offset)

            if ((tmp_item.high_ >= local_shape.data_mid.high_) and ((na(tmp_pre_item) == true) or (tmp_item.high_ > tmp_pre_item.high_)) and (record_flag == false))
                count += 1
                record_flag := true
            else if ((na(tmp_pre_item) == false) and (tmp_pre_item.high_ > tmp_item.high_))
                record_flag := false
            tmp_pre_item := tmp_item
    
    count -= 1
    count

//该函数用于判断两个分型是否构成标准笔
export is_standard_pen(shape shape_A, shape shape_B, array<data_item> chan_data_array, int chan_data_array_offset,array<data_item> data_merge_array, int data_merge_array_offset) =>
    int ret = 0
    if (shape_A.type_ == 1)
        if (shape_B.type_ == 2)
            if ((shape_B.merge_index_ - shape_A.merge_index_) >= 4) // 前一个存储分型为顶分型并且分型相差k线数量大于4
                //if (tmp_mid_data.high_ < pre_shape.data_mid.low_) // 顶分型低点高于底分型高点
                if (shape_B.data_mid.low_ < shape_A.data_mid.high_)
                    if (is_local_extre(shape_A, shape_B.merge_index_, shape_B.data_mid, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset, 0) == true)
                        // 返回1，表示向下笔
                        ret := 1                      
    else if (shape_A.type_ == 2)
        if (shape_B.type_ == 1)
            if ((shape_B.merge_index_ - shape_A.merge_index_) >= 4) // 前一个存储分型为底分型并且分型相差k线数量大于4                    
                //if (tmp_mid_data.low_ > pre_shape.data_mid.high_) // 顶分型低点高于底分型高点
                if (shape_B.data_mid.high_ > shape_A.data_mid.low_)
                    if (is_local_extre(shape_A, shape_B.merge_index_, shape_B.data_mid, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset, 0) == true)
                        // 返回2，表示向上笔
                        ret := 2               
    // 返回0，表示不构成标准笔
    ret


export process_pen(array<data_item> chan_data_array, int chan_data_array_offset,array<data_item> data_merge_array, int data_merge_array_offset, array<shape> shape_array, array<pen> pen_array, process_pen_paras input_paras) =>
    bool is_new_shape = false // 该变量用于表示是否生成新的确认分型
    bool is_pen_special = false
    process_pen_paras output_paras = process_pen_paras.new(na, na, false, na, false, na, false, false, na, false, na, na, na, na, na)

    //初始化 output_paras 和 input_paras 内部变量一致
    output_paras.la_record_shape := input_paras.la_record_shape
    output_paras.sp_tail_shape_record := input_paras.sp_tail_shape_record
    output_paras.sp_tail_flag := input_paras.sp_tail_flag
    output_paras.sp_tail_shape_record_2 := input_paras.sp_tail_shape_record_2
    output_paras.sp_tail_flag_2 := input_paras.sp_tail_flag_2
    output_paras.sp_sub_shape_record := input_paras.sp_sub_shape_record
    output_paras.sp_sub_flag := input_paras.sp_sub_flag
    output_paras.special_cond_flag_1 := input_paras.special_cond_flag_1
    output_paras.special_shape_1 := input_paras.special_shape_1
    output_paras.fix_cond_flag_1 := input_paras.fix_cond_flag_1
    output_paras.fix_cond_1_pen_1 := input_paras.fix_cond_1_pen_1
    output_paras.fix_cond_1_pen_2 := input_paras.fix_cond_1_pen_2
    output_paras.fix_cond_record_shape := input_paras.fix_cond_record_shape
    output_paras.fix_cond_1_pre_pen_1 := input_paras.fix_cond_1_pre_pen_1
    output_paras.fix_cond_1_pre_pen_2 := input_paras.fix_cond_1_pre_pen_2

    new_shape = shape_array.last()
    if (pen_array.size() == 0) // 添加第一条未成型笔
        int tmp_dir = 0
        shape tmp_first_shape = na
        if (new_shape.type_ == 1)
            local_extre_item = data_merge_array.get(0)
            count = 0
            for i = 0 to new_shape.merge_index_
                tmp_data_item = data_merge_array.get(i - data_merge_array_offset)
                if (tmp_data_item.low_ < local_extre_item.low_)
                    local_extre_item := tmp_data_item
                    count := i
            tmp_dir := 1
            tmp_first_shape := shape.new(na, local_extre_item, na, 2, count, true)
        else if (new_shape.type_ == 2)
            local_extre_item = data_merge_array.get(0)
            count = 0
            for i = 0 to new_shape.merge_index_
                tmp_data_item = data_merge_array.get(i - data_merge_array_offset)
                if (tmp_data_item.high_ > local_extre_item.high_)
                    local_extre_item := tmp_data_item
                    count := i
            tmp_dir := 2
            tmp_first_shape := shape.new(na, local_extre_item, na, 1, count, true)

        tmp_pen = pen.new(tmp_first_shape, new_shape, tmp_dir)
        pen_array.push(tmp_pen)
        output_paras.la_record_shape := new_shape
        is_new_shape := true
    else
        pre_pen = pen_array.last()
        pre_shape = pre_pen.end_
        if (is_standard_pen(pre_shape, new_shape, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) == 1) // 满足标准向下笔
            
            // 存储笔
            tmp_pen = pen.new(pre_shape, new_shape, 2) // 向下笔
            pen_array.push(tmp_pen)

            is_new_shape := true
            output_paras.la_record_shape := new_shape

        else if ((pre_shape.type_==1)and(new_shape.type_ == 1)and(new_shape.data_mid.high_ >= pre_shape.data_mid.high_)) // 顶分型并且突破了前序顶分型, 延续笔
            // 延续，修改前序顶分型为当前顶分型
            pre_pen.end_ := new_shape

            is_new_shape := true
            output_paras.la_record_shape := new_shape

        else if (is_standard_pen(pre_shape, new_shape, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) == 2) // 标准向上笔
            // 存储笔
            tmp_pen = pen.new(pre_shape, new_shape, 1) // 向上笔
            pen_array.push(tmp_pen)

            is_new_shape := true
            output_paras.la_record_shape := new_shape

        else if ((pre_shape.type_==2)and((new_shape.type_ == 2))and(new_shape.data_mid.low_ <= pre_shape.data_mid.low_)) // 底分型并且跌破了前序底分型，延续笔
            pre_pen.end_ := new_shape
            is_new_shape := true
            output_paras.la_record_shape := new_shape

        else //该部分为识别和处理特殊笔的逻辑
        
            // 处理小于5k的笔包含前一笔的特殊笔
            if (is_new_shape == false)
                if (pen_array.size() > 1)
                    pre_pre_pen = pen_array.get(-2)
                    if ((pre_shape.type_ == 1) and (new_shape.type_ == 2) and (pre_shape.data_mid.high_ >= pre_pre_pen.start_.data_mid.high_) and (new_shape.data_mid.low_ <= pre_pre_pen.end_.data_mid.low_))
                        tmp_pen = pen.new(pre_shape, new_shape, 2)
                        pen_array.push(tmp_pen)

                        is_new_shape := true
                        output_paras.la_record_shape := new_shape
                    else if ((pre_shape.type_ == 2) and (new_shape.type_ == 1) and (pre_shape.data_mid.low_ <= pre_pre_pen.start_.data_mid.low_) and (new_shape.data_mid.high_ >= pre_pre_pen.end_.data_mid.high_))
                        tmp_pen = pen.new(pre_shape, new_shape, 1)
                        pen_array.push(tmp_pen)

                        is_new_shape := true
                        output_paras.la_record_shape := new_shape

            //处理顶底分型基础k线大于等于7，且合并后的k线满足4k的特殊笔 （暂时注释，解决情况如问题 4.92）         
            // if (is_new_shape == false)
            //     if (((new_shape.data_mid.index_ - pre_shape.data_mid.index_) >= 6) and ((new_shape.merge_index_ - pre_shape.merge_index_) == 3))
            //         if ((new_shape.type_ != pre_shape.type_) and (is_local_extre(pre_shape, new_shape.merge_index_, new_shape.data_mid, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) == true))
            //             if (new_shape.type_ == 1)
            //                 tmp_pen = pen.new(pre_shape, new_shape, 1)
            //                 pen_array.push(tmp_pen)

            //                 is_new_shape := true
            //                 output_paras.la_record_shape := new_shape
            //             else if (new_shape.type_ == 2)
            //                 tmp_pen = pen.new(pre_shape, new_shape, 2)
            //                 pen_array.push(tmp_pen)

            //                 is_new_shape := true
            //                 output_paras.la_record_shape := new_shape

            //处理分型后的高（低）点小于5k，且之后产生大于等于10k的顶（底）分型，构成特殊笔
            if (is_new_shape == false)
                if ((output_paras.sp_tail_flag == true) and (output_paras.sp_tail_shape_record.merge_index_ < pre_shape.merge_index_))
                    output_paras.sp_tail_flag := false
                    output_paras.sp_tail_shape_record := na
                    output_paras.sp_tail_flag_2 := false
                    output_paras.sp_tail_shape_record_2 := na

                if (((new_shape.merge_index_ - pre_shape.merge_index_) < 4) and (new_shape.type_ != pre_shape.type_))
                    record_flag = false
                    if (na(output_paras.sp_tail_shape_record) == true) 
                        record_flag := true
                    else
                        if (pre_shape.type_ == 1)
                            if (output_paras.sp_tail_shape_record.data_mid.low_ >= new_shape.data_mid.low_)
                                record_flag := true
                        else if (pre_shape.type_ == 2)
                            if (output_paras.sp_tail_shape_record.data_mid.high_ <= new_shape.data_mid.high_)
                                record_flag := true
                    if (record_flag == true)

                        output_paras.sp_tail_shape_record := new_shape
                        output_paras.sp_tail_flag := true
                        output_paras.la_record_shape := new_shape

                else if ((output_paras.sp_tail_flag == true) and ((output_paras.sp_tail_flag_2 == false) or ((output_paras.sp_tail_shape_record_2.type_ == new_shape.type_) and (((new_shape.type_ == 1) and (output_paras.sp_tail_shape_record_2.data_mid.high_ <= new_shape.data_mid.high_)) or ((new_shape.type_ == 2) and (output_paras.sp_tail_shape_record_2.data_mid.low_ >= new_shape.data_mid.low_))))))
                    if (((new_shape.data_right.index_ - output_paras.sp_tail_shape_record.data_mid.index_) >= 10) and (is_standard_pen(output_paras.sp_tail_shape_record, new_shape, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) != 0))
                        output_paras.sp_tail_flag_2 := true
                        output_paras.sp_tail_shape_record_2 := new_shape

                else if (output_paras.sp_tail_flag_2 == true)
                    if (is_standard_pen(output_paras.sp_tail_shape_record_2, new_shape, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) != 0)

                        if (new_shape.type_ == 1)
                            tmp_pen_1 = pen.new(pre_shape, output_paras.sp_tail_shape_record, 1)
                            tmp_pen_2 = pen.new(output_paras.sp_tail_shape_record, output_paras.sp_tail_shape_record_2, 2)
                            tmp_pen_3 = pen.new(output_paras.sp_tail_shape_record_2, new_shape, 1)

                            pen_array.push(tmp_pen_1)
                            pen_array.push(tmp_pen_2)
                            pen_array.push(tmp_pen_3)

                            is_new_shape := true
                            output_paras.la_record_shape := new_shape
                        else if (new_shape.type_ == 2)
                            tmp_pen_1 = pen.new(pre_shape, output_paras.sp_tail_shape_record, 2)
                            tmp_pen_2 = pen.new(output_paras.sp_tail_shape_record, output_paras.sp_tail_shape_record_2, 1)
                            tmp_pen_3 =pen.new(output_paras.sp_tail_shape_record_2, new_shape, 2)

                            pen_array.push(tmp_pen_1)
                            pen_array.push(tmp_pen_2)
                            pen_array.push(tmp_pen_3)

                            is_new_shape := true
                            output_paras.la_record_shape := new_shape

            //处理10根k线后次低点连成特殊笔
            if (is_new_shape == false)
                if ((output_paras.sp_sub_flag == true) and (output_paras.sp_sub_shape_record.merge_index_ < pre_shape.merge_index_))
                    output_paras.sp_sub_flag := false
                    output_paras.sp_sub_shape_record := na
                
                if ((output_paras.sp_sub_flag == false) or ((output_paras.sp_sub_shape_record.type_ == 1) and (output_paras.sp_sub_shape_record.data_mid.high_ < new_shape.data_mid.high_) or (output_paras.sp_sub_shape_record.type_ == 2) and (output_paras.sp_sub_shape_record.data_mid.low_ > new_shape.data_mid.low_)))
                    if (((new_shape.data_mid.index_ - pre_shape.data_mid.index_) >= 8) and ((new_shape.merge_index_ - pre_shape.merge_index_) >= 4))
                        if ((pre_shape.type_ == 1) and (new_shape.type_ == 2))
                            if ((get_level_seq(pre_shape, new_shape, data_merge_array, data_merge_array_offset, chan_data_array, chan_data_array_offset) == 1))
                                output_paras.sp_sub_flag := true
                                output_paras.sp_sub_shape_record := new_shape
                                output_paras.la_record_shape := new_shape
                                
                        else if ((pre_shape.type_ == 2) and (new_shape.type_ == 1))
                            if ((get_level_seq(pre_shape, new_shape, data_merge_array, data_merge_array_offset, chan_data_array, chan_data_array_offset) == 1))
                                output_paras.sp_sub_flag := true
                                output_paras.sp_sub_shape_record := new_shape
                                output_paras.la_record_shape := new_shape
                else
                    if (is_standard_pen(output_paras.sp_sub_shape_record, new_shape, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) == 1) //向下笔确认
                        tmp_pen = pen.new(pre_shape, output_paras.sp_sub_shape_record, 1)
                        tmp_pen_2 = pen.new(output_paras.sp_sub_shape_record, new_shape, 2)
                        pen_array.push(tmp_pen)
                        pen_array.push(tmp_pen_2)

                        is_new_shape := true
                        output_paras.la_record_shape := new_shape
                    else if (is_standard_pen(output_paras.sp_sub_shape_record, new_shape, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) == 2) // 向上笔确认
                        tmp_pen = pen.new(pre_shape, output_paras.sp_sub_shape_record, 2)
                        tmp_pen_2 = pen.new(output_paras.sp_sub_shape_record, new_shape, 1)
                        pen_array.push(tmp_pen)
                        pen_array.push(tmp_pen_2)

                        is_new_shape := true
                        output_paras.la_record_shape := new_shape

            // 处理满足原始k线大于等于5，合并后k线小于5的特殊情况
            if (is_new_shape == false)
                if ((output_paras.special_cond_flag_1 == true)and(output_paras.special_shape_1.merge_index_ < pen_array.last().end_.merge_index_))
                    output_paras.special_cond_flag_1 := false
                    output_paras.special_shape_1 := na

                if (output_paras.special_cond_flag_1 == false)
                    if ((new_shape.is_standrad_ == true) and ((new_shape.merge_index_ - pre_shape.merge_index_)<4) and ((new_shape.data_mid.index_ - pre_shape.data_mid.index_)>=4) and (is_local_extre(pre_shape, new_shape.merge_index_, new_shape.data_mid, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset, 1) == true)) 
                        output_paras.special_cond_flag_1 := true
                        output_paras.special_shape_1 := new_shape

                        output_paras.la_record_shape := new_shape
                else if ((output_paras.special_cond_flag_1 == true))
                    if (is_standard_pen(output_paras.special_shape_1, new_shape, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) != 0)
                        if ((pre_shape.type_ == 1) and (pre_shape.data_mid.high_ > output_paras.special_shape_1.data_mid.high_))
                            tmp_pen_1 = pen.new(pre_shape, output_paras.special_shape_1, 2)  
                            tmp_pen_2 = pen.new(output_paras.special_shape_1, new_shape, 1)
                            pen_array.push(tmp_pen_1)
                            pen_array.push(tmp_pen_2)
                          
                            is_new_shape := true
                            output_paras.la_record_shape := new_shape
                        else if ((pre_shape.type_ == 2) and (pre_shape.data_mid.low_ < output_paras.special_shape_1.data_mid.low_))
                            tmp_pen_1 = pen.new(pre_shape, output_paras.special_shape_1, 1)  
                            tmp_pen_2 = pen.new(output_paras.special_shape_1, new_shape, 2)
                            pen_array.push(tmp_pen_1)
                            pen_array.push(tmp_pen_2)
                          
                            is_new_shape := true
                            output_paras.la_record_shape := new_shape

            // 满足分型顶点原始k线大于等于5，合并后k线小于5，看低级别线段结构

        // 该部分用于记录满足条件的特别的分型，后续笔修改和特殊笔可能会用到

        //特殊分型1: 分型突破（跌破）前一个同型分型

        if ((is_new_shape == false)) // 该分型未被识别为构成笔的分型, 只有这种情况下才可能记录该特殊分型

            if ((pre_shape.type_==1)and(new_shape.type_ == 2)and(pen_array.size() > 2))
                pre_pre_shape = pen_array.get(-1).start_
                if (new_shape.data_mid.low_ <= pre_pre_shape.data_mid.low_)  // 存储该分型点，立刻进行修改
                // 增加等于条件解决情况如问题 4.129
                // 存储该分型点，后续可能进行修改
                    pre_pre_pen = pen_array.get(-2)

                    output_paras.fix_cond_1_pen_1 := pen_array.pop()
                    output_paras.fix_cond_1_pen_2 := pen_array.pop()

                    output_paras.fix_cond_record_shape := new_shape

                    tmp_pen = pen.new(pre_pre_pen.start_, new_shape, 2) // 向下笔
                    pen_array.push(tmp_pen)

                    is_new_shape := true
                    output_paras.la_record_shape := new_shape
                    output_paras.fix_cond_flag_1 := true
            else if ((pre_shape.type_==2)and(new_shape.type_ == 1)and(pen_array.size() > 2)) // 存储该分型点，后续可能进行修改
                pre_pre_shape = pen_array.get(-1).start_
                if (new_shape.data_mid.high_ >= pre_pre_shape.data_mid.high_)
                    // 增加等于条件解决情况如问题 4.129
                    // 存储该分型点，后续可能进行修改
                    pre_pre_pen = pen_array.get(-2)

                    output_paras.fix_cond_1_pen_1 := pen_array.pop()
                    output_paras.fix_cond_1_pen_2 := pen_array.pop()

                    output_paras.fix_cond_record_shape := new_shape

                    tmp_pen = pen.new(pre_pre_pen.start_, new_shape, 1) // 向上笔
                    pen_array.push(tmp_pen)

                    is_new_shape := true
                    output_paras.la_record_shape := new_shape
                    output_paras.fix_cond_flag_1 := true
        
        if ((is_new_shape == true) and (output_paras.fix_cond_flag_1 == true)) // 该逻辑判断是否需要撤销修改笔
            if ((output_paras.fix_cond_1_pen_2.start_.merge_index_ == pen_array.last().start_.merge_index_) and (is_standard_pen(output_paras.fix_cond_1_pen_1.end_, new_shape, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) != 0)) // 满足条件，撤销当前组修改笔
                delete_pen =pen_array.pop()
                // if (show_line)
                //     line.delete(delete_pen.draw_line_)
                pen_array.push(output_paras.fix_cond_1_pen_2)
                pen_array.push(output_paras.fix_cond_1_pen_1)
                pen tmp_pen = na
                if (new_shape.type_ == 1)
                    tmp_pen := pen.new(output_paras.fix_cond_1_pen_1.end_, new_shape, 1)
                else
                    tmp_pen := pen.new(output_paras.fix_cond_1_pen_1.end_, new_shape, 2) // 向下笔
                pen_array.push(tmp_pen)
                is_new_shape := true
                output_paras.la_record_shape := new_shape
            else if ((na(output_paras.fix_cond_1_pre_pen_1) == false) and (output_paras.fix_cond_1_pre_pen_2.start_.merge_index_ == output_paras.fix_cond_1_pen_2.start_.merge_index_) and (pen_array.last().start_.merge_index_ <= output_paras.fix_cond_record_shape.merge_index_)) // 判断是否需要恢复前一组修改笔（连续修改笔的情况）  
   
                shape tmp_shape = na

                if (new_shape.type_ == output_paras.fix_cond_1_pre_pen_1.end_.type_)
                    tmp_shape := pen_array.last().start_
                else
                    tmp_shape := new_shape

                if (is_standard_pen(output_paras.fix_cond_1_pre_pen_1.end_, tmp_shape, chan_data_array, chan_data_array_offset, data_merge_array, data_merge_array_offset) != 0)
                    pen reserv_pen = na
                    if (tmp_shape.merge_index_ != new_shape.merge_index_)
                        reserv_pen := pen_array.pop()
                    delete_pen = pen_array.pop()
                    // if (show_line)
                    //     line.delete(delete_pen.draw_line_)
                    pen_array.push(output_paras.fix_cond_1_pre_pen_2)
                    pen_array.push(output_paras.fix_cond_1_pre_pen_1)
                    pen tmp_pen = na
                    if (tmp_shape.type_ == 1)
                        tmp_pen := pen.new(output_paras.fix_cond_1_pre_pen_1.end_, tmp_shape , 1)
                    else
                        tmp_pen := pen.new(output_paras.fix_cond_1_pre_pen_1.end_, tmp_shape , 2)
                    pen_array.push(tmp_pen)
                    is_new_shape := true
                    output_paras.la_record_shape := new_shape
                    if (tmp_shape.merge_index_ != new_shape.merge_index_)
                        pen_array.push(reserv_pen)     

            if (output_paras.fix_cond_1_pen_2.start_.merge_index_ < pen_array.last().start_.merge_index_)
                output_paras.fix_cond_1_pre_pen_1 := output_paras.fix_cond_1_pen_1
                output_paras.fix_cond_1_pre_pen_2 := output_paras.fix_cond_1_pen_2
                output_paras.fix_cond_flag_1 := false
                output_paras.fix_cond_1_pen_1 := na
                output_paras.fix_cond_1_pen_2 := na
                output_paras.fix_cond_record_shape := na

        // 特殊分型2: 分型中间k线高低点高于前序分型高低点
        if (is_new_shape == true)
            if (pen_array.size() > 0)
                tmp_la_pre_pen = pen_array.get(-1)
                tmp_la_shape = pen_array.last().end_
                tmp_la_mid_data = chan_data_array.get(tmp_la_shape.data_mid.index_ - chan_data_array_offset)
                tmp_la_right_data = chan_data_array.get(tmp_la_shape.data_right.index_ - chan_data_array_offset)
                if (tmp_la_shape.type_ == 1)
                    if ((tmp_la_mid_data.low_ < tmp_la_right_data.low_) and (is_extre_from_specific_item(tmp_la_pre_pen.start_.data_mid, 2, tmp_la_mid_data, chan_data_array, chan_data_array_offset) == true))
                        //这里修改高不为k线最高值，以免后续处理出问题
                        tmp_new_mid_data = data_item.new(tmp_la_mid_data.low_, tmp_la_mid_data.low_, tmp_la_mid_data.index_, tmp_la_mid_data.time_, tmp_la_mid_data.is_special)
                        tmp_new_shape = shape.new(tmp_la_shape.data_left, tmp_new_mid_data, tmp_la_shape.data_right, 2, tmp_la_shape.merge_index_ , true)

                        shape_array.push(tmp_new_shape)
                        tmp_new_pen = pen.new(tmp_la_shape, tmp_new_shape, 2)
                        pen_array.push(tmp_new_pen)
                        is_pen_special := true
                else if (tmp_la_shape.type_ == 2)
                    if ((tmp_la_mid_data.high_ > tmp_la_right_data.high_) and (is_extre_from_specific_item(tmp_la_pre_pen.start_.data_mid, 1, tmp_la_mid_data, chan_data_array, chan_data_array_offset) == true))
                        tmp_new_mid_data = data_item.new(tmp_la_mid_data.high_, tmp_la_mid_data.high_, tmp_la_mid_data.index_, tmp_la_mid_data.time_, tmp_la_mid_data.is_special)
                        tmp_new_shape = shape.new(tmp_la_shape.data_left, tmp_new_mid_data, tmp_la_shape.data_right, 1, tmp_la_shape.merge_index_ , true)

                        shape_array.push(tmp_new_shape)
                        tmp_new_pen = pen.new(tmp_la_shape, tmp_new_shape, 1)
                        pen_array.push(tmp_new_pen)
                        is_pen_special := true
    
    [is_new_shape, is_pen_special, output_paras]

export process_pen_subfix (array<data_item> chan_data_array, int chan_data_array_offset, array<shape> shape_array, array<pen> pen_array, bool is_new_shape_g, shape la_record_shape_g, float local_extre_val) =>
    // float extre_value = extre_value_g
    // if (pen_array.size() >= 3)
    //     local_last_pen = pen_array.get(-1)
    //     local_first_pen = pen_array.get(-3)

    //     tmp_local_extre_high = local_first_pen.start_.data_mid.high_
    //     tmp_local_extre_low = local_first_pen.start_.data_mid.low_
    //     for i = -3 to -1
    //         tmp_pen = pen_array.get(i)
            
    //         if (tmp_pen.type_ == 1)
    //             if (tmp_pen.start_.data_mid.low_ <= tmp_local_extre_low)
    //                 tmp_local_extre_low := tmp_pen.start_.data_mid.low_                
    //             if (tmp_pen.end_.data_mid.high_ >= tmp_local_extre_high)
    //                 tmp_local_extre_high := tmp_pen.end_.data_mid.high_           
    //         else if (tmp_pen.type_ == 2)
    //             if (tmp_pen.start_.data_mid.high_ >= tmp_local_extre_high)
    //                 tmp_local_extre_high := tmp_pen.start_.data_mid.high_                
    //             if (tmp_pen.end_.data_mid.low_ <= tmp_local_extre_low)
    //                 tmp_local_extre_low := tmp_pen.end_.data_mid.low_

    //     if (local_first_pen.type_ == 1)
    //         if ((local_first_pen.start_.data_mid.low_ <= tmp_local_extre_low) and (local_last_pen.end_.data_mid.high_ >= tmp_local_extre_high))
    //             extre_value := tmp_local_extre_high
    //     else if (local_first_pen.type_ == 2)
    //         if ((local_first_pen.start_.data_mid.high_ >= tmp_local_extre_high) and (local_last_pen.end_.data_mid.low_ <= tmp_local_extre_low))
    //             extre_value := tmp_local_extre_low

    shape la_record_shape = la_record_shape_g
    bool is_new_shape = is_new_shape_g

    //if ((is_store_shape == true) and (is_new_shape == false) and (pen_array.size() > 0))
    new_shape = shape_array.last()
    pre_shape = pen_array.last().end_
    
    if (((new_shape.data_mid.index_ - pre_shape.data_mid.index_) >= 4) and ((new_shape.merge_index_ - pre_shape.merge_index_) == 3))
        if (((pre_shape.type_ == 1) and (new_shape.data_mid.low_ <= local_extre_val)) or ((pre_shape.type_ == 2) and (new_shape.data_mid.high_ >= local_extre_val)))
            //low_level = get_low_level(timeframe.period)
            //if ((na(low_level) == false))
                //tmp_is_pen_line_seq = request.security(syminfo.tickerid, low_level, low_level_line_seq_info)
                //tmp_data = request.security(syminfo.tickerid, low_level, extre_value)
                //if ((pre_shape.type_ == 1) and (new_shape.data_mid.low_ == tmp_data))
            if (pre_shape.type_ == 1)
                pre_chan_data = chan_data_array.get(pre_shape.data_mid.index_ - chan_data_array_offset)
                left_chan_data = chan_data_array.get(new_shape.data_left.index_ - chan_data_array_offset)
                if (pre_chan_data.low_ > new_shape.data_mid.low_) // 加上限制条件，处理中间k线过长情况，如4.6
                    if (left_chan_data.high_ > new_shape.data_mid.high_) // 加上限制条件，处理情况4.9
                        //存储笔
                        tmp_pen = pen.new(pre_shape, new_shape, 2) // 向下笔
                        pen_array.push(tmp_pen)            
                        // if(show_shape)
                        //     tmp_label = label.new(new_shape.data_mid.time_,new_shape.data_mid.low_, "底", style=label.style_label_up, size=size.tiny, textcolor=color.white, color=color.blue, yloc=yloc.price, xloc = xloc.bar_time)
                        //     tmp_shape_draw = shape_draw.new(new_shape.merge_index_, tmp_label)
                        //     shape_draw_array.push(tmp_shape_draw)

                        is_new_shape := true
                        la_record_shape := new_shape
            //else if ((pre_shape.type_ == 2) and (new_shape.data_mid.high_ == tmp_data))
            else if (pre_shape.type_ == 2)
                pre_chan_data = chan_data_array.get(pre_shape.data_mid.index_ - chan_data_array_offset)
                left_chan_data = chan_data_array.get(new_shape.data_left.index_ - chan_data_array_offset)
                if (pre_chan_data.high_ < new_shape.data_mid.high_) // 加上限制条件，处理中间k线过长情况，如4.6
                    if (left_chan_data.low_ < new_shape.data_mid.low_)
                        // 存储笔
                        tmp_pen = pen.new(pre_shape, new_shape, 1) // 向上笔
                        pen_array.push(tmp_pen)            
                        // if(show_shape)
                        //     tmp_label = label.new(new_shape.data_mid.time_,new_shape.data_mid.high_, "顶", style=label.style_label_up, size=size.tiny, textcolor=color.white, color=color.orange, yloc=yloc.price, xloc = xloc.bar_time)
                        //     tmp_shape_draw = shape_draw.new(new_shape.merge_index_, tmp_label)
                        //     shape_draw_array.push(tmp_shape_draw)
                        is_new_shape := true
                        la_record_shape := new_shape
    [is_new_shape, la_record_shape]

export has_line_seq_gap(array<pen> pen_array,int pen_array_offset, int line_seq_type, int pen_begin_index, int pen_end_index) =>
    bool gap_flag = false
    if (line_seq_type == 1) // 向上段
        central_flag = false
        float tmp_top_min = 0
        float tmp_bottom_max = 0
        for j = pen_begin_index to pen_end_index
            tmp_pen_1 = pen_array.get(j - pen_array_offset)
            if (central_flag == true)
                if (tmp_pen_1.type_ == 2)
                    if (tmp_pen_1.end_.data_mid.low_ > tmp_top_min)
                        central_flag := false
                else if (tmp_pen_1.type_ == 1)
                    if (tmp_pen_1.end_.data_mid.high_ < tmp_bottom_max)
                        gap_flag := true
                        break                        
            if (central_flag == false)
                if ((tmp_pen_1.type_ == 2) and ((j+2)<pen_end_index))
                    //判断是否出现中枢：反向一笔开始，三笔重叠
                    tmp_pen_2 = pen_array.get(j - pen_array_offset + 1)
                    tmp_pen_3 = pen_array.get(j - pen_array_offset + 2)
                    if (tmp_pen_3.end_.data_mid.low_ < tmp_pen_1.start_.data_mid.high_)
                        //创建中枢
                        tmp_top_min := math.min(tmp_pen_1.start_.data_mid.high_, tmp_pen_3.start_.data_mid.high_)
                        tmp_bottom_max := math.max(tmp_pen_1.end_.data_mid.low_, tmp_pen_3.end_.data_mid.low_)
                        central_flag := true
    else if (line_seq_type == 2)
        central_flag = false
        float tmp_top_min = 0
        float tmp_bottom_max = 0
        for j = pen_begin_index to pen_end_index
            tmp_pen_1 = pen_array.get(j - pen_array_offset)
            if (central_flag == true)
                if (tmp_pen_1.type_ == 1)
                    if (tmp_pen_1.end_.data_mid.high_ < tmp_bottom_max)
                        central_flag := false
                else if (tmp_pen_1.type_ == 2)
                    if (tmp_pen_1.end_.data_mid.low_ > tmp_top_min)
                        gap_flag := true
                        break                        
            if (central_flag == false)
                if ((tmp_pen_1.type_ == 1) and ((j+2)<pen_end_index))
                    //判断是否出现中枢：反向一笔开始，三笔重叠
                    tmp_pen_2 = pen_array.get(j - pen_array_offset + 1)
                    tmp_pen_3 = pen_array.get(j - pen_array_offset + 2)
                    if (tmp_pen_3.end_.data_mid.high_ > tmp_pen_1.start_.data_mid.low_)
                        //创建中枢
                        tmp_top_min := math.min(tmp_pen_1.end_.data_mid.high_, tmp_pen_3.end_.data_mid.high_)
                        tmp_bottom_max := math.max(tmp_pen_1.start_.data_mid.low_, tmp_pen_3.start_.data_mid.low_)
                        central_flag := true
    gap_flag

export get_last_line_seq_gap(array<pen> pen_array,int pen_array_offset, int line_seq_type, int pen_begin_index, int pen_end_index) =>
    float top_value = -1
    float bottom_value = -1
    if (line_seq_type == 1) // 向上段
        central_flag = false
        float tmp_top_min = 0
        float tmp_bottom_max = 0
        for j = pen_begin_index to pen_end_index
            tmp_pen_1 = pen_array.get(j - pen_array_offset)
            if (central_flag == true)
                if (tmp_pen_1.type_ == 2)
                    if (tmp_pen_1.end_.data_mid.low_ > tmp_top_min)
                        central_flag := false
                        top_value := tmp_top_min
                        bottom_value := tmp_bottom_max                           
            if (central_flag == false)
                if ((tmp_pen_1.type_ == 2) and ((j+2)<pen_end_index))
                    //判断是否出现中枢：反向一笔开始，三笔重叠
                    tmp_pen_2 = pen_array.get(j - pen_array_offset + 1)
                    tmp_pen_3 = pen_array.get(j - pen_array_offset + 2)
                    if (tmp_pen_3.end_.data_mid.low_ < tmp_pen_1.start_.data_mid.high_)
                        //创建中枢
                        tmp_top_min := math.min(tmp_pen_1.start_.data_mid.high_, tmp_pen_3.start_.data_mid.high_)
                        tmp_bottom_max := math.max(tmp_pen_1.end_.data_mid.low_, tmp_pen_3.end_.data_mid.low_)
                        central_flag := true
        if (central_flag == true)
            top_value := tmp_top_min
            bottom_value := tmp_bottom_max
    else if (line_seq_type == 2)
        central_flag = false
        float tmp_top_min = 0
        float tmp_bottom_max = 0
        for j = pen_begin_index to pen_end_index
            tmp_pen_1 = pen_array.get(j - pen_array_offset)
            if (central_flag == true)
                if (tmp_pen_1.type_ == 1)
                    if (tmp_pen_1.end_.data_mid.high_ < tmp_bottom_max)
                        central_flag := false
                        top_value := tmp_top_min
                        bottom_value := tmp_bottom_max                      
            if (central_flag == false)
                if ((tmp_pen_1.type_ == 1) and ((j+2)<pen_end_index))
                    //判断是否出现中枢：反向一笔开始，三笔重叠
                    tmp_pen_2 = pen_array.get(j - pen_array_offset + 1)
                    tmp_pen_3 = pen_array.get(j - pen_array_offset + 2)
                    if (tmp_pen_3.end_.data_mid.high_ > tmp_pen_1.start_.data_mid.low_)
                        //创建中枢
                        tmp_top_min := math.min(tmp_pen_1.end_.data_mid.high_, tmp_pen_3.end_.data_mid.high_)
                        tmp_bottom_max := math.max(tmp_pen_1.start_.data_mid.low_, tmp_pen_3.start_.data_mid.low_)
                        central_flag := true 
        if (central_flag == true)
            top_value := tmp_top_min
            bottom_value := tmp_bottom_max
     
    [top_value, bottom_value]

export process_special_line_seqs(array<pen> pen_array, int pen_array_offset, array<line_seq> line_seq_array, bool is_pen_special, bool is_new_line_seq_g, float seq_local_extre_g, int line_central_new_index_g, int global_begin_seq_pen_index, bool is_seq_modify_1_g, bool is_seq_modify_2_g) =>
    
    bool is_new_line_seq = is_new_line_seq_g
    float seq_local_extre = seq_local_extre_g
    int line_central_new_index = line_central_new_index_g
    bool is_seq_modify_1 = is_seq_modify_1_g
    bool is_seq_modify_2 = is_seq_modify_2_g

    last_pen = pen.new(na,na,0,na)
    if (is_pen_special == false) //处理中间k先高低点都突破的情况
        last_pen := pen_array.last()
    else
        last_pen := pen_array.get(-2)

    //if ((is_new_line_seq == false) or (is_pen_special == true))
    if (line_seq_array.size() > 0) // 解决问题4.18，段包含未成立的情况
        // pen_index_ = -1
        // if (line_seq_array.size() > 0)
        pen_index_ = line_seq_array.last().pen_index_
        //段包含情况
        if ((line_seq_array.size() > 1) and ((pen_array.size() + pen_array_offset - 1 - pen_index_) >= 1))
            local_first_pen = pen_array.get(pen_index_ - pen_array_offset + 1)
            local_last_pen = pen_array.last()
            tmp_is_new = false
            tmp_is_special = false
            tmp_end_index = pen_array.size() + pen_array_offset - 1
            if ((is_pen_special == true) and ((pen_array.size() + pen_array_offset - 1 - pen_index_) > 1))
                local_last_pen := pen_array.get(-2)
                tmp_end_index := pen_array.size() + pen_array_offset - 2
                tmp_is_special := true
            
            local_pre_last_line_seq = line_seq_array.get(-2)
            if (local_first_pen.type_ == local_last_pen.type_)
                if ((local_first_pen.type_ == 1) and (local_first_pen.start_.data_mid.low_ <= local_pre_last_line_seq.start_.data_mid.low_) and (local_last_pen.end_.data_mid.high_ >= local_pre_last_line_seq.end_.data_mid.high_))
                    tmp_new_line_seq = line_seq.new(local_first_pen.start_, local_last_pen.end_, tmp_end_index, 1, na, 0)
                    is_new_line_seq := true
                    seq_local_extre := tmp_new_line_seq.start_.data_mid.low_
                    line_seq_array.push(tmp_new_line_seq)
                    tmp_is_new := true
                    line_central_new_index := line_central_new_index + 1
                else if ((local_first_pen.type_ == 2) and (local_first_pen.start_.data_mid.high_ >= local_pre_last_line_seq.start_.data_mid.high_) and (local_last_pen.end_.data_mid.low_ <= local_pre_last_line_seq.end_.data_mid.low_))
                    tmp_new_line_seq = line_seq.new(local_first_pen.start_, local_last_pen.end_, tmp_end_index, 2, na, 0)
                    is_new_line_seq := true
                    seq_local_extre := tmp_new_line_seq.start_.data_mid.high_
                    line_seq_array.push(tmp_new_line_seq)
                    tmp_is_new := true
                    line_central_new_index := line_central_new_index + 1
                
                //处理情况如问题 4.79
                if ((is_seq_modify_1 == true) and (tmp_is_new == true))
                    is_seq_modify_2 := true

                //处理中间k线高低点都突破的情况
                if ((is_pen_special == true) and (tmp_is_new == true) and (tmp_is_special == true))
                    local_last_pen_2 = pen_array.last()
                    if (local_last_pen_2.type_ == 1)
                        tmp_new_line_seq = line_seq.new(local_last_pen_2.start_, local_last_pen_2.end_, pen_array.size() + pen_array_offset - 1, 1, na, 0)
                        is_new_line_seq := true
                        seq_local_extre := tmp_new_line_seq.start_.data_mid.low_
                        line_seq_array.push(tmp_new_line_seq)
                        //line_central_new_index := line_seq_array.size() - 2
                        line_central_new_index := line_central_new_index + 2                  
                    else if (local_last_pen_2.type_ == 2)
                        tmp_new_line_seq = line_seq.new(local_last_pen_2.start_, local_last_pen_2.end_, pen_array.size() + pen_array_offset - 1, 2, na, 0)
                        is_new_line_seq := true
                        seq_local_extre := tmp_new_line_seq.start_.data_mid.high_
                        line_seq_array.push(tmp_new_line_seq)
                        //line_central_new_index := line_seq_array.size() - 2
                        line_central_new_index := line_central_new_index + 2

        // 缺口情况：1
        if ((is_new_line_seq == false) and ((pen_array.size() + pen_array_offset - 1 - pen_index_) >= 6))
            local_first_pen = pen_array.get(0)
            local_second_pen = pen_array.get(1)
            local_pre_last_pen = pen_array.get(-2)
            if (line_seq_array.size() > 0)
                local_first_pen := pen_array.get(pen_index_ - pen_array_offset + 1)
                local_second_pen := pen_array.get(pen_index_ - pen_array_offset + 2)
                local_pre_last_pen := pen_array.get(pen_array.size() - 2)

            if ((local_first_pen.type_ == 2) and (last_pen.type_ == 1))
                tmp_local_extre = local_first_pen.end_.data_mid.low_
                tmp_second_index = pen_index_ + 1
                for i = (pen_index_ + 2) to (pen_array.size() + pen_array_offset - 2)
                    tmp_pen = pen_array.get(i - pen_array_offset)
                    
                    if (tmp_pen.end_.data_mid.low_ <= tmp_local_extre)
                        tmp_local_extre := tmp_pen.end_.data_mid.low_
                        local_second_pen := pen_array.get(i - pen_array_offset + 1)
                        tmp_second_index := i
                
                tmp_local_extre_high = pen_array.get(tmp_second_index - pen_array_offset).end_.data_mid.high_
                tmp_local_high_index = -1
                tmp_high_line_seq = pen_array.get(tmp_second_index + 1 - pen_array_offset)
                for i = (tmp_second_index + 1) to (pen_array.size() + pen_array_offset - 2)
                    tmp_pen = pen_array.get(i - pen_array_offset)

                    if (tmp_pen.end_.data_mid.high_ >= tmp_local_extre_high)
                        tmp_local_extre_high := tmp_pen.end_.data_mid.high_
                        tmp_local_high_index := i
                        tmp_high_line_seq := pen_array.get(i - pen_array_offset)
                
                //if ((last_pen.start_.data_mid.low_ > local_second_pen.end_.data_mid.high_) and (local_pre_last_pen.start_.data_mid.high_ == tmp_local_extre_high))
                if ((last_pen.start_.data_mid.low_ > local_second_pen.end_.data_mid.high_))
                    tmp_new_line_seq_1 = line_seq.new(local_first_pen.start_, local_second_pen.start_, tmp_second_index, 2, na, 0)
                    tmp_new_line_seq_2 = line_seq.new(local_second_pen.start_, tmp_high_line_seq.end_, tmp_local_high_index, 1, na, 0)
                    is_new_line_seq := true
                    seq_local_extre := tmp_new_line_seq_2.start_.data_mid.low_
                    line_seq_array.push(tmp_new_line_seq_1)
                    line_seq_array.push(tmp_new_line_seq_2)
                    //line_central_new_index := line_seq_array.size() - 2
                    line_central_new_index := line_central_new_index + 2
            else if ((local_first_pen.type_ == 1) and (last_pen.type_ == 2))
                tmp_local_extre = local_first_pen.end_.data_mid.high_
                tmp_second_index = pen_index_ + 1
                for i = (pen_index_ + 2) to (pen_array.size() + pen_array_offset - 2)
                    tmp_pen = pen_array.get(i - pen_array_offset)
                    
                    if (tmp_pen.end_.data_mid.high_ >= tmp_local_extre)
                        tmp_local_extre := tmp_pen.end_.data_mid.high_
                        local_second_pen := pen_array.get(i-pen_array_offset+1)
                        tmp_second_index := i

                tmp_local_extre_low = pen_array.get(tmp_second_index - pen_array_offset).end_.data_mid.low_
                tmp_local_low_index = -1
                tmp_low_line_seq = pen_array.get(tmp_second_index + 1 - pen_array_offset)
                for i = (tmp_second_index + 1) to (pen_array.size() + pen_array_offset - 2)
                    tmp_pen = pen_array.get(i - pen_array_offset)

                    if (tmp_pen.end_.data_mid.low_ <= tmp_local_extre_low)
                        tmp_local_extre_low := tmp_pen.end_.data_mid.low_
                        tmp_local_low_index := i
                        tmp_low_line_seq := pen_array.get(i - pen_array_offset)
                //if ((last_pen.start_.data_mid.high_ < local_second_pen.end_.data_mid.low_) and (local_pre_last_pen.start_.data_mid.low_ == tmp_local_extre_low))
                if ((last_pen.start_.data_mid.high_ < local_second_pen.end_.data_mid.low_))
                    tmp_new_line_seq_1 = line_seq.new(local_first_pen.start_, local_second_pen.start_, tmp_second_index, 1, na, 0)
                    tmp_new_line_seq_2 = line_seq.new(local_second_pen.start_, tmp_low_line_seq.end_, tmp_local_low_index, 2, na, 0)
                    is_new_line_seq := true
                    seq_local_extre := tmp_new_line_seq_2.start_.data_mid.high_
                    line_seq_array.push(tmp_new_line_seq_1)
                    line_seq_array.push(tmp_new_line_seq_2)
                    //line_central_new_index := line_seq_array.size() - 2
                    line_central_new_index := line_central_new_index + 2

        //缺口情况：2
        if ((is_new_line_seq == false) and (line_seq_array.size() > 0))
            if ((pen_array.size() + pen_array_offset - 1 - pen_index_) >= 2)
                local_first_pen = pen_array.get(0)
                if (line_seq_array.size() > 1)
                    tmp_pen_index_ = line_seq_array.get(-2).pen_index_
                    local_first_pen := pen_array.get(tmp_pen_index_ - pen_array_offset + 1)

                local_second_pen = pen_array.get(pen_index_ - pen_array_offset)
                local_third_pen = pen_array.get(pen_index_ - pen_array_offset + 1)
                local_forth_pen = pen_array.last()
    
                if ((local_first_pen.type_ == 2) and (local_first_pen.end_.data_mid.low_ > local_second_pen.start_.data_mid.high_) and (local_third_pen.end_.data_mid.high_ > local_first_pen.start_.data_mid.high_) and (local_forth_pen.end_.data_mid.low_ < local_second_pen.end_.data_mid.low_))
                    tmp_new_line_seq_1 = line_seq.new(local_third_pen.start_, local_third_pen.end_, pen_index_ + 1, 1, na, 0)
                    tmp_new_line_seq_2 = line_seq.new(local_third_pen.end_, local_forth_pen.end_, pen_array.size() + pen_array_offset -1, 2, na, 0)
                    is_new_line_seq := true
                    seq_local_extre := tmp_new_line_seq_2.start_.data_mid.high_
                    line_seq_array.push(tmp_new_line_seq_1)
                    line_seq_array.push(tmp_new_line_seq_2)
                    //line_central_new_index := line_seq_array.size() - 2
                    line_central_new_index := line_central_new_index + 2
                else if ((local_first_pen.type_ == 1) and (local_first_pen.end_.data_mid.high_ < local_second_pen.start_.data_mid.low_) and (local_third_pen.end_.data_mid.low_ < local_first_pen.start_.data_mid.low_) and (local_forth_pen.end_.data_mid.high_ > local_second_pen.end_.data_mid.high_))
                    tmp_new_line_seq_1 = line_seq.new(local_third_pen.start_, local_third_pen.end_, pen_index_ + 1, 2, na, 0)
                    tmp_new_line_seq_2 = line_seq.new(local_third_pen.end_, local_forth_pen.end_, pen_array.size() + pen_array_offset -1, 1, na, 0)
                    is_new_line_seq := true
                    seq_local_extre := tmp_new_line_seq_2.start_.data_mid.low_
                    line_seq_array.push(tmp_new_line_seq_1)
                    line_seq_array.push(tmp_new_line_seq_2)
                    //line_central_new_index := line_seq_array.size() - 2
                    line_central_new_index := line_central_new_index + 2

        //缺口情况：3
        if ((is_new_line_seq == false) and (line_seq_array.size() > 0) and ((pen_array.size() + pen_array_offset - 1 - pen_index_) > 2))
            local_pre_pen = pen_array.get(pen_index_ - pen_array_offset)
            local_last_pen = pen_array.last()
            if ((local_pre_pen.type_ == 1) and (local_last_pen.type_ == 2))
                tmp_low = local_pre_pen.end_.data_mid.low_
                tmp_low_index = pen_index_ + 1
                gap_flag = false
                tmp_b_index = global_begin_seq_pen_index
                if (line_seq_array.size() > 1)
                    tmp_b_index := line_seq_array.get(-2).pen_index_ + 1
                [top_value, bottom_value] = get_last_line_seq_gap(pen_array, pen_array_offset, 1, tmp_b_index, pen_index_)
                if (bottom_value == -1)
                    bottom_value := local_pre_pen.start_.data_mid.low_
                else if (local_pre_pen.start_.data_mid.low_ > top_value) //解决情况如问题 4.113
                    bottom_value := local_pre_pen.start_.data_mid.low_
                for i=(pen_index_ + 1) to (pen_array.size() + pen_array_offset - 1)
                    tmp_pen = pen_array.get(i - pen_array_offset)
                    if ((tmp_pen.type_ == 1) and (bottom_value > tmp_pen.end_.data_mid.high_))
                        gap_flag := true
                    if (tmp_pen.end_.data_mid.low_ <= tmp_low)
                        tmp_low := tmp_pen.end_.data_mid.low_
                        tmp_low_index := i
            
                no_repire_flag = true
                if ((line_seq_array.size() > 1) and (local_pre_pen.end_.data_mid.high_ < line_seq_array.get(-2).start_.data_mid.high_) and (tmp_low <= line_seq_array.last().start_.data_mid.low_))
                    no_repire_flag := false

                if (no_repire_flag == false) // 根据修改是否产生缺口判断单笔成段能否成立，解决情况如问题 4.29
                    tmp_begin_index = global_begin_seq_pen_index
                    if (line_seq_array.size() > 2)
                        tmp_begin_index := line_seq_array.get(-3).pen_index_ + 1
                    no_repire_flag := has_line_seq_gap(pen_array, pen_array_offset, 2, tmp_begin_index, tmp_low_index)

                //后续可添加条件：如果高级别笔满足，也可成立特殊段

                if ((gap_flag == true) and (no_repire_flag == true))
                    //label.new(bar_index,high, "XXX", style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)
                    tmp_new_line_seq = line_seq.new(local_pre_pen.end_, pen_array.get(tmp_low_index - pen_array_offset).end_, tmp_low_index, 2, na, 0)
                    line_seq_array.push(tmp_new_line_seq)
                    is_new_line_seq := true
                    seq_local_extre := tmp_new_line_seq.start_.data_mid.high_
                    line_central_new_index := line_central_new_index + 1
            else if ((local_pre_pen.type_ == 2) and (local_last_pen.type_ == 1))
                float tmp_high = 0
                tmp_high_index = pen_index_ + 1
                gap_flag = false
                tmp_b_index = global_begin_seq_pen_index
                if (line_seq_array.size() > 1)
                    tmp_b_index := line_seq_array.get(-2).pen_index_ + 1
                [top_value, bottom_value] = get_last_line_seq_gap(pen_array, pen_array_offset, 2, tmp_b_index, pen_index_)
                if (top_value == -1)
                    top_value := local_pre_pen.start_.data_mid.high_
                else if (local_pre_pen.start_.data_mid.high_ < bottom_value) //解决情况如问题 4.113
                    top_value := local_pre_pen.start_.data_mid.high_

                for i=(pen_index_ + 1) to (pen_array.size() + pen_array_offset - 1)
                    tmp_pen = pen_array.get(i - pen_array_offset)
                    if ((tmp_pen.type_ == 2) and (top_value < tmp_pen.end_.data_mid.low_))
                        gap_flag := true
                    if (tmp_pen.end_.data_mid.high_ >= tmp_high)
                        tmp_high := tmp_pen.end_.data_mid.high_
                        tmp_high_index := i
            
                no_repire_flag = true
                if ((line_seq_array.size() > 1) and (local_pre_pen.end_.data_mid.low_ > line_seq_array.get(-2).start_.data_mid.low_) and (tmp_high >= line_seq_array.last().start_.data_mid.high_))
                    no_repire_flag := false

                if (no_repire_flag == false) // 根据修改是否产生缺口判断单笔成段能否成立，解决情况如问题 4.29
                    tmp_begin_index = global_begin_seq_pen_index
                    if (line_seq_array.size() > 2)
                        tmp_begin_index := line_seq_array.get(-3).pen_index_ + 1
                    no_repire_flag := has_line_seq_gap(pen_array, pen_array_offset, 1, tmp_begin_index, tmp_high_index)
                
                //后续可添加条件：如果高级别笔满足，也可成立特殊段
                if ((gap_flag == true) and (no_repire_flag == true))
                    //label.new(bar_index,high, "XXX", style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)
                    tmp_new_line_seq = line_seq.new(local_pre_pen.end_, pen_array.get(tmp_high_index - pen_array_offset).end_, tmp_high_index, 1, na, 0)
                    line_seq_array.push(tmp_new_line_seq)
                    is_new_line_seq := true
                    seq_local_extre := tmp_new_line_seq.start_.data_mid.low_
                    line_central_new_index := line_central_new_index + 1
        
        // 缺口情况：4， 处理情况如问题4.33
        if ((is_new_line_seq == false) and (line_seq_array.size() > 0) and ((pen_index_ - pen_array_offset - 1) > 0) and ((pen_array.size() + pen_array_offset - 1 - pen_index_) > 4))
            local_last_line_seq = line_seq_array.last()
            local_first_pen = pen_array.get(pen_index_ + 1 - pen_array_offset)
            local_pre_pre_pen = pen_array.get(pen_index_ - pen_array_offset - 1)
            if ((local_last_line_seq.type_ == 2) and (last_pen.type_ == 1))
                if ((local_pre_pre_pen.start_.data_mid.low_ > local_first_pen.end_.data_mid.high_) and (last_pen.start_.data_mid.low_ > local_first_pen.end_.data_mid.high_))
                    float tmp_high = 0
                    tmp_high_index = -1
                    for i = (pen_index_ + 1) to (pen_array.size() + pen_array_offset - 1)
                        tmp_pen = pen_array.get(i - pen_array_offset)
                        if (tmp_pen.end_.data_mid.high_ >= tmp_high)
                            tmp_high := tmp_pen.end_.data_mid.high_
                            tmp_high_index := i
                    if (tmp_high_index > 0)
                        tmp_new_line_seq = line_seq.new(local_last_line_seq.end_, pen_array.get(tmp_high_index - pen_array_offset).end_, tmp_high_index, 1, na, 0)
                        line_seq_array.push(tmp_new_line_seq)
                        is_new_line_seq := true
                        line_central_new_index := line_central_new_index + 1
                        seq_local_extre := tmp_new_line_seq.start_.data_mid.low_
            else if ((local_last_line_seq.type_ == 1) and (last_pen.type_ == 2))
                if ((local_pre_pre_pen.start_.data_mid.high_ < local_first_pen.end_.data_mid.low_) and (last_pen.start_.data_mid.high_ < local_first_pen.end_.data_mid.low_))
                    float tmp_low = local_first_pen.start_.data_mid.low_
                    tmp_low_index = -1
                    for i = (pen_index_ + 1) to (pen_array.size() + pen_array_offset - 1)
                        tmp_pen = pen_array.get(i - pen_array_offset)
                        if (tmp_pen.end_.data_mid.low_ <= tmp_low)
                            tmp_low := tmp_pen.end_.data_mid.low_
                            tmp_low_index := i
    
                    if (tmp_low_index > 0)
                        tmp_new_line_seq = line_seq.new(local_last_line_seq.end_, pen_array.get(tmp_low_index - pen_array_offset).end_, tmp_low_index, 2, na, 0)
                        line_seq_array.push(tmp_new_line_seq)
                        is_new_line_seq := true
                        line_central_new_index := line_central_new_index + 1
                        seq_local_extre := tmp_new_line_seq.start_.data_mid.high_
            
    [is_new_line_seq, seq_local_extre, line_central_new_index, is_seq_modify_2]


export process_optimize_line_seqs(array<pen> pen_array, int pen_array_offset, array<line_seq> line_seq_array, bool is_new_line_seq_g, float seq_local_extre_g, int line_central_new_index_g) =>
    bool is_new_line_seq = is_new_line_seq_g
    float seq_local_extre = seq_local_extre_g
    int line_central_new_index = line_central_new_index_g

    if (line_seq_array.size() > 2) //优化倒数第二个段为单笔成段的情况
        local_second_line_seq = line_seq_array.get(-2)
        tmp_pen = pen_array.get(local_second_line_seq.pen_index_ - pen_array_offset)
        tmp_condi_flag = false
        if (local_second_line_seq.start_.merge_index_ == tmp_pen.start_.merge_index_)
            tmp_condi_flag := true
        else if (local_second_line_seq.special_type_ == 1)
            tmp_condi_flag := true

        if (tmp_condi_flag == true)
            //label.new(bar_index,high, "this", style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)
            local_last_line_seq = line_seq_array.last()
            if (local_second_line_seq.type_ == 1)
                if (local_last_line_seq.end_.data_mid.low_ < local_second_line_seq.start_.data_mid.low_)
                    local_first_line_seq = line_seq_array.get(-3)
                    tmp_condi_flag_2 = true // 该flag用于解决情况如问题 4.28
                    if (local_second_line_seq.special_type_ == 1)
                        float tmp_tmp_high = 0
                        for i = (local_first_line_seq.pen_index_ + 1) to (line_seq_array.last().pen_index_)
                            tmp_tmp_pen = pen_array.get(i - pen_array_offset)
                            if (tmp_tmp_pen.end_.data_mid.high_ >= tmp_tmp_high)
                                tmp_tmp_high := tmp_tmp_pen.end_.data_mid.high_
                        if (tmp_tmp_high < local_first_line_seq.start_.data_mid.high_)
                            tmp_condi_flag_2 := true
                        else
                            tmp_condi_flag_2 := false

                    if ((local_first_line_seq.start_.data_mid.high_ > local_second_line_seq.end_.data_mid.high_) and (tmp_condi_flag_2 == true))
                        //检查修改后是否会出现缺口
                        tmp_begin_index = 0
                        if (line_seq_array.size() > 3)
                            tmp_begin_index := line_seq_array.get(-4).pen_index_ + 1
                        central_flag = false
                        float tmp_top_min = 0
                        float tmp_bottom_max = 0
                        bool gap_flag = false
                        for j = tmp_begin_index to local_last_line_seq.pen_index_
                            tmp_pen_1 = pen_array.get(j - pen_array_offset)
                            if (central_flag == true)
                                if (tmp_pen_1.type_ == 1)
                                    if (tmp_pen_1.end_.data_mid.high_ < tmp_bottom_max)
                                        central_flag := false
                                else if (tmp_pen_1.type_ == 2)
                                    if (tmp_pen_1.end_.data_mid.low_ > tmp_top_min)
                                        gap_flag := true
                                        break                        
                            if (central_flag == false)
                                if ((tmp_pen_1.type_ == 1) and ((j+2)<local_last_line_seq.pen_index_))
                                    //判断是否出现中枢：反向一笔开始，三笔重叠
                                    tmp_pen_2 = pen_array.get(j - pen_array_offset + 1)
                                    tmp_pen_3 = pen_array.get(j - pen_array_offset + 2)
                                    if (tmp_pen_3.end_.data_mid.high_ > tmp_pen_1.start_.data_mid.low_)
                                        //创建中枢
                                        tmp_top_min := math.min(tmp_pen_1.end_.data_mid.high_, tmp_pen_3.end_.data_mid.high_)
                                        tmp_bottom_max := math.max(tmp_pen_1.start_.data_mid.low_, tmp_pen_3.start_.data_mid.low_)
                                        central_flag := true
                        if (gap_flag == false)
                            tmp_delete_line_seq_1 = line_seq_array.pop()
                            line_seq_array.pop()
                            // tmp_new_line_seq = line_seq_array.last()
                            // tmp_new_line_seq.end_ := tmp_delete_line_seq_1.end_
                            // tmp_new_line_seq.pen_index_ := tmp_delete_line_seq_1.pen_index_
                            // tmp_new_line_seq.special_type_ := 0
                            tmp_delete_line_seq_2 = line_seq_array.pop()
                            tmp_new_line_seq = line_seq.new(tmp_delete_line_seq_2.start_, tmp_delete_line_seq_1.end_, tmp_delete_line_seq_1.pen_index_, tmp_delete_line_seq_2.type_, na, 0)
                            line_seq_array.push(tmp_new_line_seq)
                            is_new_line_seq := true
                            seq_local_extre := tmp_new_line_seq.start_.data_mid.high_
                            //line_central_new_index := 0
                            line_central_new_index := line_central_new_index + 1
            else if (local_second_line_seq.type_ == 2)
                if (local_last_line_seq.end_.data_mid.high_ > local_second_line_seq.start_.data_mid.high_)
                    local_first_line_seq = line_seq_array.get(-3)

                    tmp_condi_flag_2 = true // 该flag用于解决情况如问题 4.28
                    if (local_second_line_seq.special_type_ == 1)
                        float tmp_tmp_low = local_second_line_seq.start_.data_mid.low_
                        for i = (local_first_line_seq.pen_index_ + 1) to (line_seq_array.last().pen_index_)
                            tmp_tmp_pen = pen_array.get(i - pen_array_offset)
                            if (tmp_tmp_pen.end_.data_mid.low_ <= tmp_tmp_low)
                                tmp_tmp_low := tmp_tmp_pen.end_.data_mid.low_
                        if (tmp_tmp_low > local_first_line_seq.start_.data_mid.low_)
                            tmp_condi_flag_2 := true
                        else
                            tmp_condi_flag_2 := false

                    if ((local_first_line_seq.start_.data_mid.low_ < local_second_line_seq.end_.data_mid.low_) and (tmp_condi_flag_2 == true))
                        //检查修改后是否会出现缺口
                        tmp_begin_index = 0
                        if (line_seq_array.size() > 3)
                            tmp_begin_index := line_seq_array.get(-4).pen_index_ + 1
                        central_flag = false
                        float tmp_top_min = 0
                        float tmp_bottom_max = 0
                        bool gap_flag = false
                        for j = tmp_begin_index to local_last_line_seq.pen_index_
                            tmp_pen_1 = pen_array.get(j - pen_array_offset)
                            if (central_flag == true)
                                if (tmp_pen_1.type_ == 2)
                                    if (tmp_pen_1.end_.data_mid.low_ > tmp_top_min)
                                        central_flag := false
                                else if (tmp_pen_1.type_ == 1)
                                    if (tmp_pen_1.end_.data_mid.high_ < tmp_bottom_max)
                                        gap_flag := true
                                        break                        
                            if (central_flag == false)
                                if ((tmp_pen_1.type_ == 2) and ((j+2)<local_last_line_seq.pen_index_))
                                    //判断是否出现中枢：反向一笔开始，三笔重叠
                                    tmp_pen_2 = pen_array.get(j - pen_array_offset + 1)
                                    tmp_pen_3 = pen_array.get(j - pen_array_offset + 2)
                                    if (tmp_pen_3.end_.data_mid.low_ < tmp_pen_1.start_.data_mid.high_)
                                        //创建中枢
                                        tmp_top_min := math.min(tmp_pen_1.start_.data_mid.high_, tmp_pen_3.start_.data_mid.high_)
                                        tmp_bottom_max := math.max(tmp_pen_1.end_.data_mid.low_, tmp_pen_3.end_.data_mid.low_)
                                        central_flag := true
                        if (gap_flag == false)
                            tmp_delete_line_seq_1 = line_seq_array.pop()
                            line_seq_array.pop()
                            // tmp_new_line_seq = line_seq_array.last()
                            // tmp_new_line_seq.end_ := tmp_delete_line_seq_1.end_
                            // tmp_new_line_seq.pen_index_ := tmp_delete_line_seq_1.pen_index_
                            // tmp_new_line_seq.special_type_ := 0
                            tmp_delete_line_seq_2 = line_seq_array.pop()
                            tmp_new_line_seq = line_seq.new(tmp_delete_line_seq_2.start_, tmp_delete_line_seq_1.end_, tmp_delete_line_seq_1.pen_index_, tmp_delete_line_seq_2.type_, na, 0)
                            line_seq_array.push(tmp_new_line_seq)
                            is_new_line_seq := true
                            seq_local_extre := tmp_new_line_seq.start_.data_mid.low_
                            //line_central_new_index := 0
                            line_central_new_index := line_central_new_index + 1

    // if (true) //优化倒数第一个段为单笔成段的情况
    //     local_last_line_seq = line_seq_array.get(-1)
    //     tmp_last_pen = pen_array.get(local_last_line_seq.pen_index_ - pen_array_offset)
    //     tmp_condi_flag = false
    //     if (local_last_line_seq.start_.merge_index_ == tmp_last_pen.start_.merge_index_)
    //         tmp_condi_flag := true
        
    //     if (tmp_condi_flag == true)
    //         local_second_line_seq = line_seq_array.get(-2)
    //         if (local_second_line_seq.type_ == 1)
    //             if (local_last_line_seq.end_.data_mid.low_ < local_second_line_seq.start_.data_mid.low_)
    //                 local_first_line_seq = line_seq_array.get(-3)
    //                 if (local_first_line_seq.start_.data_mid.high_ > local_second_line_seq.end_.data_mid.high_)
    //                     //检查修改后是否会产生缺口
    //                     tmp_begin_index = global_begin_seq_pen_index
    //                     if (line_seq_array.size() > 3)
    //                         tmp_begin_index := line_seq_array.get(-4).pen_index_ + 1
    //                     tmp_repire_gap_flag = has_line_seq_gap(2, tmp_begin_index, local_last_line_seq.pen_index_)
                        
    //                     if (tmp_repire_gap_flag == false)
    //                         tmp_delete_line_seq_1 = line_seq_array.pop()
    //                         line_seq_array.pop()
    //                         tmp_new_line_seq = line_seq_array.last()
    //                         tmp_new_line_seq.end_ := tmp_delete_line_seq_1.end_
    //                         tmp_new_line_seq.pen_index_ := tmp_delete_line_seq_1.pen_index_
    //                         is_new_line_seq := true
    //                         line_central_new_index := 0
    //         else if (local_second_line_seq.type_ == 2)
    //             if (local_last_line_seq.end_.data_mid.high_ > local_second_line_seq.start_.data_mid.high_)
    //                 local_first_line_seq = line_seq_array.get(-3)
    //                 if (local_first_line_seq.start_.data_mid.low_ < local_second_line_seq.end_.data_mid.low_)
    //                     //检查修改后是否会产生缺口
    //                     tmp_begin_index = global_begin_seq_pen_index
    //                     if (line_seq_array.size() > 3)
    //                         tmp_begin_index := line_seq_array.get(-4).pen_index_ + 1
    //                     tmp_repire_gap_flag = has_line_seq_gap(1, tmp_begin_index, local_last_line_seq.pen_index_)

    //                     if (tmp_repire_gap_flag == false)
    //                         tmp_delete_line_seq_1 = line_seq_array.pop()
    //                         line_seq_array.pop()
    //                         tmp_new_line_seq = line_seq_array.last()
    //                         tmp_new_line_seq.end_ := tmp_delete_line_seq_1.end_
    //                         tmp_new_line_seq.pen_index_ := tmp_delete_line_seq_1.pen_index_
    //                         is_new_line_seq := true
    //                         line_central_new_index := 0

    if (line_seq_array.size() > 2) //优化倒数第三个段为单笔成段或特殊笔的情况，处理情况如问题4.50
        local_first_line_seq = line_seq_array.get(-3)
        tmp_pen = pen_array.get(local_first_line_seq.pen_index_ - pen_array_offset)
        tmp_condi_flag = false
        if (local_first_line_seq.start_.merge_index_ == tmp_pen.start_.merge_index_)
            tmp_condi_flag := true            
        else if (local_first_line_seq.special_type_ == 1)
            tmp_condi_flag := true

        if (tmp_condi_flag == true)
            //label.new(bar_index,high, "this", style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)
            local_last_line_seq = line_seq_array.last()
            if (local_first_line_seq.type_ == 2)
                if (local_last_line_seq.end_.data_mid.low_ < local_first_line_seq.end_.data_mid.low_)
                    local_second_line_seq = line_seq_array.get(-2)
                    tmp_condi_flag_2 = true // 该flag用于解决情况如问题 4.28
                    if (local_first_line_seq.special_type_ == 1)
                        float tmp_tmp_high = 0
                        for i = (local_first_line_seq.pen_index_ + 1) to (line_seq_array.last().pen_index_)
                            tmp_tmp_pen = pen_array.get(i - pen_array_offset)
                            if (tmp_tmp_pen.end_.data_mid.high_ >= tmp_tmp_high)
                                tmp_tmp_high := tmp_tmp_pen.end_.data_mid.high_
                        if (tmp_tmp_high < local_first_line_seq.start_.data_mid.high_)
                            tmp_condi_flag_2 := true
                        else
                            tmp_condi_flag_2 := false

                    if ((local_first_line_seq.start_.data_mid.high_ > local_second_line_seq.end_.data_mid.high_) and (tmp_condi_flag_2 == true))
                        //检查修改后是否会出现缺口
                        tmp_begin_index = 0
                        if (line_seq_array.size() > 3)
                            tmp_begin_index := line_seq_array.get(-4).pen_index_ + 1

                        bool gap_flag = has_line_seq_gap(pen_array, pen_array_offset, 2, tmp_begin_index, line_seq_array.last().pen_index_)

                        if (gap_flag == false)
                            tmp_delete_line_seq_1 = line_seq_array.pop()
                            line_seq_array.pop()
                            //tmp_new_line_seq = line_seq_array.last()
                            // tmp_new_line_seq.end_ := tmp_delete_line_seq_1.end_
                            // tmp_new_line_seq.pen_index_ := tmp_delete_line_seq_1.pen_index_
                            // tmp_new_line_seq.special_type_ := 0
                            tmp_delete_line_seq_2 = line_seq_array.pop()
                            tmp_new_line_seq = line_seq.new(tmp_delete_line_seq_2.start_, tmp_delete_line_seq_1.end_, tmp_delete_line_seq_1.pen_index_, tmp_delete_line_seq_2.type_, na, 0)
                            line_seq_array.push(tmp_new_line_seq)
                            is_new_line_seq := true
                            seq_local_extre := tmp_new_line_seq.start_.data_mid.high_
                            //line_central_new_index := 0
                            line_central_new_index := line_central_new_index + 1

            else if (local_first_line_seq.type_ == 1)
                if (local_last_line_seq.end_.data_mid.high_ > local_first_line_seq.end_.data_mid.high_)
                    local_second_line_seq = line_seq_array.get(-2)

                    tmp_condi_flag_2 = true // 该flag用于解决情况如问题 4.28
                    if (local_first_line_seq.special_type_ == 1)
                        float tmp_tmp_low = local_second_line_seq.start_.data_mid.low_
                        for i = (local_first_line_seq.pen_index_ + 1) to (line_seq_array.last().pen_index_)
                            tmp_tmp_pen = pen_array.get(i - pen_array_offset)
                            if (tmp_tmp_pen.end_.data_mid.low_ <= tmp_tmp_low)
                                tmp_tmp_low := tmp_tmp_pen.end_.data_mid.low_
                        if (tmp_tmp_low > local_first_line_seq.start_.data_mid.low_)
                            tmp_condi_flag_2 := true
                        else
                            tmp_condi_flag_2 := false

                    if ((local_first_line_seq.start_.data_mid.low_ < local_second_line_seq.end_.data_mid.low_) and (tmp_condi_flag_2 == true))
                        //检查修改后是否会出现缺口
                        tmp_begin_index = 0
                        if (line_seq_array.size() > 3)
                            tmp_begin_index := line_seq_array.get(-4).pen_index_ + 1
                        central_flag = false
                        bool gap_flag = has_line_seq_gap(pen_array, pen_array_offset, 1, tmp_begin_index, line_seq_array.last().pen_index_)

                        if (gap_flag == false)
                            tmp_delete_line_seq_1 = line_seq_array.pop()
                            line_seq_array.pop()
                            // tmp_new_line_seq = line_seq_array.last()
                            // tmp_new_line_seq.end_ := tmp_delete_line_seq_1.end_
                            // tmp_new_line_seq.pen_index_ := tmp_delete_line_seq_1.pen_index_
                            // tmp_new_line_seq.special_type_ := 0
                            tmp_delete_line_seq_2 = line_seq_array.pop()
                            tmp_new_line_seq = line_seq.new(tmp_delete_line_seq_2.start_, tmp_delete_line_seq_1.end_, tmp_delete_line_seq_1.pen_index_, tmp_delete_line_seq_2.type_, na, 0)
                            line_seq_array.push(tmp_new_line_seq)
                            is_new_line_seq := true
                            seq_local_extre := tmp_new_line_seq.start_.data_mid.low_
                            //line_central_new_index := 0
                            line_central_new_index := line_central_new_index + 1
                            //label.new(bar_index,high, "bb", style=label.style_label_down, size=size.tiny, textcolor=color.white, color=color.purple, yloc=yloc.price)
    [is_new_line_seq, seq_local_extre, line_central_new_index]