// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © moebius1977

//@version=6

// @description Contains regex search functions: 
//
// - feedRgx():  Searches for the first occurrence of `regex` pattern in the `src` and returns `src` split into parts
// as a tuple: `[<before the match>, <match>, <after the macth>]`. If no match returns `[src,"",""]`
//
// - countRgx():  Counts `regex` occurrences in the `src`.
//
// - matchRgx():  Finds given `occurence` of `regex` pattern in `src` string.
//
// ___NB!___ _countRgx() matchRgx() do not support `^` (beginning of the string 
// placeholder), lookbehind some other complex patterns, because they works by cutting off the part of the string up to 
// the first found occurence (inclusive) and then continuing the search on the remainder of the string. E.g. in a four line source `(?<=\n).+\n` should match the second and the third lines but matchRgx only 
// matches the second line since after matching it continues to search in the remainder AFTER the match only. _ 
library("RegexLib")


// // ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
// // ┃                          HELPER FUNCTIONS                                    ┃ {

// ━━━━━ trim2() ━━━━━ {
// from library moebius1977/StrTrimPadCase/2
// @function Like str.trim() but also trims line breaks ("\n")
method trim2(string s) =>
    s1 = str.trim(str.match(s,"\\S(.|\\s)*"))
    while str.length(s1) > 0 
        i = str.length(s1) - 1
        lastChar = str.substring(s1, i)
        if lastChar == "\n" // or lastChar == "\r"  \r has no special meaning in pine
            s1 := str.trim(str.substring(s1, 0, i))
        else
            break
    s1
// END OF trim2 }

// // ┃ ^^^ END OF HELPER FUNCTIONS                                       ┃}
// // ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ 


// ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
// ┃                          RegexLib LIBRARY FUNCTIONS                          ┃{

// --- feedRgx(s, regex) ---{
// @function Searches for the first occurrence of `regex` pattern in the `src` and returns `src` split into parts
// as a tuple: `[<before the match>, <match>, <after the macth>]`. If no match returns `[src,"",""]`
// @param src (string) String to search for the regex pattern
// @param regex (string) RegEx pattern
// @returns A tuple `[begS, matchS, endS]` where `begS` is the part of the `src` string from the beginning up to the
// first occurence of the `regex` pattern (or up to the end if not found), `matchS` - the first occurrence of the 
// regex pattern and `endS` the part of the strinf following the first occurrence of the `regex` pattern.
export method feedRgx(string src, string regex) =>
    begS = "" 
    endS= ""
    matchS = str.match(src, regex) 
    if matchS == ""
        begS := src
        endS := ""
    else    
        mp = str.pos(src, matchS)
        ml = str.length(matchS)
        begS := str.substring(src,0,mp)
        endS := str.substring(src,mp+ml)

    [begS, matchS, endS]
// END OF feedRgx}

// --- countRgx(s, regex) ---{
// @function Counts `regex` occurrences in the `src`. ___NB!___ _Does not support `^` (beginning of the string 
// placeholder), lookbehind some other complex patterns, because it works by cutting off the part of the string up to 
// the first found occurence (inclusive) and then continuing the search on the remainder of the string. E.g. in a four line source `(?<=\n).+\n` should match the second and the third lines but matchRgx only 
// matches the second line since after matching it continues to search in the remainder AFTER the match only. _ 
// @param src (string) String in which the regex pattern occurences are to be counted
// @param regex (string) RegEx pattern
// @returns The number of occurences of the `regex` pattern in the `src` string.
export method countRgx(string src, string regex) =>
    endS= src
	n = 0 
	while endS != "" 
	    [_begS, _matchS, _endS] = feedRgx(endS, regex)
		n += _matchS != "" ? 1 : 0
		endS := _endS
	n
// END OF countRgx}

// --- matchRgx(s, regex) ---{
// @function Finds given `occurence` of `regex` pattern in `src` string. ___NB!___ _Does not support `^` 
// (beginning of the string placeholder), lookbehind and some other complex patterns, because it works by cutting off
// the part of the string up to the first found occurence (inclusive) and then continuing the search on the remainder 
// of the string. E.g. in a four line source `(?<=\n).+\n` should match the second and the third lines but matchRgx only 
// matches the second line since after matching it continues to search in the remainder AFTER the match only. _ 
// @param src (string) String to search for the regex pattern
// @param regex (string) RegEx pattern
// @param occurrence (int) (Default is 1) The number of the occurrence to search for. If this params exceeds the actual 
// number of occurrences of the pattern in the `src` string the following tuple is returned [na, src length, na]
// @returns [matchS , matchPos, matchL] A tuple, matchS - matched substring, matchPos - position of the match, matchL - match length
export method matchRgx(string src, string regex, int occurrence = 1 ) =>
    endS= src
    matchS= ""
    matchPos = int(na)
    matchL = int(na)
	n = 0 
	cutoffL = 0
	if occurrence < 1 
		runtime.error(str.format("matchRgx(): Argument occurrence {0} is < 1", occurrence))

	while n != occurrence
	    matchS := str.match(endS, regex) 
		if matchS == "" // is the same as `is na(matchS)`
			matchPos := na
			matchL := na
			break
		else    
			n+=1
			matchPos := str.pos(endS, matchS)
			matchL := str.length(matchS)
			endS := str.substring(endS, matchPos+matchL)
			cutoffL+=matchPos+matchL
	[matchS , cutoffL-matchL, matchL]
// END OF matchRgx}

// --- csvToArS() ---{
// @function Returns a string array of CSV values 
// @param this (string) String of comma separated values
// @returns A string array of values from `this` string. 
export method csvToArS(string this) =>
    ar = array.new<string>()
    e = this
    while e != ""
        [b, m, e1] = e.feedRgx("\,")
        ar.push(b.trim2())
        e := e1
    ar

// END OF csvToArS() }

// --- csvToArF() ---{
// @function Returns a float array of CSV values. (returns NaN for non-numerical values))
// @param this (string) String of comma separated values
// @returns A float array of values from `this` string. 
export method csvToArF(string this) =>
    ar = array.new<float>()
    e = this
    while e != ""
        [b, m, e1] = e.feedRgx("\,")
        ar.push(str.tonumber(b.trim2()))
        e := e1
    ar

// END OF csvToArF() }

// --- csvToArI() ---{
// @function Returns a int array of CSV values. Returns NaN for non-numerical values. Decimals are trimmed. 
// @param this (string) String of comma separated values
// @returns An int array of values from `this` string. 
export method csvToArI(string this) =>
    ar = array.new<int>()
    e = this
    while e != ""
        [b, m, e1] = e.feedRgx("\,")
        ar.push(int(str.tonumber(b.trim2())))
        e := e1
    ar

// END OF csvToArI() }

// ┃ ^^^ END OF REGEX LIB FUNCTIONS                                               ┃}
// ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ 

 

// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║                                DEMO                                          ║ {

// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ DEMO MAIN ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ {


// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ INPUT ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ {

// --- DEMO PARAMS INPUTS ---{ 
i_N = 		input.int			(group="Sample search", defval =  1					, title = "Occurrence", inline = "")
i_rgxS = 	input.string		(group="Sample search", defval =  "[A-Z]+\\d+[\\.\\-]*\\d*"			, title = "Regex pattern")
i_s3 = 		input.text_area		(group="Sample search"
									 , defval =  "
									 Props:
									 TF1:(len=12, type=\"aaa\")\n
									 TF2.1:(len=12, type='aaa')\n
									 asasas34TF3.4:(len=12, type=aaa)RRRR3-3)\n
									 RRRR 				
									 "	
									 , title = "Source string")

i_sCSV = 		input.text_area		(group="CSV string"
									 , defval =  "2.2, 9.9, 44, a1, a2, a3"
									 , title = "CSV string")
//}

// --- TABLE INPUTS ---{
i_tblH =  input.int(group="Table properties", defval = 100, title = "Table height", inline = "")
i_tblHeadersH =  input.int(group="Table properties", defval = 10, title = "Rows height: header rows", inline = "rows")
i_tblParamRowsH =  input.int(group="Table properties", defval = 20, title = "Params", inline = "rows")
i_tblOutputRowH =  input.int(group="Table properties", defval = 70, title = "Output", inline = "rows")
i_col0W = input.int(group="Table properties", defval = 60, title = "Column width: left", inline = "w")
i_col1W = input.int(group="Table properties", defval = 40, title = "right", inline = "w")
iRow0H = i_tblH * i_tblHeadersH /100 /2
iRow1H = i_tblH * i_tblHeadersH /100 /2
iRow2H = i_tblH * i_tblParamRowsH / 100 
iRow3H = i_tblH * i_tblOutputRowH / 100
iCell0Wsmaller = i_col0W / 3 
// --- input lblSize --- {
i_textSize        = input.string  (group = "text", inline = "lbls1", defval = "Small", title="Size", options= ["Auto", "Tiny", "Small", "Normal", "Large", "Huge"])

//Turn the input into a proper label size value
simple string iTextSize =   switch i_textSize
	"Auto"    => size.auto  	
	"Tiny"    => size.tiny  
	"Small"   => size.small 
	"Normal"  => size.normal
	"Large"   => size.large 
	"Huge"    => size.huge  
	=> size.normal

// END OF lblSize input }
//}

// ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ END OF INPUT  ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ }

const color BG_COLOR = #f5f395
var t = table.new(position.bottom_center, 4, 4, bgcolor = BG_COLOR, border_color = color.black, border_width = 1, frame_color = color.black, frame_width = 1)
if barstate.islastconfirmedhistory

	// init var for output cells  of the table 
	txtOut0 = ""
	txtOut1 = ""


	// ━━━━━ test feedRgx() ━━━━━{
	txtOut0 += "\n\n -------- TEST feedRgx() -------- \n"
	txtOut0 += "Looks for 1st occurrence of regex in S input and splits\n"
	[b1, m1, a1] = i_s3.feedRgx(i_rgxS)
	txtOut0 += str.format ("
						  \nbefore:\n---\n{0}\n
						  \nmatch:\n---\n {1}\n
						  \nafter:\n---\n {2}\n
						  \n---\n 
						  " 
						  , b1
						  , m1
						  , a1
						  )
						  
	//}

	// ━━━━━ test matchRgx() ━━━━━{
	txtOut0 += "\n\n -------- TEST matchRgx() -------- \n"
	txtOut0 += str.format("Looks for {0}'s occurrence of Regex input in S input.\n", i_N)
	[m, p, l] = matchRgx(i_s3, i_rgxS, i_N)
	txtOut0 += str.format("\nFound:\n---\n{0}\n---\n at {1}, match length is {2} \n", m, p, l)
	//}
	
	// ━━━━━ test countRgx() ━━━━━{
	txtOut0 += "\n\n -------- TEST countRgx() -------- \n"
	txtOut0 += "\nCounting for regex patterns in S \n"

	txtOut0 += str.tostring(i_s3.countRgx(i_rgxS))
	//}
	
	// ━━━━━ test csvToArS() ━━━━━{
	txtOut1 += "\n -------- TEST csvToArS(), csvToArF(), csvToArI() -------- \n"
	txtOut1 += "\nSource string:  "

	txtOut1 += i_sCSV
	txtOut1 += "\nArray returned by csvToArS():  "
	txtOut1 += str.tostring( i_sCSV.csvToArS() )
	txtOut1 += "\nArray returned by csvToArF():  "
	txtOut1 += str.tostring( i_sCSV.csvToArF() )
	txtOut1 += "\nArray returned by csvToArI():  "
	txtOut1 += str.tostring( i_sCSV.csvToArI() )
	//}

	// ━━━━━ draw table ━━━━━ {
	// TEST ALL 

	// 1st row 
	table.cell(t,0,0, text_halign = text.align_left, text_valign = text.align_top, width = iCell0Wsmaller, height = iRow0H, text_font_family = font.family_monospace)
	table.cell(t,1,0, text_halign = text.align_left, text_valign = text.align_top, width = iCell0Wsmaller, height = iRow0H, text_font_family = font.family_monospace)
	table.cell(t,2,0, text_halign = text.align_left, text_valign = text.align_top, width = iCell0Wsmaller, height = iRow0H, text_font_family = font.family_monospace)
	table.cell(t,3,0, text_halign = text.align_left, text_valign = text.align_top, width = i_col1W		 , height = iRow0H, text_font_family = font.family_monospace)
	// 2nd row 
	table.cell(t,0,1, text_halign = text.align_center, text_valign = text.align_top,width = iCell0Wsmaller, height = iRow1H, text_font_family = font.family_monospace)
	table.cell(t,1,1, text_halign = text.align_center, text_valign = text.align_top,width = iCell0Wsmaller, height = iRow1H, text_font_family = font.family_monospace)
	table.cell(t,2,1, text_halign = text.align_center, text_valign = text.align_top,width = iCell0Wsmaller, height = iRow1H, text_font_family = font.family_monospace)
	table.cell(t,3,1, text_halign = text.align_center, text_valign = text.align_top,width = i_col1W		  , height = iRow1H, text_font_family = font.family_monospace)
	// 3rd row 
	table.cell(t,0,2, text_halign = text.align_left, text_valign = text.align_top, width = iCell0Wsmaller, height = iRow2H, text_font_family = font.family_monospace)
	table.cell(t,1,2, text_halign = text.align_left, text_valign = text.align_top, width = iCell0Wsmaller, height = iRow2H, text_font_family = font.family_monospace)
	table.cell(t,2,2, text_halign = text.align_left, text_valign = text.align_top, width = iCell0Wsmaller, height = iRow2H, text_font_family = font.family_monospace)
	table.cell(t,3,2, text_halign = text.align_left, text_valign = text.align_top, width = i_col1W		 , height = iRow2H, text_font_family = font.family_monospace)
	// 4th row
	table.cell(t,0,3, text_halign = text.align_left, text_valign = text.align_top, width = iCell0Wsmaller, height = iRow3H, text_font_family = font.family_monospace)
	table.cell(t,1,3, text_halign = text.align_left, text_valign = text.align_top, width = iCell0Wsmaller, height = iRow3H, text_font_family = font.family_monospace)
	table.cell(t,2,3, text_halign = text.align_left, text_valign = text.align_top, width = iCell0Wsmaller, height = iRow3H, text_font_family = font.family_monospace)
	table.cell(t,3,3, text_halign = text.align_left, text_valign = text.align_top, width = i_col1W		 , height = iRow3H, text_font_family = font.family_monospace)

	// merge first 3 cells in 1st row
	table.merge_cells(t, 0,0,2,0)
	// merge first 3 cells in 1st row
	table.merge_cells(t, 0,1,2,1)
	// merge first 3 cells in 4th row
	table.merge_cells(t, 0,3,2,3)

	// merge last column cells
	table.merge_cells(t, 3,0,3,3)

	// --- 1st row -- 

	// ---- CELL(0,0) --- 
	table.cell_set_text			(t, 0, 0, "")
	table.cell_set_text_size	(t, 0, 0, text_size = size.normal)
	table.cell_set_bgcolor		(t, 0, 0,BG_COLOR)

	// --- 2nd row --- 
	// ---- CELL(0,0) --- 
	table.cell_set_text			(t, 0, 1, "TEST REGEX LIB")
	table.cell_set_text_size	(t, 0, 1, text_size = size.normal)
	table.cell_set_bgcolor		(t, 0, 1,#ecc504)

	// --- 3nd row --- 

	// ---- CELL(0,1) --- 
	table.cell_set_text			(t, 0, 2, "S:\n" +  i_s3)
	table.cell_set_text_size	(t, 0, 2, iTextSize)
	table.cell_set_text			(t, 1, 2, "Regex:\n" +  i_rgxS)
	table.cell_set_text_size	(t, 1, 2, iTextSize)
	table.cell_set_text			(t, 2, 2, "Occurrence:" + str.tostring(i_N))
	table.cell_set_text_size	(t, 2, 2, iTextSize)

	
	// ---- 3rd row 

	// ---- CELL(0,2) --- 
	table.cell_set_text			(t, 0, 3, txtOut0)
	table.cell_set_text_size	(t, 0, 3, iTextSize)
	table.cell_set_text			(t, 3, 0, txtOut1)
	table.cell_set_text_size	(t, 3, 0, iTextSize)

	//}


// ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ END OF DEMO MAIN  ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ }

// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ DEBUG PRINTS ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ {

// plotchar(bar_index, "bar_index",  "", location = location.bottom)
// plotchar(array.size(table.all), "table.all size",  "", location = location.bottom)
// plotchar(array.size(line.all), "line.all size",  "", location = location.bottom)
// plotchar(array.size(label.all), "label.all size",  "", location = location.bottom)

// ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ END OF DEBUG PRINTS  ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲ }

 
// ║                 END OF DEMO                                                  ║ }
// ╚══════════════════════════════════════════════════════════════════════════════╝






