//@version=5
library("display_value")

// --- Enums (for clarity) ---
// @enum Assorted types for display
// @field title (DisplayFormat)  Used for titles.
// @field percent (DisplayFormat) Used for percentage values.
// @field currency (DisplayFormat) Used for currency values.
// @field decimal (DisplayFormat) Used for decimal values.
// @field integer (DisplayFormat) Used for integer values.
// @field hide (DisplayFormat) Used to hide a value.
export enum DisplayFormat
    title     = "title"
    percent  = "percent"
    currency = "currency"
    decimal  = "decimal"
    integer  = "integer"
    hide     = "hide"


// --- User Defined Types (UDTs) ---

// @type Structure representing a display value.
// @field title          (string)  The title of the display value.
// @field format_string  (string)  The format string to use for display.
// @field value          (float)   The value to display.
// @field format         (DisplayFormat) The format to use.
export type DisplayValue
    string        title          = na
    string        format_string  = na
    float         value          = na
    DisplayFormat format


// @function Gets the appropriate format string based on the display format.
// @param display_name (string)  The name of the display value. Default is na.
// @param display_value(float)   The value to display. Default is na.
// @param display_format(DisplayFormat) The display format. Default is na.
// @returns (DisplayValue) A new DisplayValue instance with the formatted value.
export create(string display_name = na, float display_value = na, DisplayFormat display_format = na) =>
    string format_string = switch display_format
        DisplayFormat.percent  => "{0} - {1,number,percent}"
        DisplayFormat.currency => "{0} - {1,number,currency}"
        DisplayFormat.integer  => "{0} - {1,number,integer}"
        DisplayFormat.decimal  => "{0} - {1,number,#.##}"
        DisplayFormat.title    => "{0}"
        => "{0} - {1}" // Default to text
    DisplayValue.new(display_name, format_string, display_value, display_format)


// @function Converts the display value to a string with the specified format.
// @param item (DisplayValue) The display value to convert to a string.
// @returns (string) The string representation of the display value.
export to_string(DisplayValue item) =>
    if na(item.title)
        item.title := ""
    if item.format == DisplayFormat.title
        str.format(item.format_string, item.title)
    else
        str.format(item.format_string, item.title, item.value)




test()=>
    // --- Test Cases ---
    if  barstate.islastconfirmedhistory
        // Test Case 1: Title Format
        var DisplayValue title_test = create("My Title", na, DisplayFormat.title)
        var string title_result = to_string(title_test)

        // Test Case 2: Percentage Format
        var DisplayValue percent_test = create("My Percentage", 0.5, DisplayFormat.percent)
        var string percent_result = to_string(percent_test)

        // Test Case 3: Currency Format
        var DisplayValue currency_test = create("My Currency", 123.45, DisplayFormat.currency)
        var string currency_result = to_string(currency_test)

        // Test Case 4: Decimal Format
        var DisplayValue decimal_test = create("My Decimal", 123.456789, DisplayFormat.decimal)
        var string decimal_result = to_string(decimal_test)

        // Test Case 5: Integer Format
        var DisplayValue integer_test = create("My Integer", 123.45, DisplayFormat.integer)
        var string integer_result = to_string(integer_test)


        // Output the results of the test cases 
        label.new(bar_index, high, title_result, color=color.green, size = size.huge)
        label.new(bar_index, high + 10, percent_result, color=color.blue, size = size.huge)
        label.new(bar_index, high + 20, currency_result, color=color.orange, size = size.huge)
        label.new(bar_index, high + 30, decimal_result, color=color.red, size = size.huge)
        label.new(bar_index, high + 40, integer_result, color=color.purple, size = size.huge)

