// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © blitz_locked

//@version=6
strategy("MACD Multi-Confirm Strategy", overlay=true, 
     initial_capital=100000, pyramiding=0, commission_type=strategy.commission.percent, commission_value=0.1)

// --- Core MACD inputs ---
fastLen = input.int(12, "MACD Fast Length")
slowLen = input.int(26, "MACD Slow Length")
sigLen = input.int(9, "MACD Signal Length")

breakevenATR = input.float(1.0, "ATR Profit Before Breakeven")

// --- Filter toggles ---
useRSIFilter = input.bool(true, "Use RSI Filter")
useVolumeFilter = input.bool(true, "Use Volume Filter")
useMTFFilter = input.bool(true, "Use Multi-Timeframe Filter")
useADXFilter = input.bool(true, "Use ADX filter")

useMarketFilter = input.bool(true, "Use Market Regime Filter")

marketSymbol = input.symbol("SPY", "Market Benchmark")

marketEMALength = input.int(200, "Market EMA Length")

rsiLen = input.int(14, "RSI Length")
rsiOverbought = input.int(70, "RSI Overbought Level")
htfRes = input.timeframe("W", "Higher Timeframe")
volMultiplier = input.float(1.2, "Volume Confirmation Multiplier")
atrLen = input.int(14, "ATR Length")
atrMult = input.float(2.5, "Stop Loss ATR Multiple")

riskPercent = input.float(1.0, "Risk % Per Trade")


adxLen = input.int(14)
adxThreshold = input.float(20)


maxBarsHeld = input.int(60)

//Market trend
marketClose =
     request.security(
          marketSymbol,
          timeframe.period,
          close,
          lookahead=barmerge.lookahead_off
     )


marketEMA =
     request.security(
          marketSymbol,
          timeframe.period,
          ta.ema(close, marketEMALength),
          lookahead=barmerge.lookahead_off
     )

marketBullish =
     marketClose > marketEMA

marketCondition =
     useMarketFilter ?
     marketBullish :
     true

// --- MACD ---
[macdLine, signalLine, histLine] = ta.macd(close, fastLen, slowLen, sigLen)
macdCrossUp = ta.crossover(macdLine, signalLine)


macdCrossDown = ta.crossunder(macdLine, signalLine)


// --- RSI filter (bypassed as "true" if toggle is off) ---
rsiVal = ta.rsi(close, rsiLen)
notOverbought = useRSIFilter ? rsiVal < rsiOverbought : true

// --- Volume filter ---
avgVolume = ta.sma(volume, 20)
volumeConfirms = useVolumeFilter ? volume > avgVolume * volMultiplier : true

// --- Multi-timeframe trend filter ---
htf_close = request.security(syminfo.tickerid, htfRes, close, lookahead=barmerge.lookahead_off)
htf_ema = request.security(syminfo.tickerid, htfRes, ta.ema(close, 50), lookahead=barmerge.lookahead_off)
higherTimeframeUptrend = useMTFFilter ? htf_close > htf_ema : true

//ADX filter
[plusDI,minusDI,adx] = ta.dmi(adxLen,adxLen)


trendStrong = useADXFilter ? adx > adxThreshold : true

// --- Combined entry ---
longCondition = macdCrossUp and notOverbought and volumeConfirms and higherTimeframeUptrend and macdLine>0 and trendStrong and marketCondition

//sizing position
atr = ta.atr(atrLen)


stopDistance = atr * atrMult


capitalRisk = strategy.equity * riskPercent / 100


positionSize =
 capitalRisk / stopDistance



if (longCondition)
    strategy.entry("Long", strategy.long, qty = positionSize)


//trailing stop
var float trailStop = na
var int entryBar = na
var float highestPrice = na

newTrade =
 strategy.position_size > 0 and
 strategy.position_size[1] <= 0

if newTrade

    highestPrice:=high

    trailStop :=
         close - atr*atrMult

    entryBar :=
         bar_index

if strategy.position_size > 0

    highestPrice := math.max(highestPrice, high)

    // price movement since entry
    newStop = highestPrice - atr*atrMult


    trailStop :=
         math.max(
             trailStop,
             newStop
         )



    strategy.exit(
         "ATR Trail",
         "Long",
         stop=trailStop
    )

    // =========================
    // MOMENTUM EXIT
    // =========================

    momentumExit = macdCrossDown and histLine < 0

    trendExit =
         htf_close < htf_ema

    timeExit = bar_index-entryBar > maxBarsHeld

    if momentumExit or trendExit or timeExit

        strategy.close("Long")



else

    trailStop := na
    entryBar := na


// EMA 50
plot(
     ta.ema(close,50),
     color=color.blue,
     linewidth=2,
     title="EMA 50"
)



// ATR Stop
plot(
     trailStop,
     color=color.red,
     linewidth=2,
     style=plot.style_linebr,
     title="ATR Trailing Stop"
)



// Market regime background

bgcolor(
     marketCondition ?
     color.new(color.green,90) :
     color.new(color.red,90),
     title="Market Regime"
)



// ADX strength marker

trendStart = trendStrong and not trendStrong[1]

plotshape(
     trendStart,
     title="Trend Started",
     style=shape.labelup,
     location=location.belowbar,
     color=color.rgb(33, 243, 114),
     text="STRONG\nTREND"
)