// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// ©
import TradingView/ta/5

//@version=5

// @description It's a library of discrete aproximations of a price or Series float it uses Fourier transform, Laplace Discrete Original and Modified transform and Euler's Theoreum for Homogenus White noice operations. Calling functions without source value it automatically take close as the default source value.
library("math")


// @function DFT3: Discrete Fourier Transform with 3 points
// @param x Array of input values
// @param y Array of imaginary values
// @param _dir Direction parameter
// @returns  Aproxiated source value
DFT3(x, y, _dir) =>  
    
    

	x_0 = array.get(x, 0) + array.get(x, 1)+ array.get(x, 2) 
	x_1 = array.get(x, 0) + array.get(x, 1) * math.cos( -2 * math.pi * _dir / 3 ) - array.get(y, 1) * math.sin( -2 * math.pi * _dir / 3)   + array.get(x, 2) * math.cos( -4 * math.pi * _dir / 3 ) - array.get(y, 2) * math.sin( -4 * math.pi * _dir / 3 ) 
	x_2 = array.get(x, 0) + array.get(x, 1) * math.cos( -4 * math.pi * _dir / 3 )- array.get(y, 1) * math.sin( -4 * math.pi * _dir / 3 )  + array.get(x, 2) * math.cos( -8 * math.pi * _dir / 3 ) - array.get(y, 2) * math.sin( -8 * math.pi * _dir / 3 )

	y_0 = array.get(x, 0) + array.get(x, 1)+ array.get(x, 2)
	y_1 = array.get(x, 0) + array.get(x, 1) * math.sin( -2 * math.pi * _dir / 3)  + array.get(y, 1) * math.cos( -2 * math.pi * _dir / 3 ) + array.get(x, 2) * math.sin( -4 * math.pi * _dir / 3 ) + array.get(y, 2) * math.cos( -4 * math.pi * _dir / 3 )
	y_2 = array.get(x, 0) + array.get(x, 1) * math.sin( -4 * math.pi * _dir / 3)  + array.get(y, 1) * math.cos( -4 * math.pi * _dir / 3 )  + array.get(x, 2) * math.sin( -8 * math.pi * _dir / 3 ) + array.get(y, 2) * math.cos( -8 * math.pi * _dir / 3 )


	div =  _dir == 1 ? 3 : _dir


	array.set(x, 0, x_0 / div)
	array.set(x, 1, x_1 / div)
	array.set(x, 2, x_2 / div)
	array.set(y, 0, y_0 / div)
	array.set(y, 1, y_1 / div)
	array.set(y, 2, y_2 / div)


// @function DFT3: Discrete Fourier Transform with last 3 points
// @param x Array of input values
// @param y Array of imaginary values
// @param _dir Direction parameter
// @returns  Aproxiated source value
export DFT3(series float xval = close , int _dir = 2) =>  
    
	x = array.new_float(3, 0.0)
	y = array.new_float(3, 0.0)
	for i = 0 to 2
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)
    

	x_0 = array.get(x, 0) + array.get(x, 1) + array.get(x, 2) 
	x_1 = array.get(x, 0) + array.get(x, 1) * math.cos( -2 * math.pi * _dir / 3 )- array.get(y, 1) * math.sin( -2 * math.pi * _dir / 3 ) + array.get(x, 2) * math.cos( -4 * math.pi * _dir / 3 ) - array.get(y, 2) * math.sin( -4 * math.pi * _dir / 3 )
	x_2 = array.get(x, 0) + array.get(x, 1) * math.cos( -4 * math.pi * _dir / 3 )- array.get(y, 1) * math.sin( -4 * math.pi * _dir / 3 ) + array.get(x, 2) * math.cos( -8 * math.pi * _dir / 3 ) - array.get(y, 2) * math.sin( -8 * math.pi * _dir / 3 )

	y_0 = array.get(x, 0) + array.get(x, 1 )+ array.get(x, 2)
	y_1 = array.get(x, 0) + array.get(x, 1) * math.sin( -2 * math.pi * _dir / 3 )+ array.get(y, 1) * math.cos( -2 * math.pi * _dir / 3 ) + array.get(x, 2) * math.sin( -4 * math.pi * _dir / 3 ) + array.get(y, 2) * math.cos( -4 * math.pi * _dir / 3 )
	y_2 = array.get(x, 0) + array.get(x, 1) * math.sin( -4 * math.pi * _dir / 3 )+ array.get(y, 1) * math.cos( -4 * math.pi * _dir / 3 ) + array.get(x, 2) * math.sin( -8 * math.pi * _dir / 3 ) + array.get(y, 2) * math.cos( -8 * math.pi * _dir / 3 )


	div =  _dir == 1 ? 3 : _dir


	array.set(x, 0, x_0 / div)
	array.set(x, 1, x_1 / div)
	array.set(x, 2, x_2 / div)
	array.set(y, 0, y_0 / div)
	array.set(y, 1, y_1 / div)
	array.set(y, 2, y_2 / div)

	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))
	dft1


// @function DFT2: Discrete Fourier Transform with last 2 points
// @param x Array of input values
// @param y Array of imaginary values
// @param _dir Direction parameter
// @returns  Aproxiated source value
DFT2(x, y, _dir) =>  
    
    

	x_0 = array.get(x, 0) + array.get(x, 1)
	x_1 = array.get(x, 0) + array.get(x, 1) * math.cos( -2 * math.pi * _dir / 2 )- array.get(y, 1) * math.sin( -2 * math.pi * _dir / 2 )

	y_0 = array.get(x, 0) + array.get(x, 1)
	y_1 = array.get(x, 0) + array.get(x, 1) * math.sin( -2 * math.pi * _dir / 2 ) + array.get(y, 1) * math.cos( -2 * math.pi * _dir / 2 )


	div =  _dir == 1 ? 3 : _dir

	array.set(x, 0, x_0 / div)
	array.set(x, 1, x_1 / div)
	array.set(y, 0, y_0 / div)
	array.set(y, 1, y_1 / div)

// @function DFT2: Discrete Fourier Transform with last 2 points
// @param x Array of input values
// @param y Array of imaginary values
// @param _dir Direction parameter
// @returns  Aproxiated source value
export DFT2(series float xval = close , int _dir = 1 ) =>  
    
	x = array.new_float(2, 0.0)
	y = array.new_float(2, 0.0)
	for i = 0 to 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)
    

	x_0 = array.get(x, 0) + array.get(x, 1)  
	x_1 = array.get(x, 0) + array.get(x, 1) * math.cos( -2 * math.pi * _dir / 2 ) - array.get(y, 1) * math.sin( -2 * math.pi * _dir / 2 ) 

	y_0 = array.get(x, 0) + array.get(x, 1) 
	y_1 = array.get(x, 0) + array.get(x, 1) * math.sin( -2 * math.pi * _dir / 2 ) + array.get(y, 1) * math.cos( -2 * math.pi * _dir / 2 ) 


	div =  _dir == 1 ? 3 : _dir

	array.set(x, 0, x_0 / div)
	array.set(x, 1, x_1 / div)
	array.set(y, 0, y_0 / div)
	array.set(y, 1, y_1 / div)

	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))
	dft1


// @function FFT: Fast Fourier Transform once. It aproximates usig last 3 points.
// @param xval Array of input values
// @returns  Aproxiated source value
export FFT(series float xval = close) => 
	N = 3
	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	DFT3(x, y, 1)

	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1

// @function DFT32: Combined Discrete Fourier Transforms of DFT3 and DTF2 it aproximates last point by first 
// aproximating last 3 ponts and than using last 2 points of the previus. 
// @param xval Array of input values
// @returns  Aproxiated source value
export DFT32(series float xval = close ) => 
	N = 3
	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	DFT3(x, y, 2)
	DFT2(x, y, 1)	

	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1



// @function DFT32: Combined Discrete Fourier Transforms of DFT3 and DTF2 it aproximates last point by first 
// aproximating last 3 ponts and than using last 2 points of the previus. 
// @param xval Array of input values
// @returns  Aproxiated source value
export DTF32(series float xval = close) => 
	dft1 = DFT32(xval)
	dft1

//@function LFT3: Discrete Laplace Transform with 3 points
// @param x Array of input values
// @param y Array of imaginary values
// @param _dir Direction parameter
// @returns  Aproxiated source value
LFT3(x, y, _dir, float a=0) =>  
    
    

	x_0 = array.get(x, 0) + array.get(x, 1) * math.exp(a)+ array.get(x, 2) * math.exp(2*a)
	x_1 = array.get(x, 0) + array.get(x, 1) * math.cos( -2 * math.pi * _dir / 3 ) * math.exp(a) - array.get(y, 1) * math.sin( -2 * math.pi * _dir / 3 )* math.exp(a)  + array.get(x, 2) * math.cos( -4 * math.pi * _dir / 3 )* math.exp(2*a) - array.get(y, 2) * math.sin( -4 * math.pi * _dir / 3 )* math.exp(2*a)
	x_2 = array.get(x, 0) + array.get(x, 1) * math.cos( -4 * math.pi * _dir / 3 ) * math.exp(a)- array.get(y, 1) * math.sin( -4 * math.pi * _dir / 3 )* math.exp(a)  + array.get(x, 2) * math.cos( -8 * math.pi * _dir / 3 )* math.exp(2*a) - array.get(y, 2) * math.sin( -8 * math.pi * _dir / 3 )* math.exp(2*a)

	y_0 = array.get(x, 0) + array.get(x, 1) * math.exp(a)+ array.get(x, 2)* math.exp(2*a)
	y_1 = array.get(x, 0) + array.get(x, 1) * math.sin( -2 * math.pi * _dir / 3 )* math.exp(a) + array.get(y, 1) * math.cos( -2 * math.pi * _dir / 3 ) * math.exp(a) + array.get(x, 2) * math.sin( -4 * math.pi * _dir / 3 )* math.exp(2*a) + array.get(y, 2) * math.cos( -4 * math.pi * _dir / 3 )* math.exp(2*a)
	y_2 = array.get(x, 0) + array.get(x, 1) * math.sin( -4 * math.pi * _dir / 3 )* math.exp(a) + array.get(y, 1) * math.cos( -4 * math.pi * _dir / 3 )* math.exp(a)  + array.get(x, 2) * math.sin( -8 * math.pi * _dir / 3 )* math.exp(2*a) + array.get(y, 2) * math.cos( -8 * math.pi * _dir / 3 )* math.exp(2*a)


	div =  _dir == 1 ? 3 : _dir


	array.set(x, 0, x_0 / div)
	array.set(x, 1, x_1 / div)
	array.set(x, 2, x_2 / div)
	array.set(y, 0, y_0 / div)
	array.set(y, 1, y_1 / div)
	array.set(y, 2, y_2 / div)


// @function LFT3: Discrete Laplace Transform with last 3 points
// @param x Array of input values
// @param y Array of imaginary values
// @param _dir Direction parameter
// @returns  Aproxiated source value
export LFT3(series float xval = close , int _dir = 2, float a=0) =>  
    
	x = array.new_float(3, 0.0)
	y = array.new_float(3, 0.0)
	for i = 0 to 2
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)
    

	x_0 = array.get(x, 0) + array.get(x, 1)* math.exp(a) + array.get(x, 2) * math.exp(2*a)
	x_1 = array.get(x, 0) + array.get(x, 1) * math.cos( -2 * math.pi * _dir / 3 ) * math.exp(a)- array.get(y, 1) * math.sin( -2 * math.pi * _dir / 3 ) * math.exp(a) + array.get(x, 2) * math.cos( -4 * math.pi * _dir / 3 )* math.exp(2*a) - array.get(y, 2) * math.sin( -4 * math.pi * _dir / 3 )* math.exp(2*a)
	x_2 = array.get(x, 0) + array.get(x, 1) * math.cos( -4 * math.pi * _dir / 3 ) * math.exp(a)- array.get(y, 1) * math.sin( -4 * math.pi * _dir / 3 ) * math.exp(a) + array.get(x, 2) * math.cos( -8 * math.pi * _dir / 3 ) * math.exp(2*a)- array.get(y, 2) * math.sin( -8 * math.pi * _dir / 3 )* math.exp(2*a)

	y_0 = array.get(x, 0) + array.get(x, 1)* math.exp(a) + array.get(x, 2)* math.exp(2*a)
	y_1 = array.get(x, 0) + array.get(x, 1) * math.sin( -2 * math.pi * _dir / 3 ) * math.exp(a)+ array.get(y, 1) * math.cos( -2 * math.pi * _dir / 3 )  * math.exp(a)+ array.get(x, 2) * math.sin( -4 * math.pi * _dir / 3 ) * math.exp(2*a)+ array.get(y, 2) * math.cos( -4 * math.pi * _dir / 3 )* math.exp(2*a)
	y_2 = array.get(x, 0) + array.get(x, 1) * math.sin( -4 * math.pi * _dir / 3 ) * math.exp(a)+ array.get(y, 1) * math.cos( -4 * math.pi * _dir / 3 )  * math.exp(a)+ array.get(x, 2) * math.sin( -8 * math.pi * _dir / 3 ) * math.exp(2*a)+ array.get(y, 2) * math.cos( -8 * math.pi * _dir / 3 )* math.exp(2*a)


	div =  _dir == 1 ? 3 : _dir


	array.set(x, 0, x_0 / div)
	array.set(x, 1, x_1 / div)
	array.set(x, 2, x_2 / div)
	array.set(y, 0, y_0 / div)
	array.set(y, 1, y_1 / div)
	array.set(y, 2, y_2 / div)

	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))
	dft1


// @function DFT2: Laplace Fourier Transform with last 2 points
// @param x Array of input values
// @param y Array of imaginary values
// @param _dir Direction parameter
// @returns  Aproxiated source value
LFT2(x, y, _dir , a = 0) =>  
    
    

	x_0 = array.get(x, 0) + array.get(x, 1) * math.exp(a)
	x_1 = array.get(x, 0) + array.get(x, 1) * math.cos( -2 * math.pi * _dir / 2 ) * math.exp(a)- array.get(y, 1) * math.sin( -2 * math.pi * _dir / 2 ) * math.exp(a)

	y_0 = array.get(x, 0) + array.get(x, 1) * math.exp(a)
	y_1 = array.get(x, 0) + array.get(x, 1) * math.sin( -2 * math.pi * _dir / 2 ) * math.exp(a) + array.get(y, 1) * math.cos( -2 * math.pi * _dir / 2 ) * math.exp(a)


	div =  _dir == 1 ? 3 : _dir

	array.set(x, 0, x_0 / div)
	array.set(x, 1, x_1 / div)
	array.set(y, 0, y_0 / div)
	array.set(y, 1, y_1 / div)

// @function LFT2: Discrete Laplace Transform with last 2 points
// @param x Array of input values
// @param y Array of imaginary values
// @param _dir Direction parameter
// @returns  Aproxiated source value
export LFT2(series float xval = close , int _dir = 1  ,float a =0) =>  
    
	x = array.new_float(2, 0.0)
	y = array.new_float(2, 0.0)
	for i = 0 to 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)
    

	x_0 = array.get(x, 0) + array.get(x, 1)   * math.exp(a)
	x_1 = array.get(x, 0) + array.get(x, 1) * math.cos( -2 * math.pi * _dir / 2 ) * math.exp(a) - array.get(y, 1) * math.sin( -2 * math.pi * _dir / 2 )  * math.exp(a)

	y_0 = array.get(x, 0) + array.get(x, 1)  * math.exp(a)
	y_1 = array.get(x, 0) + array.get(x, 1) * math.sin( -2 * math.pi * _dir / 2 ) * math.exp(a) + array.get(y, 1) * math.cos( -2 * math.pi * _dir / 2 )  * math.exp(a)


	div =  _dir == 1 ? 3 : _dir

	array.set(x, 0, x_0 / div)
	array.set(x, 1, x_1 / div)
	array.set(y, 0, y_0 / div)
	array.set(y, 1, y_1 / div)

	lft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))
	lft1


// @function FFT: Fast Laplace Transform once. It aproximates usig last 3 points.
// @param xval Array of input values
// @returns  Aproxiated source value
export LFT(series float xval = close, float a = 0) => 
	N = 3
	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	LFT3(x, y, 1, a=a)

	lft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	lft1

// @function LFT32: Combined Discrete Laplace Transforms of LFT3 and LTF2 it aproximates last point by first 
// aproximating last 3 ponts and than using last 2 points of the previus. 
// @param xval Array of input values
// @returns  Aproxiated source value
export LFT32(series float xval = close , float a = 0) => 
	N = 3
	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	LFT3(x, y, 2,a=a)
	LFT2(x, y, 1,a=a)	

	lft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))
	lft1




// @function LFT32: Combined Discrete Laplace Transforms of LFT3 and LTF2 it aproximates last point by first 
// aproximating last 3 ponts and than using last 2 points of the previus. 
// @param xval Array of input values
// @returns  Aproxiated source value
export LTF32(series float xval = close, float a = 0) => 
	dft1 = LFT32(xval,a=a)
	dft1



// @function whitenoise: Ehler's Universal Oscillator with White Noise, without extra aproximated src.
// It uses dinamic EMA to aproximate indicator and thus reducing noise.
// @param indic_ Input series for the indicator values to be smoothed
// @param dft1 Aproximated src value for white noice calculation
// @param _devided Divisor for oscillator calculations
// @param minEmaLength Minimum EMA length
// @param maxEmaLength Maximum EMA length
// @param src Source series
// @returns Smoothed indicator value
export whitenoise(series float indic_ , int _devided = 10, int minEmaLength = 1, int maxEmaLength = 8 , series float src = close ) =>
	var filt = float(na)
	indic = indic_

	w = (src - src[2])  / 2 


	a = math.sqrt(2) * math.pi / _devided
	b = math.cos(math.sqrt(2) * 180 / _devided)
	c2 = 2 *  math.pow(a, 2) * b
	c3 = math.pow(a, 4)
	c1 = 1 - 2 *  math.pow(a, 2) * math.cos(b) + math.pow(a, 4)
	
	
	filt := na(filt[1]) ? 0 : c1 * (w + nz(w[1])) / 2.0  + c2 * nz(filt[1]) - c3 * nz(filt[2])



	// Smoothness (Reduce noise)
	var emaLength = 1 //input(1, "EMA Length", group = "VZO")
	

	
	uniL = filt > 0  
	vzoL = indic_ > indic_[1] 

	// Dynamically adjust EMA length based on conditions
	emaLength := emaLength -1
	if (uniL and vzoL) or (not uniL and not vzoL)
		emaLength := emaLength + 2
		
	
	// Reset EMA length to default if it exceeds the limits
	if emaLength > maxEmaLength or emaLength < minEmaLength
		emaLength := maxEmaLength - 1


	indic := ta.ema2(indic_, emaLength) 
	

	indic


// @function whitenoise: Ehler's Universal Oscillator with White Noise and DFT1.
// It uses src and sproxiated src (dft1) to clearly define white noice.
// It uses dinamic EMA to aproximate indicator and thus reducing noise.
// @param indic_ Input series for the indicator values to be smoothed
// @param dft1 Aproximated src value for white noice calculation
// @param _devided Divisor for oscillator calculations
// @param minEmaLength Minimum EMA length
// @param maxEmaLength Maximum EMA length
// @param src Source series
// @returns Smoothed indicator value
export whitenoise(series float indic_ ,  series float dft1 , int _devided = 10, int minEmaLength = 1, int maxEmaLength = 8 , series float src = close) =>
	w = (dft1*src - dft1[2]*src[2])   / math.sqrt(math.pow(math.abs(src- src[2]),2) + math.pow(math.abs(dft1[0]- dft1[2]),2))
	//w = (close - close[2])  / 2 

	indic = indic_
	var filt = float(na)

	a = math.sqrt(2) * math.pi / _devided
	b = math.cos(math.sqrt(2) * 180 / _devided)
	c2 = 2 *  math.pow(a, 2) * b
	c3 = math.pow(a, 4)
	c1 = 1 - 2 *  math.pow(a, 2) * math.cos(b) + math.pow(a, 4)


	filt := na(filt[1]) ? 0 : c1 * (w*dft1 + nz(w[1]*dft1[1])) / 2.0 /math.abs(dft1[1]-dft1[0]) + c2 * nz(filt[1]) - c3 * nz(filt[2])


	//filt := na(filt[1]) ? 0 : c1 * (w*dft1 + nz(w[1]*dft1[1])) /math.sqrt(
	//     math.pow(math.abs(w- w[1]),2) + math.pow(math.abs(dft1[0]- dft1[1]),2)
	//     ) + c2 * nz(filt[1]) + c3 * nz(filt[2])

	//filt := na(filt[1]) ? 0 : c1 * (w + nz(w[1])) / 2.0  + c2 * nz(filt[1]) + c3 * nz(filt[2])



	// Smoothness (Reduce noise)
	var emaLength = 1 //input(1, "EMA Length", group = "VZO")

	
	uniL = filt > 0  
	vzoL = indic_ > indic_[1] 

	// Dynamically adjust EMA length based on conditions
	emaLength := emaLength -1
	if (uniL and vzoL) or (not uniL and not vzoL)
		emaLength := emaLength + 2

	
	// Reset EMA length to default if it exceeds the limits
	if emaLength > maxEmaLength or emaLength < minEmaLength
		emaLength := maxEmaLength - 1


	indic := ta.ema2(indic_, emaLength) 
	

	indic

// @function smooth: Smoothing source value with help of indicator series and aproximated source value
// It uses src and sproxiated src (dft1) to clearly define white noice.
// It uses dinamic EMA to aproximate src and thus reducing noise.
// @param dft1 Value to be smoothed.
// @param indic__ Optional input for indicator to help smooth dft1 (default is FFT)
// @param _devided Divisor for smoothing calculations
// @param minEmaLength Minimum EMA length
// @param maxEmaLength Maximum EMA length
// @param src Source series
// @returns Smoothed source (src) series 
export smooth(series float dft1 , series float indic__  = na , int _devided = 10, int minEmaLength = 1, int maxEmaLength = 8 , series float src = close) =>
	w = (dft1*src - dft1[2]*src[2])   / math.sqrt(math.pow(math.abs(src- src[2]),2) + math.pow(math.abs(dft1[0]- dft1[2]),2))
	//w = (close - close[2])  / 2 

	indic = src

	var filt = float(na)
	aprox = FFT()
	indic_ = na(indic__) ? aprox : indic__
	a = math.sqrt(2) * math.pi / _devided
	b = math.cos(math.sqrt(2) * 180 / _devided)
	c2 = 2 *  math.pow(a, 2) * b
	c3 = math.pow(a, 4)
	c1 = 1 - 2 *  math.pow(a, 2) * math.cos(b) + math.pow(a, 4)


	filt := na(filt[1]) ? 0 : c1 * (w*dft1 + nz(w[1]*dft1[1])) / 2.0 /math.abs(dft1[1]-dft1[0]) + c2 * nz(filt[1]) - c3 * nz(filt[2])


	//filt := na(filt[1]) ? 0 : c1 * (w*dft1 + nz(w[1]*dft1[1])) /math.sqrt(
	//     math.pow(math.abs(w- w[1]),2) + math.pow(math.abs(dft1[0]- dft1[1]),2)
	//     ) + c2 * nz(filt[1]) + c3 * nz(filt[2])

	//filt := na(filt[1]) ? 0 : c1 * (w + nz(w[1])) / 2.0  + c2 * nz(filt[1]) + c3 * nz(filt[2])



	// Smoothness (Reduce noise)
	var emaLength = 1 //input(1, "EMA Length", group = "VZO")

	
	uniL = filt > 0  
	vzoL = indic_ > indic_[1] 

	// Dynamically adjust EMA length based on conditions
	emaLength := emaLength -1
	if (uniL and vzoL) or (not uniL and not vzoL)
		emaLength := emaLength + 2

	
	// Reset EMA length to default if it exceeds the limits
	if emaLength > maxEmaLength or emaLength < minEmaLength
		emaLength := maxEmaLength - 1


	indic := ta.ema2(src, emaLength) 
	

	indic

// @function smooth: Smoothing source value with help of indicator series 
// It uses dinamic EMA to aproximate src and thus reducing noise.
// @param dft1 Value to be smoothed.
// @param indic__ Optional input for indicator to help smooth dft1 (default is FFT)
// @param _devided Divisor for smoothing calculations
// @param minEmaLength Minimum EMA length
// @param maxEmaLength Maximum EMA length
// @param src Source series
// @returns Smoothed src series 
export smooth(  series float indic__  = na , int _devided = 10, int minEmaLength = 1, int maxEmaLength = 8 , series float src = close) =>
	//w = (dft1*src - dft1[2]*src[2])   / math.sqrt(math.pow(math.abs(src- src[2]),2) + math.pow(math.abs(dft1[0]- dft1[2]),2))
	w = (src - src[2])  / 2 

	indic = src

	var filt = float(na)
	aprox = FFT()
	indic_ = na(indic__) ? aprox : indic__
	a = math.sqrt(2) * math.pi / _devided
	b = math.cos(math.sqrt(2) * 180 / _devided)
	c2 = 2 *  math.pow(a, 2) * b
	c3 = math.pow(a, 4)
	c1 = 1 - 2 *  math.pow(a, 2) * math.cos(b) + math.pow(a, 4)


	//filt := na(filt[1]) ? 0 : c1 * (w*dft1 + nz(w[1]*dft1[1])) / 2.0 /math.abs(dft1[1]-dft1[0]) + c2 * nz(filt[1]) - c3 * nz(filt[2])


	//filt := na(filt[1]) ? 0 : c1 * (w*dft1 + nz(w[1]*dft1[1])) /math.sqrt(
	//     math.pow(math.abs(w- w[1]),2) + math.pow(math.abs(dft1[0]- dft1[1]),2)
	//     ) + c2 * nz(filt[1]) + c3 * nz(filt[2])

	filt := na(filt[1]) ? 0 : c1 * (w + nz(w[1])) / 2.0  + c2 * nz(filt[1]) + c3 * nz(filt[2])



	// Smoothness (Reduce noise)
	var emaLength = 1 //input(1, "EMA Length", group = "VZO")

	
	uniL = filt > 0  
	vzoL = indic_ > indic_[1] 

	// Dynamically adjust EMA length based on conditions
	emaLength := emaLength -1
	if (uniL and vzoL) or (not uniL and not vzoL)
		emaLength := emaLength + 2

	
	// Reset EMA length to default if it exceeds the limits
	if emaLength > maxEmaLength or emaLength < minEmaLength
		emaLength := maxEmaLength - 1


	indic := ta.ema2(src, emaLength) 
	

	indic


// @function vzo_ema: Volume Zone Oscillator with EMA smoothing
// @param src Source series
// @param len Length parameter for EMA
// @returns VZO value
export vzo_ema(series float src, int len) => 
	dvol = math.sign(src - src[2]) * volume //chicken dinner
	dvma = ta.ema(dvol, len) //ema
	vma = ta.ema(volume, len)
	VZO_1 = vma != 0 ? 100 * dvma / vma : 0


// @function vzo_sma Volume Zone Oscillator with SMA smoothing
// @param src Source series
// @param len Length parameter for SMA
// @returns VZO value
export vzo_sma(series float src, int len) => 
	dvol = math.sign(src - src[2]) * volume //chicken dinner
	dvma = ta.sma(dvol, len) //ema
	vma = ta.sma(volume, len)
	VZO_1 = vma != 0 ? 100 * dvma / vma : 0


// @function vzo_wma: Volume Zone Oscillator with WMA smoothing
// @param src Source series
// @param len Length parameter for WMA
// @returns VZO value
export vzo_wma(series float src, int len) => 
	dvol = math.sign(src - src[2]) * volume //chicken dinner
	dvma = ta.wma(dvol, len) //ema
	vma = ta.sma(volume, len)
	VZO_1 = vma != 0 ? 100 * dvma / vma : 0



// @function alma2: Arnaud Legoux Moving Average 2 accepts sigma as series float
// @param series Input series
// @param windowsize Size of the moving average window
// @param offset Offset parameter
// @param sigma Sigma parameter
// @returns ALMA value
export alma2(series float series,int  windowsize, float offset, series float sigma) =>
    m = offset * (windowsize - 1)
    //m = math.floor(offset * (windowsize - 1)) // Used as m when math.floor=true
    s = windowsize / sigma
    norm = 0.0
    sum = 0.0
    for i = 0 to windowsize - 1
        weight = math.exp(-1 * math.pow(i - m, 2) / (2 * math.pow(s, 2)))
        norm := norm + weight
        sum := sum + series[windowsize - i - 1] * weight
    sum / norm
//Wavelet


// @function Wavelet Wavelet Transform: aproxiates srt using Discrete wavelet transform.
// @param len Length parameter for ALMA
// @param src Source series
// @returns Wavelet-transformed series
export Wavelet(series float src = close, int len = 16 , float  offset = 0.77 , float sigma = 6)=>
 	r = src * (1 + ta.alma(ta.change(src)/ src, len, offset, sigma))
	

// @function Wavelet_std: aproxiates srt using Discrete wavelet transform with standard deviation as a magnitude.
// @param len Length parameter for ALMA
// @param offset Offset parameter for ALMA
// @param mag Magnitude parameter for standard deviation
// @param src Source series
// @returns Wavelet-transformed series
export Wavelet_std(series float src = close  , int len = 20, float offset = 0.5, int mag = 2)=>
	std_dev = ta.stdev(src, len ,true)
	sigma_for_alma = std_dev * float(mag)
	alm = alma2(ta.change(src)/ src, len, offset, sigma_for_alma)
	src * (alm + 1)





// @function LFT: Discrete Laplace transform over Nx set of close prices
// @param x close price
// @param y 0 
// @param Nx number of close prices in calculations
// @param _dir Degree rotation on 2d chart
// @param a laplace coeficient
LFT(x, y, Nx, _dir, a) =>  
    float _arg = 0.0
    float _cos = 0.0
    float _sin = 0.0
    float xArr_i = 0.0
    float yArr_i = 0.0
    xArr = array.new_float(array.size(x))
    yArr = array.new_float(array.size(y))

    for i = 0 to Nx - 1 by 1
        xArr_i := 0.0
        yArr_i := 0.0
        kx = float(i) / float(Nx)
        _arg := -_dir * 2 * math.pi * kx
        for k = 0 to Nx - 1 by 1
            _cos := math.cos(k * _arg) * math.exp(k*a)
            _sin := math.sin(k * _arg) * math.exp(k*a)
            xArr_i += array.get(x, k) * _cos - array.get(y, k) * _sin
            yArr_i += array.get(x, k) * _sin + array.get(y, k) * _cos
            yArr_i
        array.set(xArr, i, xArr_i)
        array.set(yArr, i, yArr_i)

    if _dir == 1
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i) / float(Nx))
            array.set(y, i, array.get(yArr, i) / float(Nx))
    else
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i)/ float(_dir))
            array.set(y, i, array.get(yArr, i)/ float(_dir))


// @function LFTSUM: Discrete Laplace transform over Nx set of close prices sum of 2 Laplace exponent components
// @param x close price
// @param y 0 
// @param Nx number of close prices in calculations
// @param _dir Degree rotation on 2d chart
// @param a laplace coeficient
// @param b second laplace coeficient
LFTSUM(x, y, Nx, _dir, a, b) =>  
    float _arg = 0.0
    float _cos = 0.0
    float _sin = 0.0
    float xArr_i = 0.0
    float yArr_i = 0.0
    xArr = array.new_float(array.size(x))
    yArr = array.new_float(array.size(y))

    for i = 0 to Nx - 1 by 1
        xArr_i := 0.0
        yArr_i := 0.0
        kx = float(i) / float(Nx)
        _arg := -_dir * 2 * math.pi * kx
        for k = 0 to Nx - 1 by 1
            _cos := (math.cos(k * _arg) * math.exp(k*a) + math.cos(k * _arg) * math.exp(k*b) )/2
            _sin := (math.sin(k * _arg) * math.exp(k*a) + math.sin(k * _arg) * math.exp(k*b))/2
            xArr_i += array.get(x, k) * _cos - array.get(y, k) * _sin
            yArr_i += array.get(x, k) * _sin + array.get(y, k) * _cos
            yArr_i
        array.set(xArr, i, xArr_i)
        array.set(yArr, i, yArr_i)

    if _dir == 1
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i) / float(Nx))
            array.set(y, i, array.get(yArr, i) / float(Nx))
    else
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i)/ float(_dir))
            array.set(y, i, array.get(yArr, i)/ float(_dir))


// @function LFTdiff: Discrete Laplace transform over Nx set of close prices defference of 2 Laplace exponent components
// @param x close price
// @param y 0 
// @param Nx number of close prices in calculations
// @param _dir Degree rotation on 2d chart
// @param a laplace coeficient
// @param b second laplace coeficient
LFTdiff(x, y, Nx, _dir, a, b) =>  
    float _arg = 0.0
    float _cos = 0.0
    float _sin = 0.0
    float xArr_i = 0.0
    float yArr_i = 0.0
    xArr = array.new_float(array.size(x))
    yArr = array.new_float(array.size(y))

    for i = 0 to Nx - 1 by 1
        xArr_i := 0.0
        yArr_i := 0.0
        kx = float(i) / float(Nx)
        _arg := -_dir * 2 * math.pi * kx
        for k = 0 to Nx - 1 by 1
            _cos := (math.cos(k * _arg) * math.exp(k*a) - math.cos(k * _arg) * math.exp(k*b) )/2
            _sin := (math.sin(k * _arg) * math.exp(k*a) - math.sin(k * _arg) * math.exp(k*b))/2
            xArr_i += array.get(x, k) * _cos - array.get(y, k) * _sin
            yArr_i += array.get(x, k) * _sin + array.get(y, k) * _cos
            yArr_i
        array.set(xArr, i, xArr_i)
        array.set(yArr, i, yArr_i)

    if _dir == 1
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i) / float(Nx))
            array.set(y, i, array.get(yArr, i) / float(Nx))
    else
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i)/ float(_dir))
            array.set(y, i, array.get(yArr, i)/ float(_dir))


// @function LFTdiff: Discrete Laplace transform over Nx set of close prices defference of 2 Laplace exponent components, second component exponent higher for 1
// @param x close price
// @param y 0 
// @param Nx number of close prices in calculations
// @param _dir Degree rotation on 2d chart
// @param a laplace coeficient
// @param b second laplace coeficient
LFTdiffFrom2(x, y, Nx, _dir, a, b) =>  
    float _arg = 0.0
    float _cos = 0.0
    float _sin = 0.0
    float xArr_i = 0.0
    float yArr_i = 0.0
    xArr = array.new_float(array.size(x))
    yArr = array.new_float(array.size(y))

    for i = 0 to Nx - 1 by 1
        xArr_i := 0.0
        yArr_i := 0.0
        kx = float(i) / float(Nx)
        _arg := -_dir * 2 * math.pi * kx
        for k = 0 to Nx - 1 by 1
            _cos := (math.cos(k * _arg) * math.exp(k*a) - math.cos(k * _arg) * math.exp(k*b + b) )/2
            _sin := (math.sin(k * _arg) * math.exp(k*a) - math.sin(k * _arg) * math.exp(k*b + b))/2
            xArr_i += array.get(x, k) * _cos - array.get(y, k) * _sin
            yArr_i += array.get(x, k) * _sin + array.get(y, k) * _cos
            yArr_i
        array.set(xArr, i, xArr_i)
        array.set(yArr, i, yArr_i)

    if _dir == 1
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i) / float(Nx))
            array.set(y, i, array.get(yArr, i) / float(Nx))
    else
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i)/ float(_dir))
            array.set(y, i, array.get(yArr, i)/ float(_dir))


// @function LaplaceTransform: Original Laplace Transform over N set of close prices
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
export LaplaceTransform(series float xval = close , int N = 3, float a = 0) => 

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	LFT(x, y,N, 1,a=a)


	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1

// @function LaplaceTransform: Y repetirions on Original Laplace Transform over N set of close prices, each time N-k set of close prices
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param repeat number of repetitions
export NLaplaceTransform(series float xval = close , int N = 3, float a = 0, int repeat = 1) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	for i = 1 to repeat
		LFT(x, y,N-i+1, 1,a=a)


	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1

// @function LaplaceTransform: Sum of 2 exponent coeficient of Laplace Transform over N set of close prices
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
export LaplaceTransformsum(series float xval = close , int N = 3, float a = 0,float b = 0) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	
	LFTSUM(x, y,N, 1,a=a,b=b)


	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1

// @function LaplaceTransform: Difference of 2 exponent coeficient of Laplace Transform over N set of close prices
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
export NLaplaceTransformdiff(series float xval = close , int N = 3, float a = 0,float b = 0, int repeat = 1) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	for i = 1 to repeat
		LFTdiff(x, y,N-i+1, 1,a=a,b=b)


	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1


// @function LaplaceTransform: N repetitions of Difference of 2 exponent coeficient of Laplace Transform over N set of close prices, with dynamic rotation
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
// @param repeat number of repetitions
export N_divLaplaceTransformdiff(series float xval = close , int N = 3, float a = 0,float b = 0, int repeat = 1) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	
	for i = 1 to repeat
		LFTdiff(x, y,N-i+1, repeat-i+1,a=a,b=b)


	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1

// @function LaplaceTransform: Difference of 2 exponent coeficient of Laplace Transform over N set of close prices
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
// @param repeat number of repetitions
export LaplaceTransformdiff(series float xval = close , int N = 3, float a = 0,float b = 0) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	
	LFTdiff(x, y,N, 1,a=a,b=b)


	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1


// @function LaplaceTransform: N repetitions of Difference of 2 exponent coeficient of Laplace Transform over N set of close prices, second element has for 1 higher exponent factor
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
// @param repeat number of repetitions
export NLaplaceTransformdiffFrom2(series float xval = close , int N = 3, float a = 0,float b = 0, int repeat = 1) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	for i = 1 to repeat
		LFTdiffFrom2(x, y,N-i+1, 1,a=a,b=b)


	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1

// @function LaplaceTransform: N repetitions of Difference of 2 exponent coeficient of Laplace Transform over N set of close prices, second element has for 1 higher exponent factor, dynamic rotation
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
// @param repeat number of repetitions
export N_divLaplaceTransformdiffFrom2(series float xval = close , int N = 3, float a = 0,float b = 0, int repeat = 1) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	
	for i = 1 to repeat
		LFTdiffFrom2(x, y,N-i+1, repeat-i+1,a=a,b=b)


	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1

// @function LaplaceTransform: Difference of 2 exponent coeficient of Laplace Transform over N set of close prices, second element has for 1 higher exponent factor
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
// @param repeat number of repetitions
export LaplaceTransformdiffFrom2(series float xval = close , int N = 3, float a = 0,float b = 0) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	
	LFTdiffFrom2(x, y,N, 1,a=a,b=b)


	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1


LFTv1(x, y, Nx, _dir,a, b,f,g) =>  
    float _arg = 0.0
    float _cos = 0.0
    float _sin = 0.0
    float xArr_i = 0.0
    float yArr_i = 0.0
    xArr = array.new_float(array.size(x))
    yArr = array.new_float(array.size(y))

    for i = 0 to Nx - 1 by 1
        xArr_i := 0.0
        yArr_i := 0.0
        kx = float(i) / float(Nx)
        _arg := -_dir * 2 * math.pi * kx
        for k = 0 to Nx - 1 by 1
            _cos := (math.cos(k * _arg) *( f*math.exp(k*a) + g*math.exp(k*b))) 
            _sin := (math.sin(k * _arg) *(f* math.exp(k*a) + g*math.exp(k*b)))
            xArr_i += array.get(x, k) * _cos - array.get(y, k) * _sin
            yArr_i += array.get(x, k) * _sin + array.get(y, k) * _cos
            yArr_i
        array.set(xArr, i, xArr_i)
        array.set(yArr, i, yArr_i)

    if _dir == 1
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i) / float(Nx))
            array.set(y, i, array.get(yArr, i) / float(Nx))
    else
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i)/ float(_dir))
            array.set(y, i, array.get(yArr, i)/ float(_dir))

LFTv2(x, y, Nx, _dir,a, b,f,g) =>  
    float _arg = 0.0
    float _cos = 0.0
    float _sin = 0.0
    float xArr_i = 0.0
    float yArr_i = 0.0
    xArr = array.new_float(array.size(x))
    yArr = array.new_float(array.size(y))

    for i = 0 to Nx - 1 by 1
        xArr_i := 0.0
        yArr_i := 0.0
        kx = float(i) / float(Nx)
        _arg := -_dir * 2 * math.pi * kx
        for k = 0 to Nx - 1 by 1
            _cos := (math.cos(k * _arg) * (math.exp((f+k)*a/2) + math.exp((g+k)*b/2  ))) 
            _sin := (math.sin(k * _arg) * (math.exp((f+k)*a/2) + math.exp((g+k)*b/2  )))
            xArr_i += array.get(x, k) * _cos - array.get(y, k) * _sin
            yArr_i += array.get(x, k) * _sin + array.get(y, k) * _cos
            yArr_i
        array.set(xArr, i, xArr_i)
        array.set(yArr, i, yArr_i)

    if _dir == 1
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i) / float(Nx))
            array.set(y, i, array.get(yArr, i) / float(Nx))
    else
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i)/ float(_dir))
            array.set(y, i, array.get(yArr, i)/ float(_dir))


// @function calculateParameter: aproximates parrameters for a * e^k + b * e^k
// @param src series price Source 
// @param xval n
export calculateParameters(series float src = close,int n) =>
    sum_x = 0.0
    sum_y = 0.0
    sum_xy = 0.0
    sum_x2 = 0.0

    for i = 0 to n - 1
        x = i
        y = src[i]
        sum_x := sum_x + x
        sum_y := sum_y + math.log(y)
        sum_xy := sum_xy + x * math.log(y)
        sum_x2 := sum_x2 + x * x

    
    delta = n * sum_x2 - sum_x * sum_x
    a = (n * sum_xy - sum_x * sum_y) / delta
    b = (sum_y * sum_x2 - sum_x * sum_xy) / delta
    k = a
    l = b

    [a, k, b, l]


// @function LaplaceTransformv1: My version 1 of laplace transform with 4 parrameters
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
// @param c laplace multyply
// @param d second laplace multiply
// @param repeat number of repetitions
// @returns  Aproxiated source value
export LaplaceTransformv1(series float xval = close , int N = 3, float a = 0,float b = 0,float c = 0,float d = 0, int repeat = 1) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	
	for i = 1 to repeat
		LFTv1(x, y,N-i+1, repeat-i+1,a=a,b=b,f=c,g=d )



	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1



LFTv4(x, y, Nx, _dir,a, b,f,g) =>  
    float _arg = 0.0
    float _cos = 0.0
    float _sin = 0.0
    float xArr_i = 0.0
    float yArr_i = 0.0
    xArr = array.new_float(array.size(x))
    yArr = array.new_float(array.size(y))

    for i = 0 to Nx - 1 by 1
        xArr_i := 0.0
        yArr_i := 0.0
        kx = float(i) / float(Nx)
        _arg := -_dir * 2 * math.pi * kx
        for k = 0 to Nx - 1 by 1
            _cos := (math.cos(k * _arg) * (math.exp((f+a)*k/2) - math.exp((g+b)*k/2  )/((b-a)))) 
            _sin := (math.sin(k * _arg) * (math.exp((f+a)*k/2) - math.exp((g+b)*k/2  )/((b-a))))
            xArr_i += array.get(x, k) * _cos - array.get(y, k) * _sin
            yArr_i += array.get(x, k) * _sin + array.get(y, k) * _cos
            yArr_i
        array.set(xArr, i, xArr_i)
        array.set(yArr, i, yArr_i)

    if _dir == 1
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i) / float(Nx))
            array.set(y, i, array.get(yArr, i) / float(Nx))
    else
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i)/ float(_dir))
            array.set(y, i, array.get(yArr, i)/ float(_dir))


LFTv3(x, y, Nx, _dir,a, b,f,g) =>  
    float _arg = 0.0
    float _cos = 0.0
    float _sin = 0.0
    float xArr_i = 0.0
    float yArr_i = 0.0
    xArr = array.new_float(array.size(x))
    yArr = array.new_float(array.size(y))

    for i = 0 to Nx - 1 by 1
        xArr_i := 0.0
        yArr_i := 0.0
        kx = float(i) / float(Nx)
        _arg := -_dir * 2 * math.pi * kx
        for k = 0 to Nx - 1 by 1
            _cos := (math.cos(k * _arg) * (math.exp((f+k)*a/2) - math.exp((g+k)*b/2  )/((b-a)))) 
            _sin := (math.sin(k * _arg) * (math.exp((f+k)*a/2) - math.exp((g+k)*b/2  )/((b-a))))
            xArr_i += array.get(x, k) * _cos - array.get(y, k) * _sin
            yArr_i += array.get(x, k) * _sin + array.get(y, k) * _cos
            yArr_i
        array.set(xArr, i, xArr_i)
        array.set(yArr, i, yArr_i)

    if _dir == 1
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i) / float(Nx))
            array.set(y, i, array.get(yArr, i) / float(Nx))
    else
        for i = 0 to Nx - 1 by 1
            array.set(x, i, array.get(xArr, i)/ float(_dir))
            array.set(y, i, array.get(yArr, i)/ float(_dir))


// @function LaplaceTransformv1: My version 1 of laplace transform with 4 parrameters
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
// @param c laplace multyply
// @param d second laplace multiply
// @param repeat number of repetitions
// @returns  Aproxiated source value
export LaplaceTransformv2(series float xval = close , int N = 3, float a = 0,float b = 0,float c = 0,float d = 0, int repeat = 1) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	
	for i = 1 to repeat
		LFTv2(x, y,N-i+1, repeat-i+1,a=a,b=b,f=c,g=d )



	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1

// @function LaplaceTransformv3: My version 3 of laplace transform with 4 parrameters
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
// @param c laplace multyply
// @param d second laplace multiply
// @param repeat number of repetitions
// @returns  Aproxiated source value
export LaplaceTransformv3(series float xval = close , int N = 3, float a = 0,float b = 0,float c = 0,float d = 0, int repeat = 1) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	
	for i = 1 to repeat
		LFTv3(x, y,N-i+1, repeat-i+1,a=a,b=b,f=c,g=d )



	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1


// @function LaplaceStieltjesTransform: Laplace Stieltjes Transform with 4 parrameters
// @param xval series to aproximate
// @param N number of close prices in calculations
// @param a laplace coeficient
// @param b second laplace coeficient
// @param c laplace multyply
// @param d second laplace multiply
// @param repeat number of repetitions
// @returns  Aproxiated source value
export LaplaceStieltjesTransform(series float xval = close , int N = 3, float a = 0,float b = 0,float c = 0,float d = 0, int repeat = 1) => 

	

	x = array.new_float(N, 0.0)
	y = array.new_float(N, 0.0)
	for i = 0 to N - 1
		array.set(x, i, xval[i])
		array.set(y, i, 0.0)

	
	for i = 1 to repeat
		LFTv4(x, y,N-i+1, repeat-i+1,a=a,b=b,f=c,g=d )



	dft1 = math.sqrt(math.pow(array.get(x, 0), 2) + math.pow(array.get(y, 0), 2))

	dft1

