// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © Trendoscope Pty Ltd
//                                       ░▒             
//                                  ▒▒▒   ▒▒      
//                              ▒▒▒▒▒     ▒▒      
//                      ▒▒▒▒▒▒▒░     ▒     ▒▒          
//                  ▒▒▒▒▒▒           ▒     ▒▒          
//             ▓▒▒▒       ▒        ▒▒▒▒▒▒▒▒▒▒▒  
//   ▒▒▒▒▒▒▒▒▒▒▒ ▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒         
//   ▒  ▒       ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░        
//   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒         
//   ▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒                       
//    ▒▒▒▒▒         ▒▒▒▒▒▒▒                            
//                 ▒▒▒▒▒▒▒▒▒                           
//                ▒▒▒▒▒ ▒▒▒▒▒                          
//               ░▒▒▒▒   ▒▒▒▒▓      ████████╗██████╗ ███████╗███╗   ██╗██████╗  ██████╗ ███████╗ ██████╗ ██████╗ ██████╗ ███████╗
//              ▓▒▒▒▒     ▒▒▒▒      ╚══██╔══╝██╔══██╗██╔════╝████╗  ██║██╔══██╗██╔═══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
//              ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒        ██║   ██████╔╝█████╗  ██╔██╗ ██║██║  ██║██║   ██║███████╗██║     ██║   ██║██████╔╝█████╗ 
//             ▒▒▒▒▒       ▒▒▒▒▒       ██║   ██╔══██╗██╔══╝  ██║╚██╗██║██║  ██║██║   ██║╚════██║██║     ██║   ██║██╔═══╝ ██╔══╝  
//            ▒▒▒▒▒         ▒▒▒▒▒      ██║   ██║  ██║███████╗██║ ╚████║██████╔╝╚██████╔╝███████║╚██████╗╚██████╔╝██║     ███████╗
//             ▒▒             ▒                        
//@version=6

// @description Library with Simple Trade types and tracking mechanism
library('simpletrade', overlay = true)

// @type Object containing Trade drawings
// @field entryToStop box showing entry to stop range
// @field entryToTarget box showing entry to target range
// @field maxGain box highlighting max gain of the Trade
// @field maxLoss box highlighting max lowss of the Trade
// @field invalidationLine line displaying trade invalidation price
// @field invalidationLabel label displaying trade invalidation price
// @field stopLabel label displaying trade stop price
// @field entryLabel label displaying trade entry price
// @field targetLabel label displaying trade target price
// @field patternLabel label displaying trade pattern details
export type TradeDrawing
	box entryToStop
	box entryToTarget
	box maxGain
	box maxLoss
	line invalidationLine
	label invalidationLabel
	label stopLabel
	label entryLabel
	label targetLabel
	label patternLabel

// @type Object containing Simple trade details for tracking
// @field id Unique trade id
// @field pid parent id for trade. Multiple trades can have single parent id
// @field dir trade direction
// @field tradeName Trade name or description
// @field tradeColor color in which the trade needs to be drawn
// @field entry trade entry price
// @field stop trade stop price
// @field invalidation trade invalidation price
// @field target trade target price
// @field maxGainPrice price at which the trade attained max gain
// @field maxLossPrice price at which the trade attained max loss
// @field drawing TradeDrawing object contianing drawing items
// @field status current status of the trade
// @field maxStatus max status attained by the trade
export type SimpleTrade
	int id
	int pid
	int dir
	string tradeName
	color tradeColor
	float entry
	float stop
	float invalidation
	float target
	float maxGainPrice
	float maxLossPrice
	TradeDrawing drawing
	int status = 0
	int maxStatus = 0

// @function Evaluate current trade and update status
// @param this SimpleTrade object that need to be evaluated
// @returns current SimpleTrade object
export method evaluate(SimpleTrade this) =>
    if this.status != -1
        stopPrice = this.dir > 0 ? low : high
        targetPrice = this.dir > 0 ? high : low
        this.status := (this.maxStatus >= 1 ? this.stop : this.invalidation) * this.dir >= stopPrice * this.dir ? -1 : targetPrice * this.dir >= this.target * this.dir ? 2 : targetPrice * this.dir >= this.entry * this.dir ? 1 : 0
        this.maxGainPrice := this.dir > 0 ? math.max(this.maxGainPrice, targetPrice) : math.min(this.maxGainPrice, targetPrice)
        this.maxLossPrice := this.maxStatus > 0 ? this.dir > 0 ? math.min(this.maxLossPrice, stopPrice) : math.max(this.maxLossPrice, stopPrice) : this.maxLossPrice
        this.maxStatus := math.max(this.status, this.maxStatus)
        if this.maxStatus == 2
            this.status := -1
            this.status
    this

method erase(TradeDrawing this) =>
    if not na(this)
        this.entryToStop.delete()
        this.entryToTarget.delete()
        this.maxGain.delete()
        this.maxLoss.delete()
        this.invalidationLine.delete()
        this.invalidationLabel.delete()
        this.stopLabel.delete()
        this.entryLabel.delete()
        this.targetLabel.delete()
        this.patternLabel.delete()

// @function Erase SimpleTrade drawings
// @param this SimpleTrade object that needs to be erased
// @returns void
export method erase(SimpleTrade this) =>
    this.drawing.erase()

// @function Draw SimpleTrade drawings
// @param this SimpleTrade object that needs to be drawn
// @param offset offset distance at which the drawing needs to be drawn.
// @param gap gap between start and end of the Simple trade drawings
// @returns updated offset
export method draw(SimpleTrade this, int offset, int gap = 40) =>
    leftbar = bar_index + offset
    rightbar = bar_index + offset + gap

    dimmedColor = color.new(this.tradeColor, 50)
    stopLabelStyle = this.dir > 0 ? label.style_label_up : label.style_label_down
    targetLabelStyle = this.dir > 0 ? label.style_label_down : label.style_label_up
    this.drawing.entryToStop := box.new(chart.point.from_index(leftbar, this.entry), chart.point.from_index(rightbar, this.stop), this.tradeColor, 1, line.style_solid, bgcolor = color.new(color.red, 95))
    this.drawing.entryToTarget := box.new(chart.point.from_index(leftbar, this.entry), chart.point.from_index(rightbar, this.target), this.tradeColor, 1, line.style_solid, bgcolor = color.new(color.green, 95))
    transparentColor = color.new(color.red, 100)
    if this.maxStatus == 0
        this.drawing.invalidationLine := line.new(chart.point.from_index(leftbar, this.invalidation), chart.point.from_index(rightbar, this.invalidation), color = this.tradeColor, width = 2, style = line.style_solid)
        this.drawing.invalidationLabel := label.new(chart.point.from_index((leftbar + rightbar) / 2, this.invalidation), str.tostring(this.invalidation, format.mintick), textcolor = this.tradeColor, size = size.normal, textalign = text.align_center, style = stopLabelStyle, color = transparentColor, tooltip = 'Invalidation Price : ' + str.tostring(this.invalidation, format.mintick))
        this.drawing.stopLabel := label.new(chart.point.from_index((leftbar + rightbar) / 2, this.stop), str.tostring(this.stop, format.mintick), textcolor = dimmedColor, size = size.small, textalign = text.align_center, style = stopLabelStyle, color = transparentColor, tooltip = 'Stop Price : ' + str.tostring(this.stop, format.mintick))
        this.drawing.entryLabel := label.new(chart.point.from_index((leftbar + rightbar) / 2, this.entry), str.tostring(this.entry, format.mintick), textcolor = dimmedColor, size = size.small, textalign = text.align_center, style = targetLabelStyle, color = transparentColor, tooltip = 'Entry Price : ' + str.tostring(this.entry, format.mintick))
        this.drawing.targetLabel := label.new(chart.point.from_index((leftbar + rightbar) / 2, this.target), str.tostring(this.target, format.mintick), textcolor = dimmedColor, size = size.small, textalign = text.align_center, style = targetLabelStyle, color = transparentColor, tooltip = 'Target Price : ' + str.tostring(this.target, format.mintick))
        this.drawing.targetLabel
    else
        this.drawing.maxGain := box.new(chart.point.from_index(leftbar, this.entry), chart.point.from_index(rightbar, this.maxGainPrice), color(na), 0, line.style_dotted, bgcolor = color.new(color.green, 80))
        this.drawing.maxLoss := box.new(chart.point.from_index(leftbar, this.entry), chart.point.from_index(rightbar, this.maxLossPrice), color(na), bgcolor = color.new(color.red, 80))
        this.drawing.invalidationLine := line.new(chart.point.from_index(leftbar, this.invalidation), chart.point.from_index(rightbar, this.invalidation), color = this.tradeColor, width = 1, style = line.style_dotted)
        this.drawing.invalidationLabel := label.new(chart.point.from_index((leftbar + rightbar) / 2, this.invalidation), str.tostring(this.invalidation, format.mintick), textcolor = dimmedColor, size = size.small, textalign = text.align_center, style = stopLabelStyle, color = transparentColor, tooltip = 'Invalidation Price : ' + str.tostring(this.invalidation, format.mintick))
        this.drawing.stopLabel := label.new(chart.point.from_index((leftbar + rightbar) / 2, this.stop), str.tostring(this.stop, format.mintick), textcolor = this.tradeColor, size = size.normal, textalign = text.align_center, style = stopLabelStyle, color = transparentColor, tooltip = 'Stop Price : ' + str.tostring(this.stop, format.mintick))
        this.drawing.entryLabel := label.new(chart.point.from_index((leftbar + rightbar) / 2, this.entry), str.tostring(this.entry, format.mintick), textcolor = this.tradeColor, size = size.normal, textalign = text.align_center, style = targetLabelStyle, color = transparentColor, tooltip = 'Entry Price : ' + str.tostring(this.entry, format.mintick))
        this.drawing.targetLabel := label.new(chart.point.from_index((leftbar + rightbar) / 2, this.target), str.tostring(this.target, format.mintick), textcolor = this.tradeColor, size = size.normal, textalign = text.align_center, style = targetLabelStyle, color = transparentColor, tooltip = 'Target Price : ' + str.tostring(this.target, format.mintick))
        this.drawing.targetLabel

    patternLabel = str.tostring(this.pid) + ' : ' + this.tradeName + '\n' + str.tostring(this.id) + ' : ' + (this.dir > 0 ? 'Long' : 'Short') + ' (' + (this.status == 0 ? 'Awaiting Entry' : 'In Trade') + ')'
    this.drawing.patternLabel := label.new(chart.point.from_index((leftbar + rightbar) / 2, this.entry), patternLabel, textcolor = this.tradeColor, size = size.normal, textalign = text.align_center, style = stopLabelStyle, color = transparentColor, tooltip = 'Pattern Id : Pattern Type\nTrade Id : Direction (Status)')
    offset + gap
