// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © mikelivs32

//@version=5

// @description TODO: add library description here
library("mlivs")

// @function param adxlen default 14 
// param dilen default 14
// @param adxlen default 14 
// @param dilen default 14
// @returns TODO: add what function returns
export adx(float highVar, float lowVar, int adxlen, int dilen) =>
//	adxlen = 14 //input(14, title="ADX Smoothing")
//	dilen = 14//input(14, title="DI Length")
	up = ta.change(highVar)
	down = -ta.change(lowVar)
	plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
	minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
	truerange = ta.rma(ta.tr, dilen)
	plus = fixnan(100 * ta.rma(plusDM, dilen) / truerange)
	minus = fixnan(100 * ta.rma(minusDM, dilen) / truerange)
	//[plus, minus]	

	sum = plus + minus
	adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), adxlen)

export adxMA(int length)=>
	adxMA = ta.ema(adx(high, low, 14, 14), length)

//TODO return boolean. adx MA is > 20 and positive slope 

// SMMA Calculation
calc_smma(src, len) =>
    var float smma = na
    smma := na(smma[1]) ? ta.sma(src, len) : (smma[1] * (len - 1) + src) / len
    smma

// ZLEMA Calculation
calc_zlema(src, length) =>
    ema1 = ta.ema(src, length)
    ema2 = ta.ema(ema1, length)
    d = ema1 - ema2
    ema1 + d

//@param lengthMA default 34
//@param lengthSignal default 9
export impulseMACD(float srcHlc3, float srcHigh, float srcLow) =>
	
	lengthMA = 34
	lengthSignal = 9
	// Source and calculated values
	src = srcHlc3

	hi = calc_smma(srcHigh, lengthMA)
	lo = calc_smma(srcLow, lengthMA)
	mi = calc_zlema(src, lengthMA) 

	md = (mi > hi) ? (mi - hi) : (mi < lo) ? (mi - lo) : 0
	sb = ta.sma(md, lengthSignal)
	sh = md - sb
	[md, sb, sh]
	//mdc = src > mi ? (src > hi ? color.lime : color.green) : (src < lo ? color.red : color.orange)

//factorial calc
fact(int n)=>
    float a = 1
    for i = 1 to n 
        a *= i
    a

//alpha calc
_alpha(int period, int poles)=>
    w = 2.0 * math.pi / period
    float b = (1.0 - math.cos(w)) / (math.pow(1.414, 2.0 / poles) - 1.0)
    float a = - b + math.sqrt(b * b + 2.0 * b)
    a
    
//n-pole calc
_makeCoeffs(simple int period, simple int order)=>
    coeffs = matrix.new<float>(order + 1, 3, 0.)
    float a = _alpha(period, order)
    for r = 0 to order 
        out = nz(fact(order) / (fact(order - r) * fact(r)), 1)
        matrix.set(coeffs, r, 0, out)
        matrix.set(coeffs, r, 1, math.pow(a, r))
        matrix.set(coeffs, r, 2, math.pow(1.0 - a, r))
    coeffs
    
//n-pole calc
_npolegf(float src, simple int period, simple int order)=>
    var coeffs = _makeCoeffs(period, order)
    float filt = src * matrix.get(coeffs, order, 1)
    int sign = 1
    for r = 1 to order 
        filt += sign * matrix.get(coeffs, r, 0) * matrix.get(coeffs, r, 2) * nz(filt[r])
        sign *= -1
    filt

//std filter
_filt(float src, int len, float filter)=>
    float price = src
    float filtdev = filter * ta.stdev(src, len)
    price := math.abs(price - nz(price[1])) < filtdev ? nz(price[1]) : price
    price	


export stdFilter(int period, int order, float closeVar, int filterDeviation, int filterPeriod) =>
	//smthtype = //input.string("Kaufman", "Heiken-Ashi Better Smoothing", options = ["AMA", "T3", "Kaufman"], group=  "Source Settings")
	src =  closeVar

	//period = input.int(25,'Period', group = "Basic Settings")
	//order = input.int(5,'Order', group = "Basic Settings", minval = 1)

	filterop = "Gaussian Filter" //input.string("Gaussian Filter", "Filter Options", options = ["Price", "Gaussian Filter", "Both", "None"], group=  "Filter Settings")
	filter = filterDeviation // input.float(1, "Filter Devaitions", minval = 0, group= "Filter Settings")
	filterperiod = filterPeriod // input.int(10, "Filter Period", minval = 0, group= "Filter Settings")
	src := filterop == "Both" or filterop == "Price" and filter > 0 ? _filt(src, filterperiod, filter) : src
	out = _npolegf(src, period, order)
	out := filterop == "Both" or filterop == "Gaussian Filter" and filter > 0 ? _filt(out, filterperiod, filter) : out
	out


export stdFilterDirection(float out) =>
	sig = nz(out[1])
	state = 0
	if (out > sig) 
		state := 1
	if (out < sig) 
		state := -1
	bool colorBarsBool = na
	colorBarsBool := state == -1 ? false : state == 1 ? true : nz(colorBarsBool[1])
	colorBarsBool //return 

//TODO return direction (combine above)
//see if chart color can be returned 
returnColer() =>
	color.aqua

// @function superTrend
// @param Periods default 10 
// @param varhl2 default hl2
// @param Multiplier default 3
// @param closeVar default close

// @returns TODO: add what function returns
export superTrend(int Periods, float varhl2, float Multiplier, float closeVar) =>
    atr2 = ta.sma(ta.tr, Periods)
    atr =  ta.atr(Periods) 
    
    up = varhl2 - (Multiplier * atr)
    up1 = na(up[1]) ? up : up[1]
    up := closeVar[1] > up1 ? math.max(up, up1) : up

    dn = varhl2 + (Multiplier * atr)
    dn1 = na(dn[1]) ? dn : dn[1]
    dn := closeVar[1] < dn1 ? math.min(dn, dn1) : dn

    trend = 1
    trend := na(trend[1]) ? trend : trend[1]
    trend := trend == -1 and closeVar > dn1 ? 1 : trend == 1 and closeVar < up1 ? -1 : trend

    //upPlot = plot(trend == 1 ? up : na, title="Up Trend", style=plot.style_line, linewidth=2, color=color.green)
    buySignal = trend == 1 and trend[1] == -1
    //plotshape(buySignal ? up : na, title="UpTrend Begins", location=location.absolute, style=shape.circle, size=size.tiny, color=color.green, transp=0)
    //plotshape(buySignal and showsignals ? up : na, title="Buy", text="Buy", location=location.absolute, style=shape.labelup, size=size.tiny, color=color.green, textcolor=color.white, transp=0)

    //dnPlot = plot(trend == 1 ? na : dn, title="Down Trend", style=plot.style_line, linewidth=2, color=color.red)
    sellSignal = trend == -1 and trend[1] == 1
    //plotshape(sellSignal and showsignadls ? dn : na, title="Sell", text="Sell", location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.red, textcolor=color.white, transp=0)

    [up, dn, buySignal, sellSignal]