//@version=6
indicator("Earnings Analysis", overlay=true)

//-----------------------------------------------------
// Earnings
//-----------------------------------------------------
earn = request.earnings(syminfo.tickerid, earnings.actual, gaps=barmerge.gaps_on)

isEarnings = not na(earn)

//-----------------------------------------------------
// Store latest earnings label
//-----------------------------------------------------
var label earningsLabel = na

//-----------------------------------------------------
// Create label on earnings day
//-----------------------------------------------------
if isEarnings

    // -6 to -2
    pre5 = (close[2] - close[7]) / close[7] * 100

    // -1
    pre1 = (close[1] - close[2]) / close[2] * 100

    // Earnings Day
    day0 = (close - close[1]) / close[1] * 100

    earningsLabel := label.new(
         bar_index,
         high + ta.atr(14) * 1.5,
         "5D Pre : " + str.tostring(pre5, "#.##") + "%" +
         "\n1D Pre : " + str.tostring(pre1, "#.##") + "%" +
         "\n----------------" +
         "\nDay 0  : " + str.tostring(day0, "#.##") + "%" +
         "\n----------------" +
         "\n1D Post : Waiting..." +
         "\n5D Post : Waiting...",
         style = label.style_label_down,
         color = color.red,
         textcolor = color.white)

//-----------------------------------------------------
// Update after +6 trading days
//-----------------------------------------------------
if not na(earn[6])

    // +1
    post1 = (close[5] - close[6]) / close[6] * 100

    // +2 to +6
    post5 = (close - close[4]) / close[4] * 100

    label.set_text(
         earningsLabel,
         "5D Pre : " + str.tostring((close[8] - close[13]) / close[13] * 100, "#.##") + "%" +
         "\n1D Pre : " + str.tostring((close[7] - close[8]) / close[8] * 100, "#.##") + "%" +
         "\n----------------" +
         "\nDay 0  : " + str.tostring((close[6] - close[7]) / close[7] * 100, "#.##") + "%" +
         "\n----------------" +
         "\n1D Post : " + str.tostring(post1, "#.##") + "%" +
         "\n5D Post : " + str.tostring(post5, "#.##") + "%")