//=============================================================================
// COT Comm Osci
//
// Author:         GondaTom
// Date:           2025-07-25
// Pine Version:   v6
// Version:        1.01
// 
// Description
//                 This script displays a sentiment oscillator based on net positions of 
//                 Commercials, Noncommercials, or Nonreportables from the weekly COT report.
//
//                 The net positions are scaled into an index ranging from 0 to 100, making 
//                 it easier to spot positioning extremes in historical context.
//                 The user can define three time intervals (e.g. 125, 250, 500 weeks) for scaling.
//
//                 Meaning of the scale:
//                     - A value of 100 indicates that the current net position is the highest within 
//                       the selected time period.
//                     - A value of 0 indicates the lowest net position during that period. 
//
//                 New Features:
//                     - Select between Commercial, Noncommercial, or Nonreportable trader groups
//                     - Proper handling of HG Futures (Copper)
//                     - Error handling for invalid root codes (e.g., unsupported markets)
//
// Credit:         This Script is Based on the "Commercial Index-Buschi" script by MogicEins, extended and improved.
//
// License:        This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © TradingView
//=============================================================================


//@version=6
indicator("COT Comm Osci", "COT Osci",  precision=0, overlay=false)

import TradingView/LibraryCOT/4


// Eingabe-Parameter
metric = input.string(title="Positions", defval="Commercial Positions", options=["Commercial Positions", "Noncommercial Positions", "Nonreportable Positions"])
interval1 = input.int(125, title="Time Interval 1 (weeks)", minval=1)
interval2 = input.int(250, title="time Interval 2 (weeks)", minval=1)
interval3 = input.int(500, title="time Interval 3 (weeks)", minval=1) 


float COTdataseries_Long = LibraryCOT.requestCommitmentOfTraders(
     COTType         = "Legacy",
     CFTCCode        = LibraryCOT.convertRootToCOTCode("Auto"),
     includeOptions  = false, 
     metricName      = metric,
     metricDirection = "Long",
     metricType      = "All"
 )


float COTdataseries_Short = LibraryCOT.requestCommitmentOfTraders(
     COTType         = "Legacy",
     CFTCCode        = LibraryCOT.convertRootToCOTCode("Auto"),
     includeOptions  = false, 
     metricName      = metric,
     metricDirection = "Short",
     metricType      = "All"
 )

COTdataseries = COTdataseries_Long-COTdataseries_Short


// Max/Min über Zeitfenster berechnen
max1 = ta.highest(COTdataseries, interval1)
min1 = ta.lowest(COTdataseries, interval1)

max2 = ta.highest(COTdataseries, interval2)
min2 = ta.lowest(COTdataseries, interval2)

max3 = ta.highest(COTdataseries, interval3)
min3 = ta.lowest(COTdataseries, interval3)

// Commercial Index berechnen (Skalierung 0–100)
comm_index1 = 100 * (COTdataseries - min1) / math.max(max1 - min1, 1)
comm_index2 = 100 * (COTdataseries - min2) / math.max(max2 - min2, 1)
comm_index3 = 100 * (COTdataseries - min3) / math.max(max3 - min3, 1)


// Visualisierung
rootID =  LibraryCOT.convertRootToCOTCode("Auto")

//=== Root prüfen: Gültig oder nicht? ========================================
NoFuture = rootID != "098662"
plot(NoFuture ? comm_index1: na, title="Commercial Index (interval 1)", color=#cfd7ff, linewidth=2)
plot(NoFuture ? comm_index2: na, title="Commercial Index (interval 2)", color=#a4aaff, linewidth=2)
plot(NoFuture ? comm_index3: na, title="Commercial Index (interval 3)", color=color.blue, linewidth=2)

if not NoFuture
    label.new(bar_index-30, 50, "⚠️ Invalid CFTC Root Symbol - No Future: '" + syminfo.root + "'", style=label.style_label_center, color=color.red, textcolor=color.white, size=size.normal, textalign=text.align_center )

hline(0, color=color.black, title="0", linestyle=hline.style_dotted, linewidth=1)
hline(100, color=color.black, title="100", linestyle=hline.style_dotted, linewidth=1)


