//@version=6
library('LibBar', overlay = true)

// i_bar_index = input.int(1, 'Candle Index', minval = 0) // Индекс целевой свечи

//
export isBull(int i) =>
    close[i] > open[i]

export isBear(int i) =>
    close[i] < open[i]

export getBody(int i) =>
    i >= 0 and i < bar_index ? math.abs(close[i] - open[i]) : na

export getUpperWick(int i) =>
    i >= 0 and i < bar_index ? high[i] - math.max(open[i], close[i]) : na

export getLowerWick(int i) =>
    i >= 0 and i < bar_index ? math.min(open[i], close[i]) - low[i] : na

export getSize(int i) =>
    i >= 0 and i < bar_index ? high[i] - low[i] : na

export getBodyPercentage(int i) =>
    full_size = getSize(i)
    body_size = getBody(i)
    not na(full_size) and full_size > 0 ? body_size / full_size * 100 : na

export getUpperWickPercentage(int i) =>
    full_size = getSize(i)
    upper_wickSize = getUpperWick(i)
    not na(full_size) and full_size > 0 ? math.round(upper_wickSize / full_size * 100) : na

export getLowerWickPercentage(int i) =>
    full_size = getSize(i)
    lower_wickSize = getLowerWick(i)
    not na(full_size) and full_size > 0 ? math.round(lower_wickSize / full_size * 100) : na

export getBodyTop(int i) =>
    isBull(i) ? close[i] : isBear(i) ? open[i] : na

export getBodyBtm(int i) =>
    isBull(i) ? open[i] : isBear(i) ? close[i] : na

// //
// if barstate.islast
//     r = getBodyBtm(2)
//     label.new(bar_index, high, str.tostring(r))
